/**
      * This file is auto-generated by @kucoin/api-generator
      * Owner: sean.shi@kupotech.com
      */

import type { Options as ClientOptions, TDataShape, Client } from 'tools/request';
import type { GetUserByRcodeUsingGetData, GetUserByRcodeUsingGetResponse } from './types.gen';
import { client as _apiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape> = ClientOptions<TData> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
 disabledLang?: boolean;
};

/**
 * 通过邀请码获取用户信息
 */
export const getUserByRcodeUsingGet = (query: GetUserByRcodeUsingGetData['query'],options?: Options<GetUserByRcodeUsingGetData>) => {
    return (options?.client ?? _apiClient).get<GetUserByRcodeUsingGetResponse>({
        url: '/invitation/user-by-rcode',
        query,
...(options || {})
    });
};