/**
 * Owner: borden@kupotech.com
 */
export default {
  'Accumulation/Distribution': 'Acumulación/distribución',
  'Accumulative Swing Index': 'Índice de oscilación acumulativo',
  'Advance/Decline': 'Avance/retroceso',
  'Arnaud Legoux Moving Average': 'Media móvil Arnaud Legoux',
  Aroon: 'Aroon',
  ASI: 'ASI',
  'Average Directional Index': 'Índice medio de movimiento direccional',
  'Average True Range': 'Rango verdadero medio',
  'Awesome Oscillator': 'Oscilador asombroso',
  'Balance of Power': 'Correlación de fuerzas',
  'Bollinger Bands %B': 'Bandas de Bollinger %B',
  'Bollinger Bands Width': 'Ancho de las bandas de Bollinger',
  'Bollinger Bands': 'Bandas de Bollinger',
  'Chaikin Money Flow': 'Flujo monetario de Chaikin',
  'Chaikin Oscillator': 'Oscilador Chaikin',
  'Chande Kroll Stop': 'Chande Kroll Stop',
  'Chande Momentum Oscillator': 'Oscilador de momento de Chande',
  'Chop Zone': 'Zona de corte',
  'Choppiness Index': 'Índice Choppiness',
  'Commodity Channel Index': 'Índice de canal de mercaderías',
  'Connors RSI': 'RSI (índice de fuerza relativa) de Connors ',
  'Coppock Curve': 'Curva de Coppock',
  'Correlation Coefficient': 'Coeficiente de correlación',
  CRSI: 'CRSI',
  'Detrended Price Oscillator': 'Oscilador del precio sin tendencia',
  'Directional Movement': 'Movimiento direccional',
  'Donchian Channels': 'Canales de Donchian',
  'Double EMA': 'Media móvil exponencial (EMA) de doble canal',
  'Ease Of Movement': 'Facilidad de movimiento',
  'Elder\'s Force Index': 'Índice de fuerza de Elder',
  'EMA Cross': 'Cruce EMA',
  Envelopes: 'Sobre',
  'Fisher Transform': 'Transformación de Fisher',
  'Fixed Range': 'Rango fijo',
  'Historical Volatility': 'Volatilidad histórica',
  'Hull Moving Average': 'Media móvil de Hull',
  'Ichimoku Cloud': 'Nube Ichimoku',
  KDJ: 'KDJ',
  'Keltner Channels': 'Canales Keltner',
  'Klinger Oscillator': 'Oscilador Klinger',
  'Know Sure Thing': 'Know Sure Thing',
  'Least Squares Moving Average': 'Media móvil de los mínimos cuadrados',
  'Linear Regression Curve': 'Curva de regresion lineal',
  'MA Cross': 'Cruce de medias móviles',
  'MA with EMA Cross': 'Cruce de media móvil (MA) con media móvil exponencial (EMA)',
  'MA/EMA Cross': 'Cruce de media móvil (MA)/media móvil exponencial (EMA)',
  MACD: 'Convergencia/divergencia de la media móvil (MACD)',
  'Mass Index': 'Índice Mass',
  'McGinley Dynamic': 'Indicador dinámico McGinley',
  Momentum: 'Momentum',
  'Money Flow Index': 'Flujo monetario',
  'Moving Average Channel': 'Canal de medias móviles',
  'Moving Average Exponential': 'Media móvil exponencial',
  'Moving Average Weighted': 'Media móvil ponderada',
  'Moving Average': 'Media móvil',
  'Net Volume': 'Volumen neto',
  'On Balance Volume': 'Balance de volúmenes',
  'Parabolic SAR': 'Parabólica SAR',
  'Pivot Points Standard': 'Puntos pivote estándar',
  'Price Channel': 'Canal de precios',
  'Price Oscillator': 'Oscilador de precios',
  'Price Volume Trend': 'Tendencia de volumen según el precio',
  'Rate Of Change': 'Indicador de la tasa de cambio',
  'Relative Strength Index': 'Índice de fuerza relativa',
  'Relative Vigor Index': 'Índice de vigor relativo (RVI)',
  'Relative Volatility Index': 'Índice de volatilidad relativa',
  'Session Volume': 'Volumen de la sesión',
  'SMI Ergodic Indicator/Oscillator': 'Indicador/oscilador ergódico SMI',
  'Smoothed Moving Average': 'Media móvil suavizada',
  'Stochastic RSI': 'Índice de fuerza relativa (RSI) estocástica',
  Stochastic: 'Estocástica',
  'Triple EMA': 'Media móvil exponencial triple (TEMA)',
  TRIX: 'TRIX (media exponencial triple)',
  'True Strength Index': 'Índice de fuerza verdadera (TSI)',
  'Ultimate Oscillator': 'Oscilador de Williams',
  'Visible Range': 'Rango visible',
  'Volume Oscillator': 'Oscilador de volumen',
  Volume: 'Volumen',
  'Vortex Indicator': 'Indicador de vortex',
  VWAP: 'Precio medio ponderado por volumen (VWAP)',
  VWMA: 'Media móvil ponderada de volumen (VWMA)',
  'Williams %R': 'Williams %R',
  'Williams Alligator': 'Alligator de Williams',
  'Williams Fractal': 'Fractal de Williams',
  'Zig Zag': 'Zigzag',
};
