/**
 * Owner: borden@kupotech.com
 */
export default {
  'Accumulation/Distribution': 'Accumulation/Répartition',
  'Accumulative Swing Index': 'Indice d\'oscillation cumulative',
  'Advance/Decline': 'Advance/Decline',
  'Arnaud Legoux Moving Average': 'Arnaud Legoux Moyenne Mobile',
  Aroon: 'Aroon',
  ASI: 'ASI',
  'Average Directional Index': 'Average Directional Index',
  'Average True Range': 'Moyenne de la vraie amplitude',
  'Awesome Oscillator': 'Oscillateur impressionnant',
  'Balance of Power': 'Équilibre des forces',
  'Bollinger Bands %B': 'Bollinger Bands %B',
  'Bollinger Bands Width': 'Largeur Bollinger Bands',
  'Bollinger Bands': 'Bollinger Bands',
  'Chaikin Money Flow': 'Chaikin Money Flow',
  'Chaikin Oscillator': 'Chaikin Oscillator',
  'Chande Kroll Stop': 'Stop Chande Kroll',
  'Chande Momentum Oscillator': 'Chande Momentum Oscillator',
  'Chop Zone': 'Chop Zone',
  'Choppiness Index': 'Choppiness Index',
  'Commodity Channel Index': 'Commodity Channel Index',
  'Connors RSI': 'RSI de Connors',
  'Coppock Curve': 'Courbe Coppock',
  'Correlation Coefficient': 'Coefficient de Corellation',
  CRSI: 'CRSI',
  'Detrended Price Oscillator': 'Detrended Price Oscillator',
  'Directional Movement': 'Directional Movement',
  'Donchian Channels': 'Donchian Channels',
  'Double EMA': 'EMA Double',
  'Ease Of Movement': 'Ease Of Movement',
  'Elder\'s Force Index': 'Index de Force Elder',
  'EMA Cross': 'EMA Cross',
  Envelopes: 'Enveloppe',
  'Fisher Transform': 'Fisher Transform',
  'Fixed Range': 'Gamme fixe',
  'Historical Volatility': 'Volatilité Historique',
  'Hull Moving Average': 'Moyenne Mobile Hull',
  'Ichimoku Cloud': 'Nuage Ichimoku',
  KDJ: 'KDJ',
  'Keltner Channels': 'Keltner Channels',
  'Klinger Oscillator': 'Klinger Oscillator',
  'Know Sure Thing': 'Know Sure Thing',
  'Least Squares Moving Average': 'Moyenne Mobile Least Squares',
  'Linear Regression Curve': 'Courbe de régression linéaire',
  'MA Cross': 'Croisement MA',
  'MA with EMA Cross': 'MA avec EMA Cross',
  'MA/EMA Cross': 'MA/EMA Cross',
  MACD: 'MACD',
  'Mass Index': 'Index de masse',
  'McGinley Dynamic': 'McGinley Dynamic',
  Momentum: 'Momentum',
  'Money Flow Index': 'Flux d\'argent',
  'Moving Average Channel': 'Canal de moyenne mobile',
  'Moving Average Exponential': 'Moyenne mobile exponentielle',
  'Moving Average Weighted': 'Moyenne mobile pondérée',
  'Moving Average': 'Moyenne mobile',
  'Net Volume': 'Volume net',
  'On Balance Volume': 'Volume On Balance',
  'Parabolic SAR': 'Parabolique SAR',
  'Pivot Points Standard': 'Points Pivots Standard',
  'Price Channel': 'Canal de prix',
  'Price Oscillator': 'Price Oscillator',
  'Price Volume Trend': 'Tendance volume-prix',
  'Rate Of Change': 'Taux de changement',
  'Relative Strength Index': 'Relative Strength Index',
  'Relative Vigor Index': 'Relative Vigor Index',
  'Relative Volatility Index': 'Relative Volatility Index',
  'Session Volume': 'Volume de la session',
  'SMI Ergodic Indicator/Oscillator': 'SMI Ergodic Indicateur/Oscillateur',
  'Smoothed Moving Average': 'Smoothed Moving Average',
  'Stochastic RSI': 'Stochastic RSI',
  Stochastic: 'Stochastic',
  'Triple EMA': 'EMA Triple',
  TRIX: 'TRIX',
  'True Strength Index': 'Indicateur True Strength',
  'Ultimate Oscillator': 'Oscillateur Ultimate',
  'Visible Range': 'Gamme visible',
  'Volume Oscillator': 'Oscillateur de volume',
  Volume: 'Volume',
  'Vortex Indicator': 'Indicateur Vortex',
  VWAP: 'VWAP',
  VWMA: 'VWMA',
  'Williams %R': 'Williams %R',
  'Williams Alligator': 'Alligator Williams',
  'Williams Fractal': 'Fractal Williams',
  'Zig Zag': 'Zig Zag',
};
