/**
 * Owner: borden@kupotech.com
 */
export default {
  'Accumulation/Distribution': '누적/분포 (Accumulation/Distribution)',
  'Accumulative Swing Index': '어큐뮬러티브 스윙 인덱스',
  'Advance/Decline': '어드밴스/디클라인 (Advance/Decline)',
  'Arnaud Legoux Moving Average': '아르노 르구 무빙 애버리지 (Arnaud Legoux Moving Average)',
  Aroon: '아룬 (Aroon)',
  ASI: 'ASI',
  'Average Directional Index': '평균방향성지수 (Average Directional Index)',
  'Average True Range': '애버리지 트루 레인지 (Average True Range)',
  'Awesome Oscillator': '오썸 오실레이터 (Awesome Oscillator)',
  'Balance of Power': '밸런스 오브 파우어 (Balance Of Power)',
  'Bollinger Bands %B': '볼린저 밴드 %B (Bollinger Bands %B)',
  'Bollinger Bands Width': '볼린저밴드 너비 (Bollinger Bands Width)',
  'Bollinger Bands': '볼린저 밴드 (Bollinger Bands)',
  'Chaikin Money Flow': '체이킨 머니 플로우 (Chaikin Money Flow)',
  'Chaikin Oscillator': '체이킨 오실레이터 (Chaikin Oscillator)',
  'Chande Kroll Stop': '샹드 크롤 스탑',
  'Chande Momentum Oscillator': '샹드 모멘텀 오실레이터',
  'Chop Zone': '찹 존 (Chop Zone)',
  'Choppiness Index': '차피니스 인덱스 (Choppiness Index)',
  'Commodity Channel Index': '커모디티 채널 인덱스 (Commodity Channel Index)',
  'Connors RSI': '코너즈 RSI',
  'Coppock Curve': '카포크 커브(Coppock Curve)',
  'Correlation Coefficient': '코릴레이션 코에피션트 (Correlation Coefficient)',
  CRSI: 'CRSI',
  'Detrended Price Oscillator': '디트렌디드 프라이스 오실레이터 (Detrended Price Oscillator)',
  'Directional Movement': '디렉셔널 무브먼트 (Directional Movement)',
  'Donchian Channels': '돈치안 채널 (Donchian Channels)',
  'Double EMA': '더블 EMA (Double EMA)',
  'Ease Of Movement': '이즈 오브 무브먼트 (Ease Of Movement)',
  'Elder\'s Force Index': '엘더즈 포스 인덱스 (Elder\'s Force Index)',
  'EMA Cross': 'EMA 크로스',
  Envelopes: '엔빌로프 (Envelope)',
  'Fisher Transform': '피셔 트랜스폼 (Fisher Transform)',
  'Fixed Range': '픽스트 레인지',
  'Historical Volatility': '과거변동성 (Historical Volatility)',
  'Hull Moving Average': '헐 이동 평균 (Hull Moving Average)',
  'Ichimoku Cloud': '일목 구름 (Ichimoku Cloud)',
  KDJ: 'KDJ',
  'Keltner Channels': '켈트너 채널 (Keltner Channels)',
  'Klinger Oscillator': '클링거 오실레이터 (Klinger Oscillator)',
  'Know Sure Thing': '노우 슈어 씽 (Know Sure Thing)',
  'Least Squares Moving Average': '리스트 스퀘어 무빙 애버리지 (Least Squares Moving Average)',
  'Linear Regression Curve': '리니어 리그레션 커브 (Linear Regression Curve)',
  'MA Cross': 'MA 크로스 (MA Cross)',
  'MA with EMA Cross': '이동평균선과 지수이동평균선의 교차',
  'MA/EMA Cross': 'MA/EMA 크로스',
  MACD: 'MACD',
  'Mass Index': '매스 인덱스 (Mass Index)',
  'McGinley Dynamic': '맥긴리 다이내믹 (McGinley Dynamic)',
  Momentum: '모멘텀 (Momentum)',
  'Money Flow Index': '머니 플로우 (Money Flow)',
  'Moving Average Channel': '무빙 애버리지 채널',
  'Moving Average Exponential': '지수 이동 평균 (Moving Average Exponential)',
  'Moving Average Weighted': '가중 이동 평균 (Moving Average Weighted)',
  'Moving Average': '이동 평균(Moving Average)',
  'Net Volume': '순거래량 (Net Volume)',
  'On Balance Volume': '온밸런스볼륨 (On Balance Volume)',
  'Parabolic SAR': '파라볼릭 SAR (Parabolic SAR)',
  'Pivot Points Standard': '피봇 포인트 스탠다드 (Pivot Points Standard)',
  'Price Channel': '프라이스 채널',
  'Price Oscillator': '프라이스 오실레이터 (Price Oscillator)',
  'Price Volume Trend': '가격 거래량 트렌드 (Price Volume Trend)',
  'Rate Of Change': '레이트 오브 체인지 (Rate Of Change)',
  'Relative Strength Index': '상대강도지수 (Relative Strength Index)',
  'Relative Vigor Index': '렐러티브 비고르 인덱스 (Relative Vigor Index)',
  'Relative Volatility Index': '상대변동성지수 (Relative Volatility Index)',
  'Session Volume': '세션 볼륨',
  'SMI Ergodic Indicator/Oscillator': 'SMI 에르고딕 인디케이터/오실레이터 (SMI Ergodic Indicator/Oscillator)',
  'Smoothed Moving Average': '스무디드 무빙 애버리지 (Smoothed Moving Average)',
  'Stochastic RSI': '스토캐스틱 RSI (Stochastic RSI)',
  Stochastic: '스토캐스틱 (Stochastic)',
  'Triple EMA': '트리플 EMA (Triple EMA)',
  TRIX: '트릭스 (TRIX)',
  'True Strength Index': '트루 스트렝쓰 인디케이터 (True Strength Index)',
  'Ultimate Oscillator': '얼티미트 오실레이터 (Ultimate Oscillator)',
  'Visible Range': '비저블 레인지',
  'Volume Oscillator': '볼륨 오실레이터 (Volume Oscillator)',
  Volume: '거래량 (Volume)',
  'Vortex Indicator': '보텍스 인디케이터 (Vortex Indicator)',
  VWAP: '브이왑 (VWAP)',
  VWMA: '거래량 가중이동평균',
  'Williams %R': '윌리엄스 %R (Williams %R)',
  'Williams Alligator': '윌리엄스 앨리게이터 (Williams Alligator)',
  'Williams Fractal': '윌리엄스 프랙탈 (Williams Fractal)',
  'Zig Zag': '지그재그 (Zig Zag)',
};
