/**
 * Owner: borden@kupotech.com
 */
export default {
  'Accumulation/Distribution': 'Acúmulo/Distribuição',
  'Accumulative Swing Index': 'Índice Acumulativo de Swing',
  'Advance/Decline': 'Avanço/Declínio',
  'Arnaud Legoux Moving Average': 'Média móvel de Arnaud Legoux',
  Aroon: 'Aroon',
  ASI: 'IAS (ASI)',
  'Average Directional Index': 'Índice Direcional Médio',
  'Average True Range': 'Média da Amplitude de Variação (ATR)',
  'Awesome Oscillator': 'Oscilador Awesome',
  'Balance of Power': 'Equilíbrio de poder',
  'Bollinger Bands %B': 'Bandas de Bollinger %B',
  'Bollinger Bands Width': 'Largura das Bandas de Bollinger',
  'Bollinger Bands': 'Bandas de Bollinger',
  'Chaikin Money Flow': 'Fluxo Monetário de Chaikin',
  'Chaikin Oscillator': 'Oscilador de Chaikin',
  'Chande Kroll Stop': 'Parada de Chande Kroll',
  'Chande Momentum Oscillator': 'Oscilador de Momento de Chande',
  'Chop Zone': 'Zona lateralizada',
  'Choppiness Index': 'Índice de lateralização',
  'Commodity Channel Index': 'Índice de Canal de Commodities (CCI)',
  'Connors RSI': 'IFR de Connors',
  'Coppock Curve': 'Curva Coppock',
  'Correlation Coefficient': 'Coeficiente de correlação',
  CRSI: 'CRSI',
  'Detrended Price Oscillator': 'Oscilador de preço sem tendência',
  'Directional Movement': 'Movimento Direcional',
  'Donchian Channels': 'Canais Donchian',
  'Double EMA': 'Média Móvel Exponencial Dupla (Double EMA)',
  'Ease Of Movement': 'Ease of Movement',
  'Elder\'s Force Index': 'Índice de Força de Elder',
  'EMA Cross': 'Cruzamento de MME',
  Envelopes: 'Médias Móveis Envelope',
  'Fisher Transform': 'Transformada de Fisher',
  'Fixed Range': 'Range Fixo',
  'Historical Volatility': 'Volatilidade Histórica',
  'Hull Moving Average': 'Média Móvel de Hull',
  'Ichimoku Cloud': 'Nuvem Ichimoku',
  KDJ: 'KDJ',
  'Keltner Channels': 'Canais de Keltner',
  'Klinger Oscillator': 'Oscilador de Klinger',
  'Know Sure Thing': 'Know Sure Thing (KST)',
  'Least Squares Moving Average': 'Média Móvel de Mínimos Quadrados',
  'Linear Regression Curve': 'Curva de Regressão Linear',
  'MA Cross': 'Cruzamento de MM',
  'MA with EMA Cross': 'Cruzamento de Média Móvel Simples e Exponencial',
  'MA/EMA Cross': 'Cruzamento MM/MME',
  MACD: 'MACD',
  'Mass Index': 'Índice de Massa',
  'McGinley Dynamic': 'McGinley Dinâmico',
  Momentum: 'Momentum',
  'Money Flow Index': 'Fluxo Monetário',
  'Moving Average Channel': 'Canal de Média Móvel',
  'Moving Average Exponential': 'Média Móvel Exponencial',
  'Moving Average Weighted': 'Média Móvel Ponderada',
  'Moving Average': 'Média Móvel',
  'Net Volume': 'Volume Líquido',
  'On Balance Volume': 'Saldo de Volume - On Balance Volume',
  'Parabolic SAR': 'SAR Parabólico',
  'Pivot Points Standard': 'Pontos de Pivô Padrão',
  'Price Channel': 'Canal de Preço',
  'Price Oscillator': 'Oscilador de Preço',
  'Price Volume Trend': 'Tendência de Preço Volume (PVT)',
  'Rate Of Change': 'Taxa de Variação (ROC)',
  'Relative Strength Index': 'Indice de Força Relativa',
  'Relative Vigor Index': 'Índice de Vigor Relativo (RVI)',
  'Relative Volatility Index': 'Índice de Volatilidade Relativa',
  'Session Volume': 'Volume da Sessão',
  'SMI Ergodic Indicator/Oscillator': 'Indicador/Oscilador SMI Ergodic',
  'Smoothed Moving Average': 'Média Móvel Suavizada',
  'Stochastic RSI': 'RSI Estocástico',
  Stochastic: 'Estocástico',
  'Triple EMA': 'Média Móvel Exponencial Tripla',
  TRIX: 'Média Móvel Tripla (TRIX)',
  'True Strength Index': 'Indicador de Força Real',
  'Ultimate Oscillator': 'Oscilador Final',
  'Visible Range': 'Range Visível',
  'Volume Oscillator': 'Oscilador de Volume',
  Volume: 'Volume',
  'Vortex Indicator': 'Indicador Vortex',
  VWAP: 'VWAP',
  VWMA: 'VWMA',
  'Williams %R': 'Williams %R',
  'Williams Alligator': 'Indicador Alligator de Williams',
  'Williams Fractal': 'Indicador Fractal de Williams',
  'Zig Zag': 'Indicador Zig Zag',
};
