/**
 * Owner: borden@kupotech.com
 */
export default {
  'Accumulation/Distribution': 'Накопление/Распределение',
  'Accumulative Swing Index': 'Кумулятивный индекс колебаний',
  'Advance/Decline': 'Рост/падение',
  'Arnaud Legoux Moving Average': 'Скользящее среднее Арно Легу',
  Aroon: 'Арун',
  ASI: 'ASI',
  'Average Directional Index': 'Индикатор среднего направленного движения (ADX)',
  'Average True Range': 'Средний истинный диапазон',
  'Awesome Oscillator': 'Чудесный осциллятор Билла Вильямса',
  'Balance of Power': 'Баланс силы',
  'Bollinger Bands %B': '%B Полос Боллинджера',
  'Bollinger Bands Width': 'Ширина полос Боллинджера',
  'Bollinger Bands': 'Полосы Боллинджера',
  'Chaikin Money Flow': 'Денежный поток Чайкина',
  'Chaikin Oscillator': 'Осциллятор Чайкина',
  'Chande Kroll Stop': 'Chande Kroll Stop',
  'Chande Momentum Oscillator': 'Осциллятор темпа Чанде',
  'Chop Zone': 'Индикатор Chop Zone',
  'Choppiness Index': 'Индекс переменчивости',
  'Commodity Channel Index': 'Индекс товарного канала',
  'Connors RSI': 'RSI Коннора',
  'Coppock Curve': 'Кривая Коппока',
  'Correlation Coefficient': 'Коэффициент корреляции',
  CRSI: 'CRSI',
  'Detrended Price Oscillator': 'Детрендовый ценовой осциллятор',
  'Directional Movement': 'Индекс направленного движения',
  'Donchian Channels': 'Канал Дончана',
  'Double EMA': 'Двойное экспоненц. скользящ. средн.',
  'Ease Of Movement': 'Лёгкость движения',
  'Elder\'s Force Index': 'Индекс силы Элдера',
  'EMA Cross': 'Пересечение экспоненц. скользящих средних',
  Envelopes: 'Конверт',
  'Fisher Transform': 'Индикатор Fisher Transform',
  'Fixed Range': 'Фиксированный диапазон',
  'Historical Volatility': 'Историческая волатильность',
  'Hull Moving Average': 'Скользящее среднее Хала',
  'Ichimoku Cloud': 'Облако Ишимоку',
  KDJ: 'KDJ',
  'Keltner Channels': 'Канал Кельтнера',
  'Klinger Oscillator': 'Осциллятор Клингера',
  'Know Sure Thing': 'Знать наверняка',
  'Least Squares Moving Average': 'Скользящее среднее (наименьшие квадраты)',
  'Linear Regression Curve': 'Кривая линейной регрессии',
  'MA Cross': 'Пересечение скользящих средних',
  'MA with EMA Cross': 'MA с пересеч. EMA',
  'MA/EMA Cross': 'Пересечение MA/EMA',
  MACD: 'MACD',
  'Mass Index': 'Индекс массы',
  'McGinley Dynamic': 'Динамический индикатор МакГинли',
  Momentum: 'Моментум (Momentum)',
  'Money Flow Index': 'Денежный поток',
  'Moving Average Channel': 'Канал скользящей средней',
  'Moving Average Exponential': 'Скользящее среднее (эксп.)',
  'Moving Average Weighted': 'Взвешенное скользящее среднее',
  'Moving Average': 'Скользящее среднее',
  'Net Volume': 'Чистый объём',
  'On Balance Volume': 'Балансовый объём',
  'Parabolic SAR': 'Параболическая система времени/цены',
  'Pivot Points Standard': 'Стандартные точки разворота',
  'Price Channel': 'Ценовой канал',
  'Price Oscillator': 'Осциллятор цены',
  'Price Volume Trend': 'Тренд цены и объёма',
  'Rate Of Change': 'Индекс изменения',
  'Relative Strength Index': 'Индекс относительной силы',
  'Relative Vigor Index': 'Индекс относительной бодрости',
  'Relative Volatility Index': 'Относительный индекс волатильности',
  'Session Volume': 'Объём за сессию',
  'SMI Ergodic Indicator/Oscillator': 'Индикатор/Осциллятор SMI Ergodic',
  'Smoothed Moving Average': 'Сглаженное скользящее среднее',
  'Stochastic RSI': 'Стохастический индекс относительной силы',
  Stochastic: 'Стохастический осциллятор',
  'Triple EMA': 'Скользящее среднее (тройное эксп.)',
  TRIX: 'Скользящее среднее (тройное эксп. сглаженное)',
  'True Strength Index': 'Индекс истинной силы',
  'Ultimate Oscillator': 'Окончательный осциллятор',
  'Visible Range': 'Видимая область',
  'Volume Oscillator': 'Осциллятор объёма',
  Volume: 'Объём',
  'Vortex Indicator': 'Vortex индикатор',
  VWAP: 'VWAP',
  VWMA: 'Скользящее среднее, взвешенное по объёму',
  'Williams %R': 'Процентный диапазон Вильямса (%R)',
  'Williams Alligator': 'Аллигатор Билла Вильямса',
  'Williams Fractal': 'Фракталы Билла Вильямса',
  'Zig Zag': 'ЗигЗаг',
};
