/**
 * Owner: borden@kupotech.com
 */
export default {
  'Accumulation/Distribution': 'Birikim/Dağıtım',
  'Accumulative Swing Index': 'Biriktirici Sallanma Endeksi',
  'Advance/Decline': 'Yükseliş/Düşüş',
  'Arnaud Legoux Moving Average': 'Arnaud Legoux Hareketli Ortalama',
  Aroon: 'Aroon',
  ASI: 'ASI',
  'Average Directional Index': 'Ortalama Yönsel Endeks(ADX)',
  'Average True Range': 'Ortalama Gerçek Aralık',
  'Awesome Oscillator': 'Müthiş Osilatör(AO)',
  'Balance of Power': 'Güç Dengesi',
  'Bollinger Bands %B': 'Bollinger Bantları %B',
  'Bollinger Bands Width': 'Bollinger Bantları Genişliği',
  'Bollinger Bands': 'Bollinger Bantları',
  'Chaikin Money Flow': 'Chaikin Para Akışı',
  'Chaikin Oscillator': 'Chaikin Osilatörü',
  'Chande Kroll Stop': 'Chande Kroll Durdurması',
  'Chande Momentum Oscillator': 'Chande Momentum Osilatörü',
  'Chop Zone': 'Kaşe Alanı',
  'Choppiness Index': 'Dalgalılık Endeksi',
  'Commodity Channel Index': 'Emtia Kanal Endeksi(CCI)',
  'Connors RSI': 'Connors RSI',
  'Coppock Curve': 'Coppock Eğrisi',
  'Correlation Coefficient': 'Korelasyon Katsayısı',
  CRSI: 'CRSI',
  'Detrended Price Oscillator': 'Trend Azaltma Fiyat Osilatörü',
  'Directional Movement': 'Yönsel Hareket',
  'Donchian Channels': 'Donchian Kanalları',
  'Double EMA': 'DEMA',
  'Ease Of Movement': 'Hareket Kolaylığı',
  'Elder\'s Force Index': 'Elder Güç Endeksi',
  'EMA Cross': 'ÜHO Kesişme',
  Envelopes: 'Zarf',
  'Fisher Transform': 'Fisher Dönüşümü',
  'Fixed Range': 'Sabit Aralık',
  'Historical Volatility': 'Tarihi Volatilite',
  'Hull Moving Average': 'Hull Hareketli Ortalaması',
  'Ichimoku Cloud': 'Ichimoku Bulutu',
  KDJ: 'KDJ',
  'Keltner Channels': 'Keltner Kanalları',
  'Klinger Oscillator': 'Klinger Osilatörü',
  'Know Sure Thing': 'Know Sure Thing',
  'Least Squares Moving Average': 'En Küçük Kareler Hareketli Ortalaması',
  'Linear Regression Curve': 'Doğrusal Regresyon Eğrisi',
  'MA Cross': 'HO Cross',
  'MA with EMA Cross': 'HO ve ÜHO Kesişmesi',
  'MA/EMA Cross': 'HO/ÜHO Kesişmesi',
  MACD: 'MACD',
  'Mass Index': 'Kütle Endeksi',
  'McGinley Dynamic': 'McGinley Dinamik',
  Momentum: 'Momentum',
  'Money Flow Index': 'Para Akışı',
  'Moving Average Channel': 'Hareketli Ortalama Kanalı',
  'Moving Average Exponential': 'Üstel Hareketli Ortalama',
  'Moving Average Weighted': 'Ağırlıklı Hareketli Ortalama',
  'Moving Average': 'Hareketli Ortalama',
  'Net Volume': 'Net İşlem Hacmi',
  'On Balance Volume': 'Denge İşlem Hacmi',
  'Parabolic SAR': 'Parabolik SAR',
  'Pivot Points Standard': 'Pivot Noktalar Standartı',
  'Price Channel': 'Fiyat Kanalı',
  'Price Oscillator': 'Fiyat Osilatörü',
  'Price Volume Trend': 'Fiyat Hacmi Trendi',
  'Rate Of Change': 'Değişim Oranı',
  'Relative Strength Index': 'Göreceli Güç Endeksi(RSI)',
  'Relative Vigor Index': 'Göreceli Vigor Endeksi',
  'Relative Volatility Index': 'Göreceli Volatilite Endeksi',
  'Session Volume': 'Seans Hacmi',
  'SMI Ergodic Indicator/Oscillator': 'SMI Ergodik Gösterge/Osilatörü',
  'Smoothed Moving Average': 'Yuvarlatılmış Hareketli Ortalama',
  'Stochastic RSI': 'Stokastik RSI',
  Stochastic: 'Stokastik',
  'Triple EMA': 'Üçlü ÜHO',
  TRIX: 'TRIX',
  'True Strength Index': 'Gerçek Güç Göstergesi',
  'Ultimate Oscillator': 'Nihai Osilatör(UO)',
  'Visible Range': 'Görünür Aralık',
  'Volume Oscillator': 'İşlem Hacmi Osilatörü',
  Volume: 'İşlem Hacmi',
  'Vortex Indicator': 'Vortex Göstergesi',
  VWAP: 'HAOF',
  VWMA: 'HAHO',
  'Williams %R': 'Williams %R',
  'Williams Alligator': 'Williams Gator',
  'Williams Fractal': 'Williams Fraktalı',
  'Zig Zag': 'Zig Zag',
};
