/**
 * Owner: borden@kupotech.com
 */
export default {
  'Accumulation/Distribution': 'تجميع/توزيع',
  'Accumulative Swing Index': 'مؤشر الموجة التراكمي',
  'Advance/Decline': 'مؤشر الصعود/التراجع',
  'Arnaud Legoux Moving Average': 'متوسط متحرك أرنو ليجو',
  Aroon: 'آرون',
  ASI: 'مؤشر الموجة التراكمي',
  'Average Directional Index': 'مؤشر متوسط الحركة الاتجاهية',
  'Average True Range': 'متوسط المدى الحقيقي',
  'Awesome Oscillator': 'المتذبذب الرهيب Awesome Oscillator',
  'Balance of Power': 'ميزان القوة',
  'Bollinger Bands %B': 'حدود بولنجر %B',
  'Bollinger Bands Width': 'عرض حدود بولنجر',
  'Bollinger Bands': 'حدود بولنجر',
  'Chaikin Money Flow': 'مؤشر التدفق النقدي لشايكين',
  'Chaikin Oscillator': 'مؤشر شايكين',
  'Chande Kroll Stop': 'وقف اتشاند كرول',
  'Chande Momentum Oscillator': 'مؤشر زخم اتشاند',
  'Chop Zone': 'نطاق تقلب سعري (نطاق شوب)',
  'Choppiness Index': 'مؤشر التقلب السعري',
  'Commodity Channel Index': 'مؤشر قناة السلع',
  'Connors RSI': 'مؤشر القوى النسبية لكونرز',
  'Coppock Curve': 'منحنى كوبوك',
  'Correlation Coefficient': 'معامل الإرتباط',
  CRSI: 'مؤشر القوى النسبية لكونرز',
  'Detrended Price Oscillator': 'مؤشر التذبذب السعري',
  'Directional Movement': 'الحركة الاتجاهية',
  'Donchian Channels': 'قناة دونكان',
  'Double EMA': 'متوسط متحرك أسي مزدوج',
  'Ease Of Movement': 'سهولة الحركة',
  "Elder's Force Index": 'مؤشر قوى إلدر',
  'EMA Cross': 'تقاطع المتوسط المتحرك الأسي',
  Envelopes: 'مظروف',
  'Fisher Transform': 'تحويلة فيشر',
  'Fixed Range': 'مدى ثابت',
  'Historical Volatility': 'درجة نشاط السوق التاريخية',
  'Hull Moving Average': 'متوسط متحرك هال',
  'Ichimoku Cloud': 'سحابة إيتشيموكو',
  KDJ: 'KDJ',
  'Keltner Channels': 'قناة كلتنر',
  'Klinger Oscillator': 'مؤشر كلنجر',
  'Know Sure Thing': 'أعرف الأشياء المؤكدة',
  'Least Squares Moving Average': 'متوسط المربعات الصغرى المتحرك',
  'Linear Regression Curve': 'منحنى الانحدار الخطي',
  'MA Cross': 'تقاطع المتوسط المتحرك',
  'MA with EMA Cross': 'تقاطع المتوسط المتحرك مع الأسي',
  'MA/EMA Cross': 'تقاطع المتوسط المتحرك/الأسي',
  MACD: 'الماكد',
  'Mass Index': 'مؤشر الكتلة',
  'McGinley Dynamic': 'ماكجينلي ديناميك',
  Momentum: 'زخم',
  'Money Flow Index': 'التدفق النقدي',
  'Moving Average Channel': 'قناة المتوسط المتحرك',
  'Moving Average Exponential': 'المتوسط المتحرك الأسي',
  'Moving Average Weighted': 'المتوسط المتحرك المرجح',
  'Moving Average': 'المتوسط المتحرك',
  'Net Volume': 'صافي حجم التداول',
  'On Balance Volume': 'مؤشر OBV',
  'Parabolic SAR': 'مؤشر البارابوليك سار',
  'Pivot Points Standard': 'النقاط المحورية القياسية',
  'Price Channel': 'قناة سعرية',
  'Price Oscillator': 'مؤشر التذبذب السعري',
  'Price Volume Trend': 'اتجاه حجم التداول للأسعار',
  'Rate Of Change': 'معدل التغير',
  'Relative Strength Index': 'مؤشر القوة النسبية',
  'Relative Vigor Index': 'مؤشر النشاط النسبي',
  'Relative Volatility Index': 'مؤشر النشاط النسبي',
  'Session Volume': 'حجم تداول الفترة',
  'SMI Ergodic Indicator/Oscillator': 'مؤشر إرجوديك SMI',
  'Smoothed Moving Average': 'المتوسط المتحرك المحسن',
  'Stochastic RSI': 'ستوكاستك القوة النسبية (STOCH RSI)',
  Stochastic: 'مؤشر ستوكاستك',
  'Triple EMA': 'المتوسط المتحرك الأسي الثلاثي',
  TRIX: 'مؤشر TRIX',
  'True Strength Index': 'مؤشر القوة الحقيقية tsi',
  'Ultimate Oscillator': 'مؤشر Ultimate Oscillator',
  'Visible Range': 'نطاق مرئي',
  'Volume Oscillator': 'متذبذب حجم التداول',
  Volume: 'حجم التداول',
  'Vortex Indicator': 'مؤشر فورتكس  Vortex',
  VWAP: 'مؤشر متوسط السعر المرجح بحجم التداول VWAP',
  VWMA: 'المتوسط المتحرك المرجح بحجم التداول VWMA',
  'Williams %R': 'مؤشر %R، ويليامز',
  'Williams Alligator': 'مؤشر الأليجيتور، ويليامز',
  'Williams Fractal': 'مؤشر فراكتالز، ويليامز',
  'Zig Zag': 'مؤشر الزيجزاج',
  'Plots Background': 'لون الخلفية',
  SuperTrend: 'سوبرترند',
};
