/**
 * Owner: borden@kupotech.com
 */
export default {
  'Accumulation/Distribution': 'Tích lũy / phân phối',
  'Accumulative Swing Index': 'Chỉ số Swing tích lũy',
  'Advance/Decline': 'Lên/Xuống',
  'Arnaud Legoux Moving Average': 'Trung bình Động Arnaud Legoux',
  Aroon: 'Aroon',
  ASI: 'ASI',
  'Average Directional Index': 'Chỉ báo Định hướng Trung bình',
  'Average True Range': 'Trung bình biên độ chính xác của giá',
  'Awesome Oscillator': 'Chỉ số Dao động Tuyệt vời AO',
  'Balance of Power': 'Chỉ số Cân bằng Sức mạnh',
  'Bollinger Bands %B': 'Dải băng Bollinger %B',
  'Bollinger Bands Width': 'Chỉ báo Bollinger Bands Width',
  'Bollinger Bands': 'Dải băng Bollinger',
  'Chaikin Money Flow': 'Dòng tiền Chaikin',
  'Chaikin Oscillator': 'Bộ dao động Chaikin',
  'Chande Kroll Stop': 'Chiến lược Chande Kroll Stop',
  'Chande Momentum Oscillator': 'Dao động Xung lượng Chande',
  'Chop Zone': 'Vùng Biến động',
  'Choppiness Index': 'Chỉ số Biến động',
  'Commodity Channel Index': 'Chỉ số Kênh hàng hóa',
  'Connors RSI': 'Connors RSI',
  'Coppock Curve': 'Đường cong Coppock',
  'Correlation Coefficient': 'Hệ số Tương quan',
  CRSI: 'CRSI',
  'Detrended Price Oscillator': 'Công cụ đo Dao động giá không theo xu hướng',
  'Directional Movement': 'Chuyển động Định hướng',
  'Donchian Channels': 'Chỉ số Kênh Donchian',
  'Double EMA': 'EMA Kép',
  'Ease Of Movement': 'Dao động dựa trên Khối lượng EOM',
  'Elder\'s Force Index': 'Chỉ số Lực của Elder',
  'EMA Cross': 'Đường chéo EMA',
  Envelopes: 'Đường bao',
  'Fisher Transform': 'Fisher Biến đổi',
  'Fixed Range': 'Phạm vi cố định',
  'Historical Volatility': 'Biến động lịch sử',
  'Hull Moving Average': 'Đường Trung bình động Hull',
  'Ichimoku Cloud': 'Mây Ichimoku',
  KDJ: 'KDJ',
  'Keltner Channels': 'Kênh Keltner',
  'Klinger Oscillator': 'Bộ dao động Klinger',
  'Know Sure Thing': 'Điều biết chắc chắn',
  'Least Squares Moving Average': 'Đường Trung bình động Bình phương tối thiểu',
  'Linear Regression Curve': 'Đường cong Hồi quy Tuyến tính',
  'MA Cross': 'MA Cross',
  'MA with EMA Cross': 'MA với đường chéo EMA',
  'MA/EMA Cross': 'Đường chéo MA/EMA',
  MACD: 'MACD',
  'Mass Index': 'Chỉ số Khối',
  'McGinley Dynamic': 'Chỉ số Năng động McGinley',
  Momentum: 'Xung lượng',
  'Money Flow Index': 'Dòng tiền',
  'Moving Average Channel': 'Kênh Moving Average',
  'Moving Average Exponential': 'Đường Trung bình động Hàm mũ',
  'Moving Average Weighted': 'Đường Trung bình động gia quyền',
  'Moving Average': 'Đường Trung bình động',
  'Net Volume': 'Khối lượng ròng',
  'On Balance Volume': 'Khối lượng Cân bằng',
  'Parabolic SAR': 'SAR dạng đồ thị Parabol',
  'Pivot Points Standard': 'ĐIểm Pivot Tiêu chuẩn',
  'Price Channel': 'Kênh Giá',
  'Price Oscillator': 'Dao động giá',
  'Price Volume Trend': 'Xu hướng thay đổi Giá và Khối lượng',
  'Rate Of Change': 'Tỷ lệ Thay đổi giá',
  'Relative Strength Index': 'Chỉ số Sức mạnh tương đối',
  'Relative Vigor Index': 'Chỉ số Vigor tương đối',
  'Relative Volatility Index': 'Chỉ số Biến động tương đối',
  'Session Volume': 'Lượng Phiên',
  'SMI Ergodic Indicator/Oscillator': 'Chỉ báo / Dao động SMI Ergodic',
  'Smoothed Moving Average': 'Đường Trung bình động trơn',
  'Stochastic RSI': 'Chỉ số dao động RSI Stochastic',
  Stochastic: 'Stochastic',
  'Triple EMA': 'Triple EMA',
  TRIX: 'TRIX',
  'True Strength Index': 'Chỉ báo True Strength',
  'Ultimate Oscillator': 'Chỉ báo Dao động cuối cùng UO',
  'Visible Range': 'Dải hiển thị',
  'Volume Oscillator': 'Chỉ báo Khối lượng Dao động',
  Volume: 'Khối lượng',
  'Vortex Indicator': 'Chỉ báo Vortex',
  VWAP: 'VWAP',
  VWMA: 'VWMA',
  'Williams %R': 'Williams %R',
  'Williams Alligator': 'Chỉ báo Williams Alligator',
  'Williams Fractal': 'Chỉ báo Williams Fractal',
  'Zig Zag': 'Zig Zag',
};
