/**
 * Owner: borden@kupotech.com
 */
export default {
  'Accumulation/Distribution': '累积/派发线(Accumulation/Distribution)',
  'Accumulative Swing Index': '振动升降指标(ASI)',
  'Advance/Decline': '涨跌比(Advance/Decline)',
  'Arnaud Legoux Moving Average': '阿诺勒古移动平均线(Arnaud Legoux Moving Average)',
  Aroon: '阿隆指标(Aroon)',
  ASI: '振动升降指标(ASI)',
  'Average Directional Index': '平均趋向指数(Average Directional Index)',
  'Average True Range': '真实波动幅度均值(Average True Range)',
  'Awesome Oscillator': '动量震荡指标(Awesome Oscillator)',
  'Balance of Power': '均势指标(Balance of Power)',
  'Bollinger Bands %B': '布林带 %B(Bollinger Bands %B)',
  'Bollinger Bands Width': '布林带宽度(Bollinger Bands Width)',
  'Bollinger Bands': '布林带(Bollinger Bands)',
  'Chaikin Money Flow': '蔡金资金流量(Chaikin Money Flow)',
  'Chaikin Oscillator': '蔡金资金流量震荡指标(Chaikin Oscillator)',
  'Chande Kroll Stop': '钱德克罗止损(Chande Kroll Stop)',
  'Chande Momentum Oscillator': '钱德动量摆动指标(Chande Momentum Oscillator)',
  'Chop Zone': '波动区间(Chop Zone)',
  'Choppiness Index': '波动指数(Choppiness Index)',
  'Commodity Channel Index': '商品路径指标(Commodity Channel Index)',
  'Connors RSI': '康纳相对强弱指指数(CRSI)',
  'Coppock Curve': '估波曲线(Coppock Curve)',
  'Correlation Coefficient': '相关系数(Correlation Coefficient)',
  CRSI: '康纳相对强弱指指数(CRSI)',
  'Detrended Price Oscillator': '非趋势价格摆动指标(Detrended Price Oscillator)',
  'Directional Movement': '动向指标(Directional Movement)',
  'Donchian Channels': '唐奇安通道(Donchian Channels)',
  'Double EMA': '双指数移动平均线(Double EMA)',
  'Ease Of Movement': '简易波动指标(Ease Of Movement)',
  'Elder\'s Force Index': '艾达尔强力指数(Elder\'s Force Index)',
  'EMA Cross': 'EMA交叉',
  Envelopes: '包络线(Envelope)',
  'Fisher Transform': '费舍尔转换(Fisher Transform)',
  'Fixed Range': '固定范围',
  'Historical Volatility': '历史波动率(Historical Volatility)',
  'Hull Moving Average': '船体移动平均线(Hull Moving Average)',
  'Ichimoku Cloud': '一目均衡表(Ichimoku Cloud)',
  KDJ: 'KDJ',
  'Keltner Channels': '肯特纳通道(Keltner Channels)',
  'Klinger Oscillator': '克林格成交量摆动指标(Klinger Oscillator)',
  'Know Sure Thing': '加权总和变动率(Know Sure Thing)',
  'Least Squares Moving Average': '最小二乘移动平均线(Least Squares Moving Average)',
  'Linear Regression Curve': '线性回归曲线(Linear Regression Curve)',
  'MA Cross': '移动揉搓线(MA Cross)',
  'MA with EMA Cross': 'MA与EAM交叉',
  'MA/EMA Cross': 'MA/EMA交叉',
  MACD: 'MACD',
  'Mass Index': '梅斯线(Mass Index)',
  'McGinley Dynamic': '金利动态指标(McGinley Dynamic)',
  Momentum: '动量指标(Momentum)',
  'Money Flow Index': '资金流量(Money Flow)',
  'Moving Average Channel': '移动平均线通道(Moving Average Channel)',
  'Moving Average Exponential': '指数移动平均线(Moving Average Exponential)',
  'Moving Average Weighted': '加权移动平均线(Moving Average Weighted)',
  'Moving Average': '移动平均线(Moving Average)',
  'Net Volume': '净成交量(Net Volume)',
  'On Balance Volume': '能量潮指标(On Balance Volume)',
  'Parabolic SAR': '抛物线转向指标(Parabolic SAR)',
  'Pivot Points Standard': '轴枢点 - 标准(Pivot Points Standard)',
  'Price Channel': '价格通道(Price Channel)',
  'Price Oscillator': '价格摆动指标(Price Oscillator)',
  'Price Volume Trend': '价量趋势指标(Price Volume Trend)',
  'Rate Of Change': '变化速率(Rate Of Change)',
  'Relative Strength Index': '相对强弱指标(Relative Strength Index)',
  'Relative Vigor Index': '相对能量指数(Relative Vigor Index)',
  'Relative Volatility Index': '相对离散指数(Relative Volatility Index)',
  'Session Volume': '时间段成交量',
  'SMI Ergodic Indicator/Oscillator': 'SMI 遍历性指标(SMI Ergodic Indicator/Oscillator)',
  'Smoothed Moving Average': '平滑移动平均线(Smoothed Moving Average)',
  'Stochastic RSI': '随机相对强弱指数(Stoch RSI)',
  Stochastic: '随机指数(Stochastic)',
  'Triple EMA': '三重指数平滑平均线(Triple EMA)',
  TRIX: '三重指数平滑移动平均线(TRIX)',
  'True Strength Index': '真实强度指标(True Strength Index)',
  'Ultimate Oscillator': '终极波动指标(Ultimate Oscillator)',
  'Visible Range': '可视范围',
  'Volume Oscillator': '成交量摆动指标(Volume Oscillator)',
  Volume: '成交量(Volume)',
  'Vortex Indicator': '旋涡指标(Vortex Indicator)',
  VWAP: '成交量加权平均价(VWAP)',
  VWMA: '成交量加权移动平均值(VWMA)',
  'Williams %R': '威廉姆斯指标(Williams %R)',
  'Williams Alligator': '威廉姆斯鳄鱼线(Williams Alligator)',
  'Williams Fractal': '威廉姆斯分形指标(Williams Fractal)',
  'Zig Zag': '之字转向(Zig Zag)',
};
