/**
 * Owner: borden@kupotech.com
 */
export default {
  'Accumulation/Distribution': '累積/分配線',
  'Accumulative Swing Index': '振動升降指標(ASI)',
  'Advance/Decline': '價格漲落線',
  'Arnaud Legoux Moving Average': 'Arnaud Legoux移動平均',
  Aroon: '阿隆指標',
  ASI: '振動升降指標(ASI)',
  'Average Directional Index': '平均定向指數',
  'Average True Range': '真實波動幅度均值',
  'Awesome Oscillator': '動量震盪指標',
  'Balance of Power': '均勢',
  'Bollinger Bands %B': '布林線 %B',
  'Bollinger Bands Width': '布林線帶寬',
  'Bollinger Bands': '布林線',
  'Chaikin Money Flow': '蔡金資金流量',
  'Chaikin Oscillator': '蔡金震盪指標',
  'Chande Kroll Stop': '錢德克羅停損',
  'Chande Momentum Oscillator': '錢德動量擺動指標',
  'Chop Zone': '波動區域',
  'Choppiness Index': '波動指數',
  'Commodity Channel Index': '順勢指標',
  'Connors RSI': 'Connors RSI(CRSI)',
  'Coppock Curve': '估波曲線',
  'Correlation Coefficient': '相關係數',
  CRSI: 'CRSI',
  'Detrended Price Oscillator': '區間震盪指標(Detrended Price Oscillator)',
  'Directional Movement': '動向指標',
  'Donchian Channels': '唐奇安通道',
  'Double EMA': '雙指數移動平均',
  'Ease Of Movement': '簡易波動指標',
  'Elder\'s Force Index': '艾達爾強力指數(EFI)',
  'EMA Cross': 'EMA 交叉',
  Envelopes: '包路線',
  'Fisher Transform': '弗雪變換',
  'Fixed Range': '固定範圍',
  'Historical Volatility': '歷史波動率',
  'Hull Moving Average': '船體移動平均線',
  'Ichimoku Cloud': '一目均衡表',
  KDJ: 'KDJ',
  'Keltner Channels': '肯特纳通道',
  'Klinger Oscillator': '克林格成交量擺動指標',
  'Know Sure Thing': '應用確定指標',
  'Least Squares Moving Average': '最小平方移動平均線',
  'Linear Regression Curve': '線性回歸曲線',
  'MA Cross': '移动揉搓線',
  'MA with EMA Cross': 'MA與EAM交叉',
  'MA/EMA Cross': 'MA/EAM交叉',
  MACD: 'MACD 指數平滑異同移動平均線',
  'Mass Index': '梅斯線',
  'McGinley Dynamic': 'McGinley 動態指標',
  Momentum: '動量',
  'Money Flow Index': '資金流量',
  'Moving Average Channel': '移動平均通道(Moving Average Channel)',
  'Moving Average Exponential': '指數移動平均',
  'Moving Average Weighted': '移動加權',
  'Moving Average': '移動平均',
  'Net Volume': '淨量',
  'On Balance Volume': '能量潮',
  'Parabolic SAR': '拋物線',
  'Pivot Points Standard': '軸樞點 - 標準(Pivot Points Standard)',
  'Price Channel': '價格通道(Price Channel)',
  'Price Oscillator': '價格震盪指標',
  'Price Volume Trend': '價量趨勢指標',
  'Rate Of Change': '變化速率',
  'Relative Strength Index': '相對強弱指數',
  'Relative Vigor Index': '相對能量指數',
  'Relative Volatility Index': '相對離散指數',
  'Session Volume': '交易時段成交量',
  'SMI Ergodic Indicator/Oscillator': 'SMI遍歷性指標(SMI Ergodic Indicator/Oscillator)',
  'Smoothed Moving Average': '平滑移動平均',
  'Stochastic RSI': '隨機相對擺盪',
  Stochastic: 'KD 隨機指標',
  'Triple EMA': '三指數移動平均線(Triple EMA)',
  TRIX: '三重平滑均線',
  'True Strength Index': '真實強度指標',
  'Ultimate Oscillator': '終極震盪指標',
  'Visible Range': '可視範圍',
  'Volume Oscillator': '成交量擺動指標(Volume Oscillator)',
  Volume: '成交量',
  'Vortex Indicator': '渦流指標',
  VWAP: '成交量加權平均價(VWAP)',
  VWMA: '交易量加權移動平均',
  'Williams %R': '威廉姆指數',
  'Williams Alligator': '威廉姆鱷魚',
  'Williams Fractal': '威廉姆分型',
  'Zig Zag': '拋物線轉向',
};
