import { InviteBenefits } from 'src/components/InviteBenefits';
import { customRender } from 'test/setup';

const store = {
  $entrance_signUp: {
    inviter: {
      loading: false,
      error: null,
      data: {
        rcode: 'C5V9AQ2J',
        uid: 2400000000000874,
        inviterCategory: 'TobReferral',
        rcodeType: 'TOB',
        nickname: 'he**@**.com',
        userFlag: 'He',
        avatar: '',
        message: '你的投資旅程，我來助力！加入 KuCoin，享受交易的無限可能！',
        cashbackRatio: 10,
        cashbackRatioText: '专享 10% 返现',
      },
    },
  },
};

jest.mock('src/components/InviteBenefits/components/Context/index.js', () => ({
  __esModule: true,
  ...jest.requireActual('src/components/InviteBenefits/components/Context/index.js'),
  useCtx: jest.fn().mockReturnValue({
    config: {
      effectiveDays: 30,
      totalRewardAmount: '10800',
    },
    taskList: {
      now: 1739517935767,
      tempTask: {
        financialSubtitle:
          '新用戶專享<span class="highlight"> 200 % </span>年化收益，高額交易者更可獲得高達<span class="highlight"> 2,500 USDT </span>的額外獎勵。',
        taskStartTime: 1739517935764,
        taskEndTime: 1740727535764,
        limitTaskInfo: {
          subtitle: '高達<span class="highlight"> 10,500 USDT </span>合約體驗金',
          taskStatus: null,
          prizeStatus: null,
          userDepositAmount: null,
          userTradeAmount: null,
          userLevel: null,
          limitTaskLevel: [
            {
              level: 1,
              startTradeAmount: '1000',
              startDepositAmount: '100',
              endTradeAmount: '10000',
              endDepositAmount: '1000',
              prizeCode: 'newuser0228_12deposit100',
              currency: 'USDT',
              prizeName: '福利中心新客入金-12.23入金100送100',
              prizeType: 9,
              prizeAmount: '100',
              prizeConfig: {
                code: 'futures_trial_fund-20240820154617666',
                extra: {
                  code: 'futures_trial_fund-20240820154617666',
                  amount: '100',
                  currency: 'USDT',
                  issueType: null,
                  sendAmount: null,
                  voteTimes: null,
                  quota: null,
                  ext: null,
                  trialType: null,
                  minTradingVolume: null,
                  minTotalTradingAmount: null,
                  minCloseRealisedPnl: null,
                  minExtract: null,
                  maxExtract: null,
                  expireType: null,
                  activationExpiryAt: null,
                  effectiveDurition: null,
                  useExpireType: null,
                  useExpiryAt: null,
                  useDurition: null,
                  maxLeverage: null,
                  createdAt: null,
                  updatedAt: null,
                  discountRate: null,
                  minProfit: null,
                  maxProfit: null,
                  minDurition: null,
                  minTradeCount: null,
                  deductRatio: null,
                  symbolType: null,
                  couponType: null,
                  interestRate: null,
                  incomeLimit: null,
                  principalLimit: null,
                  incomeLimitCurrency: null,
                  incomeLimitType: null,
                  expireTime: null,
                  limitProduct: null,
                },
                currency: 'USDT',
                campaignName: '福利中心新客入金-12.23入金100送100',
                rewardId: null,
                webUrl: null,
                appUrl: null,
                useDurition: null,
                effectiveDurition: null,
                expireType: null,
                icon: null,
                ext: null,
                status: null,
                useExtra: null,
                type: 9,
                prizeType: 9,
              },
            },
            {
              level: 2,
              startTradeAmount: '10000',
              startDepositAmount: '1000',
              endTradeAmount: '30000',
              endDepositAmount: '5000',
              prizeCode: 'newuser0228_12deposit1k',
              currency: 'USDT',
              prizeName: '福利中心新客入金-12.23入金1000送400',
              prizeType: 9,
              prizeAmount: '400',
              prizeConfig: {
                code: 'futures_trial_fund-20240820154813464',
                extra: {
                  code: 'futures_trial_fund-20240820154813464',
                  amount: '400',
                  currency: 'USDT',
                  issueType: null,
                  sendAmount: null,
                  voteTimes: null,
                  quota: null,
                  ext: null,
                  trialType: null,
                  minTradingVolume: null,
                  minTotalTradingAmount: null,
                  minCloseRealisedPnl: null,
                  minExtract: null,
                  maxExtract: null,
                  expireType: null,
                  activationExpiryAt: null,
                  effectiveDurition: null,
                  useExpireType: null,
                  useExpiryAt: null,
                  useDurition: null,
                  maxLeverage: null,
                  createdAt: null,
                  updatedAt: null,
                  discountRate: null,
                  minProfit: null,
                  maxProfit: null,
                  minDurition: null,
                  minTradeCount: null,
                  deductRatio: null,
                  symbolType: null,
                  couponType: null,
                  interestRate: null,
                  incomeLimit: null,
                  principalLimit: null,
                  incomeLimitCurrency: null,
                  incomeLimitType: null,
                  expireTime: null,
                  limitProduct: null,
                },
                currency: 'USDT',
                campaignName: '福利中心新客入金-12.23入金1000送400',
                rewardId: null,
                webUrl: null,
                appUrl: null,
                useDurition: null,
                effectiveDurition: null,
                expireType: null,
                icon: null,
                ext: null,
                status: null,
                useExtra: null,
                type: 9,
                prizeType: 9,
              },
            },
            {
              level: 3,
              startTradeAmount: '30000',
              startDepositAmount: '5000',
              endTradeAmount: '50000',
              endDepositAmount: '10000',
              prizeCode: 'newuser0228_12deposit5k',
              currency: 'USDT',
              prizeName: '福利中心新客入金-12.23入金5000送800',
              prizeType: 9,
              prizeAmount: '800',
              prizeConfig: {
                code: 'futures_trial_fund-20240820154914593',
                extra: {
                  code: 'futures_trial_fund-20240820154914593',
                  amount: '800',
                  currency: 'USDT',
                  issueType: null,
                  sendAmount: null,
                  voteTimes: null,
                  quota: null,
                  ext: null,
                  trialType: null,
                  minTradingVolume: null,
                  minTotalTradingAmount: null,
                  minCloseRealisedPnl: null,
                  minExtract: null,
                  maxExtract: null,
                  expireType: null,
                  activationExpiryAt: null,
                  effectiveDurition: null,
                  useExpireType: null,
                  useExpiryAt: null,
                  useDurition: null,
                  maxLeverage: null,
                  createdAt: null,
                  updatedAt: null,
                  discountRate: null,
                  minProfit: null,
                  maxProfit: null,
                  minDurition: null,
                  minTradeCount: null,
                  deductRatio: null,
                  symbolType: null,
                  couponType: null,
                  interestRate: null,
                  incomeLimit: null,
                  principalLimit: null,
                  incomeLimitCurrency: null,
                  incomeLimitType: null,
                  expireTime: null,
                  limitProduct: null,
                },
                currency: 'USDT',
                campaignName: '福利中心新客入金-12.23入金5000送800',
                rewardId: null,
                webUrl: null,
                appUrl: null,
                useDurition: null,
                effectiveDurition: null,
                expireType: null,
                icon: null,
                ext: null,
                status: null,
                useExtra: null,
                type: 9,
                prizeType: 9,
              },
            },
            {
              level: 4,
              startTradeAmount: '50000',
              startDepositAmount: '10000',
              endTradeAmount: '200000',
              endDepositAmount: '100000',
              prizeCode: 'newuser0228_12deposit1w',
              currency: 'USDT',
              prizeName: '福利中心新客入金-12.23入金10000送1500',
              prizeType: 9,
              prizeAmount: '1500',
              prizeConfig: {
                code: 'futures_trial_fund-20240820155117894',
                extra: {
                  code: 'futures_trial_fund-20240820155117894',
                  amount: '1500',
                  currency: 'USDT',
                  issueType: null,
                  sendAmount: null,
                  voteTimes: null,
                  quota: null,
                  ext: null,
                  trialType: null,
                  minTradingVolume: null,
                  minTotalTradingAmount: null,
                  minCloseRealisedPnl: null,
                  minExtract: null,
                  maxExtract: null,
                  expireType: null,
                  activationExpiryAt: null,
                  effectiveDurition: null,
                  useExpireType: null,
                  useExpiryAt: null,
                  useDurition: null,
                  maxLeverage: null,
                  createdAt: null,
                  updatedAt: null,
                  discountRate: null,
                  minProfit: null,
                  maxProfit: null,
                  minDurition: null,
                  minTradeCount: null,
                  deductRatio: null,
                  symbolType: null,
                  couponType: null,
                  interestRate: null,
                  incomeLimit: null,
                  principalLimit: null,
                  incomeLimitCurrency: null,
                  incomeLimitType: null,
                  expireTime: null,
                  limitProduct: null,
                },
                currency: 'USDT',
                campaignName: '福利中心新客入金-12.23入金10000送1500',
                rewardId: null,
                webUrl: null,
                appUrl: null,
                useDurition: null,
                effectiveDurition: null,
                expireType: null,
                icon: null,
                ext: null,
                status: null,
                useExtra: null,
                type: 9,
                prizeType: 9,
              },
            },
            {
              level: 5,
              startTradeAmount: '200000',
              startDepositAmount: '100000',
              endTradeAmount: null,
              endDepositAmount: null,
              prizeCode: 'newuser0228_12deposit10w',
              currency: 'USDT',
              prizeName: '福利中心新客入金-12.23入金100000送8000',
              prizeType: 9,
              prizeAmount: '8000',
              prizeConfig: {
                code: 'futures_trial_fund-20240820155155519',
                extra: {
                  code: 'futures_trial_fund-20240820155155519',
                  amount: '8000',
                  currency: 'USDT',
                  issueType: null,
                  sendAmount: null,
                  voteTimes: null,
                  quota: null,
                  ext: null,
                  trialType: null,
                  minTradingVolume: null,
                  minTotalTradingAmount: null,
                  minCloseRealisedPnl: null,
                  minExtract: null,
                  maxExtract: null,
                  expireType: null,
                  activationExpiryAt: null,
                  effectiveDurition: null,
                  useExpireType: null,
                  useExpiryAt: null,
                  useDurition: null,
                  maxLeverage: null,
                  createdAt: null,
                  updatedAt: null,
                  discountRate: null,
                  minProfit: null,
                  maxProfit: null,
                  minDurition: null,
                  minTradeCount: null,
                  deductRatio: null,
                  symbolType: null,
                  couponType: null,
                  interestRate: null,
                  incomeLimit: null,
                  principalLimit: null,
                  incomeLimitCurrency: null,
                  incomeLimitType: null,
                  expireTime: null,
                  limitProduct: null,
                },
                currency: 'USDT',
                campaignName: '福利中心新客入金-12.23入金100000送8000',
                rewardId: null,
                webUrl: null,
                appUrl: null,
                useDurition: null,
                effectiveDurition: null,
                expireType: null,
                icon: null,
                ext: null,
                status: null,
                useExtra: null,
                type: 9,
                prizeType: 9,
              },
            },
          ],
          depositAmtType: 0,
          depositChannel: '',
          depositCurrencyOperator: null,
          depositCurrency: '',
        },
        financialNewcomerTaskInfo: {
          extraApr: '0',
          financialProductId: '2310',
          taskStatus: null,
          prizeStatus: null,
          currentBoughtAmount: null,
          maxBoughtAmount: '100',
          financialBenefitSubTitle: '+ 高達 18 USDT 合約體驗金',
        },
        financialVipTaskInfo: {
          extraApr: '0',
          financialProductId: '2451',
          taskStatus: null,
          prizeStatus: null,
          currentBoughtAmount: null,
          maxBoughtAmount: '500000',
          financialBenefitSubTitle: '+ 高達 2,500 USDT 合約體驗金',
        },
      },
    },
  }),
}));

jest.mock('src/components/InviteBenefits/hooks/useEarnDetailInfo', () => ({
  __esModule: true,
  default: (id) =>
    jest.fn().mockReturnValue(
      id == 2310
        ? {
            success: true,
            code: 200,
            msg: 'success',
            timestamp: 1739689558782,
            data: {
              product_id: 2310,
              category: 'ACTIVITY',
              type: 'MULTI_TIME',
              name: 'USDT-7D',
              tags: ['NEWBIE'],
              currency: 'USDT',
              income_currency: 'USDT',
              group_id: 0,
              have_group: 0,
              duration: 7,
              apr: '200.0000',
              pol_apr: '0.0000',
              locked_amount: '0',
              recent_income_amount: '0',
              lock_upper_limit: '100',
              user_upper_limit: '100',
              user_lower_limit: '1',
              product_upper_limit: '100000',
              product_lower_limit: '1',
              unlock_period: 0,
              redeem_type: ['TRANS_DEMAND'],
              release_type: 'DAILY',
              interest_calc_type: 'SIMPLE',
              nodes: [],
              kyc_required: false,
              kyc_exclude: [],
              trial_type: 'NONE',
              lock_percent: '46.17',
              up_status: 'UP',
              up_end_time: null,
              apply_start_time: 1731398400000,
              apply_end_time: null,
              lock_start_time: 1731376132000,
              lock_end_time: null,
              redeem_time: 1740294078000,
              interest_date: 1739689278000,
              interest_release_date: 1739793600000,
              pol_fee_percent: '8.0000',
              return_type: 'DEFAULT',
              return_rates: [],
              is_auto_lock: 0,
              can_use_coupon: 1,
              product_kcs_deduct_enable: 0,
              user_kcs_deduct_enable: 0,
              rest_lock_limit: '100',
              new_user: false,
              user_auto_lock: 0,
              status: 'ONGOING',
              start_apply_countdown: 0,
              end_apply_countdown: null,
            },
          }
        : {
            success: true,
            code: 200,
            msg: 'success',
            timestamp: 1739689558794,
            data: {
              product_id: 2451,
              category: 'ACTIVITY',
              type: 'MULTI_TIME',
              name: 'USDT-35D',
              tags: [],
              currency: 'USDT',
              income_currency: 'USDT',
              group_id: 0,
              have_group: 0,
              duration: 35,
              apr: '6.0000',
              pol_apr: '0.0000',
              locked_amount: '0',
              recent_income_amount: '0',
              lock_upper_limit: '500000',
              user_upper_limit: '500000',
              user_lower_limit: '10',
              product_upper_limit: '25000000',
              product_lower_limit: '10',
              unlock_period: 0,
              redeem_type: ['TRANS_DEMAND'],
              release_type: 'AFTER',
              interest_calc_type: 'SIMPLE',
              nodes: [],
              kyc_required: false,
              kyc_exclude: [],
              trial_type: 'NONE',
              lock_percent: '89.72',
              up_status: 'UP',
              up_end_time: null,
              apply_start_time: 1682071200000,
              apply_end_time: null,
              lock_start_time: 1682071200000,
              lock_end_time: null,
              redeem_time: 1742713278000,
              interest_date: 1739689278000,
              interest_release_date: 1742817600000,
              pol_fee_percent: '8.0000',
              return_type: 'DEFAULT',
              return_rates: [],
              is_auto_lock: 0,
              can_use_coupon: 1,
              product_kcs_deduct_enable: 0,
              user_kcs_deduct_enable: 0,
              rest_lock_limit: '500000',
              new_user: false,
              user_auto_lock: 0,
              status: 'ONGOING',
              start_apply_countdown: 0,
              end_apply_countdown: null,
            },
          },
    ),
}));

describe('test InviteBenefits', () => {
  test('test InviteBenefits', () => {
    customRender(<InviteBenefits />, store);
  });
});

describe('test InviteBenefits on Android', () => {
  const originalUserAgent = navigator.userAgent;
  beforeAll(() => {
    // Mock navigator.userAgent
    Object.defineProperty(window.navigator, 'userAgent', {
      value: 'Adr',
      configurable: true,
    });
  });
  afterAll(() => {
    // 恢复原始的 userAgent
    Object.defineProperty(window.navigator, 'userAgent', {
      value: originalUserAgent,
      configurable: true,
    });
  });
  test('test InviteBenefits', () => {
    customRender(<InviteBenefits />, store);
  });
});
