/**
 * 根据 raw-theme-tokens.json 文件生成主题文件, 使用前请先参考 grab-theme-tokens.user.js 文件抓取主题
 */

import fs from 'fs';
import path from 'path';

const ROOT = path.resolve(__dirname, '../../');
const themeSassPath = path.join(ROOT, './src/style/theme-vars.scss');

interface IRawThemeTokenItem  {
  group: string;
  tokens: { name: string, light: string, dark: string }[];
}

interface IThemeTokenItem {
  group: string;
  name: string;
  light: string;
  dark: string;
}

function standardizeThemeName(rawTokens: IRawThemeTokenItem[]) {
  const themeMap = rawTokens.reduce((acc, item) => {
    acc[item.group] = item
    return acc;
  }, {} as Record<string, IRawThemeTokenItem>);

  const getRealThemeValue = (value: string, theme: string) => {
    if (!/\//.test(value)) return value;
    const [group, name] = value.split('/');
    if (!themeMap[group]) throw new Error(`Theme group "${group}" not found`);
    const themeItem = themeMap[group].tokens.find(token => token.name === name);
    if (!themeItem) throw new Error(`Theme token "${name}" not found in group "${group}"`);
    return  getRealThemeValue(themeItem[theme], theme);
  }

  const newRawTokens: IRawThemeTokenItem[] = rawTokens.map(item => {
    const tokens = item.tokens.map(token =>  {
      return {
        name: token.name,
        light: getRealThemeValue(token.light, 'light'),
        dark: getRealThemeValue(token.dark, 'dark')
      };
    });
    return {
      group: item.group,
      tokens
    };
  });

  return newRawTokens.reduce((acc, item) => {
    const tokens: IThemeTokenItem[] = item.tokens.map(token => {
      return {
        group: item.group,
        ...token,
      };
    });

    acc.push(...tokens);
    return acc;
  }, [] as IThemeTokenItem[])
}

interface IThemeItem {
  name: string;
  light: string;
  dark: string;
}

function generateThemeName(group: string, name: string) {
  const newGroup = group.replace(/^\d+/, '')
    .trim().toLowerCase().replace(/\s+/g, '-');
  const [groupPrefix, groupPostfix = ''] = newGroup.split('-')
  const newName = name
    .toLowerCase()
    // 去掉重复的 group 名称
    .replace(newGroup, '')
    // 去掉重复的 group 前缀
    .replace(groupPrefix, '')
    .replace(groupPostfix, '')
    .replace(/\s+/g, '-')
    .replace(/\(/g, '-')
    .replace(/\)/g, '-')
    .replace(/-+/g, '-').trim()
    
  return `${newGroup}-${newName}`
    // 去掉 general 前缀
    .replace('general-', '')
    .replace(/-+/g, '-')
    .replace(/-(\d+)%?$/, ($0, $1) => $1 === '100' ? '' : $1)
    .trim()
    .replace(/(^-+|-$)/g, '')
    // 转为驼峰命名
    .replace(/-(\w)/g, (_, c) => c.toUpperCase())
}

function formatColor(color: string) {
  if (!color.includes('·')) return color;
  const [rawColor, tansparency] = color.split('·').map(item => item.trim());
  const alpha = parseFloat(tansparency) / 100;
  // 使用sass 函数 fade 来处理透明度
  return `fade(${rawColor}, ${alpha})`;
}

function getIndent(level: number) {
  return '  '.repeat(level);
}

function generateSassVariables(tokens: IThemeTokenItem[]) {
  const vars: IThemeItem[] = tokens.map(token => ({
    name: generateThemeName(token.group, token.name),
    light: formatColor(token.light),
    dark: formatColor(token.dark)
  }));

  fs.writeFileSync(
    path.join(__dirname, 'parsed-theme-tokens.json'),
    JSON.stringify(vars, null, 2));

  const lights = vars.map(item => `${item.name}: ${item.light}`).join(`,\n${getIndent(2)}`).trim();
  const darks = vars.map(item => `${item.name}: ${item.dark}`).join(`,\n${getIndent(2)}`).trim();
  const content = `// Generated by generate-themes.ts
@import './functions.scss';
$kux-theme: (
${getIndent(1)}light: (
${getIndent(2)}${lights}
${getIndent(1)}),
${getIndent(1)}dark: (
${getIndent(2)}${darks}
${getIndent(1)})
);
`;
  
  fs.writeFileSync(themeSassPath, content);
  console.log(`✅ Theme variables generated at ${themeSassPath.replace(ROOT, '.')}`);
}

function main() {
  const rawTokensPath = path.join(__dirname, 'raw-theme-tokens.json');
  if (!fs.existsSync(rawTokensPath)) {
    throw new Error('raw-theme-tokens.json not found. Please run grab-theme-tokens.user.js to generate it.');
  }

  const rawTokens: IRawThemeTokenItem[] = JSON.parse(fs.readFileSync(rawTokensPath, 'utf-8'));
  const standardizedTokens = standardizeThemeName(rawTokens);
  generateSassVariables(standardizedTokens);
  console.log(`✅ Theme tokens standardized and Sass variables generated successfully. ${standardizedTokens.length} tokens processed.`);
}

main();