/**
      * This file is auto-generated by @kucoin/api-generator
      * Owner: sean.shi@kupotech.com
      */

export type GenericResult_List_RecentlyActivitiesWebResponse__ = {
    code?: string;
    data?: Array<RecentlyActivitiesWebResponse>;
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type RecentlyActivitiesWebResponse = {
    /**
     * 预定结束时间相对于开盘时间的提前量，单位秒
     */
    arrivalLimit?: number;
    /**
     * 预约结束时间
     */
    bookEndAt?: string;
    /**
     * 币种
     */
    currency?: string;
    /**
     * 币种名称
     */
    currencyName?: string;
    /**
     * 关联币种的icon
     */
    iconUrl?: string;
    /**
     * 介绍图片
     */
    introPic?: string;
    /**
     * 是否允许预订
     */
    isAllowBook?: boolean;
    /**
     * 中文页面是否展示
     */
    isDisplay?: boolean;
    /**
     * 是否全球首发
     */
    isWorldPremiere?: boolean;
    languageInfo?: LanguageQueryReturnsParameters;
    /**
     * 提醒结束时间相对于开盘时间的提前量，单位秒
     */
    remindLimit?: number;
    /**
     * 提醒停止时间
     */
    stopReminderAt?: string;
    /**
     * 提醒状态，0 不在提醒时间，1 未点提醒，2 已点提醒
     */
    stopReminderStatus?: number;
    /**
     * 是否支持预定：0不支持；1支持
     */
    supportBook?: number;
    /**
     * 关联交易对
     */
    symbol?: string;
    /**
     * 结束倒计时
     */
    tradeCountdown?: number;
    /**
     * 交易开始时间
     */
    tradeStartAt?: string;
    /**
     * 类型
     */
    type?: string;
};

export type LanguageQueryReturnsParameters = {
    /**
     * app链接
     */
    appUrl?: string;
    /**
     * 语言
     */
    language: string;
    /**
     * 图片链接
     */
    picUrl?: string;
    /**
     * 文案
     */
    text?: string;
    /**
     * web链接
     */
    webUrl?: string;
};

export type QueryUsingGet3Data = {
    body?: never;
    path?: never;
    query: {
        /**
         * type
         */
        type: 'ACTIVITIES' | 'NEWEST';
    };
    url: '/recently/activities';
};

export type QueryUsingGet3Responses = {
    /**
     * OK
     */
    200: GenericResult_List_RecentlyActivitiesWebResponse__;
};

export type QueryUsingGet3Response = QueryUsingGet3Responses[keyof QueryUsingGet3Responses];

export type ClientOptions = { baseURL: string; };
