/**
      * This file is auto-generated by @kucoin/api-generator
      * Owner: sean.shi@kupotech.com
      */

export type GenericResult_MaintenanceStatusResponse_ = {
    code?: string;
    data?: MaintenanceStatusResponse;
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type MaintenanceStatusResponse = {
    /**
     * 是否允许撤销订单
     */
    allowCancelOrder?: boolean;
    /**
     * app通知位置
     */
    appNoticeLocation?: string;
    /**
     * 限制取消结束时间
     */
    cancelEndAt?: string;
    /**
     * 限制取消开始时间
     */
    cancelStartAt?: string;
    /**
     * 维护结束时间
     */
    endAt?: string;
    /**
     * 跳转连接
     */
    link?: string;
    maintenance?: boolean;
    /**
     * 停机范围,0:全部交易对；1：部分交易对
     */
    maintenanceScope?: number;
    maintenanceV2?: boolean;
    mnoticeLocation?: string;
    /**
     * pc通知位置
     */
    pcNoticeLocation?: string;
    /**
     * 跳转文本
     */
    redirectContent?: string;
    /**
     * 维护开始时间
     */
    startAt?: string;
    /**
     * 停机交易对列表
     */
    symbolList?: Array<string>;
    /**
     * 提示文本
     */
    title?: string;
};

export type MaintenanceStatusUsingGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * symbol
         */
        symbol?: string;
    };
    url: '/maintenance-status';
};

export type MaintenanceStatusUsingGetResponses = {
    /**
     * OK
     */
    200: GenericResult_MaintenanceStatusResponse_;
};

export type MaintenanceStatusUsingGetResponse = MaintenanceStatusUsingGetResponses[keyof MaintenanceStatusUsingGetResponses];

export type ClientOptions = { baseURL: string; };
