import { IConfig } from '@kucoin/api-generator';

const config: IConfig = {
  projectName: 'brisk-web-ssr',
  api: [
    {
      service: 'ucenter',
      outputDir: './src/api',
      baseURL: '/_api/ucenter',
      swaggerUrl: 'https://inner.sit.kucoin.net/ucenter/v3/api-docs',
      apiClient: 'gbiz-next/commonRequest',
      include: ['/locale', '/user-info', '/user/locale', '/country-codes'],
      exclude: [],
    },
    {
      service: 'growth-config',
      outputDir: './src/api',
      baseURL: '/_api/growth-config',
      swaggerUrl: 'https://inner.sit.kucoin.net/growth-config/v3/api-docs',
      apiClient: 'gbiz-next/commonRequest',
      include: ['/get/white/config', '/get/client/config/codes'],
      exclude: [],
    },
    {
      service: 'currency',
      outputDir: './src/api',
      baseURL: '/_api/currency',
      swaggerUrl: 'https://inner.sit.kucoin.net/currency/v3/api-docs',
      apiClient: 'gbiz-next/commonRequest',
      include: ['/rates', '/v2/prices'],
      exclude: [],
    },
    {
      service: 'trade-front',
      outputDir: './src/api',
      baseURL: '/_api/trade-front',
      swaggerUrl: 'https://inner.sit.kucoin.net/trade-front/v3/api-docs',
      apiClient: 'gbiz-next/commonRequest',
      include: ['/maintenance-status'],
      exclude: [],
    },
    {
      service: 'welfare',
      outputDir: './src/api',
      baseURL: '/_api/welfare',
      swaggerUrl: 'https://inner.sit.kucoin.net/welfare/v3/api-docs',
      apiClient: 'gbiz-next/commonRequest',
      include: [
        '/web/get-welfare',
        '/web/receive2phone',
        '/web/welfare-detail-phone',
        '/web/receiveV2',
        '/web/v2/welfare-detail',
        '/web/receive2code',
        '/web/welfare-detail',
        '/web/welfare-detail/hasMore',
      ],
      exclude: [],
    },
    {
      service: 'currency-front',
      outputDir: './src/api',
      baseURL: '/_api/currency-front',
      swaggerUrl: 'https://inner.sit.kucoin.net/currency-front/v3/api-docs',
      apiClient: 'gbiz-next/commonRequest',
      include: ['/recently/activities'],
      exclude: [],
    },
    {
      service: 'discover-front',
      outputDir: './src/api',
      baseURL: '/_api/discover-front',
      swaggerUrl: 'https://inner.sit.kucoin.net/discover-front/v3/api-docs',
      apiClient: 'gbiz-next/commonRequest',
      include: ['/spl'],
      exclude: [],
    },
    {
      service: 'user-dismiss',
      outputDir: './src/api',
      swaggerUrl: 'https://inner.sit.kucoin.net/user-dismiss/v3/api-docs',
      baseURL: '/_api/user-dismiss',
      apiClient: 'gbiz-next/commonRequest',
      include: ['/dismiss/kyc/status'],
      exclude: [],
    },
    {
      service: 'chameleon',
      outputDir: './src/api',
      swaggerUrl: 'https://inner.sit.kucoin.net/chameleon/v3/api-docs',
      baseURL: '/_api/chameleon',
      apiClient: 'gbiz-next/commonRequest',
      include: ['/trade-status'],
      exclude: [],
    },
    {
      service: 'account-front',
      outputDir: './src/api',
      swaggerUrl: 'https://inner.sit.kucoin.net/account-front/v3/api-docs',
      baseURL: '/_api/account-front',
      apiClient: 'gbiz-next/commonRequest',
      include: ['/query/total-balance'],
      exclude: [],
    },
    {
      service: 'kucoin-config',
      outputDir: './src/api',
      swaggerUrl: 'https://inner.sit.kucoin.net/kucoin-config/v3/api-docs',
      baseURL: '/_api/kucoin-config',
      apiClient: 'gbiz-next/commonRequest',
      include: ['/community/group'],
      exclude: [],
    },
    {
      service: 'platform-reward',
      outputDir: './src/api',
      swaggerUrl: 'https://inner.sit.kucoin.net/platform-reward/v3/api-docs',
      baseURL: '/_api/platform-reward',
      apiClient: 'gbiz-next/commonRequest',
      include: ['/newcomer/user/homepage/info'],
      exclude: [],
    },
    {
      service: 'resource-position',
      outputDir: './src/api',
      baseURL: '/_api/resource-position',
      swaggerUrl: 'https://inner.sit.kucoin.net/resource-position/v3/api-docs',
      apiClient: 'gbiz-next/commonRequest',
      include: [
        '/position',
      ],
      exclude: [],
    },
  ],
};

export default config;
