/**
 * This file is auto-generated by @kucoin/api-generator
 * Owner: sean.shi@kupotech.com
 */

import type {
  Client,
  Options as ClientOptions,
  TDataShape,
} from '../__kucoin_api_common_fetch__/client-core.types';
import { client as _apiClient } from './client.gen';
import type {
  CreateSubUserUsingPost1Data,
  CreateSubUserUsingPost1Response,
  DeletePasskeyUsingDeleteData,
  DeletePasskeyUsingDeleteResponse,
  GetUserApiKeysUsingGet1Data,
  GetUserApiKeysUsingGet1Response,
  QueryUserSubAccessUsingGetData,
  QueryUserSubAccessUsingGetResponse,
} from './types.gen';

export type Options<TData extends TDataShape = TDataShape> = ClientOptions<TData> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * 获取用户api列表
 * api列表
 */
export const getUserApiKeysUsingGet1 = (options?: Options<GetUserApiKeysUsingGet1Data>) => {
  return (options?.client ?? _apiClient).get<GetUserApiKeysUsingGet1Response>({
    url: '/v2/api-keys',
    ...(options || {}),
  });
};

/**
 * 获取用户子账号权限
 */
export const queryUserSubAccessUsingGet = (options?: Options<QueryUserSubAccessUsingGetData>) => {
  return (options?.client ?? _apiClient).get<QueryUserSubAccessUsingGetResponse>({
    url: '/v1/sub/user/access',
    ...(options || {}),
  });
};

/**
 * 删除passkey
 */
export const deletePasskeyUsingDelete = (
  query: DeletePasskeyUsingDeleteData['query'],
  options?: Options<DeletePasskeyUsingDeleteData>,
) => {
  return (options?.client ?? _apiClient).delete<DeletePasskeyUsingDeleteResponse>({
    url: '/passkey/delete',
    query,
    ...(options || {}),
  });
};

/**
 * 母账户创建子账户
 * 端上此接口只能创建普通子账号
 */
export const createSubUserUsingPost1 = (
  body?: CreateSubUserUsingPost1Data['body'],
  options?: Options<CreateSubUserUsingPost1Data>,
) => {
  return (options?.client ?? _apiClient).post<CreateSubUserUsingPost1Response>({
    url: '/v2/sub/user/create',
    body,
    ...(options || {}),
    headers: {
      'Content-Type': 'application/json',
      ...(options?.headers || {}),
    },
  });
};
