/**
 * This file is auto-generated by @kucoin/api-generator
 * Owner: sean.shi@kupotech.com
 */

export type ApiKeyDetailsResponse = {
  /**
   * api key
   */
  apiKey?: string;
  /**
   * api 名称
   */
  apiName?: string;
  /**
   * apikey版本号
   */
  apiVersion?: number;
  /**
   * API拥有的权限组信息
   */
  authGroupMap?: {
    [key: string]: boolean;
  };
  /**
   * broker唯一标识
   */
  brokerId?: string;
  /**
   * 创建时间
   */
  createdAt?: string;
  /**
   * 当前ip
   */
  currentIp?: string;
  /**
   * ip白名单
   */
  ipWhitelist?: string;
  /**
   * ip白名单作用范围
   */
  ipWhitelistScope?: string;
  /**
   * ip白名单状态：0.禁用 1.启用
   */
  ipWhitelistStatus?: number;
  /**
   * 是否激活
   */
  isActivated?: boolean;
  /**
   * API可开通的权限组信息
   */
  permissionMap?: {
    [key: string]: boolean;
  };
  /**
   * 子账号名称
   */
  subName?: string;
};

export type GenericResult_list_apiKeyDetailsResponse__ = {
  code?: string;
  data?: Array<ApiKeyDetailsResponse>;
  msg?: string;
  retry?: boolean;
  success?: boolean;
};

export type GenericResult_map_stringList_string___ = {
  code?: string;
  data?: {
    [key: string]: Array<string>;
  };
  msg?: string;
  retry?: boolean;
  success?: boolean;
};

export type GenericResult_Void_ = {
  code?: string;
  msg?: string;
  retry?: boolean;
  success?: boolean;
};

export type GenericResult_subAccountInformation_ = {
  code?: string;
  data?: SubAccountInformation;
  msg?: string;
  retry?: boolean;
  success?: boolean;
};

export type SubAccountInformation = {
  /**
   * 子账号权限
   */
  access?: string;
  /**
   * 创建时间
   */
  createdAt?: string;
  /**
   * 托管状态，该字段仅对托管子账号有效；0:未绑定,1:申请绑定中,2:已绑定,3:投资人解绑,4:交易团队解绑
   */
  hostedStatus?: number;
  /**
   * 子账号开通交易类型列表；配置来自 user.trade_type
   */
  openedTradeTypes?: Array<string>;
  /**
   * 备注
   */
  remarks?: string;
  /**
   * 状态
   */
  status?: number;
  /**
   * 子账号名
   */
  subName?: string;
  /**
   * 子账号权限；母账号控制，配置来自 user_permission
   */
  tradeTypes?: Array<string>;
  /**
   * 子账号类型
   */
  type?: number;
  /**
   * 子账号UID
   */
  uid?: number;
  /**
   * 子账号ID
   */
  userId?: string;
};

export type CreateAChildAccountForParentAccount = {
  /**
   * 密码
   */
  password: string;
  /**
   * 备注
   */
  remarks?: string;
  /**
   * 子账号名称
   */
  subName: string;
  /**
   * 交易权限
   */
  tradeTypes?: Array<string>;
  /**
   * 子账户类型
   */
  type?: number;
};

export type GetUserApiKeysUsingGet1Data = {
  body?: never;
  path?: never;
  query?: never;
  url: '/v2/api-keys';
};

export type GetUserApiKeysUsingGet1Responses = {
  /**
   * OK
   */
  200: GenericResult_list_apiKeyDetailsResponse__;
};

export type GetUserApiKeysUsingGet1Response =
  GetUserApiKeysUsingGet1Responses[keyof GetUserApiKeysUsingGet1Responses];

export type QueryUserSubAccessUsingGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/v1/sub/user/access';
};

export type QueryUserSubAccessUsingGetResponses = {
  /**
   * OK
   */
  200: GenericResult_map_stringList_string___;
};

export type QueryUserSubAccessUsingGetResponse =
  QueryUserSubAccessUsingGetResponses[keyof QueryUserSubAccessUsingGetResponses];

export type DeletePasskeyUsingDeleteData = {
  body?: never;
  path?: never;
  query: {
    /**
     * 凭证ID
     */
    id: string;
  };
  url: '/passkey/delete';
};

export type DeletePasskeyUsingDeleteResponses = {
  /**
   * OK
   */
  200: GenericResult_Void_;
};

export type DeletePasskeyUsingDeleteResponse =
  DeletePasskeyUsingDeleteResponses[keyof DeletePasskeyUsingDeleteResponses];

export type CreateSubUserUsingPost1Data = {
  body?: CreateAChildAccountForParentAccount;
  path?: never;
  query?: never;
  url: '/v2/sub/user/create';
};

export type CreateSubUserUsingPost1Responses = {
  /**
   * OK
   */
  200: GenericResult_subAccountInformation_;
};

export type CreateSubUserUsingPost1Response =
  CreateSubUserUsingPost1Responses[keyof CreateSubUserUsingPost1Responses];

export type ClientOptions = { baseUrl: string & {} };
