/**
      * This file is auto-generated by @kucoin/api-generator
      * Owner: sean.shi@kupotech.com
      */
import Client, { type SwaggerOptions as ClientOptions, type SwaggerTDataShape as TDataShape } from 'gbiz-next/commonRequest';
import type { GetUserApiKeysUsingGet1Data, GetUserApiKeysUsingGet1Response, GetCountryCodeListUsingGetData, GetCountryCodeListUsingGetResponse, GetLocationsUsingGetData, GetLocationsUsingGetResponse, DeletePasskeyUsingDeleteData, DeletePasskeyUsingDeleteResponse, CreateSubUserUsingPost1Data, CreateSubUserUsingPost1Response, GetUserInfoUsingGetData, GetUserInfoUsingGetResponse, SetUserLocaleUsingPostData, SetUserLocaleUsingPostResponse } from './types.gen';
import { client as _apiClient } from '../client.gen';
export type Options<TData extends TDataShape = TDataShape> = ClientOptions<TData> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
    disabledLang?: boolean;
};
/**
 * 获取用户api列表
 * api列表
 */
export const getUserApiKeysUsingGet1 = (options?: Options<GetUserApiKeysUsingGet1Data>) => {
  return (options?.client ?? _apiClient).pull<GetUserApiKeysUsingGet1Response>('/_api/ucenter/v2/api-keys', {
    ...(options || {})
  });
};
/**
 * 获取国际电话区号列表
 */
export const getCountryCodeListUsingGet = (options?: Options<GetCountryCodeListUsingGetData>) => {
  return (options?.client ?? _apiClient).pull<GetCountryCodeListUsingGetResponse>('/_api/ucenter/country-codes', {
    ...(options || {})
  });
};
/**
 * 获取当前位置信息
 */
export const getLocationsUsingGet = (options?: Options<GetLocationsUsingGetData>) => {
  return (options?.client ?? _apiClient).pull<GetLocationsUsingGetResponse>('/_api/ucenter/locale', {
    ...(options || {})
  });
};
/**
 * 删除passkey
 */
export const deletePasskeyUsingDelete = (params: DeletePasskeyUsingDeleteData['query'], options?: Options<DeletePasskeyUsingDeleteData>) => {
  return (options?.client ?? _apiClient).delete<DeletePasskeyUsingDeleteResponse, DeletePasskeyUsingDeleteData['query']>('/_api/ucenter/passkey/delete', params, {
    ...(options || {})
  });
};
/**
 * 母账户创建子账户
 * 端上此接口只能创建普通子账号
 */
export const createSubUserUsingPost1 = (data?: CreateSubUserUsingPost1Data['body'], options?: Options<CreateSubUserUsingPost1Data>) => {
  return (options?.client ?? _apiClient).post<CreateSubUserUsingPost1Response, CreateSubUserUsingPost1Data['body']>('/_api/ucenter/v2/sub/user/create', data, {
    ...(options || {})
  });
};
/**
 * 获取用户信息
 */
export const getUserInfoUsingGet = (options?: Options<GetUserInfoUsingGetData>) => {
  return (options?.client ?? _apiClient).pull<GetUserInfoUsingGetResponse>('/_api/ucenter/user-info', {
    ...(options || {})
  });
};
/**
 * 设置货币、语言、时区
 */
export const setUserLocaleUsingPost = (data?: SetUserLocaleUsingPostData['query'], options?: Options<SetUserLocaleUsingPostData>) => {
  return (options?.client ?? _apiClient).post<SetUserLocaleUsingPostResponse, SetUserLocaleUsingPostData['query']>('/_api/ucenter/user/locale', data, {
    ...(options || {}),
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      ...(options?.headers || {})
    }
  });
};
