// This file is auto-generated by sync-icons script
// Do not edit manually.
export type { IIconProps } from './kc-icon';
import ActivityCenterIcon from './icons/activity-center';
import AddFilledIcon from './icons/add-filled';
import AddPaymentIcon from './icons/add-payment';
import AddfavoritesIcon from './icons/addfavorites';
import AddressSwitchIcon from './icons/address-switch';
import AirdropIcon from './icons/airdrop';
import AlertSelectIcon from './icons/alert-select';
import AlertUnselectIcon from './icons/alert-unselect';
import AllnetworkIcon from './icons/allnetwork';
import AlphaIcon from './icons/alpha';
import AnnouncementIcon from './icons/announcement';
import AnnouncementBoardIcon from './icons/announcement-board';
import ApiIcon from './icons/api';
import ApiThinIcon from './icons/api-thin';
import AppdownloadIcon from './icons/appdownload';
import ApproveIcon from './icons/approve';
import ApprovesIcon from './icons/approves';
import ArchiveIcon from './icons/archive';
import ArrowDownIcon from './icons/arrow-down';
import ArrowLeftIcon from './icons/arrow-left';
import ArrowLeft2Icon from './icons/arrow-left2';
import ArrowRightIcon from './icons/arrow-right';
import ArrowRight2Icon from './icons/arrow-right2';
import ArrowUpIcon from './icons/arrow-up';
import AssetOverviewIcon from './icons/asset-overview';
import AuthenticationIcon from './icons/authentication';
import BackWithcircleIcon from './icons/back-withcircle';
import BitcoinIcon from './icons/bitcoin';
import BonusIcon from './icons/bonus';
import BorrowIcon from './icons/borrow';
import BorrowAndRepayIcon from './icons/borrow-and-repay';
import BorrowBoldIcon from './icons/borrow-bold';
import BrawlIcon from './icons/brawl';
import BrokerIcon from './icons/broker';
import BuyCryptoIcon from './icons/buy-crypto';
import BuyCrypto2Icon from './icons/buy-crypto2';
import CalculatorIcon from './icons/calculator';
import CameraIcon from './icons/camera';
import CampaignIcon from './icons/campaign';
import CandelIcon from './icons/candel';
import CarIcon from './icons/car';
import CardIcon from './icons/card';
import ChangemodeIcon from './icons/changemode';
import ChatIcon from './icons/chat';
import ClassicversionIcon from './icons/classicversion';
import ClearAllIcon from './icons/clear-all';
import CloseIcon from './icons/close';
import CloseFilledIcon from './icons/close-filled';
import CloseWithcircleIcon from './icons/close-withcircle';
import CollapsesidebarIcon from './icons/collapsesidebar';
import ConnectmanageIcon from './icons/connectmanage';
import ContractInteractionIcon from './icons/contract-interaction';
import ConvertIcon from './icons/convert';
import ConvertBoldIcon from './icons/convert-bold';
import CopyIcon from './icons/copy';
import CouponsIcon from './icons/coupons';
import CustomerIcon from './icons/customer';
import CustomerServiceIcon from './icons/customer-service';
import DarkModeIcon from './icons/dark-mode';
import DashboardIcon from './icons/dashboard';
import DeleteIcon from './icons/delete';
import Delete2Icon from './icons/delete2';
import DelistIcon from './icons/delist';
import DelistingIcon from './icons/delisting';
import DepositIcon from './icons/deposit';
import DepositBoldIcon from './icons/deposit-bold';
import DeviceUnlockIcon from './icons/device-unlock';
import DiscordIcon from './icons/discord';
import DocumentsIcon from './icons/documents';
import DoubleLeftIcon from './icons/double-left';
import DoubleRightIcon from './icons/double-right';
import DragIcon from './icons/drag';
import EarnBoldIcon from './icons/earn-bold';
import EarnPigIcon from './icons/earn-pig';
import EarnPromotionIcon from './icons/earn-promotion';
import EditIcon from './icons/edit';
import EdittagIcon from './icons/edittag';
import EduceIcon from './icons/educe';
import EmailIcon from './icons/email';
import EmailSendIcon from './icons/email-send';
import EthStakingIcon from './icons/eth-staking';
import ExitIcon from './icons/exit';
import ExtendsidebarIcon from './icons/extendsidebar';
import EyeCloseIcon from './icons/eye-close';
import EyeOpenIcon from './icons/eye-open';
import FaceidIcon from './icons/faceid';
import FailIcon from './icons/fail';
import FavoriteAlertIcon from './icons/favorite-alert';
import FavoriteSelectIcon from './icons/favorite-select';
import FavoriteUnselectIcon from './icons/favorite-unselect';
import FeevipThinIcon from './icons/feevip-thin';
import FillcolorIcon from './icons/fillcolor';
import FilterIcon from './icons/filter';
import FireIcon from './icons/fire';
import FlagIcon from './icons/flag';
import FloatingWindowIcon from './icons/floating-window';
import ForbidIcon from './icons/forbid';
import FullScreenIcon from './icons/full-screen';
import FundAccountIcon from './icons/fund-account';
import FuturesAccountIcon from './icons/futures-account';
import GaIcon from './icons/ga';
import GanewIcon from './icons/ganew';
import GasIcon from './icons/gas';
import GoogleIcon from './icons/google';
import GoogleshoppingCartIcon from './icons/googleshopping-cart';
import HeartIcon from './icons/heart';
import HeartFillIcon from './icons/heart-fill';
import HidesidebarIcon from './icons/hidesidebar';
import HistoryIcon from './icons/history';
import HistoryBoldIcon from './icons/history-bold';
import HistoryThinIcon from './icons/history-thin';
import HomepageIcon from './icons/homepage';
import HookIcon from './icons/hook';
import IcloudIcon from './icons/icloud';
import ImgIcon from './icons/img';
import IndexPriceIcon from './icons/index-price';
import IndicatorIcon from './icons/indicator';
import InfoIcon from './icons/info';
import InfoContainIcon from './icons/info-contain';
import InfoFilledIcon from './icons/info-filled';
import InstagramIcon from './icons/instagram';
import InviteFriendsIcon from './icons/invite-friends';
import IpadIcon from './icons/ipad';
import IphoneIcon from './icons/iphone';
import KcsIcon from './icons/kcs';
import KcsStakingIcon from './icons/kcs-staking';
import KcsfeeIcon from './icons/kcsfee';
import KcslevelIcon from './icons/kcslevel';
import KcsloyaltyBoldIcon from './icons/kcsloyalty-bold';
import KcsloyaltyThinIcon from './icons/kcsloyalty-thin';
import KcspayfeeThinIcon from './icons/kcspayfee-thin';
import KeyboardClearIcon from './icons/keyboard-clear';
import KlineIcon from './icons/kline';
import Kline1Icon from './icons/kline1';
import Kline2Icon from './icons/kline2';
import Kline3Icon from './icons/kline3';
import Kline5Icon from './icons/kline5';
import KsethBoldIcon from './icons/kseth-bold';
import LanguageIcon from './icons/language';
import LayoutIcon from './icons/layout';
import LendingRateIcon from './icons/lending-rate';
import LightModeIcon from './icons/light-mode';
import LightingIcon from './icons/lighting';
import LimitIcon from './icons/limit';
import LinkIcon from './icons/link';
import LoadingIcon from './icons/loading';
import LoadingSmallIcon from './icons/loading-small';
import LocationIcon from './icons/location';
import LockedIcon from './icons/locked';
import MacIcon from './icons/mac';
import MaintenceIcon from './icons/maintence';
import MarginAccountIcon from './icons/margin-account';
import MarkPriceIcon from './icons/mark-price';
import MarketHighIcon from './icons/market-high';
import MarketLowIcon from './icons/market-low';
import MarketMoveIcon from './icons/market-move';
import MechanismIcon from './icons/mechanism';
import MenuIcon from './icons/menu';
import Menu2Icon from './icons/menu2';
import MessageReadIcon from './icons/message-read';
import MoreIcon from './icons/more';
import More2Icon from './icons/more2';
import MorefilledIcon from './icons/morefilled';
import MultiTransferIcon from './icons/multi-transfer';
import MyIcon from './icons/my';
import MyrewardsThinIcon from './icons/myrewards-thin';
import NetAssetValueIcon from './icons/net-asset-value';
import NoteIcon from './icons/note';
import NotificationIcon from './icons/notification';
import NotificationCloseIcon from './icons/notification-close';
import NoviceGuideIcon from './icons/novice-guide';
import OptionsIcon from './icons/options';
import OrdersHistoryIcon from './icons/orders-history';
import OutsidelinkIcon from './icons/outsidelink';
import PasskeyIcon from './icons/passkey';
import PasswordIcon from './icons/password';
import Password2Icon from './icons/password2';
import PdfIcon from './icons/pdf';
import PlayIcon from './icons/play';
import PlusIcon from './icons/plus';
import PoweroffIcon from './icons/poweroff';
import PriceFallIcon from './icons/price-fall';
import PriceRiseIcon from './icons/price-rise';
import ProductUpdateIcon from './icons/product-update';
import QrcodeIcon from './icons/qrcode';
import QuestionIcon from './icons/question';
import RadioSelectIcon from './icons/radio-select';
import RadioUnselectIcon from './icons/radio-unselect';
import RankingIcon from './icons/ranking';
import ReceivedIcon from './icons/received';
import RecurringBuysIcon from './icons/recurring-buys';
import RedEnvelopIcon from './icons/red-envelop';
import RedpackageIcon from './icons/redpackage';
import RefreshIcon from './icons/refresh';
import Refresh2Icon from './icons/refresh2';
import RepayIcon from './icons/repay';
import RepayBoldIcon from './icons/repay-bold';
import ResearchThinIcon from './icons/research-thin';
import RewardshubThinIcon from './icons/rewardshub-thin';
import RightdownArrowIcon from './icons/rightdown-arrow';
import RightupArrowIcon from './icons/rightup-arrow';
import RobotoIcon from './icons/roboto';
import RocketIcon from './icons/rocket';
import ScanIcon from './icons/scan';
import SearchIcon from './icons/search';
import SecurityErrorfilledIcon from './icons/security-errorfilled';
import SecurityLockIcon from './icons/security-lock';
import SecuritySettingIcon from './icons/security-setting';
import SecuritySettingfilledIcon from './icons/security-settingfilled';
import SecurityThinIcon from './icons/security-thin';
import SecurityUnknownfilledIcon from './icons/security-unknownfilled';
import SecurityWarningIcon from './icons/security-warning';
import SecurityWarningfilledIcon from './icons/security-warningfilled';
import SentIcon from './icons/sent';
import SettingIcon from './icons/setting';
import SettingThinIcon from './icons/setting-thin';
import ShareIcon from './icons/share';
import ShareinviteThinIcon from './icons/shareinvite-thin';
import ShopIcon from './icons/shop';
import ShopAddIcon from './icons/shop-add';
import ShoppingBagIcon from './icons/shopping-bag';
import SmallhookIcon from './icons/smallhook';
import Smallhook2Icon from './icons/smallhook2';
import SnailIcon from './icons/snail';
import SortdownIcon from './icons/sortdown';
import SortupIcon from './icons/sortup';
import StakingIcon from './icons/staking';
import StarIcon from './icons/star';
import StickIcon from './icons/stick';
import StopwatchIcon from './icons/stopwatch';
import SubIcon from './icons/sub';
import SubFilledIcon from './icons/sub-filled';
import SuccessIcon from './icons/success';
import SuccessFilledIcon from './icons/success-filled';
import SupportThinIcon from './icons/support-thin';
import SwapIcon from './icons/swap';
import TagIcon from './icons/tag';
import TelegramIcon from './icons/telegram';
import TetherIcon from './icons/tether';
import ThumbIcon from './icons/thumb';
import ThumbFilledIcon from './icons/thumb-filled';
import TradeIcon from './icons/trade';
import TradeAddIcon from './icons/trade-add';
import TradeExchangeIcon from './icons/trade-exchange';
import TradeHorizontalIcon from './icons/trade-horizontal';
import TradeInformationIcon from './icons/trade-information';
import TradeSubIcon from './icons/trade-sub';
import TradeVerticalIcon from './icons/trade-vertical';
import TradefeeIcon from './icons/tradefee';
import TradingFeeLevelIcon from './icons/trading-fee-level';
import TransferIcon from './icons/transfer';
import TransferBoldIcon from './icons/transfer-bold';
import TransferInformationIcon from './icons/transfer-information';
import Transfer2Icon from './icons/transfer2';
import TranslateIcon from './icons/translate';
import TriangleBottomIcon from './icons/triangle-bottom';
import TriangleTopIcon from './icons/triangle-top';
import TutorialIcon from './icons/tutorial';
import UnconnectIcon from './icons/unconnect';
import UnitIcon from './icons/unit';
import UnlimitedIcon from './icons/unlimited';
import UnlockedIcon from './icons/unlocked';
import UserIcon from './icons/user';
import VerificationIcon from './icons/verification';
import VerticalSwitch2Icon from './icons/vertical-switch2';
import VipCrownIcon from './icons/vip-crown';
import WaitIcon from './icons/wait';
import WalletconnectIcon from './icons/walletconnect';
import WarningIcon from './icons/warning';
import WhaleIcon from './icons/whale';
import WithdrawIcon from './icons/withdraw';
import WithdrawBoldIcon from './icons/withdraw-bold';
import XIcon from './icons/x';
import ZoominIcon from './icons/zoomin';
import ZoomoutIcon from './icons/zoomout';

export const iconMap = {
  ActivityCenterIcon: ActivityCenterIcon,
  AddFilledIcon: AddFilledIcon,
  AddPaymentIcon: AddPaymentIcon,
  AddfavoritesIcon: AddfavoritesIcon,
  AddressSwitchIcon: AddressSwitchIcon,
  AirdropIcon: AirdropIcon,
  AlertSelectIcon: AlertSelectIcon,
  AlertUnselectIcon: AlertUnselectIcon,
  AllnetworkIcon: AllnetworkIcon,
  AlphaIcon: AlphaIcon,
  AnnouncementIcon: AnnouncementIcon,
  AnnouncementBoardIcon: AnnouncementBoardIcon,
  ApiIcon: ApiIcon,
  ApiThinIcon: ApiThinIcon,
  AppdownloadIcon: AppdownloadIcon,
  ApproveIcon: ApproveIcon,
  ApprovesIcon: ApprovesIcon,
  ArchiveIcon: ArchiveIcon,
  ArrowDownIcon: ArrowDownIcon,
  ArrowLeftIcon: ArrowLeftIcon,
  ArrowLeft2Icon: ArrowLeft2Icon,
  ArrowRightIcon: ArrowRightIcon,
  ArrowRight2Icon: ArrowRight2Icon,
  ArrowUpIcon: ArrowUpIcon,
  AssetOverviewIcon: AssetOverviewIcon,
  AuthenticationIcon: AuthenticationIcon,
  BackWithcircleIcon: BackWithcircleIcon,
  BitcoinIcon: BitcoinIcon,
  BonusIcon: BonusIcon,
  BorrowIcon: BorrowIcon,
  BorrowAndRepayIcon: BorrowAndRepayIcon,
  BorrowBoldIcon: BorrowBoldIcon,
  BrawlIcon: BrawlIcon,
  BrokerIcon: BrokerIcon,
  BuyCryptoIcon: BuyCryptoIcon,
  BuyCrypto2Icon: BuyCrypto2Icon,
  CalculatorIcon: CalculatorIcon,
  CameraIcon: CameraIcon,
  CampaignIcon: CampaignIcon,
  CandelIcon: CandelIcon,
  CarIcon: CarIcon,
  CardIcon: CardIcon,
  ChangemodeIcon: ChangemodeIcon,
  ChatIcon: ChatIcon,
  ClassicversionIcon: ClassicversionIcon,
  ClearAllIcon: ClearAllIcon,
  CloseIcon: CloseIcon,
  CloseFilledIcon: CloseFilledIcon,
  CloseWithcircleIcon: CloseWithcircleIcon,
  CollapsesidebarIcon: CollapsesidebarIcon,
  ConnectmanageIcon: ConnectmanageIcon,
  ContractInteractionIcon: ContractInteractionIcon,
  ConvertIcon: ConvertIcon,
  ConvertBoldIcon: ConvertBoldIcon,
  CopyIcon: CopyIcon,
  CouponsIcon: CouponsIcon,
  CustomerIcon: CustomerIcon,
  CustomerServiceIcon: CustomerServiceIcon,
  DarkModeIcon: DarkModeIcon,
  DashboardIcon: DashboardIcon,
  DeleteIcon: DeleteIcon,
  Delete2Icon: Delete2Icon,
  DelistIcon: DelistIcon,
  DelistingIcon: DelistingIcon,
  DepositIcon: DepositIcon,
  DepositBoldIcon: DepositBoldIcon,
  DeviceUnlockIcon: DeviceUnlockIcon,
  DiscordIcon: DiscordIcon,
  DocumentsIcon: DocumentsIcon,
  DoubleLeftIcon: DoubleLeftIcon,
  DoubleRightIcon: DoubleRightIcon,
  DragIcon: DragIcon,
  EarnBoldIcon: EarnBoldIcon,
  EarnPigIcon: EarnPigIcon,
  EarnPromotionIcon: EarnPromotionIcon,
  EditIcon: EditIcon,
  EdittagIcon: EdittagIcon,
  EduceIcon: EduceIcon,
  EmailIcon: EmailIcon,
  EmailSendIcon: EmailSendIcon,
  EthStakingIcon: EthStakingIcon,
  ExitIcon: ExitIcon,
  ExtendsidebarIcon: ExtendsidebarIcon,
  EyeCloseIcon: EyeCloseIcon,
  EyeOpenIcon: EyeOpenIcon,
  FaceidIcon: FaceidIcon,
  FailIcon: FailIcon,
  FavoriteAlertIcon: FavoriteAlertIcon,
  FavoriteSelectIcon: FavoriteSelectIcon,
  FavoriteUnselectIcon: FavoriteUnselectIcon,
  FeevipThinIcon: FeevipThinIcon,
  FillcolorIcon: FillcolorIcon,
  FilterIcon: FilterIcon,
  FireIcon: FireIcon,
  FlagIcon: FlagIcon,
  FloatingWindowIcon: FloatingWindowIcon,
  ForbidIcon: ForbidIcon,
  FullScreenIcon: FullScreenIcon,
  FundAccountIcon: FundAccountIcon,
  FuturesAccountIcon: FuturesAccountIcon,
  GaIcon: GaIcon,
  GanewIcon: GanewIcon,
  GasIcon: GasIcon,
  GoogleIcon: GoogleIcon,
  GoogleshoppingCartIcon: GoogleshoppingCartIcon,
  HeartIcon: HeartIcon,
  HeartFillIcon: HeartFillIcon,
  HidesidebarIcon: HidesidebarIcon,
  HistoryIcon: HistoryIcon,
  HistoryBoldIcon: HistoryBoldIcon,
  HistoryThinIcon: HistoryThinIcon,
  HomepageIcon: HomepageIcon,
  HookIcon: HookIcon,
  IcloudIcon: IcloudIcon,
  ImgIcon: ImgIcon,
  IndexPriceIcon: IndexPriceIcon,
  IndicatorIcon: IndicatorIcon,
  InfoIcon: InfoIcon,
  InfoContainIcon: InfoContainIcon,
  InfoFilledIcon: InfoFilledIcon,
  InstagramIcon: InstagramIcon,
  InviteFriendsIcon: InviteFriendsIcon,
  IpadIcon: IpadIcon,
  IphoneIcon: IphoneIcon,
  KcsIcon: KcsIcon,
  KcsStakingIcon: KcsStakingIcon,
  KcsfeeIcon: KcsfeeIcon,
  KcslevelIcon: KcslevelIcon,
  KcsloyaltyBoldIcon: KcsloyaltyBoldIcon,
  KcsloyaltyThinIcon: KcsloyaltyThinIcon,
  KcspayfeeThinIcon: KcspayfeeThinIcon,
  KeyboardClearIcon: KeyboardClearIcon,
  KlineIcon: KlineIcon,
  Kline1Icon: Kline1Icon,
  Kline2Icon: Kline2Icon,
  Kline3Icon: Kline3Icon,
  Kline5Icon: Kline5Icon,
  KsethBoldIcon: KsethBoldIcon,
  LanguageIcon: LanguageIcon,
  LayoutIcon: LayoutIcon,
  LendingRateIcon: LendingRateIcon,
  LightModeIcon: LightModeIcon,
  LightingIcon: LightingIcon,
  LimitIcon: LimitIcon,
  LinkIcon: LinkIcon,
  LoadingIcon: LoadingIcon,
  LoadingSmallIcon: LoadingSmallIcon,
  LocationIcon: LocationIcon,
  LockedIcon: LockedIcon,
  MacIcon: MacIcon,
  MaintenceIcon: MaintenceIcon,
  MarginAccountIcon: MarginAccountIcon,
  MarkPriceIcon: MarkPriceIcon,
  MarketHighIcon: MarketHighIcon,
  MarketLowIcon: MarketLowIcon,
  MarketMoveIcon: MarketMoveIcon,
  MechanismIcon: MechanismIcon,
  MenuIcon: MenuIcon,
  Menu2Icon: Menu2Icon,
  MessageReadIcon: MessageReadIcon,
  MoreIcon: MoreIcon,
  More2Icon: More2Icon,
  MorefilledIcon: MorefilledIcon,
  MultiTransferIcon: MultiTransferIcon,
  MyIcon: MyIcon,
  MyrewardsThinIcon: MyrewardsThinIcon,
  NetAssetValueIcon: NetAssetValueIcon,
  NoteIcon: NoteIcon,
  NotificationIcon: NotificationIcon,
  NotificationCloseIcon: NotificationCloseIcon,
  NoviceGuideIcon: NoviceGuideIcon,
  OptionsIcon: OptionsIcon,
  OrdersHistoryIcon: OrdersHistoryIcon,
  OutsidelinkIcon: OutsidelinkIcon,
  PasskeyIcon: PasskeyIcon,
  PasswordIcon: PasswordIcon,
  Password2Icon: Password2Icon,
  PdfIcon: PdfIcon,
  PlayIcon: PlayIcon,
  PlusIcon: PlusIcon,
  PoweroffIcon: PoweroffIcon,
  PriceFallIcon: PriceFallIcon,
  PriceRiseIcon: PriceRiseIcon,
  ProductUpdateIcon: ProductUpdateIcon,
  QrcodeIcon: QrcodeIcon,
  QuestionIcon: QuestionIcon,
  RadioSelectIcon: RadioSelectIcon,
  RadioUnselectIcon: RadioUnselectIcon,
  RankingIcon: RankingIcon,
  ReceivedIcon: ReceivedIcon,
  RecurringBuysIcon: RecurringBuysIcon,
  RedEnvelopIcon: RedEnvelopIcon,
  RedpackageIcon: RedpackageIcon,
  RefreshIcon: RefreshIcon,
  Refresh2Icon: Refresh2Icon,
  RepayIcon: RepayIcon,
  RepayBoldIcon: RepayBoldIcon,
  ResearchThinIcon: ResearchThinIcon,
  RewardshubThinIcon: RewardshubThinIcon,
  RightdownArrowIcon: RightdownArrowIcon,
  RightupArrowIcon: RightupArrowIcon,
  RobotoIcon: RobotoIcon,
  RocketIcon: RocketIcon,
  ScanIcon: ScanIcon,
  SearchIcon: SearchIcon,
  SecurityErrorfilledIcon: SecurityErrorfilledIcon,
  SecurityLockIcon: SecurityLockIcon,
  SecuritySettingIcon: SecuritySettingIcon,
  SecuritySettingfilledIcon: SecuritySettingfilledIcon,
  SecurityThinIcon: SecurityThinIcon,
  SecurityUnknownfilledIcon: SecurityUnknownfilledIcon,
  SecurityWarningIcon: SecurityWarningIcon,
  SecurityWarningfilledIcon: SecurityWarningfilledIcon,
  SentIcon: SentIcon,
  SettingIcon: SettingIcon,
  SettingThinIcon: SettingThinIcon,
  ShareIcon: ShareIcon,
  ShareinviteThinIcon: ShareinviteThinIcon,
  ShopIcon: ShopIcon,
  ShopAddIcon: ShopAddIcon,
  ShoppingBagIcon: ShoppingBagIcon,
  SmallhookIcon: SmallhookIcon,
  Smallhook2Icon: Smallhook2Icon,
  SnailIcon: SnailIcon,
  SortdownIcon: SortdownIcon,
  SortupIcon: SortupIcon,
  StakingIcon: StakingIcon,
  StarIcon: StarIcon,
  StickIcon: StickIcon,
  StopwatchIcon: StopwatchIcon,
  SubIcon: SubIcon,
  SubFilledIcon: SubFilledIcon,
  SuccessIcon: SuccessIcon,
  SuccessFilledIcon: SuccessFilledIcon,
  SupportThinIcon: SupportThinIcon,
  SwapIcon: SwapIcon,
  TagIcon: TagIcon,
  TelegramIcon: TelegramIcon,
  TetherIcon: TetherIcon,
  ThumbIcon: ThumbIcon,
  ThumbFilledIcon: ThumbFilledIcon,
  TradeIcon: TradeIcon,
  TradeAddIcon: TradeAddIcon,
  TradeExchangeIcon: TradeExchangeIcon,
  TradeHorizontalIcon: TradeHorizontalIcon,
  TradeInformationIcon: TradeInformationIcon,
  TradeSubIcon: TradeSubIcon,
  TradeVerticalIcon: TradeVerticalIcon,
  TradefeeIcon: TradefeeIcon,
  TradingFeeLevelIcon: TradingFeeLevelIcon,
  TransferIcon: TransferIcon,
  TransferBoldIcon: TransferBoldIcon,
  TransferInformationIcon: TransferInformationIcon,
  Transfer2Icon: Transfer2Icon,
  TranslateIcon: TranslateIcon,
  TriangleBottomIcon: TriangleBottomIcon,
  TriangleTopIcon: TriangleTopIcon,
  TutorialIcon: TutorialIcon,
  UnconnectIcon: UnconnectIcon,
  UnitIcon: UnitIcon,
  UnlimitedIcon: UnlimitedIcon,
  UnlockedIcon: UnlockedIcon,
  UserIcon: UserIcon,
  VerificationIcon: VerificationIcon,
  VerticalSwitch2Icon: VerticalSwitch2Icon,
  VipCrownIcon: VipCrownIcon,
  WaitIcon: WaitIcon,
  WalletconnectIcon: WalletconnectIcon,
  WarningIcon: WarningIcon,
  WhaleIcon: WhaleIcon,
  WithdrawIcon: WithdrawIcon,
  WithdrawBoldIcon: WithdrawBoldIcon,
  XIcon: XIcon,
  ZoominIcon: ZoominIcon,
  ZoomoutIcon: ZoomoutIcon,
};
