/**
      * This file is auto-generated by @kucoin/api-generator
      * Owner: sean.shi@kupotech.com
      */

export type GenericResult_ipCountryReturnToTheBody_ = {
    code?: string;
    data?: IpCountriesReturnToTheOutsideWorld;
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type IpCountriesReturnToTheOutsideWorld = {
    /**
     * 国家码
     */
    countryCode?: string;
    /**
     * 手机区号
     */
    mobileCode?: string;
};

export type GetCountryUsingGetData = {
    body?: never;
    headers: {
        /**
         * X-IP
         */
        'X-IP': string;
    };
    path?: never;
    query?: never;
    url: '/ip/country';
};

export type GetCountryUsingGetResponses = {
    /**
     * OK
     */
    200: GenericResult_ipCountryReturnToTheBody_;
};

export type GetCountryUsingGetResponse = GetCountryUsingGetResponses[keyof GetCountryUsingGetResponses];

export type ClientOptions = { baseURL: string; };