/**
 * This file is auto-generated by @kucoin/api-generator
 * Owner: sean.shi@kupotech.com
 */
import RequestClient, { RuntimeEnvironment } from 'gbiz-next/commonRequest';
import JsBridge from 'gbiz-next/bridge';
import { IS_SERVER_ENV } from 'kc-next/env';
import { getReport } from 'gbiz-next/report';
import { responseErrorInterceptor } from '@/tools/request/showErrorInterceptor';

export const client = new RequestClient({
  projectName: 'ucenter-web-ssr',
  environment: IS_SERVER_ENV
    ? RuntimeEnvironment.SSR
    : JsBridge.isApp()
      ? RuntimeEnvironment.APP
      : RuntimeEnvironment.BROWSER,
  fingerPrintUrlList: [
    { url: '/_api/ucenter/user/phone/update', event: 'change-phone' },
    { url: '/_api/ucenter/v2/user/phone', event: 'set-phone-v2' },
    { url: '/_api/ucenter/v2/user/email', event: 'set-email-v2' },
    { url: '/_api/ucenter/v2/user/email/update', event: 'change-email-v2' },
    {
      url: '/_api/ucenter/v2/user/withdraw-password',
      event: 'set-trade-pwd-v2',
    },
    {
      url: '/_api/ucenter/v2/user/withdraw-password/update',
      event: 'change-trade-pwd-v2',
    },
    { url: '/_api/ucenter/v2/user/google2fa', event: 'set-2fa-v2' },
    { url: '/_api/ucenter/v2/user/google2fa/update', event: 'change-2fa-v2' },
    {
      url: '/_api/ucenter/v2/user/password/update',
      event: 'change-login-pwd-v2',
    },
    { url: '/_api/ucenter/v2/user/email/unbind', event: 'unbind-email-v2' },
    { url: '/_api/ucenter/v2/user/phone/unbind', event: 'unbind-phone-v2' },
    { url: '/_api/ucenter/v2/user/phone/update', event: 'change-phone-v2' },
    { url: '/_api/ucenter/user/email/update', event: 'change-email' },
    {
      url: '/_api/ucenter/user/withdraw-password/update',
      event: 'change-trade-pwd',
    },
    { url: '/_api/ucenter/user/google2fa/update', event: 'change-2fa' },
    { url: '/_api/ucenter/user/password/update', event: 'change-login-pwd' },
    {
      url: '/_api/deposit/v1/recharge/creditcard/prerecharge',
      event: 'otc-bank-deposit',
    },
    { url: '/_api/ucenter/login-verify', event: 'login-verify' },
    { url: '/_api/ucenter/rebind-phone/apply', event: 'rebind-phone' },
    { url: '/_api/ucenter/g2fa/apply', event: 'reset-g2fa' },
    {
      url: '/_api/ucenter/reset-trade-password/apply',
      event: 'reset-trade-password',
    },
    {
      url: '/_api/validation-email/email/verify',
      event: 'validation-email-verify',
    },
    { url: '/_api/ucenter/sub/api-key/add', event: 'create-sub-api' },
    { url: '/_api/ucenter/sub/api-key/update', event: 'update-sub-api' },
    {
      url: '/_api/cyber-truck-vault/sub/api-key/delete/:id',
      event: 'delete-sub-api',
      method: 'post',
    },
    {
      url: '/_api/ucenter/sub/user/reset-password',
      event: 'sub-user-reset-pwd',
    },
    { url: '/_api/ucenter/sub/user/reset-2fa', event: 'sub-user-reset-2fa' },
    {
      url: '/_api/ucenter/sub/user/reset-trading-password',
      event: 'sub-user-reset-trading-pwd',
    },
    { url: '/_api/ucenter/v2/sub/user/create', event: 'create-sub-user' },
    { url: '/_api/ucenter/aggregate-login', event: 'login' },
    { url: '/_api/payment/inner/withdraw/apply', event: 'inner-withdrawal' },
    {
      url: '/_api/market-operation/invitation/v2/mystery/obtain',
      event: 'toc-mystery-obtain',
    },
    {
      url: '/_api/market-operation/invitation/exchange/prize',
      event: 'toc-prize-exchange',
    },
    {
      url: '/_api/payment-api/pmtapi/v1/payin_order/risk/detect',
      event: 'otc-bank-risk-check',
    },
    {
      url: '/_api/payment-api/pmtapi/v1/payin_order/create',
      event: 'otc-bank-deposit',
    },
    {
      url: '/_api/payment-api/pmtapi/v2/payin_order/create',
      event: 'otc-bank-deposit-v2',
    },
    {
      url: '/_api/payment-api/pmtapi/v2/card/attach',
      event: 'fiat-deposit-add-card',
    },
    {
      url: '/_api/payment-api/api/v1/user/create_payout_account',
      event: 'pay-fiat-bind-account',
    },
    {
      url: '/_api/payment-api/api/v2/user/payout_account/delete',
      event: 'pay-fiat-delete-account',
    },
    {
      url: '/_api/payment-api/api/v3/create_payout_transaction',
      event: 'pay-fiat-withdraw',
    },
    { url: '/_api/ucenter/user/email/unbind', event: 'unbind-email' },
    { url: '/_api/ucenter/user/phone/unbind', event: 'unbind-phone' },
    { url: '/_api/payment/withdraw-address/add', event: 'withdraw-address' },
    { url: '/_api/otc/ad/online-edit', event: 'otc-ad-online-edit' },
    { url: '/_api/otc/ad/buy/putUp', event: 'otc-ad-buy-putup' },
    { url: '/_api/otc/ad/sell/putUp', event: 'otc-ad-sell-putup' },
    { url: '/_api/otc/ad/publish', event: 'otc-ad-publish' },
    {
      url: '/_api/payment/withdraw-address/delete',
      event: 'delete-withdraw-address',
    },
    {
      url: '/_api/payment/withdraw-address/batch-add',
      event: 'batch-add-withdraw-address',
    },
    { url: '/_api/cyber-truck-vault/v2/api-key', event: 'create-api' },
    { url: '/_api/cyber-truck-vault/v2/api-key/verify', event: 'verify-api' },
    { url: '/_api/cyber-truck-vault/v2/api-key/update', event: 'update-api' },
    {
      url: '/_api/cyber-truck-vault/api-key/delete/:id',
      event: 'delete-api',
      method: 'post',
    },
    { url: '/_api/ucenter/v2/sub/api-key/add', event: 'create-sub-api' },
    {
      url: '/_api/cyber-truck-vault/v2/sub/api-key/update',
      event: 'update-sub-api',
    },
    {
      url: '/_api/payment/deposit-address/get',
      event: 'query-deposit-address',
    },
    {
      url: '/_api/pmtapi/v2/instruments/wallets/attach',
      event: 'payment-instruments-attach',
    },
    {
      url: '/_api/pmtapi/v2/instruments/batch-update',
      event: 'payment-instruments-batch-update',
    },
    { url: '/_api/pool-staking/v3/locks', event: 'account-finance-buy' },
    {
      url: '/_api/novice-zone/v2/novice/open/blind/box',
      event: 'market_mystery_box',
    },
    {
      url: '/_api/payment/inner-withdraw-contract/batch-add',
      event: 'inner-withdraw-addFav',
    },
    {
      url: '/_api/payment/inner-withdraw-contract/batch-delete',
      event: 'inner-withdraw-delFav',
    },
    {
      url: '/_api/payment/innerTransfer/getUserInfoByAccount',
      event: 'innerTransfer-getUserInfo',
    },
    {
      url: '/_api/payment/withdraw/info-confirm',
      event: 'withdraw-info-confirm',
    },
    {
      url: '/_api/validation-email/email/risk-check',
      event: 'validation-risk-check',
    },
    {
      url: '/_api/validation-email/email/resend',
      event: 'validation-email-resend',
    },
    { url: '/_api/auth-code', event: 'oauth-auth-code' },
    { url: '/_api/_oauth/v2/auth-code', event: 'oauth-auth-code-v2' },
    {
      url: '/_api/risk-validation-center/v1/security/validation/combine',
      event: 'risk-validation-center',
    },
    { url: '/_api/user-biz-front/v2/freeze-user', event: 'freeze-user' },
    {
      url: '/ucenter/send-validation-code',
      event: 'send-validation-code',
    },
    {
      url: '/ucenter/bind-phone/code',
      event: 'bind-phone-code',
    },
    {
      url: '/ucenter/bind-email/code',
      event: 'bind-email-code',
    },
    { url: '/_api/ucenter/external-binding', event: 'external-binding' },
    { url: '/_api/ucenter/external-unbinding', event: 'external-unbinding' },
    { url: '/_api/kyc/web/kyc/ng-primary/update', event: 'ng-primary-update' },
    { url: '/_api/kyc/web/kyc/channel', event: 'kyc-channel' },
    { url: '/_api/kyc/web/kyc/verify-risk/check', event: 'verify-risk-check' },
    { url: '/_api/kyc/web/kyc/ng/finish', event: 'kyc-ng-finish' },
    {
      url: '/_api/ucenter/sign-up-validation',
      event: 'sign-up-validation',
    },
    {
      url: '/_api/kyc/web/kyc/data/createStandard',
      event: 'createStandard',
    },
    {
      url: '/_api/kyc/web/compliance/thailand/advance/choose',
      event: 'thailand-advance-choose',
    },
    {
      url: '/_api/ucenter/v2/user/safe-words',
      event: 'account-safe-words',
    },
    {
      url: '/_api/ucenter/user/password',
      event: 'set-new-password',
    },
    {
      url: '/_api/kyc/web/kyc/compliance/create',
      event: 'createComplianceStandard',
    },
    {
      url: '/_api/risk-validation-center/v1/security/center/score',
      event: 'getSecurityScore',
    },
    {
      url: '/_api/risk-validation-center/v1/security/center/cache-score',
      event: 'getSecurityCacheScore',
    },
    {
      url: '/_api/ucenter/v2/passkey/register',
      event: 'passkeyRegister',
    },
    {
      url: '/_api/ucenter/v2/passkey/delete',
      event: 'passkeyDelete',
    },
  ],
  getReporter: getReport,
  responseInterceptors: [
    {
      name: 'showErrorInterceptor',
      onRejected: responseErrorInterceptor,
    },
  ],
});
