/**
      * This file is auto-generated by @kucoin/api-generator
      * Owner: sean.shi@kupotech.com
      */

import type { Options as ClientOptions, TDataShape, Client } from 'tools/request';
import type { RecalledByEmailUsingPostData, RecalledByEmailUsingPostResponse, RecalledByPhoneNumberUsingPostData, RecalledByPhoneNumberUsingPostResponse, GetMailSuffixesUsingGetData, GetMailSuffixesUsingGetResponse } from './types.gen';
import { client as _apiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape> = ClientOptions<TData> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
 disabledLang?: boolean;
};

/**
 * 通过邮箱注册
 */
export const recalledByEmailUsingPost = (body?: RecalledByEmailUsingPostData['query'],options?: Options<RecalledByEmailUsingPostData>) => {
    return (options?.client ?? _apiClient).post<RecalledByEmailUsingPostResponse>({
        url: '/recalled-email',
        body,
...(options || {})
    });
};

/**
 * 通过手机召回
 */
export const recalledByPhoneNumberUsingPost = (body?: RecalledByPhoneNumberUsingPostData['query'],options?: Options<RecalledByPhoneNumberUsingPostData>) => {
    return (options?.client ?? _apiClient).post<RecalledByPhoneNumberUsingPostResponse>({
        url: '/recalled-phone',
        body,
...(options || {})
    });
};

/**
 * 获取邮箱后缀
 */
export const getMailSuffixesUsingGet = (options?: Options<GetMailSuffixesUsingGetData>) => {
    return (options?.client ?? _apiClient).get<GetMailSuffixesUsingGetResponse>({
        url: '/mail-suffixes',
        ...(options || {})
    });
};