/**
 * This file is auto-generated by @kucoin/api-generator
 * Owner: sean.shi@kupotech.com
 */
import RequestClient, { RuntimeEnvironment } from 'gbiz-next/commonRequest';
import JsBridge from 'gbiz-next/bridge';
import { IS_SERVER_ENV } from 'kc-next/env';
import { responseErrorInterceptor } from '@/tools/request/showErrorInterceptor';
import { getReport } from 'gbiz-next/report';

export const client = new RequestClient({
  projectName: 'brisk-web-ssr',
  environment: IS_SERVER_ENV
    ? RuntimeEnvironment.SSR
    : JsBridge.isApp()
      ? RuntimeEnvironment.APP
      : RuntimeEnvironment.BROWSER,
  fingerPrintUrlList: [
    { url: '/_api/welfare/web/receive2phone', event: 'receive2phone' },
    { url: '/_api/welfare/web/receive2code', event: 'receive2code' },
    { url: '/_api/welfare/web/receiveV2', event: 'receive2codeV2' },
  ],
  getReporter: getReport,
  responseInterceptors: [
    {
      name: 'showErrorInterceptor',
      onRejected: responseErrorInterceptor,
    },
  ],
});
