
// this file is generate by genSiteConfig for rollup
// don't edit this file
window._SITE_CONFIG_ = {
  "siteType": "claim",
  "basicProperties": {
    "siteName": "claim",
    "shareGlobalAccount": 1,
    "walletType": 1,
    "storageType": 1,
    "siteDomainType": 2,
    "siteDomain": "www.kucoinauth.com",
    "siteRegion": null,
    "brandType": 2,
    "logoType": 1
  },
  "extProperties": [],
  "functions": {
    "fast_trade": false,
    "3rd_party": false,
    "fiat_deposit": false,
    "ucenter": true,
    "kyc": false,
    "kyb": false,
    "personal_center": false,
    "home_page": false,
    "message_center": false,
    "k_line": false,
    "search": false,
    "spot": false,
    "margin": false,
    "option": false,
    "convert": false,
    "futures": false,
    "financing": false,
    "copy_trading": false,
    "trading_bot": false,
    "api": false,
    "currency": false,
    "etf": false,
    "loan": false,
    "spot_growth": false,
    "platform_growth": false,
    "activity_bench": false,
    "basic_bench": false,
    "seo": false,
    "rebate_business": false,
    "invite_rebate": false,
    "affiliate": false,
    "api_broker": false,
    "nd_broker": false,
    "payment": false,
    "kucoin_pay": false,
    "kucard": false,
    "express": false,
    "p2p": false,
    "web3_wallet": false,
    "compliance_exhibition_platform": true,
    "tax_platform": true,
    "customer_service_system": true,
    "risk_control_system": true,
    "financial_system": true,
    "reconciliation_system": true,
    "data_center": true
  },
  "bizConfigs": {
    "spot_liquidity": "",
    "contract_liquidity": "",
    "rebate_range": "",
    "is_allowed_multilevel_rebate": "",
    "quote_currency": "USDT",
    "shield_currency": ""
  }
};
