/**
 * Owner: jesse.shao@kupotech.com
 */
import { showDateTimeByZone } from 'helper';
import { addLangToPath } from 'utils/lang';
import { LANDING_HOST } from 'utils/siteConfig';
import bannerImg from 'assets/luckydraw/banner.png';

// banner 配置
export const BANNER_CONFIG = {
  luckydraw: {
    activityName: 'LUCKY_DRAW',
    regToast: {
      NOT_START: {
        type: 'info',
        msg: 'Event is coming soon!',
      },
      OVER: {
        type: 'info',
        msg: 'sorry! event is finished, please wait next!',
      },
      SUCCESS: {
        type: 'success',
        msg: 'Join success! you can invite friends now!',
      },
    },
    loginBackUrl: encodeURIComponent(
      addLangToPath(`${LANDING_HOST}/referral-super-lucky-draw${window.location.search}`),
    ),
    title: 'Referral Super Lucky Draw',
    subTitle1: 'Up to ',
    subTitle2: '$600,000',
    subTitle3: ' in BTC For Grab',
    description: [
      'Win your lottery ticket',
      'Refer your friends to grab a lottery ticket',
      'Refer and Win Grand Prize',
    ],
    joinText: {
      true: 'Joined',
      false: 'Join Now',
    },
    shareText: 'Invite Friend',
    bannerBgImg: bannerImg,
  },
};

// how to participate 文案
export const PART_CONFIG = {
  luckydraw: {
    title: 'How to participate',
    content: [
      "During the event, if you invite your friends successfully using your referral code and the deposits/buy crypto amount of your friends ≥ 100 USDT, the invitees' UID numbers will become your lottery tickets. You can participate in the lucky draws at the designated times.",
      '*The region will be identified based on the KYC2 information of the invitee. If the KYC2 is not submitted, the invitee will not be identified nor be allowed to participate in the event.',
    ],
  },
};

// how to draw 文案
export const DRAW_CONFIG = {
  luckydraw: {
    title: 'How to draw',
    content: [
      'Take the hash value of the last block generated by KCC before 16:00 (UTC) on Sunday of the current week. Remove all letters and take the last 5 digits as the winning sequence.',
      'Suppose that the hash value is:',
      '0x32fe10839ec90b6abe20ee44ec8bc20f4d5067eeb53c5e8fb3cb499765e52d43',
      'Then the sequence will be:',
      '55243',
      `We will match the lucky numbers exactly starting from the last digit of the invitees’ ${window._BRAND_NAME_} UID. The matching degree and winning rules are as follows: `,
    ],
  },
};

// rules 文案
export const RULES_CONFIG = {
  luckydraw: {
    title: 'Rules',
    content: [
      '1. Please make sure that you sign up and invite new users to register with your referral code.',
      '2. Only invitees who submit the advanced identity verification and have deposits/buy crypto amount ≥ 100 USDT can generate a lottery ticket for the inviter.',
      '3. The lottery ticket for each period is only valid for that period and cannot be used to participate in the next event.',
      '4. If no prize is obtained in the current phase, the prize amount will roll over to the prize pool of the next phase.',
      '5. If no participant receives the prize pool in the last period of the event, all participants will divide the prize pool according to the total number of draws they obtained during the event.',
      '6. Reward computation: (Number of lucky draw tickets obtained by the users in all the phases/Number of lucky draw tickets obtained by all the users in all phases) * Remaining prize pool.',
      '7. All users of the same prize level in the current period will share the corresponding prize pool.',
      '8. The rewards will be issued to your account within 7 working days after the end of the event.',
      `9. Please make sure that you are inviting real users. ${window._BRAND_NAME_} will disqualify those users that show any kind of cheating behavior.`,
      '10.Only users who received the email notifications are eligible to join the event.',
    ],
  },
};

export const STATE_TEXT_CONFIG = {
  luckydraw: {
    NOT_START: 'Coming soon',
    IN_PROGRESS: 'Event in progress',
    OVER: 'Event finished',
  },
};

// 活动日期文案
export const TIME_TEXT_CONFIG = {
  luckydraw: (startDate, endDate) =>
    `Event Duration: ${showDateTimeByZone(
      startDate,
      'YYYY/MM/DD HH:mm:ss',
      0,
    )} - ${showDateTimeByZone(endDate, 'YYYY/MM/DD HH:mm:ss', 0)}(UTC)`,
};

// 活动介绍文案
export const INTRO_TEXT_CONFIG = {
  luckydraw: () =>
    `The event is divided into 4 phases with each phase last for 7 days. For invitees reaches the requirements, the inviters will gain a lottery ticket. The more tickets you have, the higher your odds of winning! If the prize pool has not been fully distributed in the 4th phase, all participants will share the remaining prizes!`,
};

export const PRIZE_CONFIG = [
  {
    top: 0,
    bottom: 1000,
    percent: '0%',
  },
  {
    top: 500,
    bottom: 2000,
    percent: '13%',
  },
  {
    top: 1000,
    bottom: 4000,
    percent: '26%',
  },
  {
    top: 2000,
    bottom: 6000,
    percent: '39%',
  },
  {
    top: 3000,
    bottom: 8000,
    percent: '52%',
  },
  {
    top: 5000,
    bottom: 20000,
    percent: '65%',
  },
  {
    top: 10000,
    bottom: 50000,
    percent: '78%',
  },
  {
    top: null,
    bottom: null,
    percent: '100%',
  },
];

export const INJECT_FULL_NUM = {
  top: 20000,
  bottom: 59000,
};

// 活动介绍文案
export const PRIZE_TEXT_CONFIG = {
  title: 'PrizePool',
  introText:
    'The prize pool will continue to grow along with the number of new users invited by all participants in the current phase.',
  topValue: 'Total tickets reached',
  bottomValue: 'Pool growth',
  phaseText: '$150,000/Phase',
};
