/**
 * Owner: willen@kupotech.com
 */
module.exports = {
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@@/(.*)$': '<rootDir>/src/.umi/$1',
    '^src/(.*)': '<rootDir>/src/$1',
    '^config/(.*)': '<rootDir>/src/config/$1',
    '^config': '<rootDir>/src/config/index.js',
    '^utils/(.*)': '<rootDir>/src/utils/$1',
    '^api/(.*)': '<rootDir>/src/api/$1',
    '^tools/(.*)': '<rootDir>/src/tools/$1',
    '^hocs/(.*)': '<rootDir>/src/hocs/$1',
    '^static/(.*)': '<rootDir>/cdnAssets/static/$1',
    '^routes/(.*)': '<rootDir>/src/routes/$1',
    '^components/(.*)': '<rootDir>/src/components/$1',
    '^helper': '<rootDir>/src/helper.js',
    '^common/(.*)': '<rootDir>/src/common/$1',
    '^services/(.*)': '<rootDir>/src/services/$1',
    '^test/(.*)': '<rootDir>/test/$1',
    '^hooks/(.*)': '<rootDir>/src/hooks/$1',
    '^@kufox/mui': '<rootDir>/node_modules/@kufox/mui/node/index.js',
    '^@kux/mui': '<rootDir>/node_modules/@kux/mui/node/index.js',
    '^@kux/design$': '<rootDir>/node_modules/@kux/design/dist/index.js',
    '^@kux/iconpack$': '<rootDir>/node_modules/@kux/iconpack/dist/index.cjs.js',
    '^@kucoin-biz/hooks$': '<rootDir>/test/__mocks__/@kucoin-biz/hooks.js',
    '^@kucoin-gbiz-next/(.*)$': '<rootDir>/test/__mocks__/@kucoin-gbiz-next/$1',
    // 处理静态资源文件（包括带 ?url 后缀的）
    '\\.(jpg|jpeg|png|gif|webp|svg|ico|bmp)\\?url$': '<rootDir>/test/__mocks__/fileMock.js',
    '\\.(jpg|jpeg|png|gif|webp|svg|ico|bmp)$': '<rootDir>/test/__mocks__/fileMock.js',
    '\\.(css|less|scss|sass)$': 'identity-obj-proxy',
  },

  verbose: true, // 是否输出 descripe 和 test/it 中的测试描述信息
  silent: true,
  globals: {
    _DEV_: true,
    _APP_NAME_: 'ucenter-web',
    _APP_: 'ucenter-web',
    _VERSION_: '0.0.1',
    _XVERSION_: '0.0.1',
    CMS_CDN: 'xxx.xxx',
    SENTRY_DEBUG: false,
    _ENV_: 'env',
    IS_SANDBOX: false,
    UCENTER_KYC_ENCRYPT_KEY: '',
    _DEFAULT_LANG_: 'en_US',
    _DEFAULT_LOCALE_: 'en',
    _BRAND_SITE_: 'KC',
    _BASE_CURRENCY_: 'USDT',
    ['__KC_LANGUAGES__.__ALL__']: [
      'de_DE',
      'en_US',
      'es_ES',
      'fr_FR',
      'ko_KR',
      'nl_NL',
      'pt_PT',
      'ru_RU',
      'tr_TR',
      'vi_VN',
      'zh_HK',
      'it_IT',
      'id_ID',
      'ms_MY',
      'hi_IN',
      'th_TH',
      'ja_JP',
      'bn_BD',
      'pl_PL',
      'fil_PH',
      'ar_AE',
      'ur_PK',
    ],
    _SAFE_WEB_DOMAIN_: [
      'kucoin.net',
      'kucoin.com',
      'kucoin.cloud',
      'kucoin.biz',
      'kucoin.top',
      'kucoin.plus',
      'kucoin.work',
      'kumex.com',
      'pool-x.io',
      'kucoin.zendesk.com',
      'localhost',
    ],
  },

  setupFilesAfterEnv: [
    '@testing-library/jest-dom',
    '@testing-library/react-hooks/disable-error-filtering.js',
    'reflect-metadata',
  ], // 在每个测试文件执行之前调用一些默认执行代码的文件路径
  setupFiles: ['./test/setupFile.js'],
  collectCoverageFrom: [
    // 覆盖率收集路径
    '<rootDir>/src/utils/**/*.js',
    '<rootDir>/src/hooks/**/*.js',
    '<rootDir>/src/helper.js',
  ],
  // testMatch: [ "**/test/utils/**/*.[jt]s?(x)"],
  // testMatch: [ "**/test/utils/webauthn-json.test.js"],
  // testMatch: ["**/test/hooks/useLocaleOrder2.test.js"],
  // testMatch: ['**/test/utils/formlize.test.js', '**/test/utils/showDatetime.test.js'],
  // testMatch: ['**/test/utils/separateNumber.test.js', '**/test/utils/precision.test.js']
};
