/**
      * This file is auto-generated by @kucoin/api-generator
      * Owner: sean.shi@kupotech.com
      */

export type GenericResult_KycStatusResponse_ = {
    code?: string;
    data?: KycStatusResponse;
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type KycStatusResponse = {
    /**
     * 展示文案
     */
    displayText?: string;
    /**
     * 展示样式
     */
    displayType?: 'ERROR' | 'SUCCESS' | 'WARN';
    /**
     * KYC限制
     */
    kycLimit?: boolean;
};

export type GetKycStatusUsingGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/dismiss/kyc/status';
};

export type GetKycStatusUsingGetResponses = {
    /**
     * OK
     */
    200: GenericResult_KycStatusResponse_;
};

export type GetKycStatusUsingGetResponse = GetKycStatusUsingGetResponses[keyof GetKycStatusUsingGetResponses];

export type ClientOptions = { baseURL: string; };
