window.__KC_LANGUAGES__ = {
  __ALL__: [
    "de_DE",
    "en_US",
    "es_ES",
    "fr_FR",
    "ko_KR",
    "nl_NL",
    "pt_PT",
    "ru_RU",
    "tr_TR",
    "vi_VN",
    "zh_HK",
    "it_IT",
    "id_ID",
    "ms_MY",
    "hi_IN",
    "th_TH",
    "ja_JP",
    "bn_BD",
    "pl_PL",
    "fil_PH",
    "ar_AE",
    "ur_PK",
    "uk_UA",
  ],
};
window.__KC_LANGUAGES_BASE_MAP__ = {
  baseToLang: {
    "en-demo": "en_US",
    "de-demo": "de_DE",
    "es-demo": "es_ES",
    "fr-demo": "fr_FR",
    "ko-demo": "ko_KR",
    "nl-demo": "nl_NL",
    "pt-demo": "pt_PT",
    "ru-demo": "ru_RU",
    "tr-demo": "tr_TR",
    "vi-demo": "vi_VN",
    "zh-hant-demo": "zh_HK",
    "it-demo": "it_IT",
    "id-demo": "id_ID",
    "ms-demo": "ms_MY",
    "hi-demo": "hi_IN",
    "th-demo": "th_TH",
    "ja-demo": "ja_JP",
    "bn-demo": "bn_BD",
    "pl-demo": "pl_PL",
    "fil-demo": "fil_PH",
    "ar-demo": "ar_AE",
    "ur-demo": "ur_PK",
    "uk-demo": "uk_UA",
  },
  langToBase: {
    en_US: "en-demo",
    de_DE: "de-demo",
    es_ES: "es-demo",
    fr_FR: "fr-demo",
    ko_KR: "ko-demo",
    nl_NL: "nl-demo",
    pt_PT: "pt-demo",
    ru_RU: "ru-demo",
    tr_TR: "tr-demo",
    vi_VN: "vi-demo",
    zh_HK: "zh-hant-demo",
    it_IT: "it-demo",
    id_ID: "id-demo",
    ms_MY: "ms-demo",
    hi_IN: "hi-demo",
    th_TH: "th-demo",
    ja_JP: "ja-demo",
    bn_BD: "bn-demo",
    pl_PL: "pl-demo",
    fil_PH: "fil-demo",
    ar_AE: "ar-demo",
    ur_PK: "ur-demo",
    uk_UA: "uk-demo",
  },
};
