FROM node:20.10.0-bullseye-slim AS builder

ARG NODE_TLS_REJECT_UNAUTHORIZED=0


# 设置工作目录
WORKDIR /home/node/app

# RUN apt-get update -y \
#   && apt-get install -y libpng-dev 

# 复制 package.json 和 yarn.lock 到工作目录
COPY package.json yarn.lock ./

# 安装依赖
RUN yarn config set registry https://nexus.kcprd.com/repository/npm-group/ && \
  yarn config set "strict-ssl" false && \
  yarn install && \
  yarn cache clean

# 复制源代码并编译 Nest.js 项目
COPY . .
RUN npm run build


FROM node:20.10.0-bullseye-slim 


ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome
ENV PUPPETEER_CACHE_DIR=/.cache/puppeteer

COPY --from=builder /home/node/app/chrome/google-chrome-stable_current_amd64.deb ./

# RUN apt-get update && apt-get install -y \
#   wget \
#   gnupg \
#   libxss1 \
#   libappindicator3-1 \
#   fonts-liberation \
#   libnss3 \
#   libgtk-3-0 \
#   libdbus-1-3 \
#   libasound2 \
#   libatk-bridge2.0-0 \
#   libatk1.0-0 \
#   libatspi2.0-0 \
#   libc6 \
#   libcairo2 \
#   libcups2 \
#   libcurl4 \
#   libglib2.0-0 \
#   libx11-6 \
#   libxcomposite1 \
#   libxrandr2 \
#   && apt-get clean 
# 安装必要依赖  
RUN apt-get update && apt-get install -y \
  wget \
  gnupg \
  libxss1 \
  libappindicator3-1 \
  fonts-liberation \
  libnss3 \
  libgtk-3-0 \
  libdbus-1-3 \
  libasound2 \
  libatk-bridge2.0-0 \
  libatk1.0-0 \
  libatspi2.0-0 \
  libc6 \
  libcairo2 \
  libcups2 \
  libcurl4 \
  libglib2.0-0 \
  libx11-6 \
  libxcomposite1 \
  libxrandr2 \
  && apt-get clean   

# 安装 Google Chrome Stable and fonts
# Note: this installs the necessary libs to make the browser work with Puppeteer.
RUN apt-get update -y \
  && apt-get install -y ./google-chrome-stable_current_amd64.deb \
  && rm -f ./google-chrome-stable_current_amd64.deb \
  && apt-get clean all


# 复制生产构建结果和依赖
COPY --from=builder /home/node/app/.vault ./.vault
COPY --from=builder /home/node/app/dist ./dist
COPY --from=builder /home/node/app/node_modules ./node_modules
COPY --from=builder /home/node/app/package.json ./
COPY --from=builder /home/node/app/.env ./.env
COPY --from=builder /home/node/app/.env.development ./.env.development 
# 首次上线保留
# COPY --from=builder /home/node/app/migration.data.backup ./migration.data.backup

# 暴露主机端口
EXPOSE 3030

# 应用程序启动命令
CMD [ "npm", "run", "start:prod" ]
