window.__KC_LANGUAGES__ = {
  __ALL__: [
    "de_DE",
    "en_US",
    "es_ES",
    "fr_FR",
    "ko_KR",
    "nl_NL",
    "pt_PT",
    "ru_RU",
    "tr_TR",
    "vi_VN",
    "zh_HK",
    "it_IT",
    "id_ID",
    "ms_MY",
    "hi_IN",
    "th_TH",
    "ja_JP",
    "bn_BD",
    "pl_PL",
    "fil_PH",
    "ar_AE",
    "ur_PK",
    "uk_UA",
  ],
};
window.__KC_LANGUAGES_BASE_MAP__ = {
  baseToLang: {
    "en-au": "en_US",
    "de-au": "de_DE",
    "es-au": "es_ES",
    "fr-au": "fr_FR",
    "ko-au": "ko_KR",
    "nl-au": "nl_NL",
    "pt-au": "pt_PT",
    "ru-au": "ru_RU",
    "tr-au": "tr_TR",
    "vi-au": "vi_VN",
    "zh-hant-au": "zh_HK",
    "it-au": "it_IT",
    "id-au": "id_ID",
    "ms-au": "ms_MY",
    "hi-au": "hi_IN",
    "th-au": "th_TH",
    "ja-au": "ja_JP",
    "bn-au": "bn_BD",
    "pl-au": "pl_PL",
    "fil-au": "fil_PH",
    "ar-au": "ar_AE",
    "ur-au": "ur_PK",
    "uk-au": "uk_UA",
  },
  langToBase: {
    en_US: "en-au",
    de_DE: "de-au",
    es_ES: "es-au",
    fr_FR: "fr-au",
    ko_KR: "ko-au",
    nl_NL: "nl-au",
    pt_PT: "pt-au",
    ru_RU: "ru-au",
    tr_TR: "tr-au",
    vi_VN: "vi-au",
    zh_HK: "zh-hant-au",
    it_IT: "it-au",
    id_ID: "id-au",
    ms_MY: "ms-au",
    hi_IN: "hi-au",
    th_TH: "th-au",
    ja_JP: "ja-au",
    bn_BD: "bn-au",
    pl_PL: "pl-au",
    fil_PH: "fil-au",
    ar_AE: "ar-au",
    ur_PK: "ur-au",
    uk_UA: "uk-au",
  },
};
