export function CheckHeaderSearchBox() {
  // 检查header搜索输入框正常响应
  cy.get('[data-inspector="inspector_header_search"]')
    .should('exist') // 确保元素存在
    .click({ force: true })
    .then(() => {
      cy.get('[data-inspector="inspector_header_search_default"]').should('exist'); // 确保该元素可见
    });
}

export function InterceptHeaderSearchApi() {
  cy.intercept('**_api/pathfinder/search**', {
    success: true,
    code: '200',
    msg: 'success',
    retry: false,
    data: [
      {
        resourceId: 'BTC-USDC',
        resourceType: 'SPOT',
        describe: 'BTC/USDC',
        searchResultType: 'BACKEND',
        resourceHits: ['BTC'],
        resourceHitStr: '[BTC]/USDC',
        resourceExtend: {
          icon: 'https://assets-currency.sit.kucoin.net/60bf8a90db892b0006d73786_BTC.png',
        },
      },
    ],
  }).as('getSearchResult');
}

export function CheckHeaderSearchInput() {
  // 搜索框输入 btc
  cy.get('[data-inspector="inspector_header_search"]')
    .find('input')
    .as('searchInput');

  cy.get('@searchInput')
    .should('exist')
    .type('btc', { force: true });

  cy.wait('@getSearchResult');

  cy.get('[data-inspector="inspector_header_search_trade_row"]').should('contain', 'BTC'); // 判断是否包含 'btc' 这个文字内容
}

export function getNavigation() {
  cy.intercept('/_api/kucoin-config/navigation*', {
    'success': true,
    'code': '200',
    'msg': 'success',
    'retry': false,
    'data': [
      {
        'type': 'NAVIGATION_FIRST_LEVEL',
        'name': '買幣',
        'explain': '',
        'darkIcons': '',
        'uri': '',
        'zhUri': '',
        'showMark': false,
        'id': '3455073d57634e00013f442f',
        'sort': 1,
        'children': [
          {
            'type': 'NAVIGATION_SECOND_LEVEL',
            'name': '快捷買幣',
            'explain': '使用 Visa/Mastercard 卡購買 USDT',
            'icons':
              'https://assets.staticimg.com/cms/media/5SeFbAJ7X0FYw6j2oH1h9li1wVTzCvB4XioTvmbpN.png',
            'darkIcons': '',
            'uri': '/express',
            'zhUri': '/express',
            'showMark': false,
            'id': '30386108f96613000975add7',
            'sort': 1,
            'createdAt': 1678864358000,
          },
          {
            'type': 'NAVIGATION_SECOND_LEVEL',
            'name': 'P2P',
            'explain': '使用銀行卡等支付方式購買主流幣',
            'icons':
              'https://assets.staticimg.com/cms/media/5swQUV3ikAZ8iboUBRZoDSJMGSsyERERDKBBRr87R.png',
            'darkIcons': '',
            'uri': '/otc',
            'zhUri': '/otc',
            'showMark': false,
            'id': '30385f4bf96613000975adc4',
            'sort': 2,
            'createdAt': 1645509281000,
          },
          {
            'type': 'NAVIGATION_SECOND_LEVEL',
            'name': '法幣充值',
            'explain': '通過銀行轉帳充值法幣餘額',
            'icons':
              'https://assets.staticimg.com/cms/media/9HjRlw2VnM49iBgbQBXLIexxEpAOpc40vUZ0uZpyN.png',
            'darkIcons': '',
            'uri': '/assets/fiat-currency/recharge',
            'zhUri': '/assets/fiat-currency/recharge',
            'showMark': false,
            'id': '3433ee8b9060ae0001f0d19c',
            'sort': 3,
            'createdAt': 1681129691000,
          },
          {
            'type': 'NAVIGATION_SECOND_LEVEL',
            'name': '第三方',
            'explain': '支持美元、歐元等法幣兌換數字貨幣服務',
            'icons':
              'https://assets.staticimg.com/cms/media/12KHshRzj3b8tTqmhIcFzQOqty01aXeH573CdNu4M.png',
            'darkIcons': '',
            'uri': '/assets/payments',
            'zhUri': '/assets/payments',
            'showMark': false,
            'id': '30385e3ff96613000975ad99',
            'sort': 4,
            'createdAt': 1645017406000,
          },
        ],
        'createdAt': 1683294013000,
      },
      {
        'type': 'NAVIGATION_FIRST_LEVEL',
        'name': '行情',
        'explain': '',
        'icons': '',
        'darkIcons': '',
        'uri': '/markets',
        'zhUri': '/markets',
        'showMark': false,
        'id': '3038cd8576a4560008db629a',
        'sort': 2,
        'createdAt': 1662370091000,
      },
      {
        'type': 'NAVIGATION_FIRST_LEVEL',
        'name': '交易',
        'explain': '',
        'darkIcons': '',
        'uri': '',
        'zhUri': '',
        'showMark': false,
        'id': '3455086757634e00013f4447',
        'sort': 3,
        'children': [
          {
            'type': 'NAVIGATION_SECOND_LEVEL',
            'name': '幣幣交易',
            'explain': '全屏交易，支持600+幣幣交易',
            'icons':
              'https://assets.staticimg.com/cms/media/7CJ1jg0BzhA5wRLflmiXLrwv1XjQQTyGnSQzhnJHl.png',
            'darkIcons': '',
            'uri': '/trade/BTC-USDT',
            'zhUri': '/trade/BTC-USDT',
            'showMark': false,
            'id': '303864ddf96613000975adea',
            'sort': 1,
            'createdAt': 1682140610000,
            'tradeType': 'SPOT',
          },
          {
            'type': 'NAVIGATION_SECOND_LEVEL',
            'name': '槓桿交易',
            'explain': '借幣增加本金，放大現貨收益',
            'icons':
              'https://assets.staticimg.com/cms/media/1tBHyyiBFklNFhHPXPfrmzu0Sb83veyXpcR488bxH.png',
            'darkIcons': '',
            'uri': '/trade/margin/BTC-USDT',
            'zhUri': '/trade/margin/BTC-USDT',
            'showMark': false,
            'id': '645c544f8124ed00011e87af',
            'sort': 2,
            'createdAt': 1683772495000,
            'tradeType': 'MARGIN',
          },
          {
            'type': 'NAVIGATION_SECOND_LEVEL',
            'name': '交易機器人',
            'explain': '無需盯盤，躺著就能賺',
            'icons':
              'https://assets.staticimg.com/cms/media/1unJ4U5QHSk7ZbG8KsdSSrH9lXwouLmjOGoYOxuDi.png',
            'darkIcons': '',
            'uri': '/trading-bot/futures/grid/XBTUSDTM',
            'zhUri': '/trading-bot/futures/grid/XBTUSDTM',
            'showMark': true,
            'marks': [
              {
                'type': 3,
                'name': 'Pro',
                'position': null,
                'styleType': null,
                'color': null,
                'icons': null,
                'darkIcons': null,
                'startAt': 1616159934000,
                'endAt': 1775654334000,
                'expired': false,
                'longShow': false,
                'id': '6727ab429d47020001531819',
              },
            ],
            'id': '3054a5cc36206700066b599d',
            'sort': 3,
            'createdAt': 1662370586000,
            'tradeType': 'TRADING_BOT',
          },
          {
            'type': 'NAVIGATION_SECOND_LEVEL',
            'name': '閃兌',
            'explain': '0手續費，一鍵完成交易',
            'icons':
              'https://assets.staticimg.com/cms/media/4xUT8WGMqAyoYRN6vUVbUZ1Y6Vr505qHbm4dTavZR.png',
            'darkIcons': '',
            'uri': '/convert',
            'zhUri': '/convert',
            'showMark': false,
            'id': '32baeba877471e0001209dce',
            'sort': 4,
            'createdAt': 1678190013000,
          },
          {
            'type': 'NAVIGATION_SECOND_LEVEL',
            'name': 'API 交易',
            'explain': '每個 API 用戶都是我們的 VIP',
            'icons':
              'https://assets.staticimg.com/cms/media/42rGhZWSAe7RBV0da8Wl2QXpqZZ86i14T7RNgFEa0.png',
            'darkIcons': '',
            'uri': '/api',
            'zhUri': '/api',
            'showMark': false,
            'id': '30386b89f96613000975ae4d',
            'sort': 5,
            'createdAt': 1681800511000,
          },
          {
            'type': 'NAVIGATION_SECOND_LEVEL',
            'name': '盤前交易',
            'explain': '前瞻交易，贏在起跑綫',
            'icons':
              'https://assets.staticimg.com/cms/media/2ptQ6aYBJV1EadRzehyYUQ2SJtHdkEbz302JQbV3z.png',
            'darkIcons': '',
            'uri': 'https://www.kucoin.com/pre-market',
            'zhUri': 'https://www.kucoin.com/pre-market',
            'showMark': false,
            'id': '652d076c86d4170001bff3fb',
            'sort': 6,
            'createdAt': 1697449836000,
          },
          {
            'type': 'NAVIGATION_SECOND_LEVEL',
            'name': 'GemSPACE',
            'explain': '潛力無限的新幣於此上線',
            'icons':
              'https://assets.staticimg.com/cms/media/5Uu6Off3A1qyORyG6uzaL3siwj2QecdXkqvL1J6LK.png',
            'darkIcons': '',
            'uri': 'https://www.kucoin.com/gemspace/ongoing',
            'zhUri': 'https://www.kucoin.com/gemspace/ongoing',
            'showMark': false,
            'id': '6613bc7159ab39000196c4b9',
            'sort': 7,
            'createdAt': 1712569457000,
          },
        ],
        'createdAt': 1683294311000,
      },
      {
        'type': 'NAVIGATION_FIRST_LEVEL',
        'name': '衍生品',
        'explain': '',
        'darkIcons': '',
        'uri': '',
        'zhUri': '',
        'showMark': false,
        'id': '345509e257634e00013f445f',
        'sort': 4,
        'children': [
          {
            'type': 'NAVIGATION_SECOND_LEVEL',
            'name': '合約簡介',
            'explain': '瀏覽所有加密貨幣衍生產品的簡介',
            'icons':
              'https://assets.staticimg.com/cms/media/8TxknmiunaJlOLG7LkCGbUf5BJ3ewsrDkTz3q46vr.png',
            'darkIcons': '',
            'uri': '/futures',
            'zhUri': '/futures',
            'showMark': false,
            'id': '34251a986a5f0c000195ec5d',
            'sort': 1,
            'createdAt': 1680159257000,
          },
          {
            'type': 'NAVIGATION_SECOND_LEVEL',
            'name': 'U 本位合約',
            'explain': '以 USDⓈ 結算的線性合約',
            'icons':
              'https://assets.staticimg.com/cms/media/8HQtRURGvASb2avsWHFC4XDNdAO1JmEnxoyc3404Q.png',
            'darkIcons': '',
            'uri': '/futures/trade/XBTUSDTM',
            'zhUri': '/futures/trade/XBTUSDTM',
            'showMark': false,
            'id': '34251d886a5f0c000195ec75',
            'sort': 2,
            'createdAt': 1680173256000,
            'tradeType': 'FUTURES_USDT',
          },
          {
            'type': 'NAVIGATION_SECOND_LEVEL',
            'name': '幣本位合約',
            'explain': '以幣結算的反向合約',
            'icons':
              'https://assets.staticimg.com/cms/media/3L3rLaS1gq6wUbxIYePUYMCpyBv9tAspYEjeuSVxr.png',
            'darkIcons': '',
            'uri': '/futures/trade/XBTUSDM',
            'zhUri': '/futures/trade/XBTUSDM',
            'showMark': false,
            'id': '34251f0dbe6cb10001b664de',
            'sort': 3,
            'createdAt': 1680159260000,
            'tradeType': 'FUTURES_CURRENCY',
          },
          {
            'type': 'NAVIGATION_SECOND_LEVEL',
            'name': '合約福利',
            'explain': '探索豐富的合約活動和專屬福利',
            'icons':
              'https://assets.staticimg.com/cms/media/53Db9a93V6NOS9nrqn0z16Qbka3cIYyjJhySXJWLk.png',
            'darkIcons': '',
            'uri': '/futures/perks',
            'zhUri': '/futures/perks',
            'showMark': false,
            'id': '342521d5be6cb10001b664f6',
            'sort': 4,
            'createdAt': 1680486700000,
          },
          {
            'type': 'NAVIGATION_SECOND_LEVEL',
            'name': '槓桿代幣',
            'explain': '固定倍數追踪標的漲跌',
            'icons':
              'https://assets.staticimg.com/cms/media/8An14lvoYxHmf4YaGKxHRbpfn5csKvTCUobxPXcxX.png',
            'darkIcons': '',
            'uri': '/leveraged-tokens',
            'zhUri': '/leveraged-tokens',
            'showMark': false,
            'id': '34252315be6cb10001b6650e',
            'sort': 5,
            'createdAt': 1680486745000,
          },
        ],
        'createdAt': 1683294690000,
      },
      {
        'type': 'NAVIGATION_FIRST_LEVEL',
        'name': '金融業務',
        'explain': '',
        'darkIcons': '',
        'uri': '',
        'zhUri': '',
        'showMark': false,
        'id': '34550b8757634e00013f4477',
        'sort': 5,
        'children': [
          {
            'type': 'NAVIGATION_GROUP',
            'name': '總覽',
            'id': '64a3bdb3a228e80001abdbe6',
            'sort': 1,
            'children': [
              {
                'type': 'NAVIGATION_SECOND_LEVEL',
                'name': 'KuCoin 賺幣',
                'explain': '投幣賺幣，穩定收益，專業資管',
                'icons':
                  'https://assets.staticimg.com/cms/media/9Fzox3fZYMqRieiu0OZGJ2CgGi3ep0ieJVWcPQyhP.png',
                'darkIcons': '',
                'uri': '/earn',
                'zhUri': '/earn',
                'showMark': false,
                'id': '3038a84ff96613000975af5a',
                'sort': 1,
                'createdAt': 1678188141000,
              },
            ],
          },
          {
            'type': 'NAVIGATION_GROUP',
            'name': '穩健賺幣',
            'id': '64a3be9ea228e80001abdca0',
            'sort': 2,
            'children': [
              {
                'type': 'NAVIGATION_SECOND_LEVEL',
                'name': '余幣寶',
                'explain': '靈活存取，每日複利',
                'icons':
                  'https://assets.staticimg.com/cms/media/2yrr8NHGC7YJLaiqGHpylQ3x2JjCfTtG0AjLqTKIU.png',
                'darkIcons': '',
                'uri': '/earn/savings',
                'zhUri': '/earn/savings',
                'showMark': false,
                'id': '64a3c204a228e80001abde99',
                'sort': 1,
                'createdAt': 1688453636000,
              },
              {
                'type': 'NAVIGATION_SECOND_LEVEL',
                'name': 'Staking',
                'explain': '鏈上質押，穩定可靠',
                'icons':
                  'https://assets.staticimg.com/cms/media/6zPU5aV9NBCcO1lQyz9YjDtZmUoifAYAWPs2PCPMr.png',
                'darkIcons': '',
                'uri': '/earn/staking',
                'zhUri': '/earn/staking',
                'showMark': false,
                'id': '64a3ca3199fc520001fc5fea',
                'sort': 2,
                'createdAt': 1688455729000,
              },
              {
                'type': 'NAVIGATION_SECOND_LEVEL',
                'name': '限時活動',
                'explain': '限時高息，額度有限',
                'icons':
                  'https://assets.staticimg.com/cms/media/2fIyfkMyIuSX05WixaVwBbokFQgwgElKmQS8elChr.png',
                'darkIcons': '',
                'uri': '/earn/promotion',
                'zhUri': '/earn/promotion',
                'showMark': false,
                'id': '64a3cc0a99fc520001fc6121',
                'sort': 3,
                'createdAt': 1688456202000,
              },
              {
                'type': 'NAVIGATION_SECOND_LEVEL',
                'name': 'KCS Staking',
                'explain': '參與鏈上 KCS 治理 分享高額收益',
                'icons':
                  'https://assets.staticimg.com/cms/media/24HpzLKK84H1O6dFkNLZTFFqUGkppaCel0dF8Fjso.png',
                'darkIcons': '',
                'uri': '/earn/kcs',
                'zhUri': '/earn/kcs',
                'showMark': false,
                'id': '6566f1f61ff4910001840bf0',
                'sort': 4,
                'createdAt': 1701245430000,
              },
            ],
          },
          {
            'type': 'NAVIGATION_GROUP',
            'name': '進階投資',
            'id': '64a3bf61e8af6300018b9516',
            'sort': 3,
            'children': [
              {
                'type': 'NAVIGATION_SECOND_LEVEL',
                'name': '鯊魚鰭',
                'explain': '本金保障，收益進階',
                'icons':
                  'https://assets.staticimg.com/cms/media/4PVFz4D8sbyt0xanzYC53iNjpfzPjzqKblIMPAAR2.png',
                'darkIcons': '',
                'uri': '/earn/shark-fin',
                'zhUri': '/earn/shark-fin',
                'showMark': false,
                'id': '64a3cd5aa228e80001abe541',
                'sort': 1,
                'createdAt': 1688456538000,
              },
              {
                'type': 'NAVIGATION_SECOND_LEVEL',
                'name': '雙幣盈',
                'explain': '低買高賣，收益規則透明',
                'icons':
                  'https://assets.staticimg.com/cms/media/1fr5kOrRdBRxKDaTLWSZoibMqKySE9IWRvoOft4Kb.png',
                'darkIcons': '',
                'uri': '/earn/dual',
                'zhUri': '/earn/dual',
                'showMark': false,
                'id': '64a3ced9a228e80001abe64d',
                'sort': 2,
                'createdAt': 1688456921000,
              },
              {
                'type': 'NAVIGATION_SECOND_LEVEL',
                'name': '雪球',
                'explain': '價格保護，高收益',
                'icons':
                  'https://assets.staticimg.com/cms/media/8r3L3CJ5KstQmALDNpvcZO3NsmdZlXihL5LbQcRFs.png',
                'darkIcons': '',
                'uri': '/earn/snowball',
                'zhUri': '/earn/snowball',
                'showMark': false,
                'id': '33b3a5cfd3b84b000187edd1',
                'sort': 3,
                'createdAt': 1680778503000,
              },
            ],
          },
          {
            'type': 'NAVIGATION_GROUP',
            'name': '特色業務',
            'id': '64a3c01399fc520001fc59d9',
            'sort': 4,
            'children': [
              {
                'type': 'NAVIGATION_SECOND_LEVEL',
                'name': '大額閒幣賺息',
                'explain': '隨存隨取，靈活申贖',
                'icons':
                  'https://assets.staticimg.com/cms/media/1iEk06qXrx1RJ8khbpGSHSOmd2YGnKXqeuWoPx1ap.png',
                'darkIcons': '',
                'uri': '/margin/v2/lend',
                'zhUri': '/margin/v2/lend',
                'showMark': false,
                'id': '64747db85994d500015533c7',
                'sort': 1,
                'createdAt': 1685355960000,
              },
              {
                'type': 'NAVIGATION_SECOND_LEVEL',
                'name': 'Spotlight',
                'explain': '代幣發行平台',
                'icons':
                  'https://assets.staticimg.com/cms/media/5mjeg2WZToeB7AIHVb8igzRMAWpXTDeUs48vs8YwI.png',
                'darkIcons': '',
                'uri': '/spotlight-center',
                'zhUri': '/spotlight-center',
                'showMark': false,
                'id': '3038b1cdf96613000975afed',
                'sort': 2,
                'createdAt': 1678188084000,
              },
              {
                'type': 'NAVIGATION_SECOND_LEVEL',
                'name': 'KCS 專區',
                'explain': '持有 KCS 助您賺取更多收益',
                'icons':
                  'https://assets.staticimg.com/cms/media/6aJuTPEDQKDkfvNTxxTOdfCb12RPmsbESDIX14Tbo.png',
                'darkIcons': '',
                'uri': 'https://www.kucoin.com/kcs',
                'zhUri': 'https://www.kucoin.com/kcs',
                'showMark': false,
                'id': '3038ad8df96613000975afad',
                'sort': 3,
                'createdAt': 1682140507000,
              },
              {
                'type': 'NAVIGATION_SECOND_LEVEL',
                'name': 'GemPool',
                'explain': '鎖定代幣以獲得免費空投',
                'icons':
                  'https://assets.staticimg.com/cms/media/9TWeruHe5P6bymdYWcIcknE52Gq7lUlcOTcVyIa1R.png',
                'uri': 'https://www.kucoin.com/gempool',
                'zhUri': 'https://www.kucoin.com/gempool',
                'showMark': false,
                'id': '66b1cdae7c66a90001288158',
                'sort': 4,
                'createdAt': 1722928558000,
              },
            ],
          },
        ],
        'createdAt': 1683295111000,
      },
      {
        'type': 'NAVIGATION_FIRST_LEVEL',
        'name': '機構',
        'explain': '',
        'darkIcons': '',
        'uri': '',
        'zhUri': '',
        'showMark': false,
        'id': '64e822a0c5b9fc0001207c0f',
        'sort': 6,
        'children': [
          {
            'type': 'NAVIGATION_SECOND_LEVEL',
            'name': '機構主頁',
            'explain': '為專業人士提供一站式數字資產管理',
            'icons':
              'https://assets.staticimg.com/cms/media/7CK2gC4zI6kIVyl0X0M7ErVeOU0wVrITJM9DvGPT4.png',
            'darkIcons': '',
            'uri': '/institution',
            'zhUri': '/institution',
            'showMark': false,
            'id': '64e83cbbc643fb0001d3a68d',
            'sort': 1,
            'createdAt': 1692941499000,
          },
          {
            'type': 'NAVIGATION_SECOND_LEVEL',
            'name': '經紀商',
            'explain': '與我們一起經紀並賺取無與倫比的佣金',
            'icons':
              'https://assets.staticimg.com/cms/media/9fdDqR7K2A4bSCIE8CEO51EpL0J3GPpy44spX28F2.png',
            'darkIcons': '',
            'uri': '/broker',
            'zhUri': '/broker',
            'showMark': false,
            'id': '64e84113c5b9fc0001209e14',
            'sort': 2,
            'createdAt': 1692942611000,
          },
          {
            'type': 'NAVIGATION_SECOND_LEVEL',
            'name': 'API',
            'explain': '借助 API 的力量進行交易',
            'icons':
              'https://assets.staticimg.com/cms/media/42rGhZWSAe7RBV0da8Wl2QXpqZZ86i14T7RNgFEa0.png',
            'darkIcons': '',
            'uri': '/api',
            'zhUri': '/api',
            'showMark': false,
            'id': '64e83ee4c643fb0001d3a8fb',
            'sort': 3,
            'createdAt': 1692942052000,
          },
          {
            'type': 'NAVIGATION_SECOND_LEVEL',
            'name': 'VIP 借貸',
            'explain': '以最低的利率快速融資',
            'icons':
              'https://assets.staticimg.com/cms/media/6oiavY3N3E7m69xoOImgR8OKftAaXVEmpmZtTrcda.png',
            'darkIcons': '',
            'uri': '/institution/borrow',
            'zhUri': '/institution/borrow',
            'showMark': false,
            'id': '64e843c5c643fb0001d3adfb',
            'sort': 4,
            'createdAt': 1692943301000,
          },
          {
            'type': 'NAVIGATION_SECOND_LEVEL',
            'name': 'VIP 權益',
            'explain': '尊享全方位專屬特權',
            'icons':
              'https://assets.staticimg.com/cms/media/8KfiNHMyeeA65X9YK8gYlr4n7vZa6xoUFt7wL2iSK.png',
            'darkIcons': '',
            'uri': '/vip/privilege',
            'zhUri': '/vip/privilege',
            'showMark': false,
            'id': '65951f2c8a1df900010ec7a7',
            'sort': 5,
            'createdAt': 1704271660000,
          },
          {
            'type': 'NAVIGATION_SECOND_LEVEL',
            'name': '做市商',
            'explain': '享受高流動性的同時獲得豐厚回報',
            'icons':
              'https://assets.staticimg.com/cms/media/7YYvR7jjjSaw9GGHpjpF9J2XhB19SqfOCTng7qWYq.png',
            'darkIcons': '',
            'uri': '/institution/marketMaker',
            'zhUri': '/institution/marketMaker',
            'showMark': false,
            'id': '64f53b07cc73c700016f8bc3',
            'sort': 6,
            'createdAt': 1693793031000,
          },
        ],
        'createdAt': 1692934816000,
      },
      {
        'type': 'NAVIGATION_FIRST_LEVEL',
        'name': '更多',
        'explain': '',
        'darkIcons': '',
        'uri': '',
        'zhUri': '',
        'showMark': false,
        'id': '34550deb57634e00013f44bf',
        'sort': 7,
        'children': [
          {
            'type': 'NAVIGATION_GROUP',
            'name': '活動',
            'id': '645dea35a9f2aa00012b566b',
            'sort': 1,
            'children': [
              {
                'type': 'NAVIGATION_SECOND_LEVEL',
                'name': '邀請計劃',
                'explain': '邀請朋友賺取 20% 的佣金',
                'icons':
                  'https://assets.staticimg.com/cms/media/594yPw8LO3Pyc3KnWM9B2XERwObWNKnpqFAzqqGKy.png',
                'darkIcons': '',
                'uri': '/referral',
                'zhUri': '/referral',
                'showMark': false,
                'id': '3038b02cf96613000975afd4',
                'sort': 1,
                'createdAt': 1682136627000,
              },
              {
                'type': 'NAVIGATION_SECOND_LEVEL',
                'name': '合夥人計劃',
                'explain': '面向代理商、社區和KOL，賺取高達60%的佣金',
                'icons':
                  'https://assets.staticimg.com/cms/media/1PJxi3UW3sLDdw3zIXdya3aYjWdO6IJHfJx748aGb.png',
                'darkIcons': '',
                'uri': '/affiliate',
                'zhUri': '/affiliate',
                'showMark': false,
                'id': '3189e285fe1b8a0001c18231',
                'sort': 2,
                'createdAt': 1662369666000,
              },
              {
                'type': 'NAVIGATION_SECOND_LEVEL',
                'name': '福利中心',
                'explain': '8200 USDT 新手禮包，還有更多常客福利',
                'icons':
                  'https://assets.staticimg.com/cms/media/6MME8m18ivrkSZqbp6eXRug0EGVrX5tE5tT2Hi6ff.png',
                'darkIcons': '',
                'uri':
                  'https://www.kucoin.com/land/KuRewards?tabKey&spm=web_rewardhub_navigationbar',
                'zhUri':
                  'https://www.kucoin.com/land/KuRewards?tabKey&spm=web_rewardhub_navigationbar',
                'showMark': false,
                'id': '646cd86d5bb59f0001b11dac',
                'sort': 3,
                'createdAt': 1684854893000,
              },
              {
                'type': 'NAVIGATION_SECOND_LEVEL',
                'name': '現金禮包',
                'explain': '邀請好友，即有機會獲得現金獎勵',
                'icons':
                  'https://assets.staticimg.com/cms/media/5sYa0TNHk7sbL19QJcQaFAwopzfq5mAOoIJHXPEU4.png',
                'uri':
                  'https://www.kucoin.com/platform/earn-crypto-rewards-by-referring?loading=2&appNeedLang=true&utm_source=cashgift',
                'zhUri':
                  'https://www.kucoin.com/platform/earn-crypto-rewards-by-referring?loading=2&appNeedLang=true&utm_source=cashgift',
                'showMark': false,
                'id': '6719af88c1bd11000113671b',
                'sort': 4,
                'createdAt': 1729736584000,
              },
              {
                'type': 'NAVIGATION_SECOND_LEVEL',
                'name': 'GemVote',
                'explain': '完成任務即可獲得票數，以支持您喜歡的項目上線KuCoin',
                'icons':
                  'https://assets.staticimg.com/cms/media/6BHFXHSDEF2Jbxh5UkJZCi7AUqx4IPkLjoYJ9JEEf.png',
                'darkIcons': '',
                'uri': 'https://www.kucoin.com/gemvote',
                'zhUri': 'https://www.kucoin.com/gemvote',
                'showMark': false,
                'id': '65fc114e1003ca000147e4b9',
                'sort': 5,
                'createdAt': 1711018318000,
              },
              {
                'type': 'NAVIGATION_SECOND_LEVEL',
                'name': 'GemSlot',
                'explain': '每天完成任務即可獲得免費代幣空投',
                'icons':
                  'https://assets.staticimg.com/cms/media/4MtsPz35FDPPxonu4zIhp4T1Rc4vHqus2j2JEaRdQ.png',
                'uri': 'https://www.kucoin.com/gemslot',
                'zhUri': 'https://www.kucoin.com/gemslot',
                'showMark': false,
                'id': '66a89f5414e5a80001143f4a',
                'sort': 6,
                'createdAt': 1722326868000,
              },
            ],
          },
          {
            'type': 'NAVIGATION_GROUP',
            'name': '內容',
            'id': '645deb0ba9f2aa00012b56a2',
            'sort': 2,
            'children': [
              {
                'type': 'NAVIGATION_SECOND_LEVEL',
                'name': 'Learn & Earn',
                'explain': '透過學習來賺取加密貨幣',
                'icons':
                  'https://assets.staticimg.com/cms/media/4aONNvlo7RMtOBqChXGFXhIxcTI3ne0a23Z3fMxlW.png',
                'uri': 'https://www.kucoin.com/learn-and-earn',
                'zhUri': 'https://www.kucoin.com/learn-and-earn',
                'showMark': false,
                'id': '66c6e87423294d0001adceba',
                'sort': 1,
                'createdAt': 1724311668000,
              },
              {
                'type': 'NAVIGATION_SECOND_LEVEL',
                'name': 'KuCoin 學院',
                'explain': '學習加密貨幣和 Web3 的最佳渠道',
                'icons':
                  'https://assets.staticimg.com/cms/media/8DYbudVbHTmBz0Wva7ympLUsABfvVEj7Gff3U9Mae.png',
                'darkIcons': '',
                'uri': '/learn',
                'zhUri': '/learn',
                'showMark': false,
                'id': '64b0c85c3e332d0001f590e6',
                'sort': 2,
                'createdAt': 1689307228000,
              },
              {
                'type': 'NAVIGATION_SECOND_LEVEL',
                'name': '公告',
                'explain': '最新活動及公告',
                'icons':
                  'https://assets.staticimg.com/cms/media/24X10bN0uY7pC5LgprmIK85rnA2GTZ9BhnGpClnIU.png',
                'darkIcons': '',
                'uri': '/announcement',
                'zhUri': '/announcement',
                'showMark': false,
                'id': '3038b5a9f96613000975b061',
                'sort': 3,
                'createdAt': 1682138825000,
              },
              {
                'type': 'NAVIGATION_SECOND_LEVEL',
                'name': '博客',
                'explain': '區塊鏈和加密貨幣資訊平台',
                'icons':
                  'https://assets.staticimg.com/cms/media/3HqPcQZdFkqJF1R73pL37xQFtpgol9paKGoxNNOF8.png',
                'darkIcons': '',
                'uri': '/blog',
                'zhUri': '/blog',
                'showMark': false,
                'id': '30703af04e84ae0006c43175',
                'sort': 4,
                'createdAt': 1662437570000,
              },
              {
                'type': 'NAVIGATION_SECOND_LEVEL',
                'name': '安全',
                'explain': '安全手段，保障用戶資產安全',
                'icons':
                  'https://assets.staticimg.com/cms/media/2ih6veDRI0exAqmJSZb7M9U5hvyxaORkbJGw2j7vX.png',
                'darkIcons': '',
                'uri': '/security',
                'zhUri': '/security',
                'showMark': false,
                'id': '645de2eaa9f2aa00012b5584',
                'sort': 5,
                'createdAt': 1683874539000,
              },
            ],
          },
          {
            'type': 'NAVIGATION_GROUP',
            'name': '投資孵化',
            'id': '645dec10a9f2aa00012b56cf',
            'sort': 3,
            'children': [
              {
                'type': 'NAVIGATION_SECOND_LEVEL',
                'name': 'KuCoin Labs',
                'explain': 'KuCoin 投資調研實驗室',
                'icons':
                  'https://assets.staticimg.com/cms/media/4LdWwm6IbAyhairOWOsxRiPqeZLAOcu9bcLtEPMmD.png',
                'darkIcons': '',
                'uri': '/land/kucoinlabs',
                'zhUri': '/land/kucoinlabs',
                'showMark': false,
                'id': '318b654510f72e0001428418',
                'sort': 1,
                'createdAt': 1663124267000,
              },
            ],
          },
          {
            'type': 'NAVIGATION_GROUP',
            'name': '應用',
            'id': '6462fa2472b8af0001a76dfa',
            'sort': 4,
            'children': [
              {
                'type': 'NAVIGATION_SECOND_LEVEL',
                'name': 'API 交易',
                'explain': '每個 API 用戶都是我們的 VIP',
                'icons':
                  'https://assets.staticimg.com/cms/media/42rGhZWSAe7RBV0da8Wl2QXpqZZ86i14T7RNgFEa0.png',
                'darkIcons': '',
                'uri': '/api',
                'zhUri': '/api',
                'showMark': false,
                'id': '30386b89f96613000975ae4d',
                'sort': 1,
                'createdAt': 1681800511000,
              },
              {
                'type': 'NAVIGATION_SECOND_LEVEL',
                'name': 'KuCard',
                'explain': '消費返利',
                'icons':
                  'https://assets.staticimg.com/cms/media/2qnsWqwo5MIVAeqvajmIn3Gr3WxHbj5M00WH1YoK8.png',
                'darkIcons': '',
                'uri': '/kucard/mvp',
                'zhUri': '/kucard/mvp',
                'showMark': true,
                'marks': [
                  {
                    'type': 3,
                    'name': 'HOT',
                    'position': null,
                    'styleType': null,
                    'color': null,
                    'icons': null,
                    'darkIcons': null,
                    'startAt': 1730885220000,
                    'endAt': 1732094876000,
                    'expired': false,
                    'longShow': false,
                    'id': '672b36ecf7026d00018cdd10',
                  },
                ],
                'id': '32b595e19a59e60001245e91',
                'sort': 2,
                'createdAt': 1662438112000,
              },
              {
                'type': 'NAVIGATION_SECOND_LEVEL',
                'name': '社群',
                'explain': '分享社群空投及交易策略',
                'icons':
                  'https://assets.staticimg.com/cms/media/8lBxR4C4aNr0FUL5xw9qZ41JImGweUiDtzoMh55Em.png',
                'darkIcons': '',
                'uri': 'https://www.kucoin.com/land/community-collect',
                'zhUri': 'https://www.kucoin.com/land/community-collect',
                'showMark': false,
                'id': '65f3f191be16c000012a9a7b',
                'sort': 3,
                'createdAt': 1710485905000,
              },
            ],
          },
          {
            'type': 'NAVIGATION_GROUP',
            'name': 'Web3',
            'id': '668f833c094420000187df1a',
            'sort': 5,
            'children': [
              {
                'type': 'NAVIGATION_SECOND_LEVEL',
                'name': 'KCC',
                'explain': 'DeFi，NFT，Web3.0',
                'icons':
                  'https://assets.staticimg.com/cms/media/48UjIxygJXiVHfS7p19Wt1WkLXpOxCXOY830GY2Pr.png',
                'darkIcons': '',
                'uri': 'https://www.kcc.io',
                'zhUri': 'https://www.kcc.io',
                'showMark': false,
                'id': '3248076308bc660001fd4186',
                'sort': 1,
                'createdAt': 1649317193000,
              },
            ],
          },
        ],
        'createdAt': 1683295723000,
      },
    ],
  }).as('getNavigation');
}

/**
 * 拦截 notice 接口，不弹出弹窗
 */
export function restrictNoticeApi() {
  cy.intercept('/_api/user-dismiss/ip-dismiss/notice*', {
    statusCode: 200,
    body: {
      success: true,
      code: '200',
      data: null,
    },
  }).as('restrictNotice');
}
