packages:
  - packages/*

# Define a catalog of version ranges.
catalog:
  react: ^18.3.1
  "kc-web-checker": "0.6.1"
  "@types/react": ^18.3.1
  react-dom: ^18.3.1
  "@types/react-dom": ^18.3.1
  zustand: ^4.5.6
  vite: ^6.3.5
  sass: ^1.89.0
  vitest: ^3.2.4
  "@vitejs/plugin-react": ^4.6.0
  "@vitest/coverage-v8": "^3.2.4"
  "rollup-plugin-sourcemaps": "^0.6.3"
  "vite-plugin-dts": 4.2.4
  "vite-bundle-analyzer": ^1.0.0
  "@testing-library/dom": "^10.4.0"
  "@testing-library/react": "^16.0.1"
  "@testing-library/react-hooks": "^8.0.1"
  "@testing-library/user-event": "^14.0.1"
  "@laynezh/vite-plugin-lib-assets": "^2.1.0"
  "@natasha/release": "1.0.2-beta.2"
  typescript: ^5.8.3
  tsx: ^4.20.3
  "@types/node": ^20.0.0
  "eslint": "^9.17.0"
  "eslint-plugin-react": "^7.37.3"
  "eslint-plugin-react-hooks": "^5.1.0"
  "@eslint/js": "^9.17.0"
  "typescript-eslint": "^8.19.0"
  "vite-plugin-eslint": "^1.8.1"
  "postcss-logical-polyfill": "^0.5.0"
  turbo: ^2.5.4
  "@turbo/gen": ^2.5.4
  prettier: "^3.3.3"
  "ts-node": "^10.9.2"
  "jsdom": "^25.0.1"
  "@testing-library/jest-dom": "^6.4.6"
  "@types/jsdom": "^21.1.7"
  "webpack": "^5.98.0"
  "@types/systemjs": "6.15.1"
  "@playwright/test": "1.54.1"
