/**
      * This file is auto-generated by @kucoin/api-generator
      * Owner: sean.shi@kupotech.com
      */

export type AccountConfig = {
    accountTypes?: Array<'EMAIL' | 'PHONE'>;
    bindingLimits?: Array<'EMAIL' | 'PHONE'>;
    siteLogoUrl?: string;
    siteType?: string;
    subUserPermissions?: Array<'FUTURES' | 'HOSTED_TRADE_CREATE_APIKEY_BLACK' | 'MARGIN' | 'OPTION' | 'SPOT'>;
    subUserTypePermissionMap?: {
        [key: string]: Array<string>;
    };
    subUserTypes?: Array<'ATS' | 'COPY_TRADING' | 'FUTURES' | 'HOSTED' | 'LEAD_TRADING' | 'MARGIN' | 'NORMAL' | 'Novice' | 'OES' | 'OPTION' | 'ROBOT'>;
    supportExtAccounts?: Array<'APPLE' | 'APPLE_KC_INFO' | 'GOOGLE' | 'TELEGRAM'>;
    supportRCode?: boolean;
    supportSubAccount?: boolean;
};

export type BaseConfig = {
    siteConfigType?: 'INDEPENDENT' | 'SHARING';
    webHost?: string;
};

export type CountryCodeResponse = {
    cn?: string;
    code?: string;
    dismiss?: boolean;
    dismissLogin?: boolean;
    en?: string;
    ico?: string;
    mobileCode?: string;
    supportVoice?: boolean;
    weight?: number;
};

export type DirectoryConfig = {
    pageDirectorys?: Array<'ACCOUNTSECURITY' | 'API' | 'DOWNLOADCENTER' | 'KYC' | 'MYREWARD' | 'OVERVIEW' | 'SUBUSER'>;
    profilePhotoDirectorys?: Array<'ACCOUNTINFO' | 'ACCOUNTSECURITY' | 'API' | 'KYC' | 'MYREWARD' | 'RATESTANDARD' | 'SUBUSER'>;
    rateStandardUrl?: string;
};

export type ExternalAccountResponse = {
    countryCode?: string;
    email?: string;
    phone?: string;
    userInfo?: string;
};

export type GenericResult = {
    code?: string;
    data?: {
        [key: string]: unknown;
    };
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type GenericResult_ExternalAccountResponse_ = {
    code?: string;
    data?: ExternalAccountResponse;
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type GenericResult_List_CountryCodeResponse__ = {
    code?: string;
    data?: Array<CountryCodeResponse>;
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type GenericResult_List_List_string___ = {
    code?: string;
    data?: Array<Array<string>>;
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type GenericResult_List_userUpdateTermResponse__ = {
    code?: string;
    data?: Array<UserUpdateTermResponse>;
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type GenericResult_list_266573956422833361333034039564357773186722411__ = {
    code?: string;
    data?: Array<Common_266573956422833361333034039564357773186722411_>;
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type GenericResult_LoginResponse_ = {
    code?: string;
    data?: LoginResponse;
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type GenericResult_qrTokenResponse_ = {
    code?: string;
    data?: QrTokenResponse;
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type GenericResult_QueryChangePasswordResponse_ = {
    code?: string;
    data?: QueryChangePasswordResponse;
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type GenericResult_ReferrerInfoResponse_ = {
    code?: string;
    data?: ReferrerInfoResponse;
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type GenericResult_ResendVerifyEmailResponse_ = {
    code?: string;
    data?: ResendVerifyEmailResponse;
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type GenericResult_SiteConfig_ = {
    code?: string;
    data?: SiteConfig;
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type GenericResult_userResponse_ = {
    code?: string;
    data?: UserResponse;
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type GenericResult_Void_ = {
    code?: string;
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type GenericResult_boolean_ = {
    code?: string;
    data?: boolean;
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type GenericResult_int_ = {
    code?: string;
    data?: number;
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type GenericResult_string_ = {
    code?: string;
    data?: string;
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type GenericResult_214573686539564357773072136820222382596825454_ = {
    code?: string;
    data?: Common_214573686539564357773072136820222382596825454_;
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type GenericResult_2519530721Token2936624577_ = {
    code?: string;
    data?: Common_2519530721Token2936624577_;
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type GenericResult_2668125454Ip3371921462210403034020301326222044924687_ = {
    code?: string;
    data?: Common_2668125454Ip3371921462210403034020301326222044924687_;
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type GenericResult_303312440525480264353246726524_ = {
    code?: string;
    data?: Common_303312440525480264353246726524_;
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type GenericResult_3703820214254802643526657395643246726524_ = {
    code?: string;
    data?: Common_3703820214254802643526657395643246726524_;
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type GenericResult_370382021425480264353246726524_ = {
    code?: string;
    data?: Common_370382021425480264353246726524_;
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type LoginConfig = {
    loginAccountTypes?: Array<'EXTLOGIN' | 'PASSKEY' | 'USERPWD'>;
    loginPageContextUrl?: string;
};

/**
 * 登录成功返回
 */
export type LoginResponse = {
    /**
     * 区号
     */
    countryCode?: string;
    /**
     * 引导页展示的脱敏email地址
     */
    email?: string;
    /**
     * 是否完成迁移升级
     */
    finishUpgrade?: boolean;
    /**
     * 外部认证token
     */
    jwtToken?: string;
    /**
     * 登录安全语
     */
    loginSafeWord?: string;
    /**
     * 登录token
     */
    loginToken?: string;
    /**
     * 需要的验证
     */
    needValidations?: Array<Array<string>>;
    /**
     * 引导页展示的脱敏手机号
     */
    phone?: string;
    /**
     * 风控类型
     */
    riskStrategy?: string;
    /**
     * 风控标签
     */
    riskTag?: string;
    /**
     * 用户站点
     */
    siteType?: string;
    /**
     * 用户类型：用户类型 1（普通用户）2 （内部账号）3（子账号）4 (测试账号) 5 (返佣做市商) 6 (项目方) 7(项目方做市商) 8 (固定费率做市商)
     */
    type?: number;
    /**
     * 短信降费- 新页面调整
     */
    validationSwitch?: boolean;
    /**
     * 授权登录token
     */
    verifyCheckToken?: string;
    /**
     * 风控授权校验token
     */
    verifyToken?: string;
};

export type MyConfig = {
    directoryConfig?: DirectoryConfig;
    overviewConfig?: OverviewConfig;
};

export type OverviewConfig = {
    assetFuncs?: Array<'ASSETOVERVIEW' | 'BUYCOINS' | 'DEPOSITCOINS' | 'ENTRUSTEDINQUIRY' | 'WITHDRAWALCOINS'>;
    supportActivityEntry?: boolean;
    supportDownloadGuide?: boolean;
    supportKcsRight?: boolean;
    supportList?: boolean;
    supportMyInfo?: boolean;
    supportNewUserBenefits?: boolean;
    supportNotice?: boolean;
    supportVipRate?: boolean;
};

export type PassKeyLoginRequest = {
    /**
     * 端上认证passkey成功的返回体
     */
    credentialResponse?: string;
    /**
     * 外部登录校验标识
     */
    jwtLogin?: boolean;
    /**
     * 提示语言
     */
    lang?: string;
    /**
     * 第三方客户信息
     */
    thirdPartClient?: string;
    /**
     * 第三方活动
     */
    utmCampaign?: string;
    /**
     * 第三方媒体
     */
    utmMedium?: string;
};

export type PhoneEmailRegisterRequest = {
    /**
     * 神策需要的匿名id
     */
    anonymousId?: string;
    /**
     * APP版本
     */
    appVersion?: string;
    /**
     * 国际区号
     */
    countryCode?: string;
    /**
     * 设备名
     */
    device?: string;
    /**
     * 设备号
     */
    deviceNo?: string;
    /**
     * 邮箱
     */
    email?: string;
    /**
     * 密码
     */
    password?: string;
    /**
     * 电话号码
     */
    phone?: string;
    /**
     * 推荐码
     */
    referralCode?: string;
    /**
     * 注册开关
     */
    registerFlagRequests?: string;
    /**
     * 系统
     */
    system?: string;
    /**
     * 系统版本
     */
    systemVersion?: string;
    /**
     * 第三方客户信息
     */
    thirdPartClient?: string;
    /**
     * 第三方推荐码
     */
    thirdPartReferralCode?: string;
    /**
     * 时区
     */
    timeZone?: string;
    /**
     * 签署的协议
     */
    userTermSubRequests?: string;
    /**
     * 第三方活动
     */
    utmCampaign?: string;
    /**
     * 第三方媒体
     */
    utmMedium?: string;
};

export type QrTokenResponse = {
    /**
     * 过期时间
     */
    expiration?: number;
    /**
     * token, 用户app扫码验证
     */
    token?: string;
};

export type QueryChangePasswordResponse = {
    /**
     * exemptionDay
     */
    exemptionDay?: number;
    /**
     * overDue
     */
    overDue?: boolean;
};

/**
 * 推荐人信息返回
 */
export type ReferrerInfoResponse = {
    /**
     * 账号（有昵称显示昵称，没有显示脱敏邮箱或电话号码）
     */
    account?: string;
    /**
     * 头像
     */
    avator?: string;
};

export type RegisterConfig = {
    privacyTermsUrl?: string;
    registerPageContextUrl?: string;
    serviceTermsUrl?: string;
    supportRegisterGuide?: boolean;
};

export type ResendVerifyEmailResponse = {
    /**
     * 授权登录token
     */
    verifyCheckToken?: string;
    /**
     * 风控授权校验token
     */
    verifyToken?: string;
};

export type SecurityConfig = {
    antiPhishingCodeOpt?: boolean;
    biometricsOpt?: boolean;
    emailBindOpt?: boolean;
    extAccountBindOpt?: boolean;
    google2faOpt?: boolean;
    loginPwdOpt?: boolean;
    passkeyOpt?: boolean;
    phoneBindOpt?: boolean;
    withdrawPwdOpt?: boolean;
};

export type SiteConfig = {
    accountConfig?: AccountConfig;
    baseConfig?: BaseConfig;
    loginConfig?: LoginConfig;
    myConfig?: MyConfig;
    registerConfig?: RegisterConfig;
    securityConfig?: SecurityConfig;
    termConfig?: TermConfig;
};

export type TermConfig = {
    userTermConfig?: Array<UserTermConfig>;
};

/**
 * 用户基本信息返回
 */
export type UserResponse = {
    /**
     * 头像
     */
    avatar?: string;
    /**
     * 头像是否审核中 ture=审核中，false=审核通过
     */
    avatarPending?: boolean;
    /**
     * 余额计价币种
     */
    balanceCurrency?: string;
    /**
     * 手机区号
     */
    countryCode?: string;
    /**
     * 创建时间（注册时间）
     */
    createdAt?: string;
    /**
     * 币种
     */
    currency?: string;
    /**
     * 用户设备
     */
    device?: string;
    /**
     * 租户ID
     */
    domainId?: string;
    /**
     * 邮箱
     */
    email?: string;
    emailValidate?: boolean;
    existLoginPsd?: boolean;
    /**
     * vip等级 0- 3
     */
    honorLevel?: number;
    /**
     * 托管子账号绑定交易团队用户ID
     */
    hostedUserId?: string;
    /**
     * 用户ID
     */
    id?: string;
    /**
     * 邮箱是否已激活
     */
    isEmailValidate?: boolean;
    /**
     * 充币是否需要验证
     */
    isNeedDepositValidate?: boolean;
    /**
     * 手机是否已激活
     */
    isPhoneValidate?: boolean;
    /**
     * 语言
     */
    language?: string;
    /**
     * 上次登录时间
     */
    lastLoginAt?: string;
    /**
     * 上次登录国家
     */
    lastLoginCountry?: string;
    needDepositValidate?: boolean;
    /**
     * 昵称
     */
    nickname?: string;
    /**
     * 昵称是否审核中 ture=审核中，false=审核通过
     */
    nicknamePending?: boolean;
    /**
     * 1:oes已绑定；0：oes待绑定；其它值(包括-1)：无法绑定oes；默认值-1
     */
    oesBound?: number;
    /**
     * true:允许创建oes子账号；false/null：不允许创建oes子账号
     */
    oesSubEnabled?: boolean;
    /**
     * parentId
     */
    parentId?: string;
    /**
     * 开通的交易类型
     */
    permissionTrades?: Array<string>;
    /**
     * 手机号
     */
    phone?: string;
    phoneValidate?: boolean;
    /**
     * 推荐码
     */
    referralCode?: string;
    /**
     * 用户站点类型global主站，turkey土耳其站
     */
    siteType?: string;
    /**
     * 用户状态 1（未激活状态）2（新用户，已激活状态）3 （冻结状态）-1（已删除）0（禁用）9(迁移完成状态) 10 (升级交易密码完成状态，老用户激活状态)
     */
    status?: number;
    /**
     * subAccount
     */
    subAccount?: string;
    /**
     * 当前会员级别 1 - 3
     */
    subLevel?: number;
    /**
     * 子账号类型
     */
    subType?: number;
    /**
     * broker租户ID
     */
    tenant?: string;
    /**
     * 时区
     */
    timeZone?: string;
    /**
     * 开通的交易类型
     */
    tradeType?: number;
    /**
     * 用户类型 1（普通用户）2 （内部账号）3（子账号）4 (测试账号) 5 (返佣做市商) 6 (项目方) 7(项目方做市商) 8 (固定费率做市商)
     */
    type?: number;
    /**
     * 用户UID, 展示给用户
     */
    uid?: number;
    /**
     * web端用户登录设备限制数 -1为不限制
     */
    webDeviceLimit?: number;
};

export type UserTermConfig = {
    termCode?: string;
    termId?: string;
    version?: string;
};

export type UserTermRequest = {
    userTermSubRequests?: Array<UserTermSubRequest>;
};

export type UserTermSubRequest = {
    signState?: number;
    termId?: string;
    version?: string;
};

export type UserUpdateTermResponse = {
    agreementForm?: string;
    order?: number;
    termId?: string;
    title?: string;
};

export type Common_214573686539564357773072136820222382596825454_ = {
    /**
     * 最大重试次数
     */
    maxRetryTimes?: number;
    /**
     * 下次调用此接口是否需要验证，true:需要极验，false：不需要。当为true时客户端需要调用/captcha/init接口初始化极验等验证
     */
    needValidate?: boolean;
    /**
     * 下次可重试时间间隔 单位秒
     */
    retryAfterSeconds?: number;
    /**
     * 重试次数
     */
    retryTimes?: number;
};

export type Common_2519530721Token2936624577_ = {
    /**
     * 外部登录token
     */
    jwtToken?: string;
    /**
     * 用于登录的token，当状态为authorized时，才有值。需要调登录接口进行登录
     */
    loginToken?: string;
    /**
     * 需要的验证
     */
    needValidations?: Array<Array<string>>;
    /**
     * 风控标签
     */
    riskTag?: string;
    /**
     * 当前状态,值包括：waiting(等待扫码)，authorized(app已确认登录)，scanned(app已扫码)，expired(不存在或过期)
     */
    status?: string;
    /**
     * 授权登录token
     */
    verifyCheckToken?: string;
    /**
     * 风控授权校验token
     */
    verifyToken?: string;
};

export type Common_266573956422833361333034039564357773186722411_ = {
    checkResult?: string;
    failedCount?: number;
    maxFailedCount?: number;
    validationType?: 'CAPTCHA' | 'EMAIL' | 'GOOGLE_2FA' | 'MY_EMAIL' | 'MY_SMS' | 'MY_VOICE' | 'PASSKEY' | 'PASSWORD' | 'SECURITY_QUESTION' | 'SELF_QUESTION' | 'SMS' | 'VOICE' | 'WITHDRAW_PASSWORD';
};

export type Common_2668125454Ip3371921462210403034020301326222044924687_ = {
    /**
     * 城市名称
     */
    city?: string;
    /**
     * 国家名称
     */
    country?: string;
    /**
     * 两位的国家码
     */
    countryCode?: string;
    /**
     * IP地址 masked
     */
    ip?: string;
    /**
     * 是否支持手机注册
     */
    phoneSignUpEnabled?: boolean;
    /**
     * 时区
     */
    timezone?: string;
    /**
     * UTC 时区偏移，单位：小时
     */
    timezoneOffset?: number;
};

export type Common_303312440525480264353246726524_ = {
    loginInfo?: LoginResponse;
    /**
     * 授权结果,值包括：success(授权成功)，failed(授权失败)，expired(不存在或过期)
     */
    status?: string;
};

export type Common_315321997726041254802643527880208763583127714_ = {
    /**
     * 神策需要的匿名id
     */
    anonymousId?: string;
    /**
     * 验证码
     */
    code?: string;
    /**
     * 国际区号
     */
    countryCode?: string;
    /**
     * 邮箱
     */
    email?: string;
    /**
     * 第三方授权成功返回信息
     */
    extInfo?: {
        [key: string]: unknown;
    };
    /**
     * 第三方授权平台标识，如:TELEGRAM
     */
    extPlatform?: string;
    /**
     * 三方账号登录的token
     */
    loginToken?: string;
    /**
     * 电话号码
     */
    phone?: string;
    /**
     * 推荐码
     */
    referralCode?: string;
    /**
     * 注册开关
     */
    registerFlagRequests?: string;
    /**
     * 第三方客户信息
     */
    thirdPartClient?: string;
    /**
     * 第三方推荐码
     */
    thirdPartReferralCode?: string;
    /**
     * 签署的协议
     */
    userTermSubRequests?: string;
    /**
     * 第三方活动
     */
    utmCampaign?: string;
    /**
     * 第三方媒体
     */
    utmMedium?: string;
    /**
     * 校验方式 EMAIL | SMS | VOICE
     */
    validationType?: string;
};

export type Common_315321997726041254802643530331244053583127714_ = {
    /**
     * 第三方授权成功返回信息
     */
    extInfo?: {
        [key: string]: unknown;
    };
    /**
     * 第三方授权平台标识，如:TELEGRAM
     */
    extPlatform?: string;
};

export type Common_3703820214254802643526657395643246726524_ = {
    /**
     * 脱敏邮箱
     */
    email?: string;
    /**
     * 风控标签
     */
    riskTag?: string;
    /**
     * 授权checkToken
     */
    verifyCheckToken?: string;
    /**
     * 授权token
     */
    verifyToken?: string;
};

export type Common_370382021425480264353246726524_ = {
    /**
     * 授权结果,值包括：success(授权成功)，failed(授权失败)，unVerify(未授权)
     */
    status?: string;
    /**
     * 附加信息
     */
    verifyInfo?: {
        [key: string]: {
            [key: string]: unknown;
        };
    };
};

export type CheckAccountUsingPost1Data = {
    body?: Common_315321997726041254802643530331244053583127714_;
    path?: never;
    query?: never;
    url: '/check-account';
};

export type CheckAccountUsingPost1Responses = {
    /**
     * OK
     */
    200: GenericResult_int_;
};

export type CheckAccountUsingPost1Response = CheckAccountUsingPost1Responses[keyof CheckAccountUsingPost1Responses];

export type GetExternalAccountUsingPostData = {
    body?: Common_315321997726041254802643530331244053583127714_;
    path?: never;
    query?: never;
    url: '/external-account';
};

export type GetExternalAccountUsingPostResponses = {
    /**
     * OK
     */
    200: GenericResult_ExternalAccountResponse_;
};

export type GetExternalAccountUsingPostResponse = GetExternalAccountUsingPostResponses[keyof GetExternalAccountUsingPostResponses];

export type SignUpByExternalUsingPostData = {
    body?: Common_315321997726041254802643527880208763583127714_;
    path?: never;
    query?: never;
    url: '/external-register';
};

export type SignUpByExternalUsingPostResponses = {
    /**
     * OK
     */
    200: GenericResult_userResponse_;
};

export type SignUpByExternalUsingPostResponse = SignUpByExternalUsingPostResponses[keyof SignUpByExternalUsingPostResponses];

export type GetLoginVerifyResultUsingGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * verifyToken
         */
        verifyToken: string;
        /**
         * verifyCheckToken
         */
        verifyCheckToken: string;
    };
    url: '/login-verify/query';
};

export type GetLoginVerifyResultUsingGetResponses = {
    /**
     * OK
     */
    200: GenericResult_303312440525480264353246726524_;
};

export type GetLoginVerifyResultUsingGetResponse = GetLoginVerifyResultUsingGetResponses[keyof GetLoginVerifyResultUsingGetResponses];

export type ResendLoginVerifyEmailUsingPostData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * APP版本
         */
        appVersion?: string;
        /**
         * 授权校验token
         */
        verifyCheckToken?: string;
        /**
         * 授权token
         */
        verifyToken?: string;
    };
    url: '/login-verify/resend';
};

export type ResendLoginVerifyEmailUsingPostResponses = {
    /**
     * OK
     */
    200: GenericResult_ResendVerifyEmailResponse_;
};

export type ResendLoginVerifyEmailUsingPostResponse = ResendLoginVerifyEmailUsingPostResponses[keyof ResendLoginVerifyEmailUsingPostResponses];

export type PhoneNumberValidateUsingGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * account
         */
        account?: string;
    };
    url: '/phone-number-validate';
};

export type PhoneNumberValidateUsingGetResponses = {
    /**
     * OK
     */
    200: GenericResult_boolean_;
};

export type PhoneNumberValidateUsingGetResponse = PhoneNumberValidateUsingGetResponses[keyof PhoneNumberValidateUsingGetResponses];

export type SendRegisterEmailUsingPostData = {
    body?: never;
    path?: never;
    query: {
        /**
         * 邮箱
         */
        email: string;
        /**
         * 语言
         */
        lang?: string;
        /**
         * 业务类型
         */
        validationBiz?: string;
    };
    url: '/register-email';
};

export type SendRegisterEmailUsingPostResponses = {
    /**
     * OK
     */
    200: GenericResult_214573686539564357773072136820222382596825454_;
};

export type SendRegisterEmailUsingPostResponse = SendRegisterEmailUsingPostResponses[keyof SendRegisterEmailUsingPostResponses];

export type SendRegisterMessageUsingGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * 国际区号
         */
        countryCode: string;
        /**
         * 语言
         */
        lang?: string;
        /**
         * 电话号码
         */
        phone: string;
        /**
         * 发送类型:SMS(短信)/VOICE(语音验证码) 默认sms
         */
        sendChannel?: string;
        /**
         * 业务类型
         */
        validationBiz?: string;
    };
    url: '/register-short-message';
};

export type SendRegisterMessageUsingGetResponses = {
    /**
     * OK
     */
    200: GenericResult_214573686539564357773072136820222382596825454_;
};

export type SendRegisterMessageUsingGetResponse = SendRegisterMessageUsingGetResponses[keyof SendRegisterMessageUsingGetResponses];

export type ResetPasswordFromEmailUsingPostData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 邮箱
         */
        email?: string;
        /**
         * 新密码
         */
        password?: string;
    };
    url: '/reset-password-email';
};

export type ResetPasswordFromEmailUsingPostResponses = {
    /**
     * OK
     */
    200: GenericResult;
};

export type ResetPasswordFromEmailUsingPostResponse = ResetPasswordFromEmailUsingPostResponses[keyof ResetPasswordFromEmailUsingPostResponses];

export type ResetPasswordFromPhoneUsingPostData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 国家电话区号
         */
        countryCode?: string;
        /**
         * 新密码
         */
        password?: string;
        /**
         * 电话号码
         */
        phone?: string;
    };
    url: '/reset-password-phone';
};

export type ResetPasswordFromPhoneUsingPostResponses = {
    /**
     * OK
     */
    200: GenericResult;
};

export type ResetPasswordFromPhoneUsingPostResponse = ResetPasswordFromPhoneUsingPostResponses[keyof ResetPasswordFromPhoneUsingPostResponses];

export type SendLoginEmailUsingGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 语言，非必填
         */
        lang?: string;
        /**
         * 登录Token
         */
        token?: string;
    };
    url: '/send-login-email';
};

export type SendLoginEmailUsingGetResponses = {
    /**
     * OK
     */
    200: GenericResult;
};

export type SendLoginEmailUsingGetResponse = SendLoginEmailUsingGetResponses[keyof SendLoginEmailUsingGetResponses];

export type SendLoginSmsUsingGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 发送类型:MY_SMS(短信)/MY_VOICE(语音验证码) 默认MY_SMS
         */
        sendChannel?: string;
        /**
         * 登录Token
         */
        token?: string;
        /**
         * lang
         */
        lang?: string;
    };
    url: '/send-login-sms';
};

export type SendLoginSmsUsingGetResponses = {
    /**
     * OK
     */
    200: GenericResult;
};

export type SendLoginSmsUsingGetResponse = SendLoginSmsUsingGetResponses[keyof SendLoginSmsUsingGetResponses];

export type SignUpByEmailUsingPostData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 神策需要的匿名id
         */
        anonymousId?: string;
        /**
         * 邮箱
         */
        email?: string;
        /**
         * 密码
         */
        password?: string;
        /**
         * 推荐码
         */
        referralCode?: string;
        /**
         * 注册开关
         */
        registerFlagRequests?: string;
        /**
         * 第三方客户信息
         */
        thirdPartClient?: string;
        /**
         * 第三方推荐码
         */
        thirdPartReferralCode?: string;
        /**
         * 时区
         */
        timeZone?: string;
        /**
         * 签署的协议
         */
        userTermSubRequests?: string;
        /**
         * 第三方活动
         */
        utmCampaign?: string;
        /**
         * 第三方媒体
         */
        utmMedium?: string;
    };
    url: '/sign-up-email';
};

export type SignUpByEmailUsingPostResponses = {
    /**
     * OK
     */
    200: GenericResult_userResponse_;
};

export type SignUpByEmailUsingPostResponse = SignUpByEmailUsingPostResponses[keyof SignUpByEmailUsingPostResponses];

export type SignUpByPhoneNumberUsingPostData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 神策需要的匿名id
         */
        anonymousId?: string;
        /**
         * APP版本
         */
        appVersion?: string;
        /**
         * 国际区号
         */
        countryCode?: string;
        /**
         * 设备名
         */
        device?: string;
        /**
         * 设备号
         */
        deviceNo?: string;
        /**
         * 密码
         */
        password?: string;
        /**
         * 电话号码
         */
        phone?: string;
        /**
         * 推荐码
         */
        referralCode?: string;
        /**
         * 注册开关
         */
        registerFlagRequests?: string;
        /**
         * 系统
         */
        system?: string;
        /**
         * 系统版本
         */
        systemVersion?: string;
        /**
         * 第三方客户信息
         */
        thirdPartClient?: string;
        /**
         * 第三方推荐码
         */
        thirdPartReferralCode?: string;
        /**
         * 时区
         */
        timeZone?: string;
        /**
         * 签署的协议
         */
        userTermSubRequests?: string;
        /**
         * 第三方活动
         */
        utmCampaign?: string;
        /**
         * 第三方媒体
         */
        utmMedium?: string;
    };
    url: '/sign-up-phone';
};

export type SignUpByPhoneNumberUsingPostResponses = {
    /**
     * OK
     */
    200: GenericResult_userResponse_;
};

export type SignUpByPhoneNumberUsingPostResponse = SignUpByPhoneNumberUsingPostResponses[keyof SignUpByPhoneNumberUsingPostResponses];

export type SignUpByPhoneNumberAndEmailUsingPostData = {
    body?: PhoneEmailRegisterRequest;
    path?: never;
    query?: never;
    url: '/sign-up-phone-email';
};

export type SignUpByPhoneNumberAndEmailUsingPostResponses = {
    /**
     * OK
     */
    200: GenericResult_userResponse_;
};

export type SignUpByPhoneNumberAndEmailUsingPostResponse = SignUpByPhoneNumberAndEmailUsingPostResponses[keyof SignUpByPhoneNumberAndEmailUsingPostResponses];

export type ValidateSignUpCodeUsingPostData = {
    body?: never;
    path?: never;
    query: {
        /**
         * 邮箱或者区号拼接上电话号码
         */
        address: string;
        /**
         * 验证码
         */
        code: string;
        /**
         * 业务类型
         */
        validationBiz?: string;
        /**
         * 验证方式
         */
        validationType: string;
    };
    url: '/sign-up-validation';
};

export type ValidateSignUpCodeUsingPostResponses = {
    /**
     * OK
     */
    200: GenericResult_Void_;
};

export type ValidateSignUpCodeUsingPostResponse = ValidateSignUpCodeUsingPostResponses[keyof ValidateSignUpCodeUsingPostResponses];

export type ResetPasswordFromEmailV2UsingPostData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 邮箱
         */
        email?: string;
        /**
         * 新密码
         */
        password?: string;
    };
    url: '/v2/reset-password-email';
};

export type ResetPasswordFromEmailV2UsingPostResponses = {
    /**
     * OK
     */
    200: GenericResult;
};

export type ResetPasswordFromEmailV2UsingPostResponse = ResetPasswordFromEmailV2UsingPostResponses[keyof ResetPasswordFromEmailV2UsingPostResponses];

export type ResetPasswordFromPhoneV2UsingPostData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 国家电话区号
         */
        countryCode?: string;
        /**
         * 新密码
         */
        password?: string;
        /**
         * 电话号码
         */
        phone?: string;
    };
    url: '/v2/reset-password-phone';
};

export type ResetPasswordFromPhoneV2UsingPostResponses = {
    /**
     * OK
     */
    200: GenericResult;
};

export type ResetPasswordFromPhoneV2UsingPostResponse = ResetPasswordFromPhoneV2UsingPostResponses[keyof ResetPasswordFromPhoneV2UsingPostResponses];

export type ResetPasswordFromEmailV2UsingPost1Data = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 邮箱
         */
        email?: string;
        /**
         * 新密码
         */
        password?: string;
    };
    url: '/v3/reset-password-email';
};

export type ResetPasswordFromEmailV2UsingPost1Responses = {
    /**
     * OK
     */
    200: GenericResult;
};

export type ResetPasswordFromEmailV2UsingPost1Response = ResetPasswordFromEmailV2UsingPost1Responses[keyof ResetPasswordFromEmailV2UsingPost1Responses];

export type ResetPasswordFromEmailV2UsingPost2Data = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 邮箱
         */
        email?: string;
        /**
         * 新密码
         */
        password?: string;
    };
    url: '/v4/reset-password-email';
};

export type ResetPasswordFromEmailV2UsingPost2Responses = {
    /**
     * OK
     */
    200: GenericResult;
};

export type ResetPasswordFromEmailV2UsingPost2Response = ResetPasswordFromEmailV2UsingPost2Responses[keyof ResetPasswordFromEmailV2UsingPost2Responses];

export type ResetPasswordFromPhoneV2UsingPost2Data = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 国家电话区号
         */
        countryCode?: string;
        /**
         * 新密码
         */
        password?: string;
        /**
         * 电话号码
         */
        phone?: string;
    };
    url: '/v4/reset-password-phone';
};

export type ResetPasswordFromPhoneV2UsingPost2Responses = {
    /**
     * OK
     */
    200: GenericResult;
};

export type ResetPasswordFromPhoneV2UsingPost2Response = ResetPasswordFromPhoneV2UsingPost2Responses[keyof ResetPasswordFromPhoneV2UsingPost2Responses];

export type GetCountryCodeListUsingGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/country-codes';
};

export type GetCountryCodeListUsingGetResponses = {
    /**
     * OK
     */
    200: GenericResult_List_CountryCodeResponse__;
};

export type GetCountryCodeListUsingGetResponse = GetCountryCodeListUsingGetResponses[keyof GetCountryCodeListUsingGetResponses];

export type GetLocationsUsingGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/locale';
};

export type GetLocationsUsingGetResponses = {
    /**
     * OK
     */
    200: GenericResult_2668125454Ip3371921462210403034020301326222044924687_;
};

export type GetLocationsUsingGetResponse = GetLocationsUsingGetResponses[keyof GetLocationsUsingGetResponses];

export type GetEmailVerifyResultUsingGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * verifyToken
         */
        verifyToken: string;
        /**
         * verifyCheckToken
         */
        verifyCheckToken: string;
    };
    url: '/ucenter-email/query';
};

export type GetEmailVerifyResultUsingGetResponses = {
    /**
     * OK
     */
    200: GenericResult_370382021425480264353246726524_;
};

export type GetEmailVerifyResultUsingGetResponse = GetEmailVerifyResultUsingGetResponses[keyof GetEmailVerifyResultUsingGetResponses];

export type ResendVerifyEmailUsingPost1Data = {
    body?: never;
    path?: never;
    query: {
        /**
         * verifyToken
         */
        verifyToken: string;
        /**
         * verifyCheckToken
         */
        verifyCheckToken: string;
    };
    url: '/ucenter-email/resend';
};

export type ResendVerifyEmailUsingPost1Responses = {
    /**
     * OK
     */
    200: GenericResult_ResendVerifyEmailResponse_;
};

export type ResendVerifyEmailUsingPost1Response = ResendVerifyEmailUsingPost1Responses[keyof ResendVerifyEmailUsingPost1Responses];

export type RiskCheckUsingPostData = {
    body?: never;
    path?: never;
    query: {
        /**
         * account
         */
        account: string;
        /**
         * bizType
         */
        bizType: string;
    };
    url: '/ucenter-email/risk-check';
};

export type RiskCheckUsingPostResponses = {
    /**
     * OK
     */
    200: GenericResult_3703820214254802643526657395643246726524_;
};

export type RiskCheckUsingPostResponse = RiskCheckUsingPostResponses[keyof RiskCheckUsingPostResponses];

export type StartAssertionUsingGet1Data = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 用户的帐号
         */
        account?: string;
    };
    url: '/passkey/authentication/options';
};

export type StartAssertionUsingGet1Responses = {
    /**
     * OK
     */
    200: GenericResult_string_;
};

export type StartAssertionUsingGet1Response = StartAssertionUsingGet1Responses[keyof StartAssertionUsingGet1Responses];

export type GetUserReferrerInfoUsingGet1Data = {
    body?: never;
    path?: never;
    query?: {
        /**
         * referrerCode
         */
        referrerCode?: string;
    };
    url: '/user/referrer-info';
};

export type GetUserReferrerInfoUsingGet1Responses = {
    /**
     * OK
     */
    200: GenericResult_ReferrerInfoResponse_;
};

export type GetUserReferrerInfoUsingGet1Response = GetUserReferrerInfoUsingGet1Responses[keyof GetUserReferrerInfoUsingGet1Responses];

export type ExpandPasswordDurationUsingPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/expand-password-duration';
};

export type ExpandPasswordDurationUsingPostResponses = {
    /**
     * OK
     */
    200: GenericResult_Void_;
};

export type ExpandPasswordDurationUsingPostResponse = ExpandPasswordDurationUsingPostResponses[keyof ExpandPasswordDurationUsingPostResponses];

export type QueryChangePasswordUsingGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/query-change-password';
};

export type QueryChangePasswordUsingGetResponses = {
    /**
     * OK
     */
    200: GenericResult_QueryChangePasswordResponse_;
};

export type QueryChangePasswordUsingGetResponse = QueryChangePasswordUsingGetResponses[keyof QueryChangePasswordUsingGetResponses];

export type GetSitCustomConfigUsingGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/site-config';
};

export type GetSitCustomConfigUsingGetResponses = {
    /**
     * OK
     */
    200: GenericResult_SiteConfig_;
};

export type GetSitCustomConfigUsingGetResponse = GetSitCustomConfigUsingGetResponses[keyof GetSitCustomConfigUsingGetResponses];

export type GetUserInfoUsingGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user-info';
};

export type GetUserInfoUsingGetResponses = {
    /**
     * OK
     */
    200: GenericResult_userResponse_;
};

export type GetUserInfoUsingGetResponse = GetUserInfoUsingGetResponses[keyof GetUserInfoUsingGetResponses];

export type SetUserLocaleUsingPostData = {
    body?: never;
    headers: {
        /**
         * X-DOMAIN-ID
         */
        'X-DOMAIN-ID': string;
    };
    path?: never;
    query?: {
        /**
         * 余额计价币种
         */
        balanceCurrency?: string;
        /**
         * 汇率
         */
        currency?: string;
        /**
         * 语言
         */
        language?: string;
        /**
         * 时区
         */
        timeZone?: string;
    };
    url: '/user/locale';
};

export type SetUserLocaleUsingPostResponses = {
    /**
     * OK
     */
    200: GenericResult_Void_;
};

export type SetUserLocaleUsingPostResponse = SetUserLocaleUsingPostResponses[keyof SetUserLocaleUsingPostResponses];

export type QueryWaitedSignTermsUsingGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/query-waited-sign-term';
};

export type QueryWaitedSignTermsUsingGetResponses = {
    /**
     * OK
     */
    200: GenericResult_List_userUpdateTermResponse__;
};

export type QueryWaitedSignTermsUsingGetResponse = QueryWaitedSignTermsUsingGetResponses[keyof QueryWaitedSignTermsUsingGetResponses];

export type AppSignUserTermUsingPostData = {
    body?: UserTermRequest;
    path?: never;
    query?: never;
    url: '/user/sign-term';
};

export type AppSignUserTermUsingPostResponses = {
    /**
     * OK
     */
    200: GenericResult_boolean_;
};

export type AppSignUserTermUsingPostResponse = AppSignUserTermUsingPostResponses[keyof AppSignUserTermUsingPostResponses];

export type CheckRequiredValidationsUsingGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * 账号，忘记密码需要用到
         */
        address?: string;
        /**
         * 业务操作类型
         */
        bizType: 'ASSETS_REFUND_PAY_FEE' | 'BIND_EMAIL' | 'BIND_EMAIL_V2' | 'BIND_GOOGLE_2FA' | 'BIND_PHONE' | 'BIND_PHONE_V2' | 'CONFIRM_AUTH' | 'CONTRACT_TRADE' | 'CREATE_API' | 'CREATE_DEPOSIT_ADDRESS' | 'CREATE_SUB_ACCOUNT' | 'CREATE_SUB_ACCOUNT_API' | 'CREATE_WALLET_ADDRESS' | 'DELETE_SUB_ACCOUNT' | 'DEPOSIT' | 'DESTROY_ACCOUNT' | 'DISABLE_FAV_WITHDRAWAL' | 'EXCHANGE' | 'EXTERNAL_BINDING' | 'FIAT_WITHDRAW' | 'FORGET_WITHDRAWAL_PASSWORD' | 'FORGOT_PASSWORD' | 'FORGOT_PASSWORD_V2' | 'FROZEN_ACCOUNT' | 'GRAY_MARKET' | 'HOSTED_SUB_BIND_TRADE' | 'HOSTED_SUB_UNBIND_TRADE' | 'KCS_GAME_CENTER' | 'KUCOINPAY_ORDER' | 'KUCOIN_MALL_PAY' | 'LOGIN' | 'LOGIN_CHECK' | 'LOGIN_V2' | 'OTC_BIND_PAY' | 'OTC_SELL' | 'OTC_SETTLE' | 'PASSKEY_DELETE' | 'PASSKEY_LOGIN' | 'PASSKEY_REGISTER' | 'PASSKEY_UPDATE' | 'PAYMENT_FIAT_RECURRING' | 'PURCHASE_SPOT_NFT' | 'REBINDING_GOOGLE_2FA' | 'REBINDING_PHONE' | 'REGISTER' | 'REGISTER_EMAIL' | 'REGISTER_SMS' | 'RESET_SUB_ACCOUNT_2FA' | 'RESET_SUB_ACCOUNT_PASSWORD' | 'RESET_SUB_ACCOUNT_WITHDRAWAL_PASSWORD' | 'SELF_FROZEN_RISK_VERIFY' | 'SELL_BITCOIN' | 'SEND_RED_ENVELOPS' | 'SET_WITHDRAWAL_PASSWORD' | 'SPOTLIGHT_ORDER' | 'UNBIND_EMAIL' | 'UNBIND_PHONE' | 'UNFROZEN_ACCOUNT' | 'UNFROZEN_SUB_ACCOUNT' | 'UPDATE_API' | 'UPDATE_EMAIL' | 'UPDATE_EMAIL_V2' | 'UPDATE_GOOGLE_2FA' | 'UPDATE_PASSWORD' | 'UPDATE_PHONE' | 'UPDATE_PRIMARY_KYC' | 'UPDATE_SUB_ACCOUNT_API' | 'UPDATE_SUB_TRADE_TYPE' | 'UPDATE_TRADE_CUSTOM_VALIDATION' | 'UPDATE_WALLET_ADDRESS' | 'UPDATE_WITHDRAWAL_PASSWORD' | 'USER_CANCELLATION' | 'USER_UPGRADE' | 'VERIFY_WITHDRAWAL_PASSWORD' | 'WITHDRAWAL' | 'WITHDRAWAL_FAV' | 'WITHDRAW_SPOT_NFT';
        /**
         * currency-  bizType为SEND_RED_ENVELOPS的时候需要,代表发送红包的币种
         */
        currency?: string;
        loginToken?: string;
        /**
         * sendAmount-  bizType为SEND_RED_ENVELOPS的时候需要,代表发送红包的数量
         */
        sendAmount?: string;
        /**
         * 验证步数从1开始,默认1. 对于需要通过多个验证步骤才能完成的业务，seq必须按照当前验证步骤数传入
         */
        seq?: number;
        /**
         * 登陆返回的token-  用于手机不可用和谷歌不可用
         */
        token?: string;
    };
    url: '/check-required-validations';
};

export type CheckRequiredValidationsUsingGetResponses = {
    /**
     * OK
     */
    200: GenericResult_List_List_string___;
};

export type CheckRequiredValidationsUsingGetResponse = CheckRequiredValidationsUsingGetResponses[keyof CheckRequiredValidationsUsingGetResponses];

export type IsVoiceSupportUsingGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/country-codes/voice-support';
};

export type IsVoiceSupportUsingGetResponses = {
    /**
     * OK
     */
    200: GenericResult_List_CountryCodeResponse__;
};

export type IsVoiceSupportUsingGetResponse = IsVoiceSupportUsingGetResponses[keyof IsVoiceSupportUsingGetResponses];

export type SendValidationCodeUsingPostData = {
    body?: never;
    headers?: {
        /**
         * lang
         */
        lang?: string;
    };
    path?: never;
    query: {
        /**
         * 接收的手机号或邮件地址.sendChannel为SMS或EMAIL则必须， 如果sendChannel为MY_SMS或MY_EMAIL则不传,忘记密码场景MY_SMS或MY_EMAIL需要传
         */
        address?: string;
        /**
         * 业务操作类型; LOGIN:登陆,
         * REGISTER:注册,
         * FORGOT_PASSWORD:忘记密码,
         * UPDATE_PHONE:修改手机号,
         * BIND_PHONE:绑定手机号,
         * UPDATE_EMAIL:修改邮箱,
         * BIND_EMAIL:绑定邮箱,
         * BIND_GOOGLE_2FA:绑定谷歌两步验证,
         * UPDATE_GOOGLE_2FA:修改谷歌两步验证,
         * SET_WITHDRAWAL_PASSWORD:设置提现密码,
         * UPDATE_WITHDRAWAL_PASSWORD:修改提现密码,
         * FORGET_WITHDRAWAL_PASSWORD:忘记提现密码,
         * UPDATE_API:修改API,
         * CREATE_API:创建API,
         * CREATE_SUB_ACCOUNT:创建子账号,
         * UPDATE_PASSWORD:修改登陆密码,
         * DESTROY_ACCOUNT:注销账号,
         * FROZEN_ACCOUNT:冻结账号,
         * UNFROZEN_ACCOUNT:解冻账号,
         * DEPOSIT:充值,
         * WITHDRAWAL:提币,
         * UPDATE_WALLET_ADDRESS:修改钱包地址,
         * CREATE_WALLET_ADDRESS:新增钱包/提现地址,
         * EXCHANGE:币币交易,
         * CREATE_DEPOSIT_ADDRESS:新增充值地址
         * REBINDING_PHONE:手机不可用
         * REBINDING_GOOGLE_2FA:两步验证不可用
         * WITHDRAWAL_FAV:常用地址提币
         */
        bizType: 'ASSETS_REFUND_PAY_FEE' | 'BIND_EMAIL' | 'BIND_EMAIL_V2' | 'BIND_GOOGLE_2FA' | 'BIND_PHONE' | 'BIND_PHONE_V2' | 'CONFIRM_AUTH' | 'CONTRACT_TRADE' | 'CREATE_API' | 'CREATE_DEPOSIT_ADDRESS' | 'CREATE_SUB_ACCOUNT' | 'CREATE_SUB_ACCOUNT_API' | 'CREATE_WALLET_ADDRESS' | 'DELETE_SUB_ACCOUNT' | 'DEPOSIT' | 'DESTROY_ACCOUNT' | 'DISABLE_FAV_WITHDRAWAL' | 'EXCHANGE' | 'EXTERNAL_BINDING' | 'FIAT_WITHDRAW' | 'FORGET_WITHDRAWAL_PASSWORD' | 'FORGOT_PASSWORD' | 'FORGOT_PASSWORD_V2' | 'FROZEN_ACCOUNT' | 'GRAY_MARKET' | 'HOSTED_SUB_BIND_TRADE' | 'HOSTED_SUB_UNBIND_TRADE' | 'KCS_GAME_CENTER' | 'KUCOINPAY_ORDER' | 'KUCOIN_MALL_PAY' | 'LOGIN' | 'LOGIN_CHECK' | 'LOGIN_V2' | 'OTC_BIND_PAY' | 'OTC_SELL' | 'OTC_SETTLE' | 'PASSKEY_DELETE' | 'PASSKEY_LOGIN' | 'PASSKEY_REGISTER' | 'PASSKEY_UPDATE' | 'PAYMENT_FIAT_RECURRING' | 'PURCHASE_SPOT_NFT' | 'REBINDING_GOOGLE_2FA' | 'REBINDING_PHONE' | 'REGISTER' | 'REGISTER_EMAIL' | 'REGISTER_SMS' | 'RESET_SUB_ACCOUNT_2FA' | 'RESET_SUB_ACCOUNT_PASSWORD' | 'RESET_SUB_ACCOUNT_WITHDRAWAL_PASSWORD' | 'SELF_FROZEN_RISK_VERIFY' | 'SELL_BITCOIN' | 'SEND_RED_ENVELOPS' | 'SET_WITHDRAWAL_PASSWORD' | 'SPOTLIGHT_ORDER' | 'UNBIND_EMAIL' | 'UNBIND_PHONE' | 'UNFROZEN_ACCOUNT' | 'UNFROZEN_SUB_ACCOUNT' | 'UPDATE_API' | 'UPDATE_EMAIL' | 'UPDATE_EMAIL_V2' | 'UPDATE_GOOGLE_2FA' | 'UPDATE_PASSWORD' | 'UPDATE_PHONE' | 'UPDATE_PRIMARY_KYC' | 'UPDATE_SUB_ACCOUNT_API' | 'UPDATE_SUB_TRADE_TYPE' | 'UPDATE_TRADE_CUSTOM_VALIDATION' | 'UPDATE_WALLET_ADDRESS' | 'UPDATE_WITHDRAWAL_PASSWORD' | 'USER_CANCELLATION' | 'USER_UPGRADE' | 'VERIFY_WITHDRAWAL_PASSWORD' | 'WITHDRAWAL' | 'WITHDRAWAL_FAV' | 'WITHDRAW_SPOT_NFT';
        /**
         * 额外的参数，key-value格式,多个用逗号,分隔。如foo=bar,foo1=bar1
         */
        ext?: Array<string>;
        /**
         * 验证码发送通道,支持SMS,VOICE(语音-指定语音验证码验证),EMAIL,MY_SMS,；,MY_EMAIL. MY_*为验证自己的号码；
         */
        sendChannel: 'CAPTCHA' | 'EMAIL' | 'GOOGLE_2FA' | 'MY_EMAIL' | 'MY_SMS' | 'MY_VOICE' | 'PASSKEY' | 'PASSWORD' | 'SECURITY_QUESTION' | 'SELF_QUESTION' | 'SMS' | 'VOICE' | 'WITHDRAW_PASSWORD';
        /**
         * 登陆返回的token-  用于手机不可用和谷歌不可用
         */
        token?: string;
    };
    url: '/send-validation-code';
};

export type SendValidationCodeUsingPostResponses = {
    /**
     * OK
     */
    200: GenericResult_214573686539564357773072136820222382596825454_;
};

export type SendValidationCodeUsingPostResponse = SendValidationCodeUsingPostResponses[keyof SendValidationCodeUsingPostResponses];

export type VerifyValidationCodeUsingPostData = {
    body?: never;
    path?: never;
    query: {
        /**
         * 发送验证码传递的手机号或邮箱，发验证码时传了手机或邮箱此参数就必须
         */
        address?: string;
        /**
         * 业务操作类型; LOGIN:登陆,
         * REGISTER:注册,
         * FORGOT_PASSWORD:忘记密码,
         * UPDATE_PHONE:修改手机号,
         * BIND_PHONE:绑定手机号,
         * UPDATE_EMAIL:修改邮箱,
         * BIND_EMAIL:绑定邮箱,
         * BIND_GOOGLE_2FA:绑定谷歌两步验证,
         * UPDATE_GOOGLE_2FA:修改谷歌两步验证,
         * SET_WITHDRAWAL_PASSWORD:设置提现密码,
         * UPDATE_WITHDRAWAL_PASSWORD:修改提现密码,
         * FORGET_WITHDRAWAL_PASSWORD:忘记提现密码,
         * UPDATE_API:修改API,
         * CREATE_API:创建API,
         * CREATE_SUB_ACCOUNT:创建子账号,
         * UPDATE_PASSWORD:修改登陆密码,
         * DESTROY_ACCOUNT:注销账号,
         * FROZEN_ACCOUNT:冻结账号,
         * UNFROZEN_ACCOUNT:解冻账号,
         * DEPOSIT:充值,
         * WITHDRAWAL:提币,
         * FIAT_WITHDRAW:法币提现,
         * UPDATE_WALLET_ADDRESS:修改钱包地址,
         * CREATE_WALLET_ADDRESS:新增钱包/提现地址,
         * EXCHANGE:币币交易,
         * CREATE_DEPOSIT_ADDRESS:新增充值地址
         * REBINDING_PHONE:手机不可用
         * REBINDING_GOOGLE_2FA:两步验证不可用
         * WITHDRAWAL_FAV:常用地址提币
         * USER_UPGRADE:迁移安全问题升级
         * SPOTLIGHT_ORDER:IEO抢购
         * CONTRACT_TRADE:合约交易下单
         * OTC_SELL:OTC卖币
         * OTC_SETTLE:OTC放币
         * OTC_BIND_PAY:添加支付方式
         * SEND_RED_ENVELOPS:app发送红包
         * POOL_X:矿池
         * KCS_GAME_CENTER:kcs生态游戏中心
         */
        bizType: 'ASSETS_REFUND_PAY_FEE' | 'BIND_EMAIL' | 'BIND_EMAIL_V2' | 'BIND_GOOGLE_2FA' | 'BIND_PHONE' | 'BIND_PHONE_V2' | 'CONFIRM_AUTH' | 'CONTRACT_TRADE' | 'CREATE_API' | 'CREATE_DEPOSIT_ADDRESS' | 'CREATE_SUB_ACCOUNT' | 'CREATE_SUB_ACCOUNT_API' | 'CREATE_WALLET_ADDRESS' | 'DELETE_SUB_ACCOUNT' | 'DEPOSIT' | 'DESTROY_ACCOUNT' | 'DISABLE_FAV_WITHDRAWAL' | 'EXCHANGE' | 'EXTERNAL_BINDING' | 'FIAT_WITHDRAW' | 'FORGET_WITHDRAWAL_PASSWORD' | 'FORGOT_PASSWORD' | 'FORGOT_PASSWORD_V2' | 'FROZEN_ACCOUNT' | 'GRAY_MARKET' | 'HOSTED_SUB_BIND_TRADE' | 'HOSTED_SUB_UNBIND_TRADE' | 'KCS_GAME_CENTER' | 'KUCOINPAY_ORDER' | 'KUCOIN_MALL_PAY' | 'LOGIN' | 'LOGIN_CHECK' | 'LOGIN_V2' | 'OTC_BIND_PAY' | 'OTC_SELL' | 'OTC_SETTLE' | 'PASSKEY_DELETE' | 'PASSKEY_LOGIN' | 'PASSKEY_REGISTER' | 'PASSKEY_UPDATE' | 'PAYMENT_FIAT_RECURRING' | 'PURCHASE_SPOT_NFT' | 'REBINDING_GOOGLE_2FA' | 'REBINDING_PHONE' | 'REGISTER' | 'REGISTER_EMAIL' | 'REGISTER_SMS' | 'RESET_SUB_ACCOUNT_2FA' | 'RESET_SUB_ACCOUNT_PASSWORD' | 'RESET_SUB_ACCOUNT_WITHDRAWAL_PASSWORD' | 'SELF_FROZEN_RISK_VERIFY' | 'SELL_BITCOIN' | 'SEND_RED_ENVELOPS' | 'SET_WITHDRAWAL_PASSWORD' | 'SPOTLIGHT_ORDER' | 'UNBIND_EMAIL' | 'UNBIND_PHONE' | 'UNFROZEN_ACCOUNT' | 'UNFROZEN_SUB_ACCOUNT' | 'UPDATE_API' | 'UPDATE_EMAIL' | 'UPDATE_EMAIL_V2' | 'UPDATE_GOOGLE_2FA' | 'UPDATE_PASSWORD' | 'UPDATE_PHONE' | 'UPDATE_PRIMARY_KYC' | 'UPDATE_SUB_ACCOUNT_API' | 'UPDATE_SUB_TRADE_TYPE' | 'UPDATE_TRADE_CUSTOM_VALIDATION' | 'UPDATE_WALLET_ADDRESS' | 'UPDATE_WITHDRAWAL_PASSWORD' | 'USER_CANCELLATION' | 'USER_UPGRADE' | 'VERIFY_WITHDRAWAL_PASSWORD' | 'WITHDRAWAL' | 'WITHDRAWAL_FAV' | 'WITHDRAW_SPOT_NFT';
        /**
         * 验证的顺序，默认1。业务需要验证次数的序号，从1开始；用于控制验证流程和检测验证是否通过
         */
        seq?: number;
        /**
         * 登陆返回的token-  用于手机不可用和谷歌不可用
         */
        token?: string;
        /**
         * 校验内容 <xK,V><验证方式，验证码>， 安全问题验证SECURITY_QUESTION， 验证码的格式为：问题:答案，冒号分隔
         */
        validations: unknown;
    };
    url: '/verify-validation-code';
};

export type VerifyValidationCodeUsingPostResponses = {
    /**
     * OK
     */
    200: GenericResult_list_266573956422833361333034039564357773186722411__;
};

export type VerifyValidationCodeUsingPostResponse = VerifyValidationCodeUsingPostResponses[keyof VerifyValidationCodeUsingPostResponses];

export type AggregationLoginUsingPostData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 邮箱或手机号码/子账号名称
         */
        account?: string;
        /**
         * 外部登录校验标识
         */
        jwtLogin?: boolean;
        /**
         * 提示语言
         */
        lang?: string;
        /**
         * 密码
         */
        password?: string;
        /**
         * 第三方客户信息
         */
        thirdPartClient?: string;
        /**
         * 第三方活动
         */
        utmCampaign?: string;
        /**
         * 第三方媒体
         */
        utmMedium?: string;
    };
    url: '/aggregate-login';
};

export type AggregationLoginUsingPostResponses = {
    /**
     * OK
     */
    200: GenericResult_LoginResponse_;
};

export type AggregationLoginUsingPostResponse = AggregationLoginUsingPostResponses[keyof AggregationLoginUsingPostResponses];

export type ExternalLoginUsingPost1Data = {
    body?: Common_315321997726041254802643530331244053583127714_;
    path?: never;
    query?: never;
    url: '/external-login';
};

export type ExternalLoginUsingPost1Responses = {
    /**
     * OK
     */
    200: GenericResult_LoginResponse_;
};

export type ExternalLoginUsingPost1Response = ExternalLoginUsingPost1Responses[keyof ExternalLoginUsingPost1Responses];

export type LoginKickOutUsingPostData = {
    body?: string;
    headers?: {
        /**
         * X-APP-FROM
         */
        'X-APP-FROM'?: string;
    };
    path?: never;
    query?: {
        /**
         * trustDevice
         */
        trustDevice?: boolean;
        /**
         * loginDecision
         */
        loginDecision?: number;
    };
    url: '/login-kickout';
};

export type LoginKickOutUsingPostResponses = {
    /**
     * OK
     */
    200: GenericResult_userResponse_;
};

export type LoginKickOutUsingPostResponse = LoginKickOutUsingPostResponses[keyof LoginKickOutUsingPostResponses];

export type PassLoginUsingPostData = {
    body?: PassKeyLoginRequest;
    path?: never;
    query?: never;
    url: '/passkey-login';
};

export type PassLoginUsingPostResponses = {
    /**
     * OK
     */
    200: GenericResult_LoginResponse_;
};

export type PassLoginUsingPostResponse = PassLoginUsingPostResponses[keyof PassLoginUsingPostResponses];

export type ObtainQrTokenUsingPostData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 外部登录校验标识
         */
        jwtLogin?: boolean;
        /**
         * 提示语言
         */
        lang?: string;
        /**
         * 第三方客户信息
         */
        thirdPartClient?: string;
        /**
         * 第三方活动
         */
        utmCampaign?: string;
        /**
         * 第三方媒体
         */
        utmMedium?: string;
    };
    url: '/qr-token/create';
};

export type ObtainQrTokenUsingPostResponses = {
    /**
     * OK
     */
    200: GenericResult_qrTokenResponse_;
};

export type ObtainQrTokenUsingPostResponse = ObtainQrTokenUsingPostResponses[keyof ObtainQrTokenUsingPostResponses];

export type CheckQrTokenStatusUsingGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * qrToken
         */
        qrToken: string;
    };
    url: '/qr-token/status';
};

export type CheckQrTokenStatusUsingGetResponses = {
    /**
     * OK
     */
    200: GenericResult_2519530721Token2936624577_;
};

export type CheckQrTokenStatusUsingGetResponse = CheckQrTokenStatusUsingGetResponses[keyof CheckQrTokenStatusUsingGetResponses];

export type AggregationLoginV2UsingPostData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 邮箱或手机号码/子账号名称
         */
        account?: string;
        /**
         * 外部登录校验标识
         */
        jwtLogin?: boolean;
        /**
         * 提示语言
         */
        lang?: string;
        /**
         * 密码
         */
        password?: string;
        /**
         * 第三方客户信息
         */
        thirdPartClient?: string;
        /**
         * 第三方活动
         */
        utmCampaign?: string;
        /**
         * 第三方媒体
         */
        utmMedium?: string;
    };
    url: '/v2/aggregate-login';
};

export type AggregationLoginV2UsingPostResponses = {
    /**
     * OK
     */
    200: GenericResult_LoginResponse_;
};

export type AggregationLoginV2UsingPostResponse = AggregationLoginV2UsingPostResponses[keyof AggregationLoginV2UsingPostResponses];

export type ExternalLoginV2UsingPost1Data = {
    body?: Common_315321997726041254802643530331244053583127714_;
    path?: never;
    query?: never;
    url: '/v2/external-login';
};

export type ExternalLoginV2UsingPost1Responses = {
    /**
     * OK
     */
    200: GenericResult_LoginResponse_;
};

export type ExternalLoginV2UsingPost1Response = ExternalLoginV2UsingPost1Responses[keyof ExternalLoginV2UsingPost1Responses];

export type ValidateLoginV2UsingPost1Data = {
    body?: never;
    headers?: {
        /**
         * X-APP-FROM
         */
        'X-APP-FROM'?: string;
        /**
         * x-last-login-device
         */
        'x-last-login-device'?: string;
        /**
         * x-online-session-count
         */
        'x-online-session-count'?: string;
    };
    path?: never;
    query: {
        anonymousId?: string;
        /**
         * 三方场景的登录策略，1：三方绑定登录，2:三方换绑登录
         */
        loginDecision?: number;
        /**
         * 登录成功后返回的token
         */
        token: string;
        /**
         * 是否信赖设备
         */
        trustDevice?: boolean;
        /**
         * 验证码
         */
        validations?: string;
    };
    url: '/v2/login-validation';
};

export type ValidateLoginV2UsingPost1Responses = {
    /**
     * OK
     */
    200: GenericResult_userResponse_;
};

export type ValidateLoginV2UsingPost1Response = ValidateLoginV2UsingPost1Responses[keyof ValidateLoginV2UsingPost1Responses];

export type ClientOptions = { baseURL: string; };