/**
      * This file is auto-generated by @kucoin/api-generator
      * Owner: sean.shi@kupotech.com
      */

import type { Options as ClientOptions, TDataShape, Client } from 'tools/request';
import type { GetValidationsUsingPostData, GetValidationsUsingPostResponse, GetRiskUserSecurityInfoUsingGetData, GetRiskUserSecurityInfoUsingGetResponse, RiskValidationVerifyUsingPostData, RiskValidationVerifyUsingPostResponse, SendValidationCodeUsingPostData, SendValidationCodeUsingPostResponse } from './types.gen';
import { client as _apiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape> = ClientOptions<TData> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
 disabledLang?: boolean;
};

/**
 * getValidations
 */
export const getValidationsUsingPost = (body?: GetValidationsUsingPostData['body'],options?: Options<GetValidationsUsingPostData>) => {
    return (options?.client ?? _apiClient).post<GetValidationsUsingPostResponse>({
        url: '/v1/security/validation/combine',
        body,
...(options || {}),
        headers: {
            'Content-Type': 'application/json',
            ...(options?.headers || {})
        }
    });
};

/**
 * 查询用户安全项信息
 */
export const getRiskUserSecurityInfoUsingGet = (options?: Options<GetRiskUserSecurityInfoUsingGetData>) => {
    return (options?.client ?? _apiClient).get<GetRiskUserSecurityInfoUsingGetResponse>({
        url: '/v1/security/validation/inner/user-info',
        ...(options || {})
    });
};

/**
 * riskValidationVerify
 */
export const riskValidationVerifyUsingPost = (body?: RiskValidationVerifyUsingPostData['body'],options?: Options<RiskValidationVerifyUsingPostData>) => {
    return (options?.client ?? _apiClient).post<RiskValidationVerifyUsingPostResponse>({
        url: '/v1/security/validation/risk/verify',
        body,
...(options || {}),
        headers: {
            'Content-Type': 'application/json',
            ...(options?.headers || {})
        }
    });
};

/**
 * sendValidationCode
 */
export const sendValidationCodeUsingPost = (body: SendValidationCodeUsingPostData['query'],options?: Options<SendValidationCodeUsingPostData>) => {
    return (options?.client ?? _apiClient).post<SendValidationCodeUsingPostResponse>({
        querySerializer: {
            array: {
                explode: false,
                style: 'form'
            }
        },
        url: '/v1/security/validation/send-validation-code',
        body,
...(options || {})
    });
};