/**
      * This file is auto-generated by @kucoin/api-generator
      * Owner: sean.shi@kupotech.com
      */

export type GenericResult_RatingPriorityResponse_ = {
    code?: string;
    data?: RatingPriorityResponse;
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type GenericResult_RiskUserSecurityInfoResponse_ = {
    code?: string;
    data?: RiskUserSecurityInfoResponse;
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type GenericResult_sendVerificationCodeToReturnData_ = {
    code?: string;
    data?: Common_214573686539564357773072136820222382596825454_;
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type GenericResult_verificationTypeThatFailsToVerify_ = {
    code?: string;
    data?: Common_266573956422833361333034039564357773186722411_;
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type RatingPriorityResponse = {
    best?: Array<string>;
    needVerify?: boolean;
    others?: Array<Array<string>>;
    supplement?: Array<Array<string>>;
    token?: string;
    transactionId?: string;
};

export type RiskUserSecurityInfoResponse = {
    /**
     * passkey相关信息
     */
    passkeyInfo?: string;
};

export type SecurityValidationRequest = {
    bizType?: string;
    data?: {
        [key: string]: unknown;
    };
    permitValidateType?: Array<string>;
};

export type Common_214573686539564357773072136820222382596825454_ = {
    /**
     * 最大重试次数
     */
    maxRetryTimes?: number;
    /**
     * 下次可重试时间间隔 单位秒
     */
    retryAfterSeconds?: number;
    /**
     * 重试次数
     */
    retryTimes?: number;
};

export type Common_266573956422833361333034039564357773186722411_ = {
    checkResult?: string;
    checkResultMsg?: string;
    failedCount?: number;
    maxFailedCount?: number;
    validationType?: 'AI' | 'DFP' | 'EMA' | 'EMV' | 'FID' | 'GAV' | 'HIT_DATA_BASE' | 'ID6' | 'MAIL_WORD' | 'MY_EMV' | 'MY_SMS' | 'MY_VOICE' | 'NAR' | 'PASSWORD' | 'PK' | 'PM6' | 'QV1' | 'SI' | 'SMS' | 'TP' | 'VOICE';
};

export type Common_26657395643956435777307212144225968_ = {
    /**
     * 发送验证码传递的手机号或邮箱，发验证码时传了手机或邮箱此参数就必须
     */
    address?: string;
    /**
     * 业务操作类型; RV_LOGIN:登陆,
     * RV_UPDATE_PHONE:修改手机号,
     *
     */
    bizType: 'RV_ALPHA' | 'RV_CARD_PAYOUT' | 'RV_CLAIM_WITHDRAW' | 'RV_KA_BILL' | 'RV_LOGIN' | 'RV_LOGIN_PWD_SET' | 'RV_OAUTH_GRANT' | 'RV_SET_SAFE_WORD' | 'RV_UPDATE_EMAIL' | 'RV_UPDATE_PHONE' | 'RV_WITHDRAWAL' | 'RV_WITHDRAWAL_FAV';
    /**
     * 该字段非前端风控验证用，只用于后端二次验证通过后清除风控豁免状态：例如修改手机号场景中，旧手机的验证状态存在豁免逻辑，新手机校验通过后清理豁免状态
     */
    clearStatusAfterSuccess?: boolean;
    /**
     * 登陆返回的token-  用于手机不可用和谷歌不可用
     */
    token?: string;
    /**
     * 前端风控校验用，撮合接口里返回的transactionId字段
     */
    transactionId?: string;
    /**
     * 校验内容 <K,V><验证方式，验证码>， 安全问题验证SECURITY_QUESTION， 验证码的格式为：问题:答案，冒号分隔
     */
    validations?: {
        [key: string]: string;
    };
};

export type GetValidationsUsingPostData = {
    body?: SecurityValidationRequest;
    path?: never;
    query?: never;
    url: '/v1/security/validation/combine';
};

export type GetValidationsUsingPostResponses = {
    /**
     * OK
     */
    200: GenericResult_RatingPriorityResponse_;
};

export type GetValidationsUsingPostResponse = GetValidationsUsingPostResponses[keyof GetValidationsUsingPostResponses];

export type GetRiskUserSecurityInfoUsingGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/security/validation/inner/user-info';
};

export type GetRiskUserSecurityInfoUsingGetResponses = {
    /**
     * OK
     */
    200: GenericResult_RiskUserSecurityInfoResponse_;
};

export type GetRiskUserSecurityInfoUsingGetResponse = GetRiskUserSecurityInfoUsingGetResponses[keyof GetRiskUserSecurityInfoUsingGetResponses];

export type RiskValidationVerifyUsingPostData = {
    body?: Common_26657395643956435777307212144225968_;
    path?: never;
    query?: never;
    url: '/v1/security/validation/risk/verify';
};

export type RiskValidationVerifyUsingPostResponses = {
    /**
     * OK
     */
    200: GenericResult_verificationTypeThatFailsToVerify_;
};

export type RiskValidationVerifyUsingPostResponse = RiskValidationVerifyUsingPostResponses[keyof RiskValidationVerifyUsingPostResponses];

export type SendValidationCodeUsingPostData = {
    body?: never;
    path?: never;
    query: {
        /**
         * 接收的手机号或邮件地址.sendChannel为SMS或EMAIL则必须， 如果sendChannel为MY_SMS或MY_EMAIL则不传
         */
        address?: string;
        /**
         * 业务操作类型; RV_LOGIN:登陆,
         * RV_UPDATE_PHONE:修改手机号,
         *
         */
        bizType: 'RV_ALPHA' | 'RV_CARD_PAYOUT' | 'RV_CLAIM_WITHDRAW' | 'RV_KA_BILL' | 'RV_LOGIN' | 'RV_LOGIN_PWD_SET' | 'RV_OAUTH_GRANT' | 'RV_SET_SAFE_WORD' | 'RV_UPDATE_EMAIL' | 'RV_UPDATE_PHONE' | 'RV_WITHDRAWAL' | 'RV_WITHDRAWAL_FAV';
        /**
         * 额外的参数，key-value格式,多个用逗号,分隔。如foo=bar,foo1=bar1
         */
        ext?: Array<string>;
        /**
         * 验证码发送通道,支持SMS,VOICE(语音-指定语音验证码验证),EMAIL,MY_SMS,；,MY_EMAIL. MY_*为验证自己的号码；
         */
        sendChannel: 'AI' | 'DFP' | 'EMA' | 'EMV' | 'FID' | 'GAV' | 'HIT_DATA_BASE' | 'ID6' | 'MAIL_WORD' | 'MY_EMV' | 'MY_SMS' | 'MY_VOICE' | 'NAR' | 'PASSWORD' | 'PK' | 'PM6' | 'QV1' | 'SI' | 'SMS' | 'TP' | 'VOICE';
        /**
         * 登陆返回的token-  用于手机不可用和谷歌不可用
         */
        token?: string;
        /**
         * 撮合接口里返回的transactionId字段，前端风控组件内的发送验证码需要该字段，组件外的不用
         */
        transactionId?: string;
    };
    url: '/v1/security/validation/send-validation-code';
};

export type SendValidationCodeUsingPostResponses = {
    /**
     * OK
     */
    200: GenericResult_sendVerificationCodeToReturnData_;
};

export type SendValidationCodeUsingPostResponse = SendValidationCodeUsingPostResponses[keyof SendValidationCodeUsingPostResponses];

export type ClientOptions = { baseURL: string; };