/**
      * This file is auto-generated by @kucoin/api-generator
      * Owner: sean.shi@kupotech.com
      */

export type GenericResult_string_ = {
    code?: string;
    data?: string;
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type GetDefaultInvitationCodeByBrokerNameUsingGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * brokerName
         */
        brokerName: string;
    };
    url: '/invitation-code/getDefaultByBrokerName';
};

export type GetDefaultInvitationCodeByBrokerNameUsingGetResponses = {
    /**
     * OK
     */
    200: GenericResult_string_;
};

export type GetDefaultInvitationCodeByBrokerNameUsingGetResponse = GetDefaultInvitationCodeByBrokerNameUsingGetResponses[keyof GetDefaultInvitationCodeByBrokerNameUsingGetResponses];

export type ClientOptions = { baseURL: string; };
