export const AU_KYC_RESTRICT_LEVEL_TYPE = {
  /** 此种无法进行交易 */
  AU_FINANCE_COMMON: 'AU_FINANCE_COMMON',
  /**  此种可以进行2x杠杆交易 */
  AU_FINANCE_RETAIL_LEVEL2: 'AU_FINANCE_RETAIL_LEVEL2',
  /**  此种可进行30x杠杆交易 */
  AU_FINANCE_WHOLESALE: 'AU_FINANCE_WHOLESALE',
};

export const AU_KYC_RESTRICT_LEVEL_BUSINESS_MAP = {
  /** 此种无法进行交易 */
  [AU_KYC_RESTRICT_LEVEL_TYPE.AU_FINANCE_COMMON]: 1,
  /**  此种可以进行2x杠杆交易 */
  [AU_KYC_RESTRICT_LEVEL_TYPE.AU_FINANCE_RETAIL_LEVEL2]: 2,
  /**  此种可进行30x杠杆交易 */
  [AU_KYC_RESTRICT_LEVEL_TYPE.AU_FINANCE_WHOLESALE]: 3,
};

/** 跟单杠杠 KYC 等级 限制 （AU 站） */
export const CopyMaxLeverageByKycLevel = {
  [AU_KYC_RESTRICT_LEVEL_BUSINESS_MAP.AU_FINANCE_COMMON]: 0,
  [AU_KYC_RESTRICT_LEVEL_BUSINESS_MAP.AU_FINANCE_RETAIL_LEVEL2]: 2,
  [AU_KYC_RESTRICT_LEVEL_BUSINESS_MAP.AU_FINANCE_WHOLESALE]: 30,
};
