/**
      * This file is auto-generated by @kucoin/api-generator
      * Owner: sean.shi@kupotech.com
      */

export type GenericResult_List_List_string___ = {
    code?: string;
    data?: Array<Array<string>>;
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type GetWebConfigListByTypeUsingGetData = {
    body?: never;
    headers?: {
        /**
         * X-KC-CDN-SITE-TYPE
         */
        'X-KC-CDN-SITE-TYPE'?: string;
    };
    path?: never;
    query?: {
        /**
         * type
         */
        type?: 'LANGUAGE';
    };
    url: '/web/international/config-list';
};

export type GetWebConfigListByTypeUsingGetResponses = {
    /**
     * OK
     */
    200: GenericResult_List_List_string___;
};

export type GetWebConfigListByTypeUsingGetResponse = GetWebConfigListByTypeUsingGetResponses[keyof GetWebConfigListByTypeUsingGetResponses];

export type ClientOptions = { baseURL: string; };
