/**
 * Owner: willen@kupotech.com
 */
/* eslint-disable linebreak-style,object-curly-spacing, max-len */
import _ from 'lodash';

export const regionOptions = [
  { code: 'AF', en: 'Afghanistan', cn: '阿富汗', mobileCode: '93', enable: true },
  { code: 'AX', en: 'Aland Island', cn: '奥兰群岛', mobileCode: '35818', enable: true },
  { code: 'AL', en: 'Albania', cn: '阿尔巴尼亚', mobileCode: '355', enable: true },
  { code: 'DZ', en: 'Algeria', cn: '阿尔及利亚', mobileCode: '213', enable: true },
  { code: 'AS', en: 'American Samoa', cn: '美属萨摩亚', mobileCode: '1684', enable: false },
  { code: 'AD', en: 'Andorra', cn: '安道尔', mobileCode: '376', enable: true },
  { code: 'AO', en: 'Angola', cn: '安哥拉', mobileCode: '244', enable: true },
  { code: 'AI', en: 'Anguilla', cn: '安圭拉', mobileCode: '1264', enable: true },
  { code: 'AQ', en: 'Antarctica', cn: '南极洲', mobileCode: '672', enable: true },
  { code: 'AG', en: 'Antigua & Barbuda', cn: '安提瓜和巴布达', mobileCode: '1268', enable: true },
  { code: 'AR', en: 'Argentina', cn: '阿根廷', mobileCode: '54', enable: true },
  { code: 'AM', en: 'Armenia', cn: '亚美尼亚', mobileCode: '374', enable: true },
  { code: 'AW', en: 'Aruba', cn: '阿鲁巴', mobileCode: '297', enable: true },
  { code: 'AU', en: 'Australia', cn: '澳大利亚', mobileCode: '61', enable: true },
  { code: 'AT', en: 'Austria', cn: '奥地利', mobileCode: '43', enable: true },
  { code: 'AZ', en: 'Azerbaijan', cn: '阿塞拜疆', mobileCode: '994', enable: true },
  { code: 'BH', en: 'Bahrain', cn: '巴林', mobileCode: '973', enable: true },
  { code: 'BD', en: 'Bangladesh', cn: '孟加拉', mobileCode: '880', enable: true },
  { code: 'BB', en: 'Barbados', cn: '巴巴多斯', mobileCode: '1246', enable: true },
  { code: 'BY', en: 'Belarus', cn: '白俄罗斯', mobileCode: '375', enable: true },
  { code: 'BE', en: 'Belgium', cn: '比利时', mobileCode: '32', enable: true },
  { code: 'BZ', en: 'Belize', cn: '伯利兹', mobileCode: '501', enable: true },
  { code: 'BJ', en: 'Benin', cn: '贝宁', mobileCode: '229', enable: true },
  { code: 'BM', en: 'Bermuda', cn: '百慕大', mobileCode: '1441', enable: true },
  { code: 'BT', en: 'Bhutan', cn: '不丹', mobileCode: '975', enable: true },
  { code: 'BO', en: 'Bolivia', cn: '玻利维亚', mobileCode: '591', enable: true },
  { code: 'BA', en: 'Bosnia & Herzegovina', cn: '波黑', mobileCode: '387', enable: false },
  { code: 'BW', en: 'Botswana', cn: '博茨瓦纳', mobileCode: '267', enable: false },
  { code: 'BV', en: 'Bouvet Island', cn: '布韦岛', mobileCode: '00', enable: true },
  { code: 'BR', en: 'Brazil', cn: '巴西', mobileCode: '55', enable: true },
  {
    code: 'IO',
    en: 'British Indian Ocean Territory',
    cn: '英属印度洋领地',
    mobileCode: '246',
    enable: true,
  },
  {
    code: 'VG',
    en: 'British Virgin Islands',
    cn: '英属维尔京群岛',
    mobileCode: '1284',
    enable: true,
  },
  { code: 'BN', en: 'Brunei', cn: '文莱', mobileCode: '673', enable: true },
  { code: 'BG', en: 'Bulgaria', cn: '保加利亚', mobileCode: '359', enable: true },
  { code: 'BF', en: 'Burkina', cn: '布基纳法索', mobileCode: '226', enable: true },
  { code: 'BI', en: 'Burundi', cn: '布隆迪', mobileCode: '257', enable: true },
  { code: 'KH', en: 'Cambodia', cn: '柬埔寨', mobileCode: '855', enable: false },
  { code: 'CM', en: 'Cameroon', cn: '喀麦隆', mobileCode: '237', enable: true },
  { code: 'CA', en: 'Canada', cn: '加拿大', mobileCode: '1', enable: true },
  { code: 'CV', en: 'Cape Verde', cn: '佛得角', mobileCode: '238', enable: true },
  { code: 'BQ', en: 'Caribbean Netherlands', cn: '荷兰加勒比区', mobileCode: '5997', enable: true },
  { code: 'KY', en: 'Cayman Islands', cn: '开曼群岛', mobileCode: '1345', enable: true },
  { code: 'CF', en: 'Central African Republic', cn: '中非', mobileCode: '236', enable: false },
  { code: 'TD', en: 'Chad', cn: '乍得', mobileCode: '235', enable: true },
  { code: 'CL', en: 'Chile', cn: '智利', mobileCode: '56', enable: true },
  { code: 'CN', en: 'China', cn: '中国', mobileCode: '86', enable: true },
  { code: 'CX', en: 'Christmas Island', cn: '圣诞岛', mobileCode: '61', enable: true },
  { code: 'CC', en: 'Cocos (Keeling) Islands', cn: '科科斯群岛', mobileCode: '61', enable: true },
  { code: 'CO', en: 'Colombia', cn: '哥伦比亚', mobileCode: '57', enable: true },
  { code: 'CK', en: 'Cook Islands', cn: '库克群岛', mobileCode: '682', enable: true },
  { code: 'CR', en: 'Costa Rica', cn: '哥斯达黎加', mobileCode: '506', enable: true },
  { code: 'CI', en: 'Cote dIvoire', cn: '科特迪瓦', mobileCode: '225', enable: true },
  { code: 'HR', en: 'Croatia', cn: '克罗地亚', mobileCode: '385', enable: true },
  { code: 'CU', en: 'Cuba', cn: '古巴', mobileCode: '53', enable: false },
  { code: 'CW', en: 'Curacao', cn: '库拉索', mobileCode: '5999', enable: true },
  { code: 'CY', en: 'Cyprus', cn: '塞浦路斯', mobileCode: '357', enable: true },
  { code: 'CZ', en: 'Czech Republic', cn: '捷克', mobileCode: '420', enable: true },
  {
    code: 'CD',
    en: 'Democratic Republic of the Congo',
    cn: '刚果（金）',
    mobileCode: '243',
    enable: false,
  },
  { code: 'DK', en: 'Denmark', cn: '丹麦', mobileCode: '45', enable: true },
  { code: 'DJ', en: 'Djibouti', cn: '吉布提', mobileCode: '253', enable: true },
  { code: 'DM', en: 'Dominica', cn: '多米尼克', mobileCode: '1767', enable: true },
  { code: 'DO', en: 'Dominican Republic', cn: '多米尼加', mobileCode: '1809', enable: true },
  { code: 'EC', en: 'Ecuador', cn: '厄瓜多尔', mobileCode: '593', enable: true },
  { code: 'EG', en: 'Egypt', cn: '埃及', mobileCode: '20', enable: true },
  { code: 'SV', en: 'El Salvador', cn: '萨尔瓦多', mobileCode: '503', enable: true },
  { code: 'GQ', en: 'Equatorial Guinea', cn: '赤道几内亚', mobileCode: '240', enable: true },
  { code: 'ER', en: 'Eritrea', cn: '厄立特里亚', mobileCode: '291', enable: false },
  { code: 'EE', en: 'Estonia', cn: '爱沙尼亚', mobileCode: '372', enable: true },
  { code: 'ET', en: 'Ethiopia', cn: '埃塞俄比亚', mobileCode: '251', enable: true },
  {
    code: 'FK',
    en: 'Falkland Islands',
    cn: '马尔维纳斯群岛（福克兰）',
    mobileCode: '500',
    enable: true,
  },
  { code: 'FO', en: 'Faroe Islands', cn: '法罗群岛', mobileCode: '298', enable: true },
  {
    code: 'FM',
    en: 'Federated States of Micronesia',
    cn: '密克罗尼西亚联邦',
    mobileCode: '691',
    enable: true,
  },
  { code: 'FJ', en: 'Fiji', cn: '斐济群岛', mobileCode: '679', enable: true },
  { code: 'FI', en: 'Finland', cn: '芬兰', mobileCode: '358', enable: true },
  { code: 'FR', en: 'France', cn: '法国', mobileCode: '33', enable: true },
  { code: 'GF', en: 'French Guiana', cn: '法属圭亚那', mobileCode: '594', enable: true },
  { code: 'PF', en: 'French polynesia', cn: '法属波利尼西亚', mobileCode: '689', enable: true },
  {
    code: 'TF',
    en: 'French Southern Territories',
    cn: '法属南部领地',
    mobileCode: '00',
    enable: true,
  },
  { code: 'GA', en: 'Gabon', cn: '加蓬', mobileCode: '241', enable: true },
  { code: 'GM', en: 'Gambia', cn: '冈比亚', mobileCode: '220', enable: true },
  { code: 'GE', en: 'Georgia', cn: '格鲁吉亚', mobileCode: '995', enable: true },
  { code: 'DE', en: 'Germany', cn: '德国', mobileCode: '49', enable: true },
  { code: 'GH', en: 'Ghana', cn: '加纳', mobileCode: '233', enable: false },
  { code: 'GI', en: 'Gibraltar', cn: '直布罗陀', mobileCode: '350', enable: true },
  {
    code: 'GB',
    en: 'Great Britain (United Kingdom; England)',
    cn: '英国',
    mobileCode: '44',
    enable: true,
  },
  { code: 'GR', en: 'Greece', cn: '希腊', mobileCode: '30', enable: true },
  { code: 'GL', en: 'Greenland', cn: '格陵兰', mobileCode: '299', enable: true },
  { code: 'GD', en: 'Grenada', cn: '格林纳达', mobileCode: '1473', enable: true },
  { code: 'GP', en: 'Guadeloupe', cn: '瓜德罗普', mobileCode: '590', enable: true },
  { code: 'GU', en: 'Guam', cn: '关岛', mobileCode: '1671', enable: false },
  { code: 'GT', en: 'Guatemala', cn: '危地马拉', mobileCode: '502', enable: true },
  { code: 'GG', en: 'Guernsey', cn: '根西岛', mobileCode: '44', enable: true },
  { code: 'GN', en: 'Guinea', cn: '几内亚', mobileCode: '224', enable: true },
  { code: 'GW', en: 'Guinea-Bissau', cn: '几内亚比绍', mobileCode: '245', enable: true },
  { code: 'GY', en: 'Guyana', cn: '圭亚那', mobileCode: '592', enable: true },
  { code: 'HT', en: 'Haiti', cn: '海地', mobileCode: '509', enable: true },
  {
    code: 'HM',
    en: 'Heard Island and McDonald Islands',
    cn: '赫德岛和麦克唐纳群岛',
    mobileCode: '00',
    enable: true,
  },
  { code: 'HN', en: 'Honduras', cn: '洪都拉斯', mobileCode: '504', enable: true },
  { code: 'HK', en: 'Hong Kong', cn: '香港', mobileCode: '852', enable: true },
  { code: 'HU', en: 'Hungary', cn: '匈牙利', mobileCode: '36', enable: true },
  { code: 'IS', en: 'Iceland', cn: '冰岛', mobileCode: '354', enable: false },
  { code: 'IN', en: 'India', cn: '印度', mobileCode: '91', enable: true },
  { code: 'ID', en: 'Bahasa Indonesia', cn: '印尼', mobileCode: '62', enable: true },
  { code: 'IR', en: 'Iran', cn: '伊朗', mobileCode: '98', enable: false },
  { code: 'IQ', en: 'Iraq', cn: '伊拉克', mobileCode: '964', enable: false },
  { code: 'IE', en: 'Ireland', cn: '爱尔兰', mobileCode: '353', enable: true },
  { code: 'IM', en: 'Isle of Man', cn: '马恩岛', mobileCode: '44', enable: true },
  { code: 'IL', en: 'Israel', cn: '以色列', mobileCode: '972', enable: true },
  { code: 'IT', en: 'Italy', cn: '意大利', mobileCode: '39', enable: true },
  { code: 'JM', en: 'Jamaica', cn: '牙买加', mobileCode: '1876', enable: true },
  { code: 'JP', en: 'Japan', cn: '日本', mobileCode: '81', enable: false },
  { code: 'JE', en: 'Jersey', cn: '泽西岛', mobileCode: '44', enable: true },
  { code: 'JO', en: 'Jordan', cn: '约旦', mobileCode: '962', enable: true },
  { code: 'XK', en: 'Kosovo', cn: '科索沃', mobileCode: '383', enable: true },
  { code: 'KZ', en: 'Kazakhstan', cn: '哈萨克斯坦', mobileCode: '7', enable: true },
  { code: 'KE', en: 'Kenya', cn: '肯尼亚', mobileCode: '254', enable: true },
  { code: 'KI', en: 'Kiribati', cn: '基里巴斯', mobileCode: '686', enable: true },
  { code: 'KW', en: 'Kuwait', cn: '科威特', mobileCode: '965', enable: true },
  { code: 'KG', en: 'Kyrgyzstan', cn: '吉尔吉斯斯坦', mobileCode: '996', enable: true },
  { code: 'LA', en: 'Laos', cn: '老挝', mobileCode: '856', enable: true },
  { code: 'LV', en: 'Latvia', cn: '拉脱维亚', mobileCode: '371', enable: true },
  { code: 'LB', en: 'Lebanon', cn: '黎巴嫩', mobileCode: '961', enable: false },
  { code: 'LS', en: 'Lesotho', cn: '莱索托', mobileCode: '266', enable: true },
  { code: 'LR', en: 'Liberia', cn: '利比里亚', mobileCode: '231', enable: true },
  { code: 'LY', en: 'Libya', cn: '利比亚', mobileCode: '218', enable: false },
  { code: 'LI', en: 'Liechtenstein', cn: '列支敦士登', mobileCode: '423', enable: true },
  { code: 'LT', en: 'Lithuania', cn: '立陶宛', mobileCode: '370', enable: true },
  { code: 'LU', en: 'Luxembourg', cn: '卢森堡', mobileCode: '352', enable: true },
  { code: 'MO', en: 'Macao', cn: '澳门', mobileCode: '853', enable: true },
  { code: 'MG', en: 'Madagascar', cn: '马达加斯加', mobileCode: '261', enable: true },
  { code: 'MW', en: 'Malawi', cn: '马拉维', mobileCode: '265', enable: true },
  { code: 'MY', en: 'Malaysia', cn: '马来西亚', mobileCode: '60', enable: true },
  { code: 'MV', en: 'Maldives', cn: '马尔代夫', mobileCode: '960', enable: true },
  { code: 'ML', en: 'Mali', cn: '马里', mobileCode: '223', enable: true },
  { code: 'MT', en: 'Malta', cn: '马耳他', mobileCode: '356', enable: true },
  { code: 'MH', en: 'Marshall islands', cn: '马绍尔群岛', mobileCode: '692', enable: true },
  { code: 'MQ', en: 'Martinique', cn: '马提尼克', mobileCode: '596', enable: true },
  { code: 'MR', en: 'Mauritania', cn: '毛里塔尼亚', mobileCode: '222', enable: true },
  { code: 'MU', en: 'Mauritius', cn: '毛里求斯', mobileCode: '230', enable: true },
  { code: 'YT', en: 'Mayotte', cn: '马约特', mobileCode: '262', enable: true },
  { code: 'MX', en: 'Mexico', cn: '墨西哥', mobileCode: '52', enable: true },
  { code: 'MD', en: 'Moldova', cn: '摩尔多瓦', mobileCode: '373', enable: true },
  { code: 'MC', en: 'Monaco', cn: '摩纳哥', mobileCode: '377', enable: true },
  { code: 'MN', en: 'Mongolia', cn: '蒙古国', mobileCode: '976', enable: false },
  { code: 'ME', en: 'Montenegro', cn: '黑山', mobileCode: '382', enable: true },
  { code: 'MS', en: 'Montserrat', cn: '蒙塞拉特岛', mobileCode: '1664', enable: true },
  { code: 'MA', en: 'Morocco', cn: '摩洛哥', mobileCode: '212', enable: true },
  { code: 'MZ', en: 'Mozambique', cn: '莫桑比克', mobileCode: '258', enable: true },
  { code: 'MM', en: 'Myanmar (Burma)', cn: '缅甸', mobileCode: '95', enable: false },
  { code: 'NA', en: 'Namibia', cn: '纳米比亚', mobileCode: '264', enable: true },
  { code: 'NR', en: 'Nauru', cn: '瑙鲁', mobileCode: '674', enable: true },
  { code: 'NP', en: 'Nepal', cn: '尼泊尔', mobileCode: '977', enable: true },
  { code: 'NL', en: 'Netherlands', cn: '荷兰', mobileCode: '31', enable: true },
  { code: 'NC', en: 'New Caledonia', cn: '新喀里多尼亚', mobileCode: '687', enable: true },
  { code: 'NZ', en: 'New Zealand', cn: '新西兰', mobileCode: '64', enable: true },
  { code: 'NI', en: 'Nicaragua', cn: '尼加拉瓜', mobileCode: '505', enable: true },
  { code: 'NE', en: 'Niger', cn: '尼日尔', mobileCode: '227', enable: true },
  { code: 'NG', en: 'Nigeria', cn: '尼日利亚', mobileCode: '234', enable: true },
  { code: 'NU', en: 'Niue', cn: '纽埃', mobileCode: '683', enable: true },
  { code: 'NF', en: 'Norfolk Island', cn: '诺福克岛', mobileCode: '672', enable: true },
  { code: 'KP', en: 'North Korea', cn: '朝鲜', mobileCode: '850', enable: false },
  {
    code: 'MP',
    en: 'Northern Mariana Islands',
    cn: '北马里亚纳群岛',
    mobileCode: '1670',
    enable: false,
  },
  { code: 'NO', en: 'Norway', cn: '挪威', mobileCode: '47', enable: true },
  { code: 'OM', en: 'Oman', cn: '阿曼', mobileCode: '968', enable: true },
  { code: 'PK', en: 'Pakistan', cn: '巴基斯坦', mobileCode: '92', enable: false },
  { code: 'PW', en: 'Palau', cn: '帕劳', mobileCode: '680', enable: true },
  { code: 'PS', en: 'Palestinian territories', cn: '巴勒斯坦', mobileCode: '970', enable: true },
  { code: 'PA', en: 'Panama', cn: '巴拿马', mobileCode: '507', enable: true },
  { code: 'PG', en: 'Papua New Guinea', cn: '巴布亚新几内亚', mobileCode: '675', enable: true },
  { code: 'PY', en: 'Paraguay', cn: '巴拉圭', mobileCode: '595', enable: true },
  { code: 'PE', en: 'Peru', cn: '秘鲁', mobileCode: '51', enable: true },
  { code: 'PN', en: 'Pitcairn Islands', cn: '皮特凯恩群岛', mobileCode: '64', enable: true },
  { code: 'PL', en: 'Poland', cn: '波兰', mobileCode: '48', enable: true },
  { code: 'PT', en: 'Portugal', cn: '葡萄牙', mobileCode: '351', enable: true },
  { code: 'PR', en: 'Puerto Rico', cn: '波多黎各', mobileCode: '1787', enable: false },
  { code: 'QA', en: 'Qatar', cn: '卡塔尔', mobileCode: '974', enable: true },
  {
    code: 'MK',
    en: 'Republic of Macedonia (FYROM)',
    cn: '马其顿',
    mobileCode: '389',
    enable: true,
  },
  { code: 'CG', en: 'Republic of the Congo', cn: '刚果（布）', mobileCode: '242', enable: true },
  { code: 'RE', en: 'Réunion', cn: '留尼汪', mobileCode: '262', enable: true },
  { code: 'RO', en: 'Romania', cn: '罗马尼亚', mobileCode: '40', enable: true },
  { code: 'RU', en: 'Russian Federation', cn: '俄罗斯', mobileCode: '7', enable: true },
  { code: 'RW', en: 'Rwanda', cn: '卢旺达', mobileCode: '250', enable: true },
  { code: 'BL', en: 'Saint Barthélemy', cn: '圣巴泰勒米岛', mobileCode: '590', enable: true },
  { code: 'MF', en: 'Saint Martin (France)', cn: '法属圣马丁', mobileCode: '590', enable: true },
  {
    code: 'PM',
    en: 'Saint-Pierre and Miquelon',
    cn: '圣皮埃尔和密克隆',
    mobileCode: '508',
    enable: true,
  },
  { code: 'WS', en: 'Samoa', cn: '萨摩亚', mobileCode: '685', enable: true },
  { code: 'SM', en: 'San Marino', cn: '圣马力诺', mobileCode: '378', enable: true },
  {
    code: 'ST',
    en: 'Sao Tome & Principe',
    cn: '圣多美和普林西比',
    mobileCode: '239',
    enable: true,
  },
  { code: 'SA', en: 'Saudi Arabia', cn: '沙特阿拉伯', mobileCode: '966', enable: true },
  { code: 'SN', en: 'Senegal', cn: '塞内加尔', mobileCode: '221', enable: true },
  { code: 'RS', en: 'Serbia', cn: '塞尔维亚', mobileCode: '381', enable: true },
  { code: 'SC', en: 'Seychelles', cn: '塞舌尔', mobileCode: '248', enable: true },
  { code: 'SL', en: 'Sierra Leone', cn: '塞拉利昂', mobileCode: '232', enable: true },
  { code: 'SG', en: 'Singapore', cn: '新加坡', mobileCode: '65', enable: true },
  { code: 'SX', en: 'Sint Maarten', cn: '荷属圣马丁', mobileCode: '1721', enable: true },
  { code: 'SK', en: 'Slovakia', cn: '斯洛伐克', mobileCode: '421', enable: true },
  { code: 'SI', en: 'Slovenia', cn: '斯洛文尼亚', mobileCode: '386', enable: true },
  { code: 'SB', en: 'Solomon Islands', cn: '所罗门群岛', mobileCode: '677', enable: true },
  { code: 'SO', en: 'Somalia', cn: '索马里', mobileCode: '252', enable: false },
  { code: 'ZA', en: 'South Africa', cn: '南非', mobileCode: '27', enable: true },
  {
    code: 'GS',
    en: 'South Georgia and the South Sandwich Islands',
    cn: '南乔治亚岛和南桑威奇群岛',
    mobileCode: '500',
    enable: true,
  },
  { code: 'KR', en: 'South Korea', cn: '韩国', mobileCode: '82', enable: true },
  { code: 'SS', en: 'South Sudan', cn: '南苏丹', mobileCode: '211', enable: false },
  { code: 'ES', en: 'Spain', cn: '西班牙', mobileCode: '34', enable: true },
  { code: 'LK', en: 'Sri Lanka', cn: '斯里兰卡', mobileCode: '94', enable: true },
  { code: 'SH', en: 'St. Helena & Dependencies', cn: '圣赫勒拿', mobileCode: '290', enable: true },
  { code: 'KN', en: 'St. Kitts & Nevis', cn: '圣基茨和尼维斯', mobileCode: '1869', enable: true },
  { code: 'LC', en: 'St. Lucia', cn: '圣卢西亚', mobileCode: '1758', enable: true },
  {
    code: 'VC',
    en: 'St. Vincent & the Grenadines',
    cn: '圣文森特和格林纳丁斯',
    mobileCode: '1784',
    enable: true,
  },
  { code: 'SD', en: 'Sudan', cn: '苏丹', mobileCode: '249', enable: false },
  { code: 'SR', en: 'Suriname', cn: '苏里南', mobileCode: '597', enable: true },
  {
    code: 'SJ',
    en: 'Svalbard and Jan Mayen',
    cn: '斯瓦尔巴群岛和扬马延岛',
    mobileCode: '47',
    enable: true,
  },
  { code: 'SZ', en: 'Swaziland', cn: '斯威士兰', mobileCode: '268', enable: true },
  { code: 'SE', en: 'Sweden', cn: '瑞典', mobileCode: '46', enable: true },
  { code: 'CH', en: 'Switzerland', cn: '瑞士', mobileCode: '41', enable: true },
  { code: 'SY', en: 'Syria', cn: '叙利亚', mobileCode: '963', enable: false },
  { code: 'TW', en: 'Taiwan', cn: '台湾', mobileCode: '886', enable: true },
  { code: 'TJ', en: 'Tajikistan', cn: '塔吉克斯坦', mobileCode: '992', enable: true },
  { code: 'TZ', en: 'Tanzania', cn: '坦桑尼亚', mobileCode: '255', enable: true },
  { code: 'TH', en: 'Thailand', cn: '泰国', mobileCode: '66', enable: true },
  { code: 'BS', en: 'The Bahamas', cn: '巴哈马', mobileCode: '1242', enable: false },
  { code: 'KM', en: 'The Comoros', cn: '科摩罗', mobileCode: '269', enable: true },
  { code: 'PH', en: 'The Philippines', cn: '菲律宾', mobileCode: '63', enable: true },
  { code: 'TL', en: 'Timor-Leste (East Timor)', cn: '东帝汶', mobileCode: '670', enable: true },
  { code: 'TG', en: 'Togo', cn: '多哥', mobileCode: '228', enable: true },
  { code: 'TK', en: 'Tokelau', cn: '托克劳', mobileCode: '690', enable: true },
  { code: 'TO', en: 'Tonga', cn: '汤加', mobileCode: '676', enable: true },
  {
    code: 'TT',
    en: 'Trinidad & Tobago',
    cn: '特立尼达和多巴哥',
    mobileCode: '1868',
    enable: false,
  },
  { code: 'TN', en: 'Tunisia', cn: '突尼斯', mobileCode: '216', enable: true },
  { code: 'TR', en: 'Turkey', cn: '土耳其', mobileCode: '90', enable: true },
  { code: 'TM', en: 'Turkmenistan', cn: '土库曼斯坦', mobileCode: '993', enable: true },
  {
    code: 'TC',
    en: 'Turks & Caicos Islands',
    cn: '特克斯和凯科斯群岛',
    mobileCode: '1649',
    enable: true,
  },
  { code: 'TV', en: 'Tuvalu', cn: '图瓦卢', mobileCode: '688', enable: true },
  { code: 'UG', en: 'Uganda', cn: '乌干达', mobileCode: '256', enable: true },
  { code: 'UA', en: 'Ukraine', cn: '乌克兰', mobileCode: '380', enable: true },
  { code: 'AE', en: 'United Arab Emirates', cn: '阿联酋', mobileCode: '971', enable: true },
  {
    code: 'UM',
    en: 'United States Minor Outlying Islands',
    cn: '美国本土外小岛屿',
    mobileCode: '1',
    enable: false,
  },
  { code: 'US', en: 'United States of America (USA)', cn: '美国', mobileCode: '1', enable: false },
  {
    code: 'VI',
    en: 'United States Virgin Islands',
    cn: '美属维尔京群岛',
    mobileCode: '1340',
    enable: false,
  },
  { code: 'UY', en: 'Uruguay', cn: '乌拉圭', mobileCode: '598', enable: true },
  { code: 'UZ', en: 'Uzbekistan', cn: '乌兹别克斯坦', mobileCode: '998', enable: true },
  { code: 'VU', en: 'Vanuatu', cn: '瓦努阿图', mobileCode: '678', enable: true },
  { code: 'VA', en: 'Vatican City (The Holy See)', cn: '梵蒂冈', mobileCode: '379', enable: true },
  { code: 'VE', en: 'Venezuela', cn: '委内瑞拉', mobileCode: '58', enable: true },
  { code: 'VN', en: 'Vietnam', cn: '越南', mobileCode: '84', enable: true },
  { code: 'WF', en: 'Wallis and Futuna', cn: '瓦利斯和富图纳', mobileCode: '681', enable: true },
  { code: 'EH', en: 'Western Sahara', cn: '西撒哈拉', mobileCode: '212', enable: true },
  { code: 'YE', en: 'Yemen', cn: '也门', mobileCode: '967', enable: false },
  { code: 'ZM', en: 'Zambia', cn: '赞比亚', mobileCode: '260', enable: true },
  { code: 'ZW', en: 'Zimbabwe', cn: '津巴布韦', mobileCode: '263', enable: false },
];

export const regionOptionsWithOthers = [
  ...regionOptions,
  { code: 'OT', en: 'Others', cn: '其他', mobileCode: '0', enable: true },
];

export const findRegionNameByCode = (code, isCN, findWithOthers) => {
  if (!code) return null;
  let name = null;
  _.each(findWithOthers ? regionOptionsWithOthers : regionOptions, (item) => {
    if (code === item.code) {
      name = isCN ? item.cn : item.en;
      return false;
    }
  });
  return name;
};

export const findRegionCodeByName = (n, isCN) => {
  let code = null;
  let name;
  _.each(regionOptions, (item) => {
    name = isCN ? item.cn : item.en;
    if (name === n) {
      code = item.code;
      return false;
    }
  });
  return code;
};

export const FORBIDDEN_COUNTRIES_FOR_USE = [
  {
    code: 'CN',
    mobileCode: '86',
    aliasName: '其他', // 被屏蔽的国家，界面显示的别名
    aliasNameEN: 'Other',
  },
];

export const isForbiddenCountry = (mobileCode, field = 'mobileCode') => {
  return _.find(FORBIDDEN_COUNTRIES_FOR_USE, (forbiddenItem) => {
    return forbiddenItem[field] === mobileCode;
  });
};
