/**
      * This file is auto-generated by @kucoin/api-generator
      * Owner: sean.shi@kupotech.com
      */
import Client, { type SwaggerOptions as ClientOptions, type SwaggerTDataShape as TDataShape } from 'gbiz-next/commonRequest';
import type { PositionUsingGet3Data, PositionUsingGet3Response } from './types.gen';
import { client as _apiClient } from '../client.gen';
export type Options<TData extends TDataShape = TDataShape> = ClientOptions<TData> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
    disabledLang?: boolean;
};
/**
 * web端资源位请求
 */
export const positionUsingGet3 = (params: PositionUsingGet3Data['query'], options?: Options<PositionUsingGet3Data>) => {
  return (options?.client ?? _apiClient).pull<PositionUsingGet3Response, PositionUsingGet3Data['query']>('/_api/resource-position/position', params, {
    ...(options || {})
  });
};
