export interface WebPositionResponse {
    srcTextMap: {
        content: string;
        btnTxt: string;
    }
    webUrl: string;
    appUrl: string;
};

/**
      * This file is auto-generated by @kucoin/api-generator
      * Owner: sean.shi@kupotech.com
      */

export type GenericResult_map_stringList_webPositionResponse___ = {
    code?: string;
    data?: {
        [key: string]: Array<WebPositionResponse>;
    };
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type PositionUsingGet3Data = {
    body?: never;
    headers?: {
        /**
         * X-USER-ID
         */
        'X-USER-ID'?: string;
        /**
         * LANG
         */
        LANG?: string;
        /**
         * X-KC-CDN-SITE-TYPE
         */
        'X-KC-CDN-SITE-TYPE'?: string;
        /**
         * X-LOCATION-CODE
         */
        'X-LOCATION-CODE'?: string;
    };
    path?: never;
    query: {
        /**
         * codes
         */
        codes: string;
    };
    url: '/position';
};

export type PositionUsingGet3Responses = {
    /**
     * OK
     */
    200: GenericResult_map_stringList_webPositionResponse___;
};

export type PositionUsingGet3Response = PositionUsingGet3Responses[keyof PositionUsingGet3Responses];

export type ClientOptions = { baseURL: string; };
