window.__KC_LANGUAGES__ = {
  __ALL__: [
    "de_DE",
    "en_US",
    "es_ES",
    "fr_FR",
    "ko_KR",
    "nl_NL",
    "pt_PT",
    "ru_RU",
    "tr_TR",
    "vi_VN",
    "zh_HK",
    "it_IT",
    "id_ID",
    "ms_MY",
    "hi_IN",
    "th_TH",
    "ja_JP",
    "bn_BD",
    "pl_PL",
    "fil_PH",
    "ar_AE",
    "ur_PK",
    "uk_UA",
  ],
};
window.__KC_LANGUAGES_BASE_MAP__ = {
  baseToLang: {
    "en-eu": "en_US",
    "de-eu": "de_DE",
    "es-eu": "es_ES",
    "fr-eu": "fr_FR",
    "ko-eu": "ko_KR",
    "nl-eu": "nl_NL",
    "pt-eu": "pt_PT",
    "ru-eu": "ru_RU",
    "tr-eu": "tr_TR",
    "vi-eu": "vi_VN",
    "zh-hant-eu": "zh_HK",
    "it-eu": "it_IT",
    "id-eu": "id_ID",
    "ms-eu": "ms_MY",
    "hi-eu": "hi_IN",
    "th-eu": "th_TH",
    "ja-eu": "ja_JP",
    "bn-eu": "bn_BD",
    "pl-eu": "pl_PL",
    "fil-eu": "fil_PH",
    "ar-eu": "ar_AE",
    "ur-eu": "ur_PK",
    "uk-eu": "uk_UA",
  },
  langToBase: {
    en_US: "en-eu",
    de_DE: "de-eu",
    es_ES: "es-eu",
    fr_FR: "fr-eu",
    ko_KR: "ko-eu",
    nl_NL: "nl-eu",
    pt_PT: "pt-eu",
    ru_RU: "ru-eu",
    tr_TR: "tr-eu",
    vi_VN: "vi-eu",
    zh_HK: "zh-hant-eu",
    it_IT: "it-eu",
    id_ID: "id-eu",
    ms_MY: "ms-eu",
    hi_IN: "hi-eu",
    th_TH: "th-eu",
    ja_JP: "ja-eu",
    bn_BD: "bn-eu",
    pl_PL: "pl-eu",
    fil_PH: "fil-eu",
    ar_AE: "ar-eu",
    ur_PK: "ur-eu",
    uk_UA: "uk-eu",
  },
};
