
// this file is generate by genSiteConfig for rollup
// don't edit this file
window._SITE_CONFIG_ = {
  "siteType": "europe",
  "basicProperties": {
    "siteName": "欧洲站",
    "shareGlobalAccount": 1,
    "walletType": 2,
    "storageType": 2,
    "siteDomainType": 1,
    "siteDomain": "www.kucoin.com",
    "siteRegion": "eu",
    "brandType": 2,
    "logoType": 2
  },
  "extProperties": [],
  "functions": {
    "api_broker": true,
    "fast_trade": true,
    "spot_growth": true,
    "3rd_party": false,
    "convert": true,
    "seo": true,
    "trading_bot": false,
    "financial_system": true,
    "kyc": true,
    "home_page": true,
    "affiliate": true,
    "nd_broker": false,
    "spot": true,
    "option": false,
    "reconciliation_system": true,
    "etf": true,
    "payment": true,
    "kucard": true,
    "platform_growth": true,
    "tax_platform": true,
    "copy_trading": false,
    "loan": false,
    "data_center": true,
    "invite_rebate": true,
    "api": true,
    "message_center": true,
    "margin": true,
    "web3_wallet": true,
    "customer_service_system": true,
    "financing": true,
    "personal_center": true,
    "rebate_business": true,
    "p2p": false,
    "search": true,
    "fiat_deposit": true,
    "futures": true,
    "risk_control_system": true,
    "currency": true,
    "k_line": true,
    "kucoin_pay": false,
    "basic_bench": true,
    "express": true,
    "ucenter": true,
    "activity_bench": true,
    "kyb": true,
    "compliance_exhibition_platform": true
  },
  "bizConfigs": {
    "contract_liquidity": "ats",
    "shield_currency": "USDT",
    "spot_liquidity": "ats",
    "is_allowed_multilevel_rebate": "not_allow_multi",
    "quote_currency": "USDC",
    "rebate_range": "cross_site_rebate"
  }
};
