/**
      * This file is auto-generated by @kucoin/api-generator
      * Owner: sean.shi@kupotech.com
      */

export type GenericResult_map_string44Bigdecimal__ = {
    code?: string;
    data?: {
        [key: string]: string;
    };
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type GenericResult_map_stringString__ = {
    code?: string;
    data?: {
        [key: string]: string;
    };
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type RatesUsingGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 法币币种 如：USD,CNY
         */
        base?: string;
        /**
         * [optional] Enter a list of comma-separated currency codes to limit output currencies
         */
        targets?: string;
    };
    url: '/rates';
};

export type RatesUsingGetResponses = {
    /**
     * OK
     */
    200: GenericResult_map_stringString__;
};

export type RatesUsingGetResponse = RatesUsingGetResponses[keyof RatesUsingGetResponses];

export type GetPricesV2UsingGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 法定币种 如：USD,CNY,EUR
         */
        base?: string;
        /**
         * [optional] Enter a list of comma-separated currency codes to limit output currencies
         */
        targets?: string;
        /**
         * domainId
         */
        domainId?: string;
    };
    url: '/v2/prices';
};

export type GetPricesV2UsingGetResponses = {
    /**
     * OK
     */
    200: GenericResult_map_string44Bigdecimal__;
};

export type GetPricesV2UsingGetResponse = GetPricesV2UsingGetResponses[keyof GetPricesV2UsingGetResponses];

export type ClientOptions = { baseURL: string; };
