/**
 * Owner: willen@kupotech.com
 */
module.exports = {
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    // '^@@/(.*)$': '<rootDir>/src/.umi/$1',
    '^src/(.*)': '<rootDir>/src/$1',
    '^config/(.*)': '<rootDir>/src/config/$1',
    '^config': '<rootDir>/src/config/index.js',
    '^utils/(.*)': '<rootDir>/src/utils/$1',
    '^tools/(.*)': '<rootDir>/src/tools/$1',
    '^static/(.*)': '<rootDir>/cdnAssets/static/$1',
    '^routes/(.*)': '<rootDir>/src/routes/$1',
    '^components/(.*)': '<rootDir>/src/components/$1',
    '^helper': '<rootDir>/src/helper.js',
    '^common/(.*)': '<rootDir>/src/common/$1',
    '^services/(.*)': '<rootDir>/src/services/$1',
  },
  // testMatch: ['<rootDir>/src/test/utils/**.test.js',],
  // testMatch: [
  //   '<rootDir>/src/test/components/Loading.test.js',
  // ],
  verbose: true, // 是否输出 descripe 和 test/it 中的测试描述信息
  globals: {
    _USE_MOCK_: false,
    _VERSION_: '0.0.1',
    _DEV_: false,
    // IS_TEST_ENV: false,
    // NOT_PROD: false,
    // IS_SANDBOX: false,
    SENTRY_DEBUG: true,
    _APP_NAME_: 'landing-web',
    _XVERSION_: '0.0.1',
    _APP_: 'landing-web',
    LANDING_HOST: '/land',
    __webpack_public_path__: 'xxx/xxx',
    _WEB_RELATION_: {
      DOCS_HOST: 'https://docs.kucoin.com',
      TRADE_HOST: 'https://docs.kucoin.com',
    },
    __UMI_HTML_SUFFIX: false,
  },

  // setupFilesAfterEnv: ['@testing-library/jest-dom'], // 在每个测试文件执行之前调用一些默认执行代码的文件路径
  setupFilesAfterEnv: ['<rootDir>/setup-jest.js'],
  // testEnvironment: 'jsdom',
  setupFiles: ['./setupFile.js', 'jest-useragent-mock'],
  transformIgnorePatterns: [`<rootDir>/node_modules/(?!${['@kufox/mui', 'lodash-es', 'rc-picker'].join('|')})`],
  collectCoverageFrom: [
    // 这些页面组件活动已经过期，排除单测范围: https://expsg-my.sharepoint.com/:x:/g/personal/meeta_kupotech_com/EahY0zV4f5NAmQAxzmVTVpABp2ULK6yEUeCRN3Syz8huUw?e=ZXkXsg&wdOrigin=TEAMS-ELECTRON.p2p.mw&wdExp=TEAMS-CONTROL&wdhostclicktime=1677055963242&web=1
    '!<rootDir>/src/utils/createImg.js',
    '!<rootDir>/src/components/$/Anniversary_4th/**/*.js',
    '!<rootDir>/src/components/$/Register/Carousel/**/*.js',
    '!<rootDir>/src/components/$/Anniversary_New/**/*.js',
    '!<rootDir>/src/components/$/MarketCommon/luckydrawCommon.js',
    '!<rootDir>/src/components/$/MarketCommon/Share/**/*.js',
    '!<rootDir>/src/components/$/ReferFriends/**/*.js',
    // ApiKing2.0 已下架
    '!<rootDir>/src/components/$/ActivityComponents/**/*.js',
    '!<rootDir>/src/components/ActivityComponents/selectors.js',
    '!<rootDir>/src/components/$/AnnualReport/*.js',
    '!<rootDir>/src/components/$/AnnualReport/**/*.js',
    '!<rootDir>/src/components/$/AntiPhishing/**/*.js',
    '!<rootDir>/src/components/$/ApiKing/**/*.js',
    '!<rootDir>/src/components/$/AsianCarnival/**/*.js',
    '!<rootDir>/src/components/$/CommunityCollect/**/*.js',
    '!<rootDir>/src/components/$/Consensus/**/*.js',
    '!<rootDir>/src/components/$/CryptoCup/**/*.js',
    '!<rootDir>/src/components/$/Delegation/**/*.js',
    '!<rootDir>/src/components/$/DepositFAQ/**/*.js',
    '!<rootDir>/src/components/$/EthMerge/**/*.js',
    '!<rootDir>/src/components/$/Finance_mvp/**/*.js',
    '!<rootDir>/src/components/$/**/*.js',
    '!<rootDir>/src/components/$/KcsGame/**/*.js',
    '!<rootDir>/src/components/$/KcsWhitePaperLottery/**/*.js',
    '!<rootDir>/src/components/$/KucoinToken/**/*.js',
    '!<rootDir>/src/components/$/Luckydraw/**/*.js',
    '!<rootDir>/src/components/$/LuckydrawTurkey/**/*.js',
    '!<rootDir>/src/components/$/Lunc/**/*.js',
    '!<rootDir>/src/components/$/NFTQuiz/**/*.js',
    '!<rootDir>/src/components/$/NewCoin/**/*.js',
    '!<rootDir>/src/components/$/NewcomerGuide/**/*.js',
    '!<rootDir>/src/components/$/NewcomerPackage/**/*.js',
    '!<rootDir>/src/components/$/NftInfo/**/*.js',
    '!<rootDir>/src/components/$/PakistanCampaign/**/*.js',
    '!<rootDir>/src/components/$/Partner/**/*.js',
    '!<rootDir>/src/components/$/Prediction/**/*.js',
    '!<rootDir>/src/components/$/Security/**/*.js',
    '!<rootDir>/src/components/$/ShowCase/**/*.js',
    '!<rootDir>/src/components/$/V3Landing/**/*.js',
    '!<rootDir>/src/components/$/Web3Nft/**/*.js',
    '!<rootDir>/src/components/$/luckydrawSepa/**/*.js',
    // 与相关同事确认 暂无Spotlight5相关的活动 可以忽略
    '!<rootDir>/src/components/$/Spotlight5/**/*.js',
    '!<rootDir>/src/components/$/Spotlight5/module/**/*.js',
    '!<rootDir>/src/components/$/Spotlight5/module/AgreeModal/index.js',
    '!<rootDir>/src/components/$/Spotlight5/module/GradientCard/index.js',
    '!<rootDir>/src/components/$/Spotlight5_H5/module/**/*.js',
    '!<rootDir>/src/components/$/KuRewards/**/*.js',

    '!<rootDir>/src/components/$/Anniversary_New/config.js',
    '!<rootDir>/src/components/$/CryptoCup/config.js',
    '!<rootDir>/src/components/$/MarketCommon/config.js',
    '!<rootDir>/src/components/$/ApiKing/config.js',
    '!<rootDir>/src/components/$/Prediction/config.js',
    '!<rootDir>/src/components/$/Finance_mvp/config.js',
    '!<rootDir>/src/components/$/AnnualReport/config.js',
    '!<rootDir>/src/components/$/NFTQuiz/context.js',
    '!<rootDir>/src/components/$/Anniversary_New/Dialog/index.js',
    '!<rootDir>/src/components/$/Nps/hooks/useQuestion.js',
    '!<rootDir>/src/components/$/Guardian/RenderCMS/index.js',
    '!<rootDir>/src/components/$/Prediction/Schedule/StyledComps.js',
    '!<rootDir>/src/components/$/MarketCommon/luckydrawCommon.js',
    '!<rootDir>/src/components/$/LuckydrawTurkey/config.js',
    '!<rootDir>/src/components/$/Recall/config.js',
    '!<rootDir>/src/components/$/Anniversary_New/Header/index.js',
    '!<rootDir>/src/components/$/Anniversary_4th/config.js',

    '!<rootDir>/src/components/$/Prediction/selector.js',
    '!<rootDir>/src/components/$/Luckydraw/config.js',
    '!<rootDir>/src/components/$/MarketCommon/Share/index.js',

    '!<rootDir>/src/components/$/AnnualReport/CommonBtn/index.js',
    '!<rootDir>/src/components/$/AnnualReport/BottomTip/index.js',
    '!<rootDir>/src/components/$/AnnualReport/PageTip/index.js',
    '!<rootDir>/src/components/$/Finance_mvp/Header/index.js',
    '!<rootDir>/src/components/$/ApiKing/selectors.js',
    '!<rootDir>/src/components/$/Anniversary_New/Loading/index.js',
    '!<rootDir>/src/components/$/luckydrawSepa/config.js',
    '!<rootDir>/src/components/$/Consensus/JumpLink/index.js',

    '!<rootDir>/src/components/$/MarketCommon/NewShare/index.js',
    '!<rootDir>/src/components/$/Spotlight/module/GradientCard/index.js',
    '!<rootDir>/src/components/$/Investment/components/KSlider.js',
    '!<rootDir>/src/components/$/Prediction/WrappedSpin/index.js',
    '!<rootDir>/src/components/$/NFTQuiz/Card.js',
    '!<rootDir>/src/components/$/Nps/config.js',
    '!<rootDir>/src/components/$/NewCoin/config.js',
    '!<rootDir>/src/components/$/NftInfo/config.js',
    '!<rootDir>/src/components/$/AsianCarnival/config.js',
    '!<rootDir>/src/components/$/LeGo/config/index.js',
    '!<rootDir>/src/components/$/PakistanCampaign/config.js',
    '!<rootDir>/src/components/$/Anniversary_New/PosterShare/index.js',

    '!<rootDir>/src/components/$/Finance_mvp/Nodata/index.js',
    '!<rootDir>/src/components/$/Finance_mvp/CommonDialog/index.js',
    '!<rootDir>/src/components/$/Prediction/context.js',
    '!<rootDir>/src/components/$/Prediction/Schedule/PrizePool.js',
    '!<rootDir>/src/components/$/ApiKing/TopHeader/index.js',
    '!<rootDir>/src/components/$/NFTQuiz/LearnNFT/styled.js',
    '!<rootDir>/src/components/$/Nps/components/Question/NpsTextArea.js',
    '!<rootDir>/src/components/$/AnnualReport/Modal/index.js',
    '!<rootDir>/src/components/$/EthMerge/ActivityCalendar/StyledComps.js',
    '!<rootDir>/src/components/$/EthMerge/ActivityCalendar/config.js',
    '!<rootDir>/src/components/$/Spotlight_H5/module/GradientCard/index.js',
    '!<rootDir>/src/components/$/Anniversary_New/Mall/PiecesDialog.js',
    '!<rootDir>/src/components/$/Lunc/CoinList/config.js',

    '!<rootDir>/src/components/$/Investment/JoinButton/index.js',
    '!<rootDir>/src/components/$/Security/config.js',
    '!<rootDir>/src/components/$/KcsWhitePaperLottery/Common/Button/index.js',
    '!<rootDir>/src/components/$/KcsWhitePaperLottery/Common/Modal/index.js',
    '!<rootDir>/src/components/$/Finance_mvp/EarningBox/index.js',
    '!<rootDir>/src/components/$/Finance_mvp/Footer/index.js',
    '!<rootDir>/src/components/$/Finance_mvp/Timeline/index.js',
    '!<rootDir>/src/components/$/Prediction/Schedule/Status.js',
    '!<rootDir>/src/components/$/ApiKing/NoData/index.js',
    '!<rootDir>/src/components/$/ApiKing/HomePage/Rule.js',
    '!<rootDir>/src/components/$/ApiKing/UpgradeModal/index.js',
    '!<rootDir>/src/components/$/NftInfo/CoinCurrency.js',
    '!<rootDir>/src/components/$/AnnualReport/PosterShare/index.js',
    '!<rootDir>/src/components/$/AnnualReport/Logo/index.js',
    '!<rootDir>/src/components/$/AnnualReport/Wing/index.js',
    '!<rootDir>/src/components/$/EthMerge/CoinList/StyledComps.js',
    '!<rootDir>/src/components/$/EthMerge/HomePage/StyledComps.js',
    '!<rootDir>/src/components/$/EthMerge/MoneyManage/StyledComps.js',
    '!<rootDir>/src/components/$/EthMerge/Detail/StyledComps.js',
    '!<rootDir>/src/components/$/EthMerge/Community/StyledComps.js',
    '!<rootDir>/src/components/$/Spotlight5_H5/module/GradientCard/index.js',
    '!<rootDir>/src/components/$/Register/Carousel/index.js',
    '!<rootDir>/src/components/$/RegisterCommon/tool.js',
    '!<rootDir>/src/components/$/LeGo/components/CommonText/index.js',
    '!<rootDir>/src/components/$/LeGo/components/CommonImg/index.js',
    '!<rootDir>/src/components/$/MarketCommon/CommonDialog/index.js',
    '!<rootDir>/src/components/$/LeGo/templates/TemplatesA/config.js',
    '!<rootDir>/src/components/$/LeGo/templates/TemplatesA/index.js',
    '!<rootDir>/src/components/$/PriceProtect/config.js',
    '!<rootDir>/src/components/$/Anniversary_New/Discount/Components/AllCount.js',
    '!<rootDir>/src/components/$/Anniversary_New/CarveUpPool/index.js',
    '!<rootDir>/src/components/$/Anniversary_New/FlashSale/SectionTitle.js',
    '!<rootDir>/src/components/$/Anniversary_New/Mall/MyPieces.js',
    '!<rootDir>/src/components/$/Anniversary_New/RecordList/index.js',
    '!<rootDir>/src/components/$/Anniversary_New/Mall/Card.js',
    '!<rootDir>/src/components/$/Anniversary_New/ShardAwards/index.js',
    '!<rootDir>/src/components/$/Anniversary_New/RecordList/Static.js',
    '!<rootDir>/src/components/$/Anniversary_New/DiscountRecord/ListItem.js',
    '!<rootDir>/src/components/$/Anniversary_New/EmptyList/index.js',
    '!<rootDir>/src/components/$/AntiPhishing/CommonAttacks.js',
    '!<rootDir>/src/components/$/Lunc/CoinList/StyledComps.js',
    '!<rootDir>/src/components/$/Lunc/Community/StyledComps.js',
    '!<rootDir>/src/components/$/Lunc/ActivityCalendar/StyledComps.js',
    '!<rootDir>/src/components/$/CommunityCollect/config.js',
    '!<rootDir>/src/components/$/NewcomerGuide/config.js',
    '!<rootDir>/src/components/ShareModel/pc/config.js',
    '!<rootDir>/src/components/ShareModel/mobile/config.js',
    '!<rootDir>/src/components/ShareModel/index.js',
    '!<rootDir>/src/components/TimeOut/index.js',
    '!<rootDir>/src/components/CommonCaptcha/index.js',
    '!<rootDir>/src/components/common/KcCoinIcon/index.js',
    '!<rootDir>/src/components/EmptyNew/index.js',
    // 覆盖率收集路径
    '<rootDir>/src/utils/**/*.js',
    '<rootDir>/src/hooks/**/*.js',
    '<rootDir>/src/helper.js',
    '!<rootDir>/src/utils/common_models/**/*js',
    '<rootDir>/src/components/Responsive/index.js',
    '<rootDir>/src/components/Toast/index.js',
    '<rootDir>/src/components/common/LoginDrawer/index.js',
    '<rootDir>/src/components/VirtualizedFixList/index.js',
    '<rootDir>/src/components/Portal/index.js',
    '<rootDir>/src/components/common/TimeCountDownBox/index.js',
    '<rootDir>/src/components/CmsComs/ErrorBoundary.js',
    '<rootDir>/src/components/Footer/KCFooter/index.js',
    '<rootDir>/src/components/Locale/LocaleContext.js',
    '<rootDir>/src/components/common/KCSvgIcon.js',
    '<rootDir>/src/components/DrawerSignUp/index.js',
    '<rootDir>/src/components/AbsoluteLoading/index.js',
    '<rootDir>/src/components/QrCodeWithLogo/index.js',
    '<rootDir>/src/components/common/Empty/index.js',
    '<rootDir>/src/components/H5HeaderNew/index.js',
    '<rootDir>/src/components/DrawerSignUp/const.js',
    '<rootDir>/src/components/DrawerSignUp/index.js',
    '<rootDir>/src/components/Loading/index.js',
    '<rootDir>/src/components/img/JumpImg.js',
    '<rootDir>/src/components/Router/index.js',
    '<rootDir>/src/components/common/AntiDuplication/index.js',
    '<rootDir>/src/components/common/CoinPrecision/index.js',
    '<rootDir>/src/components/common/CoinCodeToName/index.js',
    '<rootDir>/src/components/common/Html/index.js',
    '<rootDir>/src/components/Header/LangSelector/index.js',
    '<rootDir>/src/components/$/LeGo/hocs/ByVisible.js',
    '<rootDir>/src/components/$/LeGo/components/Empty/index.js',
    '<rootDir>/src/components/$/LeGoActivity/components/Share/ShareModel/pc/config.js',
    '<rootDir>/src/components/$/LeGoActivity/components/Share/ShareModel/mobile/config.js',
    '<rootDir>/src/components/$/LeGoActivity/components/Editor/index.js',
    '!<rootDir>/src/components/CmsComs/**/*.js', // 未使用
    '!<rootDir>/src/components/Header/**/*.js',
    '!<rootDir>/src/components/common/LoginDrawer/**/*.js'
  ],
};
