/**
      * This file is auto-generated by @kucoin/api-generator
      * Owner: sean.shi@kupotech.com
      */
import Client, { type SwaggerOptions as ClientOptions, type SwaggerTDataShape as TDataShape } from 'gbiz-next/commonRequest';
import type { GetClientPropertyByCodeUsingGet1Data, GetClientPropertyByCodeUsingGet1Response, GetWhiteConfigByAppIdUsingGetData, GetWhiteConfigByAppIdUsingGetResponse } from './types.gen';
import { client as _apiClient } from '../client.gen';
export type Options<TData extends TDataShape = TDataShape> = ClientOptions<TData> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
    disabledLang?: boolean;
};
/**
 * client config  code
 */
export const getClientPropertyByCodeUsingGet1 = (params: GetClientPropertyByCodeUsingGet1Data['query'], options?: Options<GetClientPropertyByCodeUsingGet1Data>) => {
  return (options?.client ?? _apiClient).pull<GetClientPropertyByCodeUsingGet1Response, GetClientPropertyByCodeUsingGet1Data['query']>('/_api/growth-config/get/client/config/codes', params, {
    ...(options || {})
  });
};
/**
 * 根据appId
 */
export const getWhiteConfigByAppIdUsingGet = (params: GetWhiteConfigByAppIdUsingGetData['query'], options?: Options<GetWhiteConfigByAppIdUsingGetData>) => {
  return (options?.client ?? _apiClient).pull<GetWhiteConfigByAppIdUsingGetResponse, GetWhiteConfigByAppIdUsingGetData['query']>('/_api/growth-config/get/white/config', params, {
    ...(options || {})
  });
};
