/**
      * This file is auto-generated by @kucoin/api-generator
      * Owner: sean.shi@kupotech.com
      */

export type CampaignGroupPrizeExtraResponse = {
    /**
     * 激活有效期
     */
    activationExpiryAt?: string;
    /**
     * 面额
     */
    amount?: string;
    /**
     * 奖品code
     */
    code?: string;
    /**
     * 奖券类型 1-vip1，2-vip2，3 vip3 4 vip 4
     */
    couponType?: number;
    createdAt?: string;
    /**
     * 币种
     */
    currency?: string;
    /**
     * 抵扣比例,需大于0，小于等于1，最多两位小数
     */
    deductRatio?: string;
    /**
     * 利率折扣
     */
    discountRate?: string;
    /**
     * 激活有效时长
     */
    effectiveDurition?: number;
    expireTime?: string;
    /**
     * 有效期类型:1-相对时间，2-绝对时间
     */
    expireType?: number;
    ext?: CampaignPrizeExtResponse;
    incomeLimit?: string;
    incomeLimitCurrency?: string;
    incomeLimitType?: string;
    interestRate?: string;
    /**
     * 发奖类型，0-等U金额，1-代币数量
     */
    issueType?: number;
    limitProduct?: LimitProduct;
    /**
     * 最大可提金额
     */
    maxExtract?: string;
    /**
     * 最大杠杆倍数
     */
    maxLeverage?: string;
    /**
     * 最大利润
     */
    maxProfit?: string;
    /**
     * 最小已实现盈亏
     */
    minCloseRealisedPnl?: string;
    /**
     * 最小时长
     */
    minDurition?: number;
    /**
     * 最小可提金额
     */
    minExtract?: string;
    /**
     * 最小利润
     */
    minProfit?: string;
    /**
     * 最小总成交金额
     */
    minTotalTradingAmount?: string;
    /**
     * 最小交易次数
     */
    minTradeCount?: number;
    /**
     * 最小成交次数
     */
    minTradingVolume?: number;
    principalLimit?: string;
    /**
     * 额度
     */
    quota?: string;
    /**
     * 发放的对应币种的金额
     */
    sendAmount?: string;
    /**
     * 抵扣币对类型，0：全部现货交易对；1：全部现货交易对-去除ETF；2：全部ETF交易对，3：自定义交易对
     */
    symbolType?: number;
    /**
     * 类型:NORMAL,VIP
     */
    trialType?: string;
    updatedAt?: string;
    /**
     * 使用时长
     */
    useDurition?: number;
    /**
     * 使用有效期类型:0-绝对时间，1-相对发放时间，2-相对激活时间
     */
    useExpireType?: number;
    /**
     * 使用有效期
     */
    useExpiryAt?: string;
    /**
     * 投票数（投票上币券场景）
     */
    voteTimes?: number;
};

export type CampaignGroupPrizeResponse = {
    appUrl?: string;
    campaignName?: string;
    code?: string;
    currency?: string;
    effectiveDurition?: number;
    expireType?: number;
    ext?: string;
    extra?: CampaignGroupPrizeExtraResponse;
    icon?: string;
    prizeType?: number;
    rewardId?: string;
    status?: number;
    type?: number;
    useDurition?: number;
    useExtra?: UseExtra;
    webUrl?: string;
};

export type CampaignPrizeExtResponse = {
    amount?: string;
    compliantCode?: string;
    convertFromUsdt?: boolean;
    exchangeRate?: string;
    usdtLimit?: string;
};

export type GenericResult_newCustomerTaskGeneralConfigurationInformation_ = {
    code?: string;
    data?: Common_26032234582021921153368902999237197326222044924687_;
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type LimitProduct = {
    category?: string;
    currency?: string;
    incomeCurrency?: string;
    productId?: string;
    productName?: string;
    productSource?: string;
    type?: string;
};

export type NewcomerLimitTaskLevelDetailVo = {
    currency?: string;
    /**
     * 前端不用传
     */
    endDepositAmount?: string;
    /**
     * 前端不用传
     */
    endTradeAmount?: string;
    level?: number;
    /**
     * 前端不用传
     */
    prizeAmount?: string;
    /**
     * 发奖中台活动编码
     */
    prizeCode?: string;
    prizeConfig?: CampaignGroupPrizeResponse;
    prizeName?: string;
    /**
     * 前端不用传
     */
    prizeType?: number;
    startDepositAmount?: string;
    startTradeAmount?: string;
};

export type QuestPrizeResponse = {
    amount?: string;
    couponAmount?: string;
    couponType?: number;
    currency?: string;
    issueType?: number;
    level?: number;
    num?: string;
    prizeCode?: string;
    prizeDetail?: CampaignGroupPrizeResponse;
    prizeHandOutType?: number;
    prizeProbability?: string;
    prizeStock?: number;
    prizeStockLat?: number;
    prizeType?: number;
    rewardPercent?: string;
    type?: number;
    unlocked?: boolean;
    unlockedAmount?: string;
    unlockedNum?: string;
    validityPeriod?: number;
    version?: string;
    vipNum?: number;
    vipType?: string;
};

export type UseExtra = {
    amount?: string;
    closeRealisedPnl?: string;
    /**
     * 累计收益
     */
    cumulativeProfit?: string;
    currency?: string;
    currencyName?: string;
    deductedAmount?: string;
    realisedGrossCost?: string;
    rewardId?: string;
    robotId?: string;
    strategy?: number;
    symbol?: string;
    totalAmount?: string;
    totalUsdt?: string;
    usedAmount?: string;
    usedCurrency?: string;
    withDrawableAmount?: string;
    withDrawnAmount?: string;
};

export type Common_215123242220307395643732938480261022021921153_ = {
    /**
     * 入金渠道，数字枚举：0-全量渠道，1-充值（Deposit，不包含站内转账)，2-入金-P2P（全量），3-入金-法币充值（按渠道）
     */
    depositAmtType?: number;
    /**
     * 限时任务首次入金法币渠道
     */
    depositChannel?: string;
    /**
     * 限时任务首次入金充值币种
     */
    depositCurrency?: string;
    /**
     * 币种选择逻辑，0为正选，1为仅排除，2为全选
     */
    depositCurrencyOperator?: number;
    limitTaskLevel?: Array<NewcomerLimitTaskLevelDetailVo>;
    prizeStatus?: string;
    /**
     * 限时挑战任务任务子标题
     */
    subtitle?: string;
    taskStatus?: string;
    userDepositAmount?: string;
    userLevel?: number;
    userTradeAmount?: string;
};

export type Common_260322345820219211532999225143Kyc202192115335814247732044924687_ = {
    /**
     * 奖励类型 LOTTERY/FIX
     */
    awardType?: string;
    /**
     * 入金渠道，数字枚举：0-全量渠道，1-充值（Deposit，不包含站内转账)，2-入金-P2P（全量），3-入金-法币充值（按渠道）
     */
    depositAmtType?: number;
    /**
     * 首次入金法币渠道
     */
    depositChannel?: string;
    /**
     * 首次入金充值币种
     */
    depositCurrency?: string;
    /**
     * 币种选择逻辑，0为正选，1为仅排除，2为全选
     */
    depositCurrencyOperator?: number;
    /**
     * 任务有效结束时间
     */
    effectiveEndTime?: string;
    /**
     * 任务有效开始时间
     */
    effectiveStartTime?: string;
    /**
     * 固定金额
     */
    fixAmount?: string;
    /**
     * 奖品信息
     */
    prize?: Array<Common_260322345820219211532999225143202192115322870211692044924687_>;
    /**
     * 翻牌子金额选项
     */
    prizeAmount?: Array<string>;
    /**
     * 进阶任务合约交易完成任务金额
     */
    proContractCompleteAmount?: string;
    /**
     * 进阶任务现货交易完成任务金额
     */
    proSpotCompleteAmount?: string;
    /**
     * 任务顺序排序 ex:1
     */
    sort?: number;
    /**
     * 奖品信息
     */
    subTitle?: string;
    /**
     * 任务状态 INIT(未完成)/EXPIRE（已过期）/COMPLETE（已完成）
     */
    taskStatus?: string;
    /**
     * 任务类型 SIGN_UP/DEPOSIT/TRADE/PRO
     */
    taskType?: string;
};

export type Common_260322345820219211532999225143202192115322870211692044924687_ = {
    couponDetail?: QuestPrizeResponse;
    /**
     * 奖励生成时间
     */
    createTime?: string;
    /**
     * 奖品领取有效结束时间
     */
    effectiveEndTime?: string;
    /**
     * 奖品领取有效结束时间
     */
    effectiveStartTime?: string;
    /**
     * 错误码
     */
    errorCode?: string;
    /**
     * 用户抽奖最终获取金额
     */
    finalPrizeAmount?: string;
    /**
     * 奖励code
     */
    prizeCode?: string;
    prizePlatform?: string;
    /**
     * 奖品状态WAIT_DRAW(待领取)/DRAWED（已领取）/EXPIRE（已过期）
     */
    prizeStatus?: string;
    /**
     * 奖励类型 USDT/COUPON
     */
    prizeType?: string;
    /**
     * 任务类型
     */
    taskType?: string;
    /**
     * USDT提现申请状态 INIT(已申请提现待运营处理)/PROCESSING（运营处理中）/SUCCESS(处理成功)/REJECT（拒绝)/PAY_NIT(提现申请付款中)
     */
    withdrawStatus?: string;
};

export type Common_26032234582021921153368902999237197326222044924687_ = {
    /**
     * 配置版本号 1/2
     */
    configVersion?: number;
    /**
     * 活动展示总金额
     */
    displayTotalAmount?: string;
    /**
     * 活动结束时间
     */
    effectiveEndTime?: string;
    /**
     * 是否是新客任务用户 用户任务过期时，isEffectiveNewcomer也为true
     */
    isEffectiveNewcomer?: boolean;
    /**
     * 新客任务整体状态
     */
    newcomerTaskStatus?: string;
    /**
     * 当前系统时间
     */
    now?: string;
    /**
     * 用户注册时间
     */
    registerDate?: string;
    /**
     * 用户任务信息列表
     */
    taskList?: Array<Common_260322345820219211532999225143Kyc202192115335814247732044924687_>;
    tempTask?: Common_2603223458384802610220219211532044924687_;
};

export type Common_2603223458384802610220219211532044924687_ = {
    financialNewcomerTaskInfo?: Common_297023613038480261022021921153_;
    /**
     * 理财限时任务子标题
     */
    financialSubtitle?: string;
    financialVipTaskInfo?: Common_297023613038480261022021921153_;
    limitTaskInfo?: Common_215123242220307395643732938480261022021921153_;
    taskEndTime?: string;
    taskStartTime?: string;
};

export type Common_297023613038480261022021921153_ = {
    /**
     * 当前用户申购金额
     */
    currentBoughtAmount?: string;
    /**
     * 其他收益
     */
    extraApr?: string;
    /**
     * 理财限时任务收益子标题
     */
    financialBenefitSubTitle?: string;
    financialProductId?: string;
    /**
     * 总申购金额
     */
    maxBoughtAmount?: string;
    prizeStatus?: string;
    taskStatus?: string;
};

export type ConfigUsingGetData = {
    body?: never;
    headers: {
        /**
         * X-USER-ID
         */
        'X-USER-ID'?: string;
        /**
         * X-IP
         */
        'X-IP'?: string;
        /**
         * LANG
         */
        LANG: string;
    };
    path?: never;
    query?: never;
    url: '/newcomer/config';
};

export type ConfigUsingGetResponses = {
    /**
     * OK
     */
    200: GenericResult_newCustomerTaskGeneralConfigurationInformation_;
};

export type ConfigUsingGetResponse = ConfigUsingGetResponses[keyof ConfigUsingGetResponses];

export type ClientOptions = { baseURL: string; };