/**
      * This file is auto-generated by @kucoin/api-generator
      * Owner: sean.shi@kupotech.com
      */

export type CurrencyResponse = {
    /**
     * 涨跌幅
     */
    changeRate?: string;
    /**
     * 币种code
     */
    currency?: string;
    /**
     * 描述
     */
    description?: string;
    /**
     * 是否持有
     */
    holding?: boolean;
    /**
     * 图标链接
     */
    iconUrl?: string;
    /**
     * 币种名称
     */
    name?: string;
    /**
     * 价格
     */
    price?: string;
    /**
     * 交易对code
     */
    symbolCode?: string;
};

export type GenericResult_SplResponse_ = {
    code?: string;
    data?: SplResponse;
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type PlateResponse = {
    /**
     * 算术平均涨跌幅
     */
    avgChangeRate?: string;
    /**
     * 板块币种
     */
    currencies?: Array<CurrencyResponse>;
    /**
     * 热币名称列表
     */
    currencyList?: Array<string>;
    /**
     * 板块描述
     */
    description?: string;
    /**
     * 下跌数量
     */
    downNum?: number;
    /**
     * 是否持有
     */
    holding?: boolean;
    /**
     * 持有币种
     */
    holdingCurrencies?: Array<CurrencyResponse>;
    /**
     * 热币名称列表
     */
    hotCurrencyNameList?: Array<string>;
    /**
     * 领涨币种
     */
    leadingCurrencies?: Array<CurrencyResponse>;
    /**
     * 标签ID
     */
    tagId?: string;
    /**
     * 板块名称
     */
    title?: string;
    /**
     * 上涨数量，包含涨幅为0
     */
    upNum?: number;
    /**
     * 权重
     */
    weight?: number;
};

export type SplItemResponse = {
    /**
     * 实体
     */
    item?: string;
    /**
     * 特殊标注便签
     */
    operationTags?: Array<TagResponse>;
    /**
     * 实体标签列表
     */
    tags?: Array<TagResponse>;
    /**
     * 权重
     */
    weight?: string;
};

export type SplResponse = {
    /**
     * 算法
     */
    algorithm?: 'CONTINUOUS_FALL' | 'CONTINUOUS_RISE' | 'DECREASE' | 'FIRST_HOT_CURRENCY' | 'GEM_BOX' | 'HEAT_SURGE_OPERATE' | 'HOT_CURRENCY' | 'HOT_SEARCH' | 'INCREASE' | 'KUCOIN_30' | 'NEW_CURRENCY' | 'NEW_CURRENCY_OPEN' | 'NEW_CURRENCY_TRADE' | 'OUTPERFORM_BTC' | 'PLATE' | 'SUDDEN_FALL' | 'SUDDEN_RISE' | 'TRADE_VOLUME_RISE' | 'TRADE_VOLUME_SUDDEN_RISE' | 'VOLUME';
    /**
     * 综合平均涨跌幅
     */
    avgChangeRate?: string;
    /**
     * 描述
     */
    description?: string;
    /**
     * 下跌数量
     */
    downNum?: number;
    /**
     * 是否热门
     */
    isHot?: boolean;
    /**
     * 实体列表
     */
    items?: Array<SplItemResponse>;
    /**
     * 龙头币
     */
    leadCurrencies?: Array<CurrencyResponse>;
    /**
     * 埋点ID
     */
    pointId?: string;
    /**
     * 关联板块
     */
    relationPlates?: Array<PlateResponse>;
    /**
     * 副标题
     */
    subtitle?: string;
    /**
     * 标题
     */
    title?: string;
    /**
     * 当前列表存在在top20中的币种列表
     */
    topIncludeCurrencies?: Array<SplItemResponse>;
    /**
     * 上涨数量，包含涨幅为0
     */
    upNum?: number;
};

export type TagResponse = {
    /**
     * 算法
     */
    algorithm?: number;
    /**
     * 描述
     */
    description?: string;
    /**
     * 样式类型
     */
    displayType?: number;
    /**
     * GemBox描述
     */
    gemBoxDescription?: string;
    /**
     * 副标签标题
     */
    subtitle?: string;
    /**
     * 标签ID
     */
    tagId?: string;
    /**
     * 标签标题
     */
    title?: string;
    /**
     * 类型
     */
    type?: number;
};

export type GetSplUsingGetData = {
    body?: never;
    headers: {
        /**
         * X-KC-CDN-SITE-TYPE
         */
        'X-KC-CDN-SITE-TYPE': string;
    };
    path?: never;
    query: {
        /**
         * 算法
         */
        algorithm?: 'CONTINUOUS_FALL' | 'CONTINUOUS_RISE' | 'DECREASE' | 'FIRST_HOT_CURRENCY' | 'GEM_BOX' | 'HEAT_SURGE_OPERATE' | 'HOT_CURRENCY' | 'HOT_SEARCH' | 'INCREASE' | 'KUCOIN_30' | 'NEW_CURRENCY' | 'NEW_CURRENCY_OPEN' | 'NEW_CURRENCY_TRADE' | 'OUTPERFORM_BTC' | 'PLATE' | 'SUDDEN_FALL' | 'SUDDEN_RISE' | 'TRADE_VOLUME_RISE' | 'TRADE_VOLUME_SUDDEN_RISE' | 'VOLUME';
        /**
         * 语言
         */
        lang?: string;
        /**
         * 站点
         */
        siteType?: string;
        /**
         * 标签ID
         */
        tagId?: string;
        /**
         * 类型
         */
        type: 'GEM_BOX' | 'HOME_LIST' | 'INDEX' | 'LIST' | 'PLATE';
    };
    url: '/spl';
};

export type GetSplUsingGetResponses = {
    /**
     * OK
     */
    200: GenericResult_SplResponse_;
};

export type GetSplUsingGetResponse = GetSplUsingGetResponses[keyof GetSplUsingGetResponses];

export type ClientOptions = { baseURL: string; };
