/**
 * This file is auto-generated by @kucoin/api-generator
 * Owner: sean.shi@kupotech.com
 */
import RequestClient, { RuntimeEnvironment } from 'gbiz-next/commonRequest';
import JsBridge from 'gbiz-next/bridge';
import { IS_SERVER_ENV } from 'kc-next/env';
import { getReport } from 'gbiz-next/report';
// import { responseErrorInterceptor } from '@/tools/request/showErrorInterceptor';

export const client = new RequestClient({
  projectName: 'ssr-fast-template',
  environment: IS_SERVER_ENV
    ? RuntimeEnvironment.SSR
    : JsBridge.isApp()
      ? RuntimeEnvironment.APP
      : RuntimeEnvironment.BROWSER,
  fingerPrintUrlList: [{ url: '/_api/ucenter/user-info', event: 'userInfo' }],
  getReporter: getReport,
  // responseInterceptors: [
  //   {
  // 如果放开这里，需要修改 showErrorInterceptor 内部的 useUserStore
  //     name: 'showErrorInterceptor',
  //     onRejected: responseErrorInterceptor,
  //   },
  // ],
});
