/**
      * This file is auto-generated by @kucoin/api-generator
      * Owner: sean.shi@kupotech.com
      */
import Client, { type SwaggerOptions as ClientOptions, type SwaggerTDataShape as TDataShape } from 'gbiz-next/commonRequest';
import type { GetByCodeUsingGetData, GetByCodeUsingGetResponse, Receive2CodeUsingPostData, Receive2CodeUsingPostResponse, Receive2PhoneUsingPostData, Receive2PhoneUsingPostResponse, ReceiveV2UsingPostData, ReceiveV2UsingPostResponse, GetWelfareReceiveRecordV2UsingPostData, GetWelfareReceiveRecordV2UsingPostResponse, GetWelfareDetailUsingGet1Data, GetWelfareDetailUsingGet1Response, GetWelfareReceiveRecordUsingGet1Data, GetWelfareReceiveRecordUsingGet1Response, GetWelfareDetailListUsingGet1Data, GetWelfareDetailListUsingGet1Response } from './types.gen';
import { client as _apiClient } from '../client.gen';
export type Options<TData extends TDataShape = TDataShape> = ClientOptions<TData> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
    disabledLang?: boolean;
};
/**
 * web/m 校验福利记录是否存在，存在则返回
 */
export const getByCodeUsingGet = (params?: GetByCodeUsingGetData['query'], options?: Options<GetByCodeUsingGetData>) => {
  return (options?.client ?? _apiClient).pull<GetByCodeUsingGetResponse, GetByCodeUsingGetData['query']>('/_api/welfare/web/get-welfare', params, {
    ...(options || {})
  });
};
/**
 * web/m 登录领取
 */
export const receive2CodeUsingPost = (data?: Receive2CodeUsingPostData['query'], options?: Options<Receive2CodeUsingPostData>) => {
  return (options?.client ?? _apiClient).post<Receive2CodeUsingPostResponse, Receive2CodeUsingPostData['query']>('/_api/welfare/web/receive2code', data, {
    ...(options || {}),
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      ...(options?.headers || {})
    }
  });
};
/**
 * web/m 用户通过手机号发起领取福利
 */
export const receive2PhoneUsingPost = (data: Receive2PhoneUsingPostData['query'], options?: Options<Receive2PhoneUsingPostData>) => {
  return (options?.client ?? _apiClient).post<Receive2PhoneUsingPostResponse, Receive2PhoneUsingPostData['query']>('/_api/welfare/web/receive2phone', data, {
    ...(options || {}),
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      ...(options?.headers || {})
    }
  });
};
/**
 * web/m 用户通过手机号或邮箱发起领取福利v2
 */
export const receiveV2UsingPost = (data?: ReceiveV2UsingPostData['body'], options?: Options<ReceiveV2UsingPostData>) => {
  return (options?.client ?? _apiClient).post<ReceiveV2UsingPostResponse, ReceiveV2UsingPostData['body']>('/_api/welfare/web/receiveV2', data, {
    ...(options || {})
  });
};
/**
 * web/m 获取福利明细以及用户的领取记录v2
 */
export const getWelfareReceiveRecordV2UsingPost = (data?: GetWelfareReceiveRecordV2UsingPostData['body'], options?: Options<GetWelfareReceiveRecordV2UsingPostData>) => {
  return (options?.client ?? _apiClient).post<GetWelfareReceiveRecordV2UsingPostResponse, GetWelfareReceiveRecordV2UsingPostData['body']>('/_api/welfare/web/v2/welfare-detail', data, {
    ...(options || {})
  });
};
/**
 * web/m 获取福利以及用户的领取记录
 */
export const getWelfareDetailUsingGet1 = (params?: GetWelfareDetailUsingGet1Data['query'], options?: Options<GetWelfareDetailUsingGet1Data>) => {
  return (options?.client ?? _apiClient).pull<GetWelfareDetailUsingGet1Response, GetWelfareDetailUsingGet1Data['query']>('/_api/welfare/web/welfare-detail', params, {
    ...(options || {})
  });
};
/**
 * web/m 获取福利明细以及用户的领取记录
 */
export const getWelfareReceiveRecordUsingGet1 = (params: GetWelfareReceiveRecordUsingGet1Data['query'], options?: Options<GetWelfareReceiveRecordUsingGet1Data>) => {
  return (options?.client ?? _apiClient).pull<GetWelfareReceiveRecordUsingGet1Response, GetWelfareReceiveRecordUsingGet1Data['query']>('/_api/welfare/web/welfare-detail-phone', params, {
    ...(options || {})
  });
};
/**
 * web/m 获取单个福利的所有用户的领取记录
 */
export const getWelfareDetailListUsingGet1 = (params?: GetWelfareDetailListUsingGet1Data['query'], options?: Options<GetWelfareDetailListUsingGet1Data>) => {
  return (options?.client ?? _apiClient).pull<GetWelfareDetailListUsingGet1Response, GetWelfareDetailListUsingGet1Data['query']>('/_api/welfare/web/welfare-detail/hasMore', params, {
    ...(options || {})
  });
};
