/**
      * This file is auto-generated by @kucoin/api-generator
      * Owner: sean.shi@kupotech.com
      */

export type GenericHasMoreResult_WelfareReceiveRecordResponse_ = {
    code?: string;
    context?: {
        [key: string]: unknown;
    };
    dataList?: Array<WelfareReceiveRecordResponse>;
    hasMore?: boolean;
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type GenericResult_WelfareReceive2PhoneRecordResponse_ = {
    code?: string;
    data?: WelfareReceive2PhoneRecordResponse;
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type GenericResult_WelfareReceiveRecordResponse_ = {
    code?: string;
    data?: WelfareReceiveRecordResponse;
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type GenericResult_WelfareReceiveRecordV2Response_ = {
    code?: string;
    data?: WelfareReceiveRecordV2Response;
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type GenericResult_WelfareRecordExistsResponse_ = {
    code?: string;
    data?: WelfareRecordExistsResponse;
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type GenericResult_WelfareResponse_ = {
    code?: string;
    data?: WelfareResponse;
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type WelfareReceive2PhoneRecordResponse = {
    /**
     * 币种
     */
    currency?: string;
    /**
     * 过期时间
     */
    expiredAt?: number;
    /**
     * 主键id
     */
    id?: string;
    /**
     * 索引
     */
    index?: number;
    /**
     * 是否手气最佳
     */
    isLucky?: boolean;
    /**
     * 是否新用户
     */
    isNewUser?: boolean;
    /**
     * 当前数据是否是自己的领取记录：是-true，否-false
     */
    isSelf?: boolean;
    /**
     * 领取人昵称
     */
    nickName?: string;
    /**
     * 已领取金额
     */
    receiveAmount?: string;
    /**
     * 领取时间
     */
    receiveAt?: string;
    /**
     * 领取状态  0-待领取,1-已领取,2-入账成功,11-锁定,12-退回
     */
    receiveStatus?: number;
    /**
     * 剩余时间
     */
    remainingAt?: number;
    /**
     * 发送金额
     */
    sendAmount?: string;
    /**
     * 发送人昵称
     */
    sendNickName?: string;
    /**
     * 福利状态：-1-异常状态,0-不存在，1-领取中，2-抢完，3-过期
     */
    welfareStatus?: number;
};

export type WelfareReceiveRecordRequest = {
    /**
     * 国际区号
     */
    countryCode?: string;
    /**
     * 邮箱
     */
    email?: string;
    /**
     * 领取人的电话
     */
    phone?: string;
    /**
     * 发送记录ID
     */
    sendRecordId?: string;
};

export type WelfareReceiveRecordResponse = {
    /**
     * 币种
     */
    currency?: string;
    /**
     * 过期时间
     */
    expiredAt?: number;
    /**
     * 主键id
     */
    id?: string;
    /**
     * 索引
     */
    index?: number;
    /**
     * 是否手气最佳
     */
    isLucky?: boolean;
    /**
     * 是否新用户
     */
    isNewUser?: boolean;
    /**
     * 当前数据是否是自己的领取记录：是-true，否-false
     */
    isSelf?: boolean;
    /**
     * 领取人昵称
     */
    nickName?: string;
    /**
     * 已领取金额
     */
    receiveAmount?: string;
    /**
     * 领取时间
     */
    receiveAt?: string;
    /**
     * 领取状态  0-待领取,1-已领取,2-入账成功,11-锁定,12-退回
     */
    receiveStatus?: number;
    /**
     * 剩余时间
     */
    remainingAt?: number;
    /**
     * 发送金额
     */
    sendAmount?: string;
    /**
     * 发送人昵称
     */
    sendNickName?: string;
    /**
     * 福利状态：-1-异常状态,0-不存在，1-领取中，2-抢完，3-过期
     */
    welfareStatus?: number;
};

export type WelfareReceiveRecordV2Response = {
    /**
     * 币种
     */
    currency?: string;
    /**
     * 过期时间
     */
    expiredAt?: number;
    /**
     * 主键id
     */
    id?: string;
    /**
     * 索引
     */
    index?: number;
    /**
     * 是否手气最佳
     */
    isLucky?: boolean;
    /**
     * 是否新用户
     */
    isNewUser?: boolean;
    /**
     * 当前数据是否是自己的领取记录：是-true，否-false
     */
    isSelf?: boolean;
    /**
     * 领取人昵称
     */
    nickName?: string;
    /**
     * 已领取金额
     */
    receiveAmount?: string;
    /**
     * 领取时间
     */
    receiveAt?: string;
    /**
     * 领取状态  0-待领取,1-已领取,2-入账成功,11-锁定,12-退回
     */
    receiveStatus?: number;
    /**
     * 剩余时间
     */
    remainingAt?: number;
    /**
     * 发送金额
     */
    sendAmount?: string;
    /**
     * 发送人昵称
     */
    sendNickName?: string;
    /**
     * 福利状态：-1-异常状态,0-不存在，1-领取中，2-抢完，3-过期
     */
    welfareStatus?: number;
};

export type WelfareReceiveV2Request = {
    /**
     * 渠道
     */
    channel?: 'APP' | 'M' | 'WEB';
    /**
     * 福利口令code
     */
    code?: string;
    /**
     * 国际区号
     */
    countryCode?: string;
    /**
     * 邮箱
     */
    email?: string;
    /**
     * 领取人的电话
     */
    phone?: string;
};

export type WelfareRecordExistsResponse = {
    /**
     * 祝福语
     */
    bestWishes?: string;
    /**
     * 币种
     */
    currency?: string;
    /**
     * 红包封面地址
     */
    extendUrl?: string;
    /**
     * 是否是新人红包
     */
    isNewBee?: boolean;
    /**
     * 是否已领取：false-未领取，true-已领取
     */
    isReceive?: boolean;
    /**
     * 福利发送人
     */
    nickName?: string;
    /**
     * 已经领取的金额
     */
    receiveAmount?: string;
    /**
     * 领取状态  0-待领取,1-已领取,2-入账成功,11-锁定,12-退回
     */
    receiveStatus?: number;
    /**
     * 发送福利表id
     */
    sendRecordId?: string;
    /**
     * 福利状态：-1-异常状态,0-不存在，1-领取中，2-抢完，3-过期
     */
    welfareStatus?: number;
    /**
     * 福利类型类型：0-实时福利(拼)、1-实时福利(固定金额）
     */
    welfareType?: number;
};

export type WelfareResponse = {
    /**
     * 祝福语
     */
    bestWishes?: string;
    /**
     * 发送币种
     */
    currency?: string;
    /**
     * 红包封面地址
     */
    extendUrl?: string;
    /**
     * 首次领取时间
     */
    firstAt?: string;
    /**
     * 主键id
     */
    id?: string;
    /**
     * 是否是新人红包
     */
    isNewBee?: boolean;
    /**
     * 当前登录用户是否已领取：false-未领取，true-已领取
     */
    isReceive?: boolean;
    /**
     * 当前福利是否是自己发送的：是-true，否-false
     */
    isSelf?: boolean;
    /**
     * 最后领取时间
     */
    lastAt?: string;
    /**
     * 福利发送人昵称
     */
    nickName?: string;
    receive?: WelfareReceiveRecordResponse;
    /**
     * 已领取币种数量
     */
    receiveAmount?: string;
    /**
     * 已领取个数
     */
    receiveNum?: number;
    /**
     * 发送币种数量
     */
    sendAmount?: string;
    /**
     * 红包发送时间
     */
    sendAt?: string;
    /**
     * 发送个数
     */
    sendNum?: number;
    /**
     * 福利状态：-1-异常状态,0-不存在，1-领取中，2-抢完，3-过期
     */
    welfareStatus?: number;
    /**
     * 获取福利类型：0-实时福利(拼)、1-实时福利(普通）
     */
    welfareType?: number;
};

export type GetByCodeUsingGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 标识发放福利表的code
         */
        code?: string;
    };
    url: '/web/get-welfare';
};

export type GetByCodeUsingGetResponses = {
    /**
     * OK
     */
    200: GenericResult_WelfareRecordExistsResponse_;
};

export type GetByCodeUsingGetResponse = GetByCodeUsingGetResponses[keyof GetByCodeUsingGetResponses];

export type Receive2CodeUsingPostData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 渠道
         */
        channel?: 'APP' | 'M' | 'WEB';
        /**
         * 福利口令code
         */
        code?: string;
        /**
         * 领取福利用户昵称
         */
        receiveNickName?: string;
    };
    url: '/web/receive2code';
};

export type Receive2CodeUsingPostResponses = {
    /**
     * OK
     */
    200: GenericResult_WelfareReceiveRecordResponse_;
};

export type Receive2CodeUsingPostResponse = Receive2CodeUsingPostResponses[keyof Receive2CodeUsingPostResponses];

export type Receive2PhoneUsingPostData = {
    body?: never;
    path?: never;
    query: {
        /**
         * 渠道
         */
        channel?: 'APP' | 'M' | 'WEB';
        /**
         * 福利口令code
         */
        code?: string;
        /**
         * 国际区号
         */
        countryCode: string;
        /**
         * 领取人的电话
         */
        phone?: string;
    };
    url: '/web/receive2phone';
};

export type Receive2PhoneUsingPostResponses = {
    /**
     * OK
     */
    200: GenericResult_WelfareReceive2PhoneRecordResponse_;
};

export type Receive2PhoneUsingPostResponse = Receive2PhoneUsingPostResponses[keyof Receive2PhoneUsingPostResponses];

export type ReceiveV2UsingPostData = {
    body?: WelfareReceiveV2Request;
    path?: never;
    query?: never;
    url: '/web/receiveV2';
};

export type ReceiveV2UsingPostResponses = {
    /**
     * OK
     */
    200: GenericResult_WelfareReceiveRecordV2Response_;
};

export type ReceiveV2UsingPostResponse = ReceiveV2UsingPostResponses[keyof ReceiveV2UsingPostResponses];

export type GetWelfareReceiveRecordV2UsingPostData = {
    body?: WelfareReceiveRecordRequest;
    path?: never;
    query?: never;
    url: '/web/v2/welfare-detail';
};

export type GetWelfareReceiveRecordV2UsingPostResponses = {
    /**
     * OK
     */
    200: GenericResult_WelfareResponse_;
};

export type GetWelfareReceiveRecordV2UsingPostResponse = GetWelfareReceiveRecordV2UsingPostResponses[keyof GetWelfareReceiveRecordV2UsingPostResponses];

export type GetWelfareDetailUsingGet1Data = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 发放福利表id
         */
        sendRecordId?: string;
    };
    url: '/web/welfare-detail';
};

export type GetWelfareDetailUsingGet1Responses = {
    /**
     * OK
     */
    200: GenericResult_WelfareResponse_;
};

export type GetWelfareDetailUsingGet1Response = GetWelfareDetailUsingGet1Responses[keyof GetWelfareDetailUsingGet1Responses];

export type GetWelfareReceiveRecordUsingGet1Data = {
    body?: never;
    path?: never;
    query: {
        /**
         * 发放福利表id
         */
        sendRecordId?: string;
        /**
         * 领取人的电话
         */
        phone?: string;
        /**
         * 国际区号
         */
        countryCode: string;
    };
    url: '/web/welfare-detail-phone';
};

export type GetWelfareReceiveRecordUsingGet1Responses = {
    /**
     * OK
     */
    200: GenericResult_WelfareResponse_;
};

export type GetWelfareReceiveRecordUsingGet1Response = GetWelfareReceiveRecordUsingGet1Responses[keyof GetWelfareReceiveRecordUsingGet1Responses];

export type GetWelfareDetailListUsingGet1Data = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 索引
         */
        index?: number;
        /**
         * 发放福利表id
         */
        sendRecordId?: string;
        /**
         * 条数
         */
        size?: number;
    };
    url: '/web/welfare-detail/hasMore';
};

export type GetWelfareDetailListUsingGet1Responses = {
    /**
     * OK
     */
    200: GenericHasMoreResult_WelfareReceiveRecordResponse_;
};

export type GetWelfareDetailListUsingGet1Response = GetWelfareDetailListUsingGet1Responses[keyof GetWelfareDetailListUsingGet1Responses];

export type ClientOptions = { baseURL: string; };
