
// this file is generate by genSiteConfig for rollup
// don't edit this file
window._SITE_CONFIG_ = {
  "siteType": "thailand",
  "basicProperties": {
    "siteName": "泰国站",
    "shareGlobalAccount": 2,
    "walletType": 2,
    "storageType": 1,
    "siteDomainType": 2,
    "siteDomain": "www.kucoin.th",
    "siteRegion": null,
    "brandType": 2,
    "logoType": 2
  },
  "extProperties": [],
  "functions": {
    "api_broker": false,
    "fast_trade": false,
    "spot_growth": true,
    "3rd_party": false,
    "convert": false,
    "seo": true,
    "trading_bot": false,
    "financial_system": true,
    "kyc": true,
    "home_page": true,
    "affiliate": false,
    "nd_broker": false,
    "spot": true,
    "option": false,
    "reconciliation_system": true,
    "etf": false,
    "payment": true,
    "kucard": false,
    "platform_growth": true,
    "tax_platform": true,
    "copy_trading": false,
    "loan": false,
    "data_center": true,
    "invite_rebate": false,
    "api": true,
    "message_center": true,
    "margin": false,
    "web3_wallet": false,
    "customer_service_system": true,
    "financing": false,
    "personal_center": true,
    "rebate_business": false,
    "p2p": false,
    "search": true,
    "fiat_deposit": true,
    "futures": false,
    "risk_control_system": true,
    "currency": true,
    "k_line": true,
    "kucoin_pay": false,
    "basic_bench": true,
    "express": true,
    "ucenter": true,
    "activity_bench": true,
    "kyb": true,
    "compliance_exhibition_platform": true
  },
  "bizConfigs": {
    "contract_liquidity": "",
    "shield_currency": "",
    "spot_liquidity": "shared_liquidity",
    "is_allowed_multilevel_rebate": "",
    "quote_currency": "THB",
    "rebate_range": ""
  }
};
