/**
 * owner: Clyne@kupotech.com
 */

const PEPEUSDTM = {
  m: 3773300,
  mmrLimit: 0.3,
  f: 1.3,
  k: 500,
  id: '389',
  symbol: 'PEPEUSDTM',
  rootSymbol: 'USDT',
  type: 'FFWCSX',
  firstOpenDate: 1683304200000,
  expireDate: null,
  settleDate: null,
  baseCurrency: 'PEPE',
  quoteCurrency: 'USDT',
  settleCurrency: 'USDT',
  spotCurrency: 'PEPE',
  maxOrderQty: 1000000,
  maxPrice: 1000000.0,
  lotSize: 1,
  tickSize: 1.0e-10,
  indexPriceTickSize: 1.0e-10,
  priceMultiplier: 1.0,
  multiplier: 37733,
  initialMargin: 0.014,
  maintainMargin: 0.007,
  maxRiskLimit: 25000,
  minRiskLimit: 25000,
  riskStep: 12500,
  makerFeeRate: 0.0002,
  takerFeeRate: 0.0006,
  takerFixFee: 0.0,
  makerFixFee: 0.0,
  settlementFeeRate: 0.0,
  settlementFixFee: 0.0,
  isDeleverage: true,
  isQuanto: false,
  isInverse: false,
  markMethod: 'FairPrice',
  fairMethod: 'FundingRate',
  fundingBaseSymbol: '.PEPEINT8H',
  fundingQuoteSymbol: '.USDTINT8H',
  fundingRateSymbol: '.PEPEUSDTMFPI8H',
  indexSymbol: '.KPEPEUSDT',
  settlementSymbol: '',
  status: 'Open',
  displayNameMap: null,
  displaySettleCurrency: 'USDT',
  order: 5,
  createdAt: 1683288195000,
  updatedAt: 1711520523000,
  maxLeverage: 20,
  sourceExchanges: ['gateio', 'okex', 'kucoin', 'bybit', 'bitget'],
  v2: true,
  v2_1: true,
  deviateFactor: 0.05,
  premiumsSymbol1M: '.PEPEUSDTMPI',
  premiumsSymbol8H: '.PEPEUSDTMPI8H',
  fundingBaseSymbol1M: '.PEPEINT',
  fundingQuoteSymbol1M: '.USDTINT',
  orderPriceRange: 0.05,
  reducePriceRange: 0.05,
  supportGridTrading: true,
  tradeStrategy: 'td',
  stepRiskLimitStatus: 2,
  isMigrate: true,
  isTrialFunds: true,
};

const XBTUSDTM = {
  k: 500,
  m: 196,
  f: 1.3,
  mmrLimit: 0.3,
  id: '101',
  symbol: 'XBTUSDTM',
  rootSymbol: 'USDT',
  type: 'FFWCSX',
  firstOpenDate: 1585555200000,
  expireDate: null,
  settleDate: null,
  baseCurrency: 'XBT',
  quoteCurrency: 'USDT',
  settleCurrency: 'USDT',
  spotCurrency: 'BTC',
  maxOrderQty: 1000000,
  maxPrice: 1000000,
  lotSize: 1,
  tickSize: 0.1,
  indexPriceTickSize: 0.01,
  priceMultiplier: 1,
  multiplier: 0.001,
  initialMargin: 0.008,
  maintainMargin: 0.004,
  maxRiskLimit: 100000,
  minRiskLimit: 100000,
  riskStep: 50000,
  makerFeeRate: 0.0002,
  takerFeeRate: 0.0006,
  takerFixFee: 0,
  makerFixFee: 0,
  settlementFeeRate: 0,
  settlementFixFee: 0,
  isDeleverage: true,
  isQuanto: true,
  isInverse: false,
  markMethod: 'FairPrice',
  fairMethod: 'FundingRate',
  fundingBaseSymbol: '.XBTINT8H',
  fundingQuoteSymbol: '.USDTINT8H',
  fundingRateSymbol: '.XBTUSDTMFPI8H',
  indexSymbol: '.KXBTUSDT',
  settlementSymbol: '',
  status: 'Open',
  displayNameMap: null,
  displaySettleCurrency: 'USDT',
  order: 0,
  createdAt: 1585509512000,
  updatedAt: 1711347006000,
  maxLeverage: 100,
  sourceExchanges: ['okex', 'binance', 'kucoin', 'bybit', 'bitget', 'bitmart', 'gateio'],
  v2: true,
  v2_1: true,
  deviateFactor: 0.05,
  premiumsSymbol1M: '.XBTUSDTMPI',
  premiumsSymbol8H: '.XBTUSDTMPI8H',
  fundingBaseSymbol1M: '.XBTINT',
  fundingQuoteSymbol1M: '.USDTINT',
  orderPriceRange: 0.05,
  reducePriceRange: 0.05,
  supportGridTrading: true,
  tradeStrategy: 'td',
  stepRiskLimitStatus: 1,
  imgUrl:
    'https://kc-v2-config.s3.ap-northeast-1.amazonaws.com/icon/65962204b01aba000122af14_XBTUSDTM.png',
  extra: null,
  isMigrate: true,
  isTrialFunds: true,
};

const IDUSDTM = {
  k: 500,
  m: 196,
  f: 1.3,
  mmrLimit: 0.3,
  id: '373',
  symbol: 'IDUSDTM',
  rootSymbol: 'USDT',
  type: 'FFWCSX',
  firstOpenDate: 1679995800000,
  expireDate: null,
  settleDate: null,
  baseCurrency: 'ID',
  quoteCurrency: 'USDT',
  settleCurrency: 'USDT',
  spotCurrency: 'ID',
  maxOrderQty: 1000000,
  maxPrice: 1000000.0,
  lotSize: 1,
  tickSize: 1.0e-5,
  indexPriceTickSize: 1.0e-5,
  priceMultiplier: 1.0,
  multiplier: 10.0,
  initialMargin: 0.02,
  maintainMargin: 0.012,
  maxRiskLimit: 10000,
  minRiskLimit: 10000,
  riskStep: 5000,
  makerFeeRate: 2.0e-4,
  takerFeeRate: 6.0e-4,
  takerFixFee: 0.0,
  makerFixFee: 0.0,
  settlementFeeRate: 0.0,
  settlementFixFee: 0.0,
  isDeleverage: true,
  isQuanto: false,
  isInverse: false,
  markMethod: 'FairPrice',
  fairMethod: 'FundingRate',
  fundingBaseSymbol: '.IDINT8H',
  fundingQuoteSymbol: '.USDTINT8H',
  fundingRateSymbol: '.IDUSDTMFPI8H',
  indexSymbol: '.KIDUSDT',
  settlementSymbol: '',
  status: 'Open',
  displayNameMap: null,
  displaySettleCurrency: 'USDT',
  order: 5,
  createdAt: 1679886736000,
  updatedAt: 1711694428000,
  maxLeverage: 20,
  sourceExchanges: ['binance', 'kucoin', 'gateio', 'okex', 'bitget'],
  v2: true,
  v2_1: true,
  deviateFactor: 0.05,
  premiumsSymbol1M: '.IDUSDTMPI',
  premiumsSymbol8H: '.IDUSDTMPI8H',
  fundingBaseSymbol1M: '.IDINT',
  fundingQuoteSymbol1M: '.USDTINT',
  orderPriceRange: 0.05,
  reducePriceRange: 0.05,
  supportGridTrading: true,
  tradeStrategy: 'td',
  stepRiskLimitStatus: 2,
  isMigrate: true,
  isTrialFunds: true,
};

const XBTUSDM = {
  m: 20000,
  mmrLimit: 0.3,
  f: 1.3,
  k: 100000,
  id: '1',
  symbol: 'XBTUSDM',
  rootSymbol: 'XBT',
  type: 'FFWCSX',
  firstOpenDate: 1552638575000,
  expireDate: null,
  settleDate: null,
  baseCurrency: 'XBT',
  quoteCurrency: 'USD',
  settleCurrency: 'XBT',
  spotCurrency: 'BTC',
  maxOrderQty: 10000000,
  maxPrice: 1000000,
  lotSize: 1,
  tickSize: 0.1,
  indexPriceTickSize: 0.1,
  priceMultiplier: 1,
  multiplier: -1,
  initialMargin: 0.014,
  maintainMargin: 0.007,
  maxRiskLimit: 1,
  minRiskLimit: 1,
  riskStep: 0,
  makerFeeRate: 0.0002,
  takerFeeRate: 0.0006,
  takerFixFee: 0,
  makerFixFee: 0,
  settlementFeeRate: 0,
  settlementFixFee: 0,
  isDeleverage: true,
  isQuanto: false,
  isInverse: true,
  markMethod: 'FairPrice',
  fairMethod: 'FundingRate',
  fundingBaseSymbol: '.XBTINT8H',
  fundingQuoteSymbol: '.USDINT8H',
  fundingRateSymbol: '.XBTUSDMFPI8H',
  indexSymbol: '.BXBT',
  settlementSymbol: null,
  status: 'Open',
  displayNameMap: null,
  displaySettleCurrency: 'BTC',
  order: 1,
  createdAt: 1547407112000,
  updatedAt: 1704272910000,
  maxLeverage: 20,
  sourceExchanges: ['coinbase', 'bitstamp', 'crypto', 'kraken'],
  v2: true,
  v2_1: true,
  deviateFactor: 0.05,
  premiumsSymbol1M: '.XBTUSDMPI',
  premiumsSymbol8H: '.XBTUSDMPI8H',
  fundingBaseSymbol1M: '.XBTINT',
  fundingQuoteSymbol1M: '.USDINT',
  orderPriceRange: 0.05,
  reducePriceRange: 0.05,
  supportGridTrading: false,
  tradeStrategy: 'td',
  stepRiskLimitStatus: 1,
  imgUrl:
    'https://kc-v2-config.s3.ap-northeast-1.amazonaws.com/icon/65962204b01aba000122af13_XBTUSDM.png',
  extra: null,
  isMigrate: true,
  isTrialFunds: true,
};

const XBTMM24 = {
  m: 20000,
  mmrLimit: 0.3,
  f: 1.3,
  k: 100000,
  id: '512',
  symbol: 'XBTMM24',
  rootSymbol: 'XBT',
  type: 'FFICSX',
  firstOpenDate: 1710489600000,
  expireDate: 1719561600000,
  settleDate: 1719561600000,
  baseCurrency: 'XBT',
  quoteCurrency: 'USD',
  settleCurrency: 'XBT',
  spotCurrency: 'BTC',
  maxOrderQty: 1000000,
  maxPrice: 1000000.0,
  lotSize: 1,
  tickSize: 0.1,
  indexPriceTickSize: 0.01,
  priceMultiplier: 1.0,
  multiplier: -1.0,
  initialMargin: 0.05,
  maintainMargin: 0.025,
  maxRiskLimit: 4,
  minRiskLimit: 4,
  riskStep: 2,
  makerFeeRate: 0.0002,
  takerFeeRate: 0.0006,
  takerFixFee: 0.0,
  makerFixFee: 0.0,
  settlementFeeRate: 2.5e-4,
  settlementFixFee: 0.0,
  isDeleverage: true,
  isQuanto: false,
  isInverse: true,
  markMethod: 'FairPrice',
  fairMethod: null,
  fundingBaseSymbol: null,
  fundingQuoteSymbol: null,
  fundingRateSymbol: null,
  indexSymbol: '.BXBT',
  settlementSymbol: '.BXBT30M',
  status: 'Open',
  displayNameMap: null,
  displaySettleCurrency: 'BTC',
  order: 102,
  createdAt: 1710470927000,
  updatedAt: 1710470927000,
  maxLeverage: 50,
  sourceExchanges: ['coinbase', 'bitstamp', 'crypto', 'kraken'],
  v2: true,
  v2_1: true,
  deviateFactor: 0.05,
  premiumsSymbol1M: '.XBTUSDMPI',
  premiumsSymbol8H: '.XBTUSDMPI8H',
  fundingBaseSymbol1M: null,
  fundingQuoteSymbol1M: null,
  orderPriceRange: 0.05,
  reducePriceRange: 0.05,
  supportGridTrading: false,
  tradeStrategy: 'td',
  stepRiskLimitStatus: 2,
  imgUrl:
    'https://kc-v2-config.s3.ap-northeast-1.amazonaws.com/icon/65f3b4d052890a0001f40b86_BTC.png',
  extra: '{"engineId":3,"isMainCurrency":true,"matchWeight":2000.0}',
  isMigrate: true,
  isTrialFunds: true,
};

export const activeContracts = {
  success: true,
  code: '200',
  msg: 'success',
  retry: false,
  data: [XBTUSDTM, PEPEUSDTM, IDUSDTM, XBTUSDM, XBTMM24],
};

export const allContracts = {
  success: true,
  code: '200',
  msg: 'success',
  retry: false,
  data: [XBTUSDTM, PEPEUSDTM, IDUSDTM, XBTUSDM, XBTMM24],
};

export const mockMap = {
  '/_api_kumex/kumex-contract/contracts-GET': allContracts,
  '/_api_kumex/kumex-contract/contracts/active': activeContracts,
};
