/**
 * Owner: clyne@kupotech.com
 */

export const activeOrders = {
  success: true,
  code: '200',
  msg: 'success',
  retry: false,
  data: {
    currentPage: 1,
    pageSize: 150,
    totalNum: 1,
    totalPage: 1,
    items: [
      {
        id: '171072148528431104',
        symbol: 'XBTUSDTM',
        type: 'limit',
        side: 'buy',
        price: 60000,
        size: 5,
        value: 6000,
        dealValue: 0,
        dealSize: 0,
        cancelSize: 0,
        stp: '',
        stop: '',
        stopPriceType: '',
        stopTriggered: false,
        stopPrice: null,
        timeInForce: 'GTC',
        postOnly: false,
        hidden: false,
        iceberg: false,
        leverage: 10,
        forceHold: false,
        closeOrder: false,
        closeOnly: false,
        visibleSize: 0,
        cancelAfter: null,
        channel: 'WEB',
        clientOid: '',
        remark: null,
        tags: '',
        cancelExist: false,
        createdAt: 1713599980632,
        updatedAt: 1713599980632,
        endAt: null,
        isActive: true,
        shortcut: false,
        settleCurrency: 'USDT',
        fromReduce: false,
        orderTime: 1713599980576000300,
        triggerStopUpPrice: null,
        triggerStopDownPrice: null,
        triggerOrderId: '0',
        kubotMsg: null,
        isTrialFunds: false,
        noMarginSize: null,
        marginMode: 'CROSS',
        positionSide: 'BOTH',
        remainHoldAmount: null,
        status: 'open',
        displayType: 'limit',
      },
      {
        id: '171072148528431104',
        symbol: 'XBTUSDTM',
        type: 'limit',
        side: 'sell',
        price: 60000,
        size: 6,
        value: 6000,
        dealValue: 0,
        dealSize: 0,
        cancelSize: 0,
        stp: '',
        stop: '',
        stopPriceType: '',
        stopTriggered: false,
        stopPrice: null,
        timeInForce: 'GTC',
        postOnly: false,
        hidden: false,
        iceberg: false,
        leverage: 10,
        forceHold: false,
        closeOrder: false,
        closeOnly: false,
        visibleSize: 0,
        cancelAfter: null,
        channel: 'WEB',
        clientOid: '',
        remark: null,
        tags: '',
        cancelExist: false,
        createdAt: 1713599980632,
        updatedAt: 1713599980632,
        endAt: null,
        isActive: true,
        shortcut: false,
        settleCurrency: 'USDT',
        fromReduce: false,
        orderTime: 1713599980576000300,
        triggerStopUpPrice: null,
        triggerStopDownPrice: null,
        triggerOrderId: '0',
        kubotMsg: null,
        isTrialFunds: false,
        noMarginSize: null,
        marginMode: 'CROSS',
        positionSide: 'BOTH',
        remainHoldAmount: null,
        status: 'open',
        displayType: 'limit',
      },
      {
        id: '171072148528431104',
        symbol: 'PEPEUSDTM',
        type: 'limit',
        side: 'sell',
        price: 0.0000065,
        size: 200,
        value: 6000,
        dealValue: 0,
        dealSize: 0,
        cancelSize: 0,
        stp: '',
        stop: '',
        stopPriceType: '',
        stopTriggered: false,
        stopPrice: null,
        timeInForce: 'GTC',
        postOnly: false,
        hidden: false,
        iceberg: false,
        leverage: 10,
        forceHold: false,
        closeOrder: false,
        closeOnly: false,
        visibleSize: 0,
        cancelAfter: null,
        channel: 'WEB',
        clientOid: '',
        remark: null,
        tags: '',
        cancelExist: false,
        createdAt: 1713599980632,
        updatedAt: 1713599980632,
        endAt: null,
        isActive: true,
        shortcut: false,
        settleCurrency: 'USDT',
        fromReduce: false,
        orderTime: 1713599980576000300,
        triggerStopUpPrice: null,
        triggerStopDownPrice: null,
        triggerOrderId: '0',
        kubotMsg: null,
        isTrialFunds: false,
        noMarginSize: null,
        marginMode: 'CROSS',
        positionSide: 'BOTH',
        remainHoldAmount: null,
        status: 'open',
        displayType: 'limit',
      },
      {
        id: '171072148528431104',
        symbol: 'PEPEUSDTM',
        type: 'limit',
        side: 'buy',
        price: 0.0000064,
        size: 500,
        value: 6000,
        dealValue: 0,
        dealSize: 0,
        cancelSize: 0,
        stp: '',
        stop: '',
        stopPriceType: '',
        stopTriggered: false,
        stopPrice: null,
        timeInForce: 'GTC',
        postOnly: false,
        hidden: false,
        iceberg: false,
        leverage: 10,
        forceHold: false,
        closeOrder: false,
        closeOnly: false,
        visibleSize: 0,
        cancelAfter: null,
        channel: 'WEB',
        clientOid: '',
        remark: null,
        tags: '',
        cancelExist: false,
        createdAt: 1713599980632,
        updatedAt: 1713599980632,
        endAt: null,
        isActive: true,
        shortcut: false,
        settleCurrency: 'USDT',
        fromReduce: false,
        orderTime: 1713599980576000300,
        triggerStopUpPrice: null,
        triggerStopDownPrice: null,
        triggerOrderId: '0',
        kubotMsg: null,
        isTrialFunds: false,
        noMarginSize: null,
        marginMode: 'CROSS',
        positionSide: 'BOTH',
        remainHoldAmount: null,
        status: 'open',
        displayType: 'limit',
      },

      // 反向合约
      {
        id: '171072148528431104',
        symbol: 'XBTUSDM',
        type: 'limit',
        side: 'sell',
        price: 61000,
        size: 2,
        value: 6000,
        dealValue: 0,
        dealSize: 0,
        cancelSize: 0,
        stp: '',
        stop: '',
        stopPriceType: '',
        stopTriggered: false,
        stopPrice: null,
        timeInForce: 'GTC',
        postOnly: false,
        hidden: false,
        iceberg: false,
        leverage: 10,
        forceHold: false,
        closeOrder: false,
        closeOnly: false,
        visibleSize: 0,
        cancelAfter: null,
        channel: 'WEB',
        clientOid: '',
        remark: null,
        tags: '',
        cancelExist: false,
        createdAt: 1713599980632,
        updatedAt: 1713599980632,
        endAt: null,
        isActive: true,
        shortcut: false,
        settleCurrency: 'USDT',
        fromReduce: false,
        orderTime: 1713599980576000300,
        triggerStopUpPrice: null,
        triggerStopDownPrice: null,
        triggerOrderId: '0',
        kubotMsg: null,
        isTrialFunds: false,
        noMarginSize: null,
        marginMode: 'CROSS',
        positionSide: 'BOTH',
        remainHoldAmount: null,
        status: 'open',
        displayType: 'limit',
      },
      {
        id: '171072148528431104',
        symbol: 'XBTUSDM',
        type: 'limit',
        side: 'buy',
        price: 59000,
        size: 3,
        value: 6000,
        dealValue: 0,
        dealSize: 0,
        cancelSize: 0,
        stp: '',
        stop: '',
        stopPriceType: '',
        stopTriggered: false,
        stopPrice: null,
        timeInForce: 'GTC',
        postOnly: false,
        hidden: false,
        iceberg: false,
        leverage: 10,
        forceHold: false,
        closeOrder: false,
        closeOnly: false,
        visibleSize: 0,
        cancelAfter: null,
        channel: 'WEB',
        clientOid: '',
        remark: null,
        tags: '',
        cancelExist: false,
        createdAt: 1713599980632,
        updatedAt: 1713599980632,
        endAt: null,
        isActive: true,
        shortcut: false,
        settleCurrency: 'USDT',
        fromReduce: false,
        orderTime: 1713599980576000300,
        triggerStopUpPrice: null,
        triggerStopDownPrice: null,
        triggerOrderId: '0',
        kubotMsg: null,
        isTrialFunds: false,
        noMarginSize: null,
        marginMode: 'CROSS',
        positionSide: 'BOTH',
        remainHoldAmount: null,
        status: 'open',
        displayType: 'limit',
      },
    ],
    offset: 1,
    trialOffset: 0,
  },
};

export const stopOrders = {
  success: true,
  code: '200',
  msg: 'success',
  retry: false,
  data: {
    currentPage: 1,
    pageSize: 150,
    totalNum: 1,
    totalPage: 1,
    items: [
      // {
      //   id: '170696468007579649',
      //   symbol: 'THETAUSDTM',
      //   type: 'limit',
      //   side: 'buy',
      //   price: 1,
      //   size: 1,
      //   value: 0,
      //   dealValue: 0,
      //   dealSize: 0,
      //   cancelSize: 0,
      //   stp: null,
      //   stop: 'down',
      //   stopPriceType: 'TP',
      //   stopTriggered: false,
      //   stopPrice: 1,
      //   timeInForce: 'GTC',
      //   postOnly: false,
      //   hidden: false,
      //   iceberg: false,
      //   leverage: 5,
      //   forceHold: false,
      //   closeOrder: false,
      //   closeOnly: false,
      //   visibleSize: 0,
      //   cancelAfter: null,
      //   channel: 'WEB',
      //   clientOid: '',
      //   remark: null,
      //   tags: '',
      //   cancelExist: false,
      //   createdAt: 1713510411368,
      //   updatedAt: 1713510411368,
      //   endAt: null,
      //   isActive: true,
      //   shortcut: false,
      //   settleCurrency: 'USDT',
      //   fromReduce: false,
      //   orderTime: 1713510411359939800,
      //   triggerStopUpPrice: null,
      //   triggerStopDownPrice: null,
      //   triggerOrderId: '0',
      //   kubotMsg: null,
      //   isTrialFunds: false,
      //   status: 'open',
      //   displayType: 'limit_stop',
      // },
    ],
    offset: 1,
    trialOffset: 0,
  },
};

export const mockMap = {
  '/_api_kumex/web-front/orders-GET': activeOrders,
  '/_api_kumex/web-front/stopOrders-GET': stopOrders,
};
