/**
 * Owner: clyne@kupotech.com
 */

// l3余额接口
export const l3 = {
  success: true,
  code: '200',
  msg: 'success',
  retry: false,
  data: {
    availableBalance: 2.75203725,
    margin: 2.75203725,
    usdsGroup: {
      maintMargin: 0,
      orderMargin: 0,
      availableBalance: 1.75203725,
      margin: 1.75203725,
      unrealisedPNL: 0,
      trialBalance: 0,
      trialLimit: 0,
      totalMargin: 1.75203725,
      items: [
        {
          orderMargin: 0,
          availableBalance: 0,
          withdrawHold: 200,
          unrealisedPNL: 0,
          maintMargin: 0,
          margin: 0,
          walletBalance: 1200,
          trialBalance: 0,
          trialLimit: 0,
          trialHistory: false,
          currency: 'USDT',
          isTrialFunds: null,
          trialCode: null,
          totalMargin: 0,
        },
        {
          orderMargin: 0,
          availableBalance: 0,
          withdrawHold: 0,
          unrealisedPNL: 0,
          maintMargin: 0,
          margin: 0,
          walletBalance: 0,
          trialBalance: 0,
          trialLimit: 0,
          trialHistory: false,
          currency: 'USDC',
          isTrialFunds: null,
          trialCode: null,
          totalMargin: 0,
        },
        {
          orderMargin: 0,
          availableBalance: 0,
          withdrawHold: 0,
          unrealisedPNL: 0,
          maintMargin: 0,
          margin: 0,
          walletBalance: 0,
          trialBalance: 0,
          trialLimit: 0,
          trialHistory: false,
          currency: 'USDT',
          isTrialFunds: true,
          trialCode: '',
          totalMargin: null,
        },
      ],
    },
    otherGroup: {
      maintMargin: 0,
      orderMargin: 0,
      availableBalance: 1,
      margin: 1,
      unrealisedPNL: 0,
      trialBalance: 0,
      trialLimit: 0,
      totalMargin: 1,
      items: [
        {
          orderMargin: 0,
          availableBalance: 0,
          withdrawHold: 0,
          unrealisedPNL: 0,
          maintMargin: 0,
          margin: 0,
          walletBalance: 0.01,
          trialBalance: 0,
          trialLimit: 0,
          trialHistory: false,
          currency: 'XBT',
          isTrialFunds: null,
          trialCode: null,
          totalMargin: 1,
        },
        {
          orderMargin: 0,
          availableBalance: 0,
          withdrawHold: 0,
          unrealisedPNL: 0,
          maintMargin: 0,
          margin: 0,
          walletBalance: 0,
          trialBalance: 0,
          trialLimit: 0,
          trialHistory: false,
          currency: 'ETH',
          isTrialFunds: null,
          trialCode: null,
          totalMargin: null,
        },
        {
          orderMargin: 0,
          availableBalance: 0,
          withdrawHold: 0,
          unrealisedPNL: 0,
          maintMargin: 0,
          margin: 0,
          walletBalance: 0,
          trialBalance: 0,
          trialLimit: 0,
          trialHistory: false,
          currency: 'DOT',
          isTrialFunds: null,
          trialCode: null,
          totalMargin: 0,
        },
        {
          orderMargin: 0,
          availableBalance: 0,
          withdrawHold: 0,
          unrealisedPNL: 0,
          maintMargin: 0,
          margin: 0,
          walletBalance: 0,
          trialBalance: 0,
          trialLimit: 0,
          trialHistory: false,
          currency: 'XRP',
          isTrialFunds: null,
          trialCode: null,
          totalMargin: 0,
        },
        {
          orderMargin: 0,
          availableBalance: 0,
          withdrawHold: 0,
          unrealisedPNL: 0,
          maintMargin: 0,
          margin: 0,
          walletBalance: 0,
          trialBalance: 0,
          trialLimit: 0,
          trialHistory: false,
          currency: 'USD',
          isTrialFunds: null,
          trialCode: null,
          totalMargin: null,
        },
        {
          orderMargin: 0,
          availableBalance: 0,
          withdrawHold: 0,
          unrealisedPNL: 0,
          maintMargin: 0,
          margin: 0,
          walletBalance: 0,
          trialBalance: 0,
          trialLimit: 0,
          trialHistory: false,
          currency: 'SOL',
          isTrialFunds: null,
          trialCode: null,
          totalMargin: null,
        },
      ],
    },
  },
};

export const mockMap = {
  '/_api_kumex/web-front/account/total-equity-l3-new-GET': l3,
};
