/**
      * This file is auto-generated by @kucoin/api-generator
      * Owner: sean.shi@kupotech.com
      */
import Client, { type SwaggerOptions as ClientOptions, type SwaggerTDataShape as TDataShape } from 'gbiz-next/commonRequest';
import type { GetUserTradeStatusUsingGetData, GetUserTradeStatusUsingGetResponse } from './types.gen';
import { client as _apiClient } from '../client.gen';
export type Options<TData extends TDataShape = TDataShape> = ClientOptions<TData> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
    disabledLang?: boolean;
};
/**
 * 用户交易状态获取
 */
export const getUserTradeStatusUsingGet = (options?: Options<GetUserTradeStatusUsingGetData>) => {
  return (options?.client ?? _apiClient).pull<GetUserTradeStatusUsingGetResponse>('/_api/chameleon/trade-status', {
    ...(options || {})
  });
};
