/**
      * This file is auto-generated by @kucoin/api-generator
      * Owner: sean.shi@kupotech.com
      */

export type GenericResult_userTransactionStatusReturnBody_ = {
    code?: string;
    data?: UserTransactionStatusReturnVolume;
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type UserTransactionStatusReturnVolume = {
    /**
     * 用户交易状态
     */
    tradeStatus?: boolean;
};

export type GetUserTradeStatusUsingGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/trade-status';
};

export type GetUserTradeStatusUsingGetResponses = {
    /**
     * OK
     */
    200: GenericResult_userTransactionStatusReturnBody_;
};

export type GetUserTradeStatusUsingGetResponse = GetUserTradeStatusUsingGetResponses[keyof GetUserTradeStatusUsingGetResponses];

export type ClientOptions = { baseURL: string; };
