/**
      * This file is auto-generated by @kucoin/api-generator
      * Owner: sean.shi@kupotech.com
      */
import Client, { type SwaggerOptions as ClientOptions, type SwaggerTDataShape as TDataShape } from 'gbiz-next/commonRequest';
import type { HomePageInfoUsingGet1Data, HomePageInfoUsingGet1Response } from './types.gen';
import { client as _apiClient } from '../client.gen';
export type Options<TData extends TDataShape = TDataShape> = ClientOptions<TData> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
    disabledLang?: boolean;
};
/**
 * 新客任务-app首页用户信息查询
 */
export const homePageInfoUsingGet1 = (options?: Options<HomePageInfoUsingGet1Data>) => {
  return (options?.client ?? _apiClient).pull<HomePageInfoUsingGet1Response>('/_api/platform-reward/newcomer/user/homepage/info', {
    ...(options || {})
  });
};
