/**
      * This file is auto-generated by @kucoin/api-generator
      * Owner: sean.shi@kupotech.com
      */

export type GenericResult_newCustomerTaskAppUserHomePageInformationVo_ = {
    code?: string;
    data?: NewCustomerTaskAppUserHomePageInformationVo;
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type SignUpSubTitleV2EntryVo = {
    couponType?: number;
    subTitle?: string;
};

export type NewCustomerTaskAppUserHomePageInformationVo = {
    /**
     * 配置版本号 1/2
     */
    configVersion?: number;
    /**
     * 用户活动结束日期
     */
    displayTotalAmount?: string;
    /**
     * 用户活动结束日期
     */
    effectiveEndTime?: string;
    kycTargetLevel?: number;
    /**
     * 当前系统时间
     */
    now?: string;
    /**
     * 用户已完成进阶任务合约交易金额 ex:10000
     */
    proContractCompleteAmount?: string;
    /**
     * 完成进阶任务需要的合约交易门槛值 ex:10000
     */
    proContractTargetAmount?: string;
    /**
     * 用户已完成进阶任务现货交易金额 ex:1000
     */
    proSpotCompleteAmount?: string;
    /**
     * 完成进阶任务需要的现货交易门槛值 ex:1000
     */
    proSpotTargetAmount?: string;
    region?: string;
    /**
     * 配置的福利中心跳转链接
     */
    rewardCenterUri?: string;
    shardingFlag?: string;
    /**
     * 用户任务信息列表
     */
    taskList?: Array<NewCustomerTaskAppUserHomeTaskDetails>;
    /**
     * 提现门槛值 ex:8.00
     */
    withdrawAmount?: string;
    /**
     * 提现状态
     */
    withdrawStatus?: string;
};

export type NewCustomerTaskAppUserHomeTaskDetails = {
    /**
     * 展示金额
     */
    displayAmount?: string;
    /**
     * 任务副标题
     */
    subTitle?: string;
    /**
     * 任务副标题V2
     */
    subTitleV2?: Array<SignUpSubTitleV2EntryVo>;
    /**
     * 任务状态 INIT(未完成)/COMPLETE（已完成）
     */
    taskStatus?: string;
    /**
     * 任务类型 SIGN_UP/DEPOSIT/TRADE/PRO
     */
    taskType?: string;
};

export type HomePageInfoUsingGet1Data = {
    body?: never;
    headers?: {
        /**
         * X-USER-ID
         */
        'X-USER-ID'?: string;
        /**
         * X-IP
         */
        'X-IP'?: string;
        /**
         * LANG
         */
        LANG?: string;
    };
    path?: never;
    query?: never;
    url: '/newcomer/user/homepage/info';
};

export type HomePageInfoUsingGet1Responses = {
    /**
     * OK
     */
    200: GenericResult_newCustomerTaskAppUserHomePageInformationVo_;
};

export type HomePageInfoUsingGet1Response = HomePageInfoUsingGet1Responses[keyof HomePageInfoUsingGet1Responses];

export type ClientOptions = { baseURL: string; };
