/**
 * This file is auto-generated by @kucoin/api-generator
 * Owner: sean.shi@kupotech.com
 */

import type {
  Client,
  Options as ClientOptions,
  TDataShape,
} from '../__kucoin_api_common_fetch__/client-core.types';
import { client as _apiClient } from './client.gen';
import type {
  GetDefaultInvitationCodeByBrokerNameUsingGetData,
  GetDefaultInvitationCodeByBrokerNameUsingGetResponse,
} from './types.gen';

export type Options<TData extends TDataShape = TDataShape> = ClientOptions<TData> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * getDefaultInvitationCodeByBrokerName
 */
export const getDefaultInvitationCodeByBrokerNameUsingGet = (
  query: GetDefaultInvitationCodeByBrokerNameUsingGetData['query'],
  options?: Options<GetDefaultInvitationCodeByBrokerNameUsingGetData>,
) => {
  return (options?.client ?? _apiClient).get<GetDefaultInvitationCodeByBrokerNameUsingGetResponse>({
    url: '/invitation-code/getDefaultByBrokerName',
    query,
    ...(options || {}),
  });
};
