/**
      * This file is auto-generated by @kucoin/api-generator
      * Owner: sean.shi@kupotech.com
      */
import Client, { type SwaggerOptions as ClientOptions, type SwaggerTDataShape as TDataShape } from 'gbiz-next/commonRequest';
import type { RatesUsingGetData, RatesUsingGetResponse, GetPricesV2UsingGetData, GetPricesV2UsingGetResponse, GetAllCurrenciesByCategoryFlatUsingGet1Data, GetAllCurrenciesByCategoryFlatUsingGet1Response } from './types.gen';
import { client as _apiClient } from '../client.gen';
export type Options<TData extends TDataShape = TDataShape> = ClientOptions<TData> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
    disabledLang?: boolean;
};
/**
 * 获取法币汇率
 */
export const ratesUsingGet = (params?: RatesUsingGetData['query'], options?: Options<RatesUsingGetData>) => {
  return (options?.client ?? _apiClient).pull<RatesUsingGetResponse, RatesUsingGetData['query']>('/_api/currency/rates', params, {
    ...(options || {})
  });
};
/**
 * 获取交易所实时的币种（包括法币）对法币的价格
 */
export const getPricesV2UsingGet = (params?: GetPricesV2UsingGetData['query'], options?: Options<GetPricesV2UsingGetData>) => {
  return (options?.client ?? _apiClient).pull<GetPricesV2UsingGetResponse, GetPricesV2UsingGetData['query']>('/_api/currency/v2/prices', params, {
    ...(options || {})
  });
};
/**
 * 获取所有kumex,pool,kucoin币种
 */
export const getAllCurrenciesByCategoryFlatUsingGet1 = (params: GetAllCurrenciesByCategoryFlatUsingGet1Data['query'], options?: Options<GetAllCurrenciesByCategoryFlatUsingGet1Data>) => {
  return (options?.client ?? _apiClient).pull<GetAllCurrenciesByCategoryFlatUsingGet1Response, GetAllCurrenciesByCategoryFlatUsingGet1Data['query']>('/_api/currency/site/transfer-currencies', params, {
    ...(options || {})
  });
};
