/**
      * This file is auto-generated by @kucoin/api-generator
      * Owner: sean.shi@kupotech.com
      */

export type AccountFrontTotalBalanceModel = {
    /**
     * 账户可用余额
     */
    availableBalance?: string;
    /**
     * 账户冻结金额
     */
    holdBalance?: string;
    /**
     * 账户总额
     */
    totalBalance?: string;
};

export type AccountFrontTotalBalanceResponse = {
    /**
     * 总资产显示的转换币种编码
     */
    baseCurrency?: string;
    /**
     * 总资产显示的转换币种名称
     */
    baseCurrencyName?: string;
    isolatedModel?: AccountFrontTotalBalanceModel;
    mainModel?: AccountFrontTotalBalanceModel;
    marginModel?: AccountFrontTotalBalanceModel;
    optionModel?: AccountFrontTotalBalanceModel;
    poolModel?: AccountFrontTotalBalanceModel;
    tradeHFModel?: AccountFrontTotalBalanceModel;
    tradeModel?: AccountFrontTotalBalanceModel;
};

export type GenericResult_AccountFrontTotalBalanceResponse_ = {
    code?: string;
    data?: AccountFrontTotalBalanceResponse;
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type QueryTotalBalanceUsingGet1Data = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 转换的目标币种
         */
        baseCurrency?: string;
    };
    url: '/query/total-balance';
};

export type QueryTotalBalanceUsingGet1Responses = {
    /**
     * OK
     */
    200: GenericResult_AccountFrontTotalBalanceResponse_;
};

export type QueryTotalBalanceUsingGet1Response = QueryTotalBalanceUsingGet1Responses[keyof QueryTotalBalanceUsingGet1Responses];

export type ClientOptions = { baseURL: string; };
