/**
 * Owner: jesse.shao@kupotech.com
 */
import JsBridge from 'utils/jsBridge';
import { _t } from 'utils/lang';
import nowPosterBg from 'assets/marketCommon/poster-back.png';
import { isIOS } from 'helper';

const clearNewCoinSubTitle = _t('newCoin.banner.subtitle').replace('<span>', '');
const NewCoinSubTitle = clearNewCoinSubTitle.replace('</span>', '');

// 宝藏币二期 多语海报
const newCoinPoster = {
  en_US: 'https://assets.staticimg.com/cms/media/7R46K7eXjFPnCGDfMA8WHJbwk4DkdChqL4IheCUqQ.jpg',
  de_DE: 'https://assets.staticimg.com/cms/media/9AmJ7Ro0qiM3bEeGwQYk7Q5j6d76rbe1O1V4J1Kl2.jpg',
  es_ES: 'https://assets.staticimg.com/cms/media/9mruHIcaxjeouvUtbi2OiIPeTyo6RDVPbtra6Jdzb.jpg',
  tr_TR: 'https://assets.staticimg.com/cms/media/2xLGEfBMVEqPcCXvKS8ggvwX0tz33NEWFehCXUK8G.jpg',
  pt_PT: 'https://assets.staticimg.com/cms/media/2PTbvgC7HyTxH7mxnFBjB9MzJqMUBuwTw69tFUSQu.jpg',
  vi_VN: 'https://assets.staticimg.com/cms/media/8DWQnNToy5VCtFV8er4OhHgma3gTlrmVAwCiKIHdH.jpg',
};

export const SHARE_CONFIG = {
  luckydrawTurkey: () => {
    return {
      shareTitle:
        '1,500,000 TRY Ödülü Kazanmak için Hemen Kaydolun!(Yalnızca Türk Kullanıcılarına Özel)',
      posterBg: nowPosterBg,
      shareTexts: [
        {
          color: '#24ae8f',
          fontSize: 34,
          fontWeight: '500',
          text: '1,500,000 TRY Ödülü',
          x: 30,
          y: 100,
          lineHeight: 48,
          lineSpace: 0,
          needCompute: true,
          newLine: true,
        },
        {
          color: '#24ae8f',
          fontSize: 34,
          fontWeight: '500',
          text: 'Kazanmak için Hemen',
          x: 20,
          y: 145,
          lineHeight: 48,
          lineSpace: 0,
          needCompute: true,
          newLine: true,
        },
        {
          color: '#24ae8f',
          fontSize: 34,
          fontWeight: '500',
          text: 'Kaydolun!',
          x: 110,
          y: 188,
          lineHeight: 48,
          lineSpace: 0,
          needCompute: true,
          newLine: true,
        },
        {
          color: '#fff',
          fontSize: 14,
          fontWeight: '400',
          text: 'Yalnızca Türk Kullanıcılarına Özel',
          x: 85,
          y: 225,
          lineHeight: 25,
          lineSpace: 0,
          needCompute: true,
          newLine: true,
        },
        {
          color: '#00142a',
          fontSize: 14,
          fontWeight: '500',
          text: 'Şimdi BTC,ETH ve KCS ticaretine',
          x: 60,
          y: 615,
          lineHeight: 23,
          lineSpace: 0,
          needCompute: true,
          newLine: true,
        },
        {
          color: '#00142a',
          fontSize: 14,
          fontWeight: '500',
          text: 'başlayın!',
          x: 60,
          y: 630,
          lineHeight: 23,
          lineSpace: 0,
          needCompute: true,
          newLine: true,
        },
        {
          color: '#b8c6d8',
          fontSize: 14,
          fontWeight: '400',
          text: `${window._BRAND_NAME_} Uygulamasını İndir`,
          x: 60,
          y: 648,
          lineHeight: 24,
          lineSpace: 0,
          needCompute: true,
          newLine: true,
        },
      ],
    };
  },
  luckydraw: () => {
    return {
      shareTitle:
        'Referral Super Lucky Draw. Up to $600,000 in BTC For Grab! Win your lottery ticket. Refer your friends to grab a lottery ticket. Refer and Win Grand Prize.',
      posterBg: nowPosterBg,
      shareTexts: [
        {
          color: '#24ae8f',
          fontSize: 34,
          fontWeight: '500',
          text: 'Referral Super Lucky',
          x: 30,
          y: 70,
          lineHeight: 48,
          lineSpace: 0,
          needCompute: true,
          newLine: true,
        },
        {
          color: '#24ae8f',
          fontSize: 34,
          fontWeight: '500',
          text: 'Draw Up to $600,000',
          x: 32,
          y: 115,
          lineHeight: 48,
          lineSpace: 0,
          needCompute: true,
          newLine: true,
        },
        {
          color: '#24ae8f',
          fontSize: 34,
          fontWeight: '500',
          text: 'in BTC For Grab',
          x: 65,
          y: 160,
          lineHeight: 48,
          lineSpace: 0,
          needCompute: true,
          newLine: true,
        },
        {
          color: '#fff',
          fontSize: 14,
          fontWeight: '400',
          text: 'Win your lottery ticket',
          x: 117,
          y: 200,
          lineHeight: 25,
          lineSpace: 0,
          needCompute: true,
          newLine: true,
        },
        {
          color: '#fff',
          fontSize: 14,
          fontWeight: '400',
          text: 'Refer your friends to grab a lottery ticket',
          x: 61,
          y: 225,
          lineHeight: 25,
          lineSpace: 0,
          needCompute: true,
          newLine: true,
        },
        {
          color: '#fff',
          fontSize: 14,
          fontWeight: '400',
          text: 'Refer and Win Grand Prize',
          x: 107,
          y: 250,
          lineHeight: 25,
          lineSpace: 0,
          needCompute: true,
          newLine: true,
        },
        {
          color: '#00142a',
          fontSize: 14,
          fontWeight: '500',
          text: 'Start trading BTC, ETH and KCS',
          x: 60,
          y: 615,
          lineHeight: 23,
          lineSpace: 0,
          needCompute: true,
          newLine: true,
        },
        {
          color: '#00142a',
          fontSize: 14,
          fontWeight: '500',
          text: 'now!',
          x: 60,
          y: 630,
          lineHeight: 23,
          lineSpace: 0,
          needCompute: true,
          newLine: true,
        },
        {
          color: '#b8c6d8',
          fontSize: 14,
          fontWeight: '400',
          text: `Download ${window._BRAND_NAME_} APP`,
          x: 60,
          y: 648,
          lineHeight: 24,
          lineSpace: 0,
          needCompute: true,
          newLine: true,
        },
      ],
    };
  },
  luckydrawSepa: () => {
    return {
      shareTitle: _t('spea.banner.title1'),
      posterBg: nowPosterBg,
      shareTexts: [
        {
          color: '#24ae8f',
          fontSize: 28,
          fontWeight: '500',
          lineHeight: 28,
          wordSpace: 2,
          textAlign: 'center',
          text: _t('spea.banner.title1'),
          x: 190,
          y: 70,
          needCompute: true,
        },
        {
          color: '#00142a',
          fontSize: 14,
          fontWeight: '500',
          lineHeight: 5,
          wordSpace: 2,
          text: 'Start trading BTC, ETH and KCS now!',
          x: 60,
          y: 617,
          firstWidth: 220,
          needCompute: true,
          newLine: true,
          independent: true,
        },
        {
          color: '#b8c6d8',
          fontSize: 14,
          fontWeight: '400',
          wordSpace: 2,
          text: `Download ${window._BRAND_NAME_} APP`,
          x: 60,
          y: 650,
          needCompute: true,
          newLine: true,
          independent: true,
        },
      ],
    };
  },
  newCoinCarnival: ({ round, currentLang }) => {
    const roundConfig = {
      one: {
        shareTitle: `${window._BRAND_NAME_} ${_t('newCoin.banner.title')},${NewCoinSubTitle}`,
        posterBg: nowPosterBg,
        shareTexts: [
          {
            color: '#24ae8f',
            fontSize: 28,
            fontWeight: '500',
            lineHeight: 28,
            wordSpace: 2,
            textAlign: 'center',
            text: `${window._BRAND_NAME_} ${_t('newCoin.banner.title')}`,
            x: 190,
            y: 70,
            needCompute: true,
          },
          {
            color: '#fff',
            fontSize: 16,
            fontWeight: '400',
            lineHeight: 25,
            wordSpace: 2,
            textAlign: 'center',
            text: NewCoinSubTitle,
            x: 190,
            y: 150,
            needCompute: true,
            newLine: true,
            independent: true,
          },
          {
            color: '#00142a',
            fontSize: 14,
            fontWeight: '500',
            lineHeight: 5,
            wordSpace: 2,
            text: 'Start trading BTC, ETH and KCS now!',
            x: 60,
            y: 617,
            firstWidth: 220,
            needCompute: true,
            newLine: true,
            independent: true,
          },
          {
            color: '#b8c6d8',
            fontSize: 14,
            fontWeight: '400',
            wordSpace: 2,
            text: `Download ${window._BRAND_NAME_} APP`,
            x: 60,
            y: 650,
            needCompute: true,
            newLine: true,
            independent: true,
          },
        ],
      },
      two: {
        shareTitle: `${window._BRAND_NAME_} ${_t('newCoin.banner.title')},${NewCoinSubTitle}`,
        posterBg: newCoinPoster[currentLang] || newCoinPoster['en_US'],
        shareTexts: [
          {
            color: '#00142a',
            fontSize: 14,
            fontWeight: '500',
            lineHeight: 5,
            wordSpace: 2,
            text: 'Start trading BTC, ETH and KCS now!',
            x: 60,
            y: 617,
            firstWidth: 220,
            needCompute: true,
            newLine: true,
            independent: true,
          },
          {
            color: '#b8c6d8',
            fontSize: 14,
            fontWeight: '400',
            wordSpace: 2,
            text: `Download ${window._BRAND_NAME_} APP`,
            x: 60,
            y: 650,
            needCompute: true,
            newLine: true,
            independent: true,
          },
        ],
      },
    };

    return roundConfig[round];
  },
  pakistanCampaign: () => {
    return {
      shareTitle: `120,000 TRX & an iPhone 13 Give Away!(Exclusive for Pakistani Users)`,
      posterBg: nowPosterBg,
      shareTexts: [
        {
          color: '#24ae8f',
          fontSize: 28,
          fontWeight: '500',
          lineHeight: 28,
          wordSpace: 2,
          textAlign: 'center',
          text: `120,000 TRX & an iPhone 13 Give Away!`,
          x: 190,
          y: 70,
          needCompute: true,
        },
        {
          color: '#fff',
          fontSize: 16,
          fontWeight: '400',
          lineHeight: 25,
          wordSpace: 2,
          textAlign: 'center',
          text: '(Exclusive for Pakistani Users)',
          x: 190,
          y: 150,
          needCompute: true,
          newLine: true,
          independent: true,
        },
        {
          color: '#00142a',
          fontSize: 14,
          fontWeight: '500',
          lineHeight: 5,
          wordSpace: 2,
          text: 'Start trading BTC, ETH and KCS now!',
          x: 60,
          y: 617,
          firstWidth: 220,
          needCompute: true,
          newLine: true,
          independent: true,
        },
        {
          color: '#b8c6d8',
          fontSize: 14,
          fontWeight: '400',
          wordSpace: 2,
          text: `Download ${window._BRAND_NAME_} APP`,
          x: 60,
          y: 650,
          needCompute: true,
          newLine: true,
          independent: true,
        },
      ],
    };
  },
  newTurkey: () => {
    return {
      shareTitle:
        `${window._BRAND_NAME_} Yaz Çılgınlığı! 320 TL Kazanmak İçin Kaydol!(Yalnızca Türk Kullanıcılar İçin)`,
      posterBg: nowPosterBg,
      shareTexts: [
        {
          color: '#24ae8f',
          fontSize: 28,
          fontWeight: '500',
          lineHeight: 28,
          wordSpace: 2,
          textAlign: 'center',
          text: `${window._BRAND_NAME_} Yaz Çılgınlığı! 320 TL Kazanmak İçin Kaydol!`,
          x: 190,
          y: 60,
          needCompute: true,
        },
        {
          color: '#fff',
          fontSize: 16,
          fontWeight: '400',
          lineHeight: 25,
          wordSpace: 2,
          textAlign: 'center',
          text: '(Yalnızca Türk Kullanıcılar İçin)',
          x: 190,
          y: 150,
          needCompute: true,
          newLine: true,
          independent: true,
        },
        {
          color: '#00142a',
          fontSize: 14,
          fontWeight: '500',
          lineHeight: 5,
          wordSpace: 2,
          text: 'Şimdi BTC,ETH ve KCS ticaretine başlayın!',
          x: 60,
          y: 617,
          firstWidth: 220,
          needCompute: true,
          newLine: true,
          independent: true,
        },
        {
          color: '#b8c6d8',
          fontSize: 14,
          fontWeight: '400',
          wordSpace: 2,
          text: `${window._BRAND_NAME_} Uygulamasını İndir`,
          x: 60,
          y: 650,
          needCompute: true,
          newLine: true,
          independent: true,
        },
      ],
    };
  },
  lego: ({ title, subTitle }) => {
    return {
      shareTitle: `${title},${subTitle}`,
      posterBg: nowPosterBg,
      shareTexts: [
        {
          color: '#24ae8f',
          fontSize: 28,
          fontWeight: '500',
          lineHeight: 28,
          wordSpace: 2,
          textAlign: 'center',
          text: title,
          x: 190,
          y: 70,
          needCompute: true,
        },
        {
          color: '#fff',
          fontSize: 16,
          fontWeight: '400',
          lineHeight: 25,
          wordSpace: 2,
          textAlign: 'center',
          text: subTitle,
          x: 190,
          y: 120,
          newLine: true,
          needCompute: true,
        },
        {
          color: '#00142a',
          fontSize: 14,
          fontWeight: '500',
          lineHeight: 5,
          wordSpace: 2,
          text: 'Start trading BTC, ETH and KCS now!',
          x: 60,
          y: 617,
          firstWidth: 200,
          needCompute: true,
          newLine: true,
          independent: true,
        },
        {
          color: '#b8c6d8',
          fontSize: 14,
          fontWeight: '400',
          wordSpace: 2,
          text: `Download ${window._BRAND_NAME_} APP`,
          x: 60,
          y: 650,
          needCompute: true,
          newLine: true,
          independent: true,
        },
      ],
    };
  },
};

// 支持多海报分享的首个版本
export const SUPPORT_GALLERY_VERSION = '3.45.0';

// 分享海报
export const sharePoster = (supportGallery, galleryLink, {
  needQrCode = false,
  utmSource = null,
  rcode = undefined,
  useNewShareVersion= false,
}) => {
  // 新app版本的多张海报分享
  if (supportGallery) {
    JsBridge.open({
      type: 'func',
      params: {
        name: 'share',
        category: 'gallery',
        data: JSON.stringify({
          galleryType: 'CUSTOMER_INVITE',
          galleryLink,
          needQrCode: true,
          rcode,
        }),
      },
    });
    return;
  }
  const isInIos = isIOS();
  // 低版本的默认分享
  JsBridge.open({
    type: 'func',
    params: {
      name: 'share',
      category: 'img',
      rcode,
      qrCodeUrl: galleryLink, // footer二维码链接 默认注册链接 只有当needQrCode 是true 的时候才会生效
      needQrCode,
      utmSource,
      // FIXME: 新版分享组件在 安卓 和 ios 实现不一样，所以我们要交给客户端绘制底部。
      ...(!isInIos && useNewShareVersion
        ? {
            needQrCode: true,
          }
        : {}),
    },
  });
};
