/**
 * Owner: willen@kupotech.com
 */
module.exports = {
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@@/(.*)$': '<rootDir>/src/.umi/$1',
    '^src/(.*)': '<rootDir>/src/$1',
    '^config/(.*)': '<rootDir>/src/config/$1',
    '^config': '<rootDir>/src/config/index.js',
    '^utils/(.*)': '<rootDir>/src/utils/$1',
    '^tools/(.*)': '<rootDir>/src/tools/$1',
    '^static/(.*)': '<rootDir>/cdnAssets/static/$1',
    '^routes/(.*)': '<rootDir>/src/routes/$1',
    '^components/(.*)': '<rootDir>/src/components/$1',
    '^helper': '<rootDir>/src/helper.js',
    '^common/(.*)': '<rootDir>/src/common/$1',
    '^services/(.*)': '<rootDir>/src/services/$1',
    '^test/(.*)': '<rootDir>/test/$1',
    '^hooks/(.*)': '<rootDir>/src/hooks/$1',
    '^hooks': '<rootDir>/src/hooks',
    '^hocs/(.*)': '<rootDir>/src/hocs/$1',
  },

  verbose: false, // 是否输出 descripe 和 test/it 中的测试描述信息
  silent: true,
  globals: {
    _DEV_: true,
    _APP_NAME_: 'kucoin-main-web',
    _XVERSION_: '0.0.1',
    _APP_: 'kucoin-main-web',
    IS_SANDBOX: false,
    __webpack_public_path__: 'xxx/xxx',
    _WEB_RELATION_: {
      DOCS_HOST: 'https://docs.kucoin.com',
      TRADE_HOST: 'https://docs.kucoin.com',
    },
    IS_INSIDE_WEB: true,
    _VERSION_: '0.0.1',
    _ENV_: 'env',
    _DEFAULT_LANG_: 'en_US',
    _DEFAULT_LOCALE_: 'en',
    _SAFE_WEB_DOMAIN_: [
      'kucoin.net',
      'kucoin.com',
      'kucoin.cloud',
      'kucoin.biz',
      'kucoin.top',
      'kucoin.plus',
      'kucoin.work',
      'kumex.com',
      'pool-x.io',
      'kucoin.zendesk.com',
      'localhost',
    ],
  },

  // setupFilesAfterEnv: ['@testing-library/jest-dom'], // 在每个测试文件执行之前调用一些默认执行代码的文件路径
  // testEnvironment: 'jsdom',
  setupFilesAfterEnv: [
    '@testing-library/jest-dom',
    // '@testing-library/react-hooks/disable-error-filtering.js',
    'reflect-metadata',
  ],
  setupFiles: ['./test/setupFile.js'],
  collectCoverageFrom: [
    // 覆盖率收集路径
    '<rootDir>/src/utils/**/*.js',
    '<rootDir>/src/hooks/**/*.js',
    '<rootDir>/src/helper.js',
    '!<rootDir>/src/utils/createImg.js',
    '!<rootDir>/src/components/Kumex/**/*.js',
    '!<rootDir>/src/components/Margin/**/*.js',
    '!<rootDir>/src/routes/FuturesRecords/**/*.js',
    '!<rootDir>/src/routes/OtcPage/**/*.js',
    '!<rootDir>/src/routes/AssetsPage/**/*.js',
    '!<rootDir>/src/routes/BitcoinHalving/**/*.js',
    '!<rootDir>/src/components/Landing/**/*.js',
    '!<rootDir>/src/routes/SpotNFTPage/**/*.js',
    '!<rootDir>/src/routes/AssetsPage/EarnAccountV3',
    '!<rootDir>/src/hooks/tdk/*.js',
    '!<rootDir>/src/utils/meta/assets.js',
    '!<rootDir>/src/utils/meta/codes.js',
    '!<rootDir>/src/utils/meta/global.js',
  ],
};
