/**
      * This file is auto-generated by @kucoin/api-generator
      * Owner: sean.shi@kupotech.com
      */

import type { Options as ClientOptions, TDataShape, Client } from 'tools/request';
import type { GetUserInfoUsingGetData, GetUserInfoUsingGetResponse, IsVoiceSupportUsingGetData, IsVoiceSupportUsingGetResponse } from './types.gen';
import { client as _apiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape> = ClientOptions<TData> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
 disabledLang?: boolean;
};

/**
 * 获取用户信息
 */
export const getUserInfoUsingGet = (options?: Options<GetUserInfoUsingGetData>) => {
    return (options?.client ?? _apiClient).get<GetUserInfoUsingGetResponse>({
        url: '/user-info',
        ...(options || {})
    });
};

/**
 * 获取支持语音的区号列表
 */
export const isVoiceSupportUsingGet = (options?: Options<IsVoiceSupportUsingGetData>) => {
    return (options?.client ?? _apiClient).get<IsVoiceSupportUsingGetResponse>({
        url: '/country-codes/voice-support',
        ...(options || {})
    });
};