import { IConfig } from '@kucoin/api-generator';

const config: IConfig = {
  projectName: 'gbiz-next-entrance',
  api: [
    {
      service: 'universal-core',
      outputDir: './src/api',
      swaggerUrl: 'https://inner.sit.kucoin.net/universal-core/v3/api-docs',
      baseURL: '/universal-core',
      apiClient: 'tools/request',
      include: ['/ip/country'],
      exclude: [],
    },
    {
      service: 'ucenter',
      outputDir: './src/api',
      swaggerUrl: 'https://inner.sit.kucoin.net/ucenter/v3/api-docs',
      baseURL: '/ucenter',
      apiClient: 'tools/request',
      include: [
        '/external-register',
        '/register-email',
        '/register-short-message',
        '/sign-up-validation',
        '/sign-up-phone-email',
        '/sign-up-email',
        '/sign-up-phone',
        '/user/referrer-info',
        '/reset-password-email',
        '/reset-password-phone',
        '/reset-password',
        '/reset-password/voice',
        '/reset-password/validate',
        '/send-validation-code',
        '/verify-validation-code',
        '/v2/reset-password-email',
        '/v3/reset-password-email',
        '/v4/reset-password-email',
        '/v2/reset-password-phone',
        '/v3/reset-password-email',
        '/v4/reset-password-phone',
        '/send-validation-code',
        '/verify-validation-code',
        '/check-required-validations',
        '/risk-check',
        '/ucenter-email/resend',
        '/ucenter-email/risk-check',
        '/ucenter-email/query',
        '/aggregate-login',
        '/v2/login-validation',
        '/send-login-sms',
        '/send-login-email',
        '/country-codes',
        '/phone-number-validate',
        '/qr-token/status',
        '/qr-token/create',
        '/v2/login-validation',
        '/v2/aggregate-login',
        '/login-verify/resend',
        '/login-verify/query',
        '/login-kickout',
        '/external-login',
        '/v2/external-login',
        '/check-account',
        '/external-account',
        '/passkey/authentication/options',
        '/passkey-login',
        '/send-validation-code',
        '/user/query-waited-sign-term',
        '/user/sign-term',
        '/locale',
        '/user-info',
        '/user/locale',
        '/site-config',
        '/country-codes/voice-support',
        '/user/query-change-password',
        '/user/expand-password-duration',
      ],
      exclude: [],
    },
    {
      service: 'market-operation',
      outputDir: './src/api',
      swaggerUrl: 'https://inner.sit.kucoin.net/market-operation/v3/api-docs',
      baseURL: '/market-operation',
      apiClient: 'tools/request',
      include: ['/mail-suffixes', '/recalled-email', '/recalled-phone'],
      exclude: [],
    },
    {
      service: 'growth-config',
      outputDir: './src/api',
      swaggerUrl: 'https://inner.sit.kucoin.net/growth-config/v3/api-docs',
      baseURL: '/growth-config',
      apiClient: 'tools/request',
      include: ['/get/client/config/codes'],
      exclude: [],
    },
    {
      service: 'growth-ucenter',
      outputDir: './src/api',
      swaggerUrl: 'https://inner.sit.kucoin.net/growth-ucenter/v3/api-docs',
      baseURL: '/growth-ucenter',
      apiClient: 'tools/request',
      include: ['/invitation/user-by-rcode'],
      exclude: [],
    },
    {
      service: 'platform-reward',
      outputDir: './src/api',
      swaggerUrl: 'https://inner.sit.kucoin.net/platform-reward/v3/api-docs',
      baseURL: '/platform-reward',
      apiClient: 'tools/request',
      include: ['/newcomer/config'],
      exclude: [],
    }
  ],
};

export default config;
