/**
      * This file is auto-generated by @kucoin/api-generator
      * Owner: sean.shi@kupotech.com
      */

export type ClientPropertyResponse = {
    appId?: string;
    businessLine?: string;
    properties?: Array<PropertyValueResponse>;
};

export type FissionPropertyResponse = {
    appId?: string;
    code?: string;
    createdAt?: string;
    id?: string;
    key?: string;
    keyHash?: number;
    operatorId?: string;
    servicePropertyId?: string;
    updatedAt?: string;
    value?: string;
};

export type GenericResult_ClientPropertyResponse_ = {
    code?: string;
    data?: ClientPropertyResponse;
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type PropertyValueResponse = {
    appId?: string;
    backupValues?: {
        [key: string]: string;
    };
    fission?: Array<FissionPropertyResponse>;
    id?: string;
    jumpType?: string;
    jumpUrl?: string;
    lang?: string;
    name?: string;
    property?: string;
    siteType?: string;
    status?: number;
    updatedDate?: string;
    value?: string;
    version?: number;
};

export type GetClientPropertyByCodeUsingGet1Data = {
    body?: never;
    headers: {
        /**
         * X-KC-CDN-SITE-TYPE
         */
        'X-KC-CDN-SITE-TYPE': string;
    };
    path?: never;
    query: {
        /**
         * businessLine
         */
        businessLine: string;
        /**
         * codes
         */
        codes: string;
    };
    url: '/get/client/config/codes';
};

export type GetClientPropertyByCodeUsingGet1Responses = {
    /**
     * OK
     */
    200: GenericResult_ClientPropertyResponse_;
};

export type GetClientPropertyByCodeUsingGet1Response = GetClientPropertyByCodeUsingGet1Responses[keyof GetClientPropertyByCodeUsingGet1Responses];

export type ClientOptions = { baseURL: string; };