/**
      * This file is auto-generated by @kucoin/api-generator
      * Owner: sean.shi@kupotech.com
      */

export type CommunityGroupModel = {
    /**
     * 官方账号ID
     */
    accountId?: string;
    /**
     * URL地址
     */
    iconUrl?: string;
    /**
     * ID
     */
    id?: string;
    /**
     * 社交平台
     */
    platform?: string;
    /**
     * 类型，OFFICIAL_URL:链接，WECHAT_ACCOUNT:微信公众号，WECHAT_GROUP:微信群
     */
    type?: string;
    /**
     * 链接
     */
    url?: string;
};

export type CommunityGroupResponse = {
    /**
     * 背景图片
     */
    backgroundUrl?: string;
    /**
     * H5背景图片
     */
    backgroundUrlH5?: string;
    /**
     * 社区
     */
    communityGroup?: string;
    /**
     * 社交平台
     */
    communityPlatforms?: Array<CommunityGroupModel>;
    /**
     * 语言
     */
    language?: string;
    /**
     * 社区native name
     */
    nativeName?: string;
};

export type GenericResult_List_CommunityGroupResponse__ = {
    code?: string;
    data?: Array<CommunityGroupResponse>;
    msg?: string;
    retry?: boolean;
    success?: boolean;
};

export type GetCommunityGroupConfigUsingGetData = {
    body?: never;
    headers?: {
        /**
         * X-KC-CDN-SITE-TYPE
         */
        'X-KC-CDN-SITE-TYPE'?: string;
    };
    path?: never;
    query?: never;
    url: '/community/group';
};

export type GetCommunityGroupConfigUsingGetResponses = {
    /**
     * OK
     */
    200: GenericResult_List_CommunityGroupResponse__;
};

export type GetCommunityGroupConfigUsingGetResponse = GetCommunityGroupConfigUsingGetResponses[keyof GetCommunityGroupConfigUsingGetResponses];

export type ClientOptions = { baseURL: string; };
